<?php

// AUTO-GENERATED BASE FILE.
// Do not edit this file manually or with AI/Codex.
// Keep customizations in the wrapper class and use this base file exactly as regenerated by the tool.

// Generated from canonical DataClass metadata.
// Base DTO generated from DataClass / DataClass fields.

class EbookCmsBookDataBase
{
    public $id;
    public $title;
    public $slug;
    public $authorName;
    public $genreName;
    public $status;
    public $coverImageUrl;
    public $summary;
    public $epubDownloadUrl;
    public $epubMimeType;
    public $epubSha256;
    public $publishedAt;
    public $updatedAt;

    public function __construct()
    {
    }
}

?>