<?php

// AUTO-GENERATED BASE FILE.
// Do not edit this file manually or with AI/Codex.
// Keep customizations in the wrapper class and use this base file exactly as regenerated by the tool.

// Generated from canonical DB Access metadata.
// Base class generated from project_db_access_* metadata.

require_once __DIR__ . '/../_support/mtool_runtime_db.php';


class EbookCmsBookDBAccessBase
{
    public function __construct()
    {
    }

    // source_of_truth=manual class_source=manual action_type=SELECTLIST order=10 generation=canonical-bootstrap
    // reason=generated from canonical table metadata without legacy runtime source
    public function GetPublicEbookCmsBookList($limit)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $result = array();

        $last_sql_command_for_mtooldb = 'select `ebook_cms_book`.`id`, `ebook_cms_book`.`title`, `ebook_cms_book`.`slug`, `ebook_cms_book`.`author_name`, `ebook_cms_book`.`genre_name`, `ebook_cms_book`.`status`, `ebook_cms_book`.`cover_image_url`, `ebook_cms_book`.`summary`, `ebook_cms_book`.`epub_download_url`, `ebook_cms_book`.`epub_mime_type`, `ebook_cms_book`.`epub_sha256`, `ebook_cms_book`.`published_at`, `ebook_cms_book`.`updated_at` from `ebook_cms_book` order by `ebook_cms_book`.`id`';
        $ret = $mtooldb->execute($last_sql_command_for_mtooldb, [
        ]);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new EbookCmsBookData();
            $thisresult->id = $thisline[0];
            $thisresult->title = $thisline[1];
            $thisresult->slug = $thisline[2];
            $thisresult->authorName = $thisline[3];
            $thisresult->genreName = $thisline[4];
            $thisresult->status = $thisline[5];
            $thisresult->coverImageUrl = $thisline[6];
            $thisresult->summary = $thisline[7];
            $thisresult->epubDownloadUrl = $thisline[8];
            $thisresult->epubMimeType = $thisline[9];
            $thisresult->epubSha256 = $thisline[10];
            $thisresult->publishedAt = $thisline[11];
            $thisresult->updatedAt = $thisline[12];
            array_push($result, $thisresult);
        }
        return $result;
    }

    // source_of_truth=manual class_source=manual action_type=SELECTSINGLE order=20 generation=canonical-bootstrap
    // reason=generated from canonical table metadata without legacy runtime source
    public function GetPublicEbookCmsBook($param_EbookCmsBook_Slug_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'select `ebook_cms_book`.`id`, `ebook_cms_book`.`title`, `ebook_cms_book`.`slug`, `ebook_cms_book`.`author_name`, `ebook_cms_book`.`genre_name`, `ebook_cms_book`.`status`, `ebook_cms_book`.`cover_image_url`, `ebook_cms_book`.`summary`, `ebook_cms_book`.`epub_download_url`, `ebook_cms_book`.`epub_mime_type`, `ebook_cms_book`.`epub_sha256`, `ebook_cms_book`.`published_at`, `ebook_cms_book`.`updated_at` from `ebook_cms_book` where `ebook_cms_book`.`id` = ?';
        $ret = $mtooldb->execute($last_sql_command_for_mtooldb, [
            $param_EbookCmsBook_Slug_where,
        ]);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new EbookCmsBookData();
            $thisresult->id = $thisline[0];
            $thisresult->title = $thisline[1];
            $thisresult->slug = $thisline[2];
            $thisresult->authorName = $thisline[3];
            $thisresult->genreName = $thisline[4];
            $thisresult->status = $thisline[5];
            $thisresult->coverImageUrl = $thisline[6];
            $thisresult->summary = $thisline[7];
            $thisresult->epubDownloadUrl = $thisline[8];
            $thisresult->epubMimeType = $thisline[9];
            $thisresult->epubSha256 = $thisline[10];
            $thisresult->publishedAt = $thisline[11];
            $thisresult->updatedAt = $thisline[12];
            return $thisresult;
        }
        return NULL;
    }

    // source_of_truth=manual class_source=manual action_type=SELECTLIST order=30 generation=canonical-bootstrap
    // reason=generated from canonical table metadata without legacy runtime source
    public function GetPublicEbookCmsChapterList($param_EbookCmsChapter_BookSlug_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $result = array();

        $last_sql_command_for_mtooldb = 'select `ebook_cms_book`.`id`, `ebook_cms_book`.`title`, `ebook_cms_book`.`slug`, `ebook_cms_book`.`author_name`, `ebook_cms_book`.`genre_name`, `ebook_cms_book`.`status`, `ebook_cms_book`.`cover_image_url`, `ebook_cms_book`.`summary`, `ebook_cms_book`.`epub_download_url`, `ebook_cms_book`.`epub_mime_type`, `ebook_cms_book`.`epub_sha256`, `ebook_cms_book`.`published_at`, `ebook_cms_book`.`updated_at` from `ebook_cms_book` order by `ebook_cms_book`.`id`';
        $ret = $mtooldb->execute($last_sql_command_for_mtooldb, [
        ]);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new EbookCmsBookData();
            $thisresult->id = $thisline[0];
            $thisresult->title = $thisline[1];
            $thisresult->slug = $thisline[2];
            $thisresult->authorName = $thisline[3];
            $thisresult->genreName = $thisline[4];
            $thisresult->status = $thisline[5];
            $thisresult->coverImageUrl = $thisline[6];
            $thisresult->summary = $thisline[7];
            $thisresult->epubDownloadUrl = $thisline[8];
            $thisresult->epubMimeType = $thisline[9];
            $thisresult->epubSha256 = $thisline[10];
            $thisresult->publishedAt = $thisline[11];
            $thisresult->updatedAt = $thisline[12];
            array_push($result, $thisresult);
        }
        return $result;
    }

    // source_of_truth=manual class_source=manual action_type=SELECTSINGLE order=40 generation=canonical-bootstrap
    // reason=generated from canonical table metadata without legacy runtime source
    public function GetPublicEbookCmsChapter($param_EbookCmsChapter_BookSlug_where, $param_EbookCmsChapter_ChapterSlug_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'select `ebook_cms_book`.`id`, `ebook_cms_book`.`title`, `ebook_cms_book`.`slug`, `ebook_cms_book`.`author_name`, `ebook_cms_book`.`genre_name`, `ebook_cms_book`.`status`, `ebook_cms_book`.`cover_image_url`, `ebook_cms_book`.`summary`, `ebook_cms_book`.`epub_download_url`, `ebook_cms_book`.`epub_mime_type`, `ebook_cms_book`.`epub_sha256`, `ebook_cms_book`.`published_at`, `ebook_cms_book`.`updated_at` from `ebook_cms_book` where `ebook_cms_book`.`id` = ?';
        $ret = $mtooldb->execute($last_sql_command_for_mtooldb, [
            $param_EbookCmsChapter_BookSlug_where,
        ]);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new EbookCmsBookData();
            $thisresult->id = $thisline[0];
            $thisresult->title = $thisline[1];
            $thisresult->slug = $thisline[2];
            $thisresult->authorName = $thisline[3];
            $thisresult->genreName = $thisline[4];
            $thisresult->status = $thisline[5];
            $thisresult->coverImageUrl = $thisline[6];
            $thisresult->summary = $thisline[7];
            $thisresult->epubDownloadUrl = $thisline[8];
            $thisresult->epubMimeType = $thisline[9];
            $thisresult->epubSha256 = $thisline[10];
            $thisresult->publishedAt = $thisline[11];
            $thisresult->updatedAt = $thisline[12];
            return $thisresult;
        }
        return NULL;
    }

    // source_of_truth=manual class_source=manual action_type=SELECTLIST order=50 generation=canonical-bootstrap
    // reason=generated from canonical table metadata without legacy runtime source
    public function GetPublicEbookCmsEpubDeliveryList($param_EbookCmsBook_Slug_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $result = array();

        $last_sql_command_for_mtooldb = 'select `ebook_cms_book`.`id`, `ebook_cms_book`.`title`, `ebook_cms_book`.`slug`, `ebook_cms_book`.`author_name`, `ebook_cms_book`.`genre_name`, `ebook_cms_book`.`status`, `ebook_cms_book`.`cover_image_url`, `ebook_cms_book`.`summary`, `ebook_cms_book`.`epub_download_url`, `ebook_cms_book`.`epub_mime_type`, `ebook_cms_book`.`epub_sha256`, `ebook_cms_book`.`published_at`, `ebook_cms_book`.`updated_at` from `ebook_cms_book` order by `ebook_cms_book`.`id`';
        $ret = $mtooldb->execute($last_sql_command_for_mtooldb, [
        ]);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new EbookCmsBookData();
            $thisresult->id = $thisline[0];
            $thisresult->title = $thisline[1];
            $thisresult->slug = $thisline[2];
            $thisresult->authorName = $thisline[3];
            $thisresult->genreName = $thisline[4];
            $thisresult->status = $thisline[5];
            $thisresult->coverImageUrl = $thisline[6];
            $thisresult->summary = $thisline[7];
            $thisresult->epubDownloadUrl = $thisline[8];
            $thisresult->epubMimeType = $thisline[9];
            $thisresult->epubSha256 = $thisline[10];
            $thisresult->publishedAt = $thisline[11];
            $thisresult->updatedAt = $thisline[12];
            array_push($result, $thisresult);
        }
        return $result;
    }

    // source_of_truth=manual class_source=manual action_type=SELECTSINGLE order=60 generation=canonical-bootstrap
    // reason=generated from canonical table metadata without legacy runtime source
    public function GetEditorEbookCmsChapter($param_EbookCmsChapter_Id_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'select `ebook_cms_book`.`id`, `ebook_cms_book`.`title`, `ebook_cms_book`.`slug`, `ebook_cms_book`.`author_name`, `ebook_cms_book`.`genre_name`, `ebook_cms_book`.`status`, `ebook_cms_book`.`cover_image_url`, `ebook_cms_book`.`summary`, `ebook_cms_book`.`epub_download_url`, `ebook_cms_book`.`epub_mime_type`, `ebook_cms_book`.`epub_sha256`, `ebook_cms_book`.`published_at`, `ebook_cms_book`.`updated_at` from `ebook_cms_book` where `ebook_cms_book`.`id` = ?';
        $ret = $mtooldb->execute($last_sql_command_for_mtooldb, [
            $param_EbookCmsChapter_Id_where,
        ]);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new EbookCmsBookData();
            $thisresult->id = $thisline[0];
            $thisresult->title = $thisline[1];
            $thisresult->slug = $thisline[2];
            $thisresult->authorName = $thisline[3];
            $thisresult->genreName = $thisline[4];
            $thisresult->status = $thisline[5];
            $thisresult->coverImageUrl = $thisline[6];
            $thisresult->summary = $thisline[7];
            $thisresult->epubDownloadUrl = $thisline[8];
            $thisresult->epubMimeType = $thisline[9];
            $thisresult->epubSha256 = $thisline[10];
            $thisresult->publishedAt = $thisline[11];
            $thisresult->updatedAt = $thisline[12];
            return $thisresult;
        }
        return NULL;
    }

    // source_of_truth=manual class_source=manual action_type=UPDATE order=70 generation=canonical-bootstrap
    // reason=generated from canonical table metadata without legacy runtime source
    public function UpdateEditorEbookCmsChapterDraft($EbookCmsChapterObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'update `ebook_cms_book` SET `title` = ?, `slug` = ?, `author_name` = ?, `genre_name` = ?, `status` = ?, `cover_image_url` = ?, `summary` = ?, `epub_download_url` = ?, `epub_mime_type` = ?, `epub_sha256` = ?, `published_at` = ?, `updated_at` = ? where `ebook_cms_book`.`id` = ?';
        $result = $mtooldb->execute($last_sql_command_for_mtooldb, [
            $EbookCmsChapterObj->title,
            $EbookCmsChapterObj->slug,
            $EbookCmsChapterObj->authorName,
            $EbookCmsChapterObj->genreName,
            $EbookCmsChapterObj->status,
            $EbookCmsChapterObj->coverImageUrl,
            $EbookCmsChapterObj->summary,
            $EbookCmsChapterObj->epubDownloadUrl,
            $EbookCmsChapterObj->epubMimeType,
            $EbookCmsChapterObj->epubSha256,
            $EbookCmsChapterObj->publishedAt,
            $EbookCmsChapterObj->updatedAt,
            $EbookCmsChapterObj->id,
        ]);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }

    // source_of_truth=manual class_source=manual action_type=UPDATE order=80 generation=canonical-bootstrap
    // reason=generated from canonical table metadata without legacy runtime source
    public function PublishEditorEbookCmsChapter($EbookCmsChapterObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'update `ebook_cms_book` SET `title` = ?, `slug` = ?, `author_name` = ?, `genre_name` = ?, `status` = ?, `cover_image_url` = ?, `summary` = ?, `epub_download_url` = ?, `epub_mime_type` = ?, `epub_sha256` = ?, `published_at` = ?, `updated_at` = ? where `ebook_cms_book`.`id` = ?';
        $result = $mtooldb->execute($last_sql_command_for_mtooldb, [
            $EbookCmsChapterObj->title,
            $EbookCmsChapterObj->slug,
            $EbookCmsChapterObj->authorName,
            $EbookCmsChapterObj->genreName,
            $EbookCmsChapterObj->status,
            $EbookCmsChapterObj->coverImageUrl,
            $EbookCmsChapterObj->summary,
            $EbookCmsChapterObj->epubDownloadUrl,
            $EbookCmsChapterObj->epubMimeType,
            $EbookCmsChapterObj->epubSha256,
            $EbookCmsChapterObj->publishedAt,
            $EbookCmsChapterObj->updatedAt,
            $EbookCmsChapterObj->id,
        ]);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }
}

?>