<?php

// AUTO-GENERATED BASE FILE.
// Do not edit this file manually or with AI/Codex.
// Keep customizations in the wrapper class and use this base file exactly as regenerated by the tool.

// Generated from canonical DB Access metadata.
// Base class generated from project_db_access_* metadata.

require_once __DIR__ . '/../_support/mtool_runtime_db.php';


class EbookCmsBookDBAccessBase
{
    public function __construct()
    {
    }

    // source_of_truth=manual class_source=manual action_type=SELECTLIST order=10 generation=canonical-bootstrap
    // reason=generated from canonical table metadata without legacy runtime source
    public function GetPublicEbookCmsBookList($limit)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $result = array();

        $last_sql_command_for_mtooldb = 'select `EbookCmsBook`.`Id`, `EbookCmsBook`.`Title`, `EbookCmsBook`.`Slug`, `EbookCmsBook`.`AuthorName`, `EbookCmsBook`.`GenreName`, `EbookCmsBook`.`Status`, `EbookCmsBook`.`CoverImageUrl`, `EbookCmsBook`.`Summary`, `EbookCmsBook`.`EpubDownloadUrl`, `EbookCmsBook`.`EpubMimeType`, `EbookCmsBook`.`EpubSha256`, `EbookCmsBook`.`PublishedAt`, `EbookCmsBook`.`UpdatedAt` from `EbookCmsBook` order by `EbookCmsBook`.`Id`';
        $ret = $mtooldb->execute($last_sql_command_for_mtooldb, [
        ]);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new EbookCmsBookData();
            $thisresult->Id = $thisline[0];
            $thisresult->Title = $thisline[1];
            $thisresult->Slug = $thisline[2];
            $thisresult->AuthorName = $thisline[3];
            $thisresult->GenreName = $thisline[4];
            $thisresult->Status = $thisline[5];
            $thisresult->CoverImageUrl = $thisline[6];
            $thisresult->Summary = $thisline[7];
            $thisresult->EpubDownloadUrl = $thisline[8];
            $thisresult->EpubMimeType = $thisline[9];
            $thisresult->EpubSha256 = $thisline[10];
            $thisresult->PublishedAt = $thisline[11];
            $thisresult->UpdatedAt = $thisline[12];
            array_push($result, $thisresult);
        }
        return $result;
    }

    // source_of_truth=manual class_source=manual action_type=SELECTSINGLE order=20 generation=canonical-bootstrap
    // reason=generated from canonical table metadata without legacy runtime source
    public function GetPublicEbookCmsBook($param_EbookCmsBook_Slug_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'select `EbookCmsBook`.`Id`, `EbookCmsBook`.`Title`, `EbookCmsBook`.`Slug`, `EbookCmsBook`.`AuthorName`, `EbookCmsBook`.`GenreName`, `EbookCmsBook`.`Status`, `EbookCmsBook`.`CoverImageUrl`, `EbookCmsBook`.`Summary`, `EbookCmsBook`.`EpubDownloadUrl`, `EbookCmsBook`.`EpubMimeType`, `EbookCmsBook`.`EpubSha256`, `EbookCmsBook`.`PublishedAt`, `EbookCmsBook`.`UpdatedAt` from `EbookCmsBook` where `EbookCmsBook`.`Id` = ?';
        $ret = $mtooldb->execute($last_sql_command_for_mtooldb, [
            $param_EbookCmsBook_Id_where,
        ]);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new EbookCmsBookData();
            $thisresult->Id = $thisline[0];
            $thisresult->Title = $thisline[1];
            $thisresult->Slug = $thisline[2];
            $thisresult->AuthorName = $thisline[3];
            $thisresult->GenreName = $thisline[4];
            $thisresult->Status = $thisline[5];
            $thisresult->CoverImageUrl = $thisline[6];
            $thisresult->Summary = $thisline[7];
            $thisresult->EpubDownloadUrl = $thisline[8];
            $thisresult->EpubMimeType = $thisline[9];
            $thisresult->EpubSha256 = $thisline[10];
            $thisresult->PublishedAt = $thisline[11];
            $thisresult->UpdatedAt = $thisline[12];
            return $thisresult;
        }
        return NULL;
    }

    // source_of_truth=manual class_source=manual action_type=SELECTLIST order=30 generation=canonical-bootstrap
    // reason=generated from canonical table metadata without legacy runtime source
    public function GetPublicEbookCmsChapterList($param_EbookCmsChapter_BookSlug_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $result = array();

        $last_sql_command_for_mtooldb = 'select `EbookCmsBook`.`Id`, `EbookCmsBook`.`Title`, `EbookCmsBook`.`Slug`, `EbookCmsBook`.`AuthorName`, `EbookCmsBook`.`GenreName`, `EbookCmsBook`.`Status`, `EbookCmsBook`.`CoverImageUrl`, `EbookCmsBook`.`Summary`, `EbookCmsBook`.`EpubDownloadUrl`, `EbookCmsBook`.`EpubMimeType`, `EbookCmsBook`.`EpubSha256`, `EbookCmsBook`.`PublishedAt`, `EbookCmsBook`.`UpdatedAt` from `EbookCmsBook` order by `EbookCmsBook`.`Id`';
        $ret = $mtooldb->execute($last_sql_command_for_mtooldb, [
        ]);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new EbookCmsBookData();
            $thisresult->Id = $thisline[0];
            $thisresult->Title = $thisline[1];
            $thisresult->Slug = $thisline[2];
            $thisresult->AuthorName = $thisline[3];
            $thisresult->GenreName = $thisline[4];
            $thisresult->Status = $thisline[5];
            $thisresult->CoverImageUrl = $thisline[6];
            $thisresult->Summary = $thisline[7];
            $thisresult->EpubDownloadUrl = $thisline[8];
            $thisresult->EpubMimeType = $thisline[9];
            $thisresult->EpubSha256 = $thisline[10];
            $thisresult->PublishedAt = $thisline[11];
            $thisresult->UpdatedAt = $thisline[12];
            array_push($result, $thisresult);
        }
        return $result;
    }

    // source_of_truth=manual class_source=manual action_type=SELECTSINGLE order=40 generation=canonical-bootstrap
    // reason=generated from canonical table metadata without legacy runtime source
    public function GetPublicEbookCmsChapter($param_EbookCmsChapter_BookSlug_where, $param_EbookCmsChapter_ChapterSlug_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'select `EbookCmsBook`.`Id`, `EbookCmsBook`.`Title`, `EbookCmsBook`.`Slug`, `EbookCmsBook`.`AuthorName`, `EbookCmsBook`.`GenreName`, `EbookCmsBook`.`Status`, `EbookCmsBook`.`CoverImageUrl`, `EbookCmsBook`.`Summary`, `EbookCmsBook`.`EpubDownloadUrl`, `EbookCmsBook`.`EpubMimeType`, `EbookCmsBook`.`EpubSha256`, `EbookCmsBook`.`PublishedAt`, `EbookCmsBook`.`UpdatedAt` from `EbookCmsBook` where `EbookCmsBook`.`Id` = ?';
        $ret = $mtooldb->execute($last_sql_command_for_mtooldb, [
            $param_EbookCmsBook_Id_where,
        ]);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new EbookCmsBookData();
            $thisresult->Id = $thisline[0];
            $thisresult->Title = $thisline[1];
            $thisresult->Slug = $thisline[2];
            $thisresult->AuthorName = $thisline[3];
            $thisresult->GenreName = $thisline[4];
            $thisresult->Status = $thisline[5];
            $thisresult->CoverImageUrl = $thisline[6];
            $thisresult->Summary = $thisline[7];
            $thisresult->EpubDownloadUrl = $thisline[8];
            $thisresult->EpubMimeType = $thisline[9];
            $thisresult->EpubSha256 = $thisline[10];
            $thisresult->PublishedAt = $thisline[11];
            $thisresult->UpdatedAt = $thisline[12];
            return $thisresult;
        }
        return NULL;
    }

    // source_of_truth=manual class_source=manual action_type=SELECTLIST order=50 generation=canonical-bootstrap
    // reason=generated from canonical table metadata without legacy runtime source
    public function GetPublicEbookCmsEpubDeliveryList($param_EbookCmsBook_Slug_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $result = array();

        $last_sql_command_for_mtooldb = 'select `EbookCmsBook`.`Id`, `EbookCmsBook`.`Title`, `EbookCmsBook`.`Slug`, `EbookCmsBook`.`AuthorName`, `EbookCmsBook`.`GenreName`, `EbookCmsBook`.`Status`, `EbookCmsBook`.`CoverImageUrl`, `EbookCmsBook`.`Summary`, `EbookCmsBook`.`EpubDownloadUrl`, `EbookCmsBook`.`EpubMimeType`, `EbookCmsBook`.`EpubSha256`, `EbookCmsBook`.`PublishedAt`, `EbookCmsBook`.`UpdatedAt` from `EbookCmsBook` order by `EbookCmsBook`.`Id`';
        $ret = $mtooldb->execute($last_sql_command_for_mtooldb, [
        ]);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new EbookCmsBookData();
            $thisresult->Id = $thisline[0];
            $thisresult->Title = $thisline[1];
            $thisresult->Slug = $thisline[2];
            $thisresult->AuthorName = $thisline[3];
            $thisresult->GenreName = $thisline[4];
            $thisresult->Status = $thisline[5];
            $thisresult->CoverImageUrl = $thisline[6];
            $thisresult->Summary = $thisline[7];
            $thisresult->EpubDownloadUrl = $thisline[8];
            $thisresult->EpubMimeType = $thisline[9];
            $thisresult->EpubSha256 = $thisline[10];
            $thisresult->PublishedAt = $thisline[11];
            $thisresult->UpdatedAt = $thisline[12];
            array_push($result, $thisresult);
        }
        return $result;
    }

    // source_of_truth=manual class_source=manual action_type=SELECTSINGLE order=60 generation=canonical-bootstrap
    // reason=generated from canonical table metadata without legacy runtime source
    public function GetEditorEbookCmsChapter($param_EbookCmsChapter_Id_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'select `EbookCmsBook`.`Id`, `EbookCmsBook`.`Title`, `EbookCmsBook`.`Slug`, `EbookCmsBook`.`AuthorName`, `EbookCmsBook`.`GenreName`, `EbookCmsBook`.`Status`, `EbookCmsBook`.`CoverImageUrl`, `EbookCmsBook`.`Summary`, `EbookCmsBook`.`EpubDownloadUrl`, `EbookCmsBook`.`EpubMimeType`, `EbookCmsBook`.`EpubSha256`, `EbookCmsBook`.`PublishedAt`, `EbookCmsBook`.`UpdatedAt` from `EbookCmsBook` where `EbookCmsBook`.`Id` = ?';
        $ret = $mtooldb->execute($last_sql_command_for_mtooldb, [
            $param_EbookCmsBook_Id_where,
        ]);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new EbookCmsBookData();
            $thisresult->Id = $thisline[0];
            $thisresult->Title = $thisline[1];
            $thisresult->Slug = $thisline[2];
            $thisresult->AuthorName = $thisline[3];
            $thisresult->GenreName = $thisline[4];
            $thisresult->Status = $thisline[5];
            $thisresult->CoverImageUrl = $thisline[6];
            $thisresult->Summary = $thisline[7];
            $thisresult->EpubDownloadUrl = $thisline[8];
            $thisresult->EpubMimeType = $thisline[9];
            $thisresult->EpubSha256 = $thisline[10];
            $thisresult->PublishedAt = $thisline[11];
            $thisresult->UpdatedAt = $thisline[12];
            return $thisresult;
        }
        return NULL;
    }

    // source_of_truth=manual class_source=manual action_type=UPDATE order=70 generation=canonical-bootstrap
    // reason=generated from canonical table metadata without legacy runtime source
    public function UpdateEditorEbookCmsChapterDraft($EbookCmsChapterObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'update `EbookCmsBook` SET `Title` = ?, `Slug` = ?, `AuthorName` = ?, `GenreName` = ?, `Status` = ?, `CoverImageUrl` = ?, `Summary` = ?, `EpubDownloadUrl` = ?, `EpubMimeType` = ?, `EpubSha256` = ?, `PublishedAt` = ?, `UpdatedAt` = ? where `EbookCmsBook`.`Id` = ?';
        $result = $mtooldb->execute($last_sql_command_for_mtooldb, [
            $EbookCmsBookObj->Title,
            $EbookCmsBookObj->Slug,
            $EbookCmsBookObj->AuthorName,
            $EbookCmsBookObj->GenreName,
            $EbookCmsBookObj->Status,
            $EbookCmsBookObj->CoverImageUrl,
            $EbookCmsBookObj->Summary,
            $EbookCmsBookObj->EpubDownloadUrl,
            $EbookCmsBookObj->EpubMimeType,
            $EbookCmsBookObj->EpubSha256,
            $EbookCmsBookObj->PublishedAt,
            $EbookCmsBookObj->UpdatedAt,
            $EbookCmsBookObj->Id,
        ]);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }

    // source_of_truth=manual class_source=manual action_type=UPDATE order=80 generation=canonical-bootstrap
    // reason=generated from canonical table metadata without legacy runtime source
    public function PublishEditorEbookCmsChapter($EbookCmsChapterObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'update `EbookCmsBook` SET `Title` = ?, `Slug` = ?, `AuthorName` = ?, `GenreName` = ?, `Status` = ?, `CoverImageUrl` = ?, `Summary` = ?, `EpubDownloadUrl` = ?, `EpubMimeType` = ?, `EpubSha256` = ?, `PublishedAt` = ?, `UpdatedAt` = ? where `EbookCmsBook`.`Id` = ?';
        $result = $mtooldb->execute($last_sql_command_for_mtooldb, [
            $EbookCmsBookObj->Title,
            $EbookCmsBookObj->Slug,
            $EbookCmsBookObj->AuthorName,
            $EbookCmsBookObj->GenreName,
            $EbookCmsBookObj->Status,
            $EbookCmsBookObj->CoverImageUrl,
            $EbookCmsBookObj->Summary,
            $EbookCmsBookObj->EpubDownloadUrl,
            $EbookCmsBookObj->EpubMimeType,
            $EbookCmsBookObj->EpubSha256,
            $EbookCmsBookObj->PublishedAt,
            $EbookCmsBookObj->UpdatedAt,
            $EbookCmsBookObj->Id,
        ]);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }
}

?>