<?php

// AUTO-GENERATED BASE FILE.
// Do not edit this file manually or with AI/Codex.
// Keep customizations in the wrapper class and use this base file exactly as regenerated by the tool.

// Generated by migrating a legacy data class.
// Generated members are kept in this base file. Former editable areas move to the wrapper file.
// Generated trailing enum-type classes also stay in this base file when present.

class ReqDataBase
{
    public $PID;
    public $TargetProjectPID;
    public $UserRequest;
    public $Summary;
    public $Analyzed;
    public $RequestIsBug;
    public $RequestIsFunc;
    public $RequestIsNonFuncUserbility;
    public $RequestIsNonFuncPerformance;
    public $RequestIsNonFuncReliability;
    public $RequestIsNonFuncSecurity;
    public $RequestIsNonFuncServiceability;
    public $RequestIsNonFuncInteroperability;
    public $RequestIsNonFuncSystemConstraints;
    public $Priority;
    public $status;
    public $AddedDateTime;
    public $UpdatedDateTime;
    public $StakeHolders;
    public $AssignedTo;
    public $ScheduledStartDate;
    public $Deadline;

    public function __construct()
    {
    }
}

?>
