<?php

// AUTO-GENERATED BASE FILE.
// Do not edit this file manually or with AI/Codex.
// Keep customizations in the wrapper/custom class and use this base file exactly as regenerated by the tool.

require_once __DIR__ . '/../_support/legacy-dbaccess/dbaccess-BuildToken.php';

// Generated from canonical DB Access metadata.
// Simple CRUD / joined select methods regenerate SQL when canonical metadata is sufficient.
// Known helper-style methods regenerate canonical PHP bodies when SQL regeneration is not the right fit.
// Remaining unsupported methods continue to delegate to copied legacy support under `_support/legacy-dbaccess/`.

class BuildTokenDBAccessBase extends BuildTokenDBAccessLegacy
{
    // source_of_truth=sync-bootstrap action_type=UNKNOWN order=11 generation=canonical-constructor
    // reason=bootstrap constructor is empty, so runtime owns the no-op constructor directly
    public function __construct()
    {
    }

    // source_of_truth=sync-bootstrap action_type=SELECTSINGLE order=14 generation=canonical-sql
    public function GetBuildToken($param_BuildToken_Token_where, $param_BuildToken_ProjectPID_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'select BuildToken.PID, BuildToken.Token, BuildToken.ProjectPID, BuildToken.IsOutputToTempFolder, BuildToken.IsOutputAfterCopyToTempFolder, BuildToken.IsQuickBuild, BuildToken.IsOutputDebugMessage, BuildToken.CreatedDateTime from BuildToken' . ' where ' . 'BuildToken.Token = ' . '\'' . $mtooldb->real_escape_string($param_BuildToken_Token_where) . '\'' . ' and ' . 'BuildToken.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($param_BuildToken_ProjectPID_where) . '\'';
        $ret = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new BuildTokenData();
            $thisresult->PID = $thisline[0];
            $thisresult->Token = $thisline[1];
            $thisresult->ProjectPID = $thisline[2];
            $thisresult->IsOutputToTempFolder = $thisline[3];
            $thisresult->IsOutputAfterCopyToTempFolder = $thisline[4];
            $thisresult->IsQuickBuild = $thisline[5];
            $thisresult->IsOutputDebugMessage = $thisline[6];
            $thisresult->CreatedDateTime = $thisline[7];
            return $thisresult;
        }
        return NULL;
    }

    // source_of_truth=sync-bootstrap action_type=INSERT order=43 generation=canonical-sql
    public function InsertBuildToken($BuildTokenObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'insert into BuildToken (Token, ProjectPID, IsOutputToTempFolder, IsOutputAfterCopyToTempFolder, IsQuickBuild, IsOutputDebugMessage) values(' . '\'' . $mtooldb->real_escape_string($BuildTokenObj->Token) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($BuildTokenObj->ProjectPID) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($BuildTokenObj->IsOutputToTempFolder) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($BuildTokenObj->IsOutputAfterCopyToTempFolder) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($BuildTokenObj->IsQuickBuild) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($BuildTokenObj->IsOutputDebugMessage) . '\'' . ')';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=DELETE order=59 generation=canonical-sql
    public function DeleteOld()
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'delete from BuildToken where ' . 'BuildToken.CreatedDateTime < ' . '(now() - interval 3 day)';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }
}

?>