<?php

// AUTO-GENERATED BASE FILE.
// Do not edit this file manually or with AI/Codex.
// Keep customizations in the wrapper/custom class and use this base file exactly as regenerated by the tool.

require_once __DIR__ . '/../_support/legacy-dbaccess/dbaccess-TestConditionSelection.php';

// Generated from canonical DB Access metadata.
// Simple CRUD / joined select methods regenerate SQL when canonical metadata is sufficient.
// Known helper-style methods regenerate canonical PHP bodies when SQL regeneration is not the right fit.
// Remaining unsupported methods continue to delegate to copied legacy support under `_support/legacy-dbaccess/`.

class TestConditionSelectionDBAccessBase extends TestConditionSelectionDBAccessLegacy
{
    // source_of_truth=sync-bootstrap action_type=UNKNOWN order=11 generation=canonical-constructor
    // reason=bootstrap constructor is empty, so runtime owns the no-op constructor directly
    public function __construct()
    {
    }

    // source_of_truth=seed-legacy action_type=SELECTLIST order=14 generation=canonical-sql
    public function GetTestConditionSelectionList($param_TestConditionSelection_ProjectPID_where, $param_TestConditionSelection_TestGroupPID_where, $param_TestConditionSelection_TestPID_where, $param_TestConditionSelection_TestConditionPID_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $result = array();

        $last_sql_command_for_mtooldb = 'select TestConditionSelection.ProjectPID, TestConditionSelection.TestGroupPID, TestConditionSelection.TestPID, TestConditionSelection.TestConditionPID, TestConditionSelection.PID, TestConditionSelection.Selection, TestConditionSelection.SelectionOrder, TestConditionSelection.IsNewest, TestConditionSelection.ResultExists from TestConditionSelection' . ' where ' . 'TestConditionSelection.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($param_TestConditionSelection_ProjectPID_where) . '\'' . ' and ' . 'TestConditionSelection.TestGroupPID = ' . '\'' . $mtooldb->real_escape_string($param_TestConditionSelection_TestGroupPID_where) . '\'' . ' and ' . 'TestConditionSelection.TestPID = ' . '\'' . $mtooldb->real_escape_string($param_TestConditionSelection_TestPID_where) . '\'' . ' and ' . 'TestConditionSelection.TestConditionPID = ' . '\'' . $mtooldb->real_escape_string($param_TestConditionSelection_TestConditionPID_where) . '\'' . ' order by TestConditionSelection.SelectionOrder,TestConditionSelection.PID';
        $ret = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new TestConditionSelectionData();
            $thisresult->ProjectPID = $thisline[0];
            $thisresult->TestGroupPID = $thisline[1];
            $thisresult->TestPID = $thisline[2];
            $thisresult->TestConditionPID = $thisline[3];
            $thisresult->PID = $thisline[4];
            $thisresult->Selection = $thisline[5];
            $thisresult->SelectionOrder = $thisline[6];
            $thisresult->IsNewest = $thisline[7];
            $thisresult->ResultExists = $thisline[8];
            array_push($result, $thisresult);
        }
        return $result;
    }

    // source_of_truth=seed-legacy action_type=SELECTLIST order=46 generation=canonical-sql
    public function GetNewestTestConditionSelectionList($param_TestConditionSelection_ProjectPID_where, $param_TestConditionSelection_TestGroupPID_where, $param_TestConditionSelection_TestPID_where, $param_TestConditionSelection_TestConditionPID_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $result = array();

        $last_sql_command_for_mtooldb = 'select TestConditionSelection.ProjectPID, TestConditionSelection.TestGroupPID, TestConditionSelection.TestPID, TestConditionSelection.TestConditionPID, TestConditionSelection.PID, TestConditionSelection.Selection, TestConditionSelection.SelectionOrder, TestConditionSelection.IsNewest, TestConditionSelection.ResultExists from TestConditionSelection' . ' where ' . 'TestConditionSelection.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($param_TestConditionSelection_ProjectPID_where) . '\'' . ' and ' . 'TestConditionSelection.TestGroupPID = ' . '\'' . $mtooldb->real_escape_string($param_TestConditionSelection_TestGroupPID_where) . '\'' . ' and ' . 'TestConditionSelection.TestPID = ' . '\'' . $mtooldb->real_escape_string($param_TestConditionSelection_TestPID_where) . '\'' . ' and ' . 'TestConditionSelection.TestConditionPID = ' . '\'' . $mtooldb->real_escape_string($param_TestConditionSelection_TestConditionPID_where) . '\'' . ' and ' . 'TestConditionSelection.IsNewest = ' . '\'' . $mtooldb->real_escape_string('1') . '\'' . ' order by TestConditionSelection.SelectionOrder,TestConditionSelection.PID';
        $ret = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new TestConditionSelectionData();
            $thisresult->ProjectPID = $thisline[0];
            $thisresult->TestGroupPID = $thisline[1];
            $thisresult->TestPID = $thisline[2];
            $thisresult->TestConditionPID = $thisline[3];
            $thisresult->PID = $thisline[4];
            $thisresult->Selection = $thisline[5];
            $thisresult->SelectionOrder = $thisline[6];
            $thisresult->IsNewest = $thisline[7];
            $thisresult->ResultExists = $thisline[8];
            array_push($result, $thisresult);
        }
        return $result;
    }

    // source_of_truth=seed-legacy action_type=SELECTLIST order=78 generation=canonical-sql
    public function GetNewestOrHasResultTestConditionSelectionList($param_TestConditionSelection_ProjectPID_where, $param_TestConditionSelection_TestGroupPID_where, $param_TestConditionSelection_TestPID_where, $param_TestConditionSelection_TestConditionPID_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $result = array();

        $last_sql_command_for_mtooldb = 'select TestConditionSelection.ProjectPID, TestConditionSelection.TestGroupPID, TestConditionSelection.TestPID, TestConditionSelection.TestConditionPID, TestConditionSelection.PID, TestConditionSelection.Selection, TestConditionSelection.SelectionOrder, TestConditionSelection.IsNewest, TestConditionSelection.ResultExists from TestConditionSelection' . ' where ' . 'TestConditionSelection.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($param_TestConditionSelection_ProjectPID_where) . '\'' . ' and ' . 'TestConditionSelection.TestGroupPID = ' . '\'' . $mtooldb->real_escape_string($param_TestConditionSelection_TestGroupPID_where) . '\'' . ' and ' . 'TestConditionSelection.TestPID = ' . '\'' . $mtooldb->real_escape_string($param_TestConditionSelection_TestPID_where) . '\'' . ' and ' . 'TestConditionSelection.TestConditionPID = ' . '\'' . $mtooldb->real_escape_string($param_TestConditionSelection_TestConditionPID_where) . '\'' . ' and ' . '(' . 'TestConditionSelection.IsNewest = ' . '\'' . $mtooldb->real_escape_string('1') . '\'' . ' or ' . 'TestConditionSelection.ResultExists = ' . '\'' . $mtooldb->real_escape_string('1') . '\'' . ')' . ' order by TestConditionSelection.SelectionOrder,TestConditionSelection.PID';
        $ret = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new TestConditionSelectionData();
            $thisresult->ProjectPID = $thisline[0];
            $thisresult->TestGroupPID = $thisline[1];
            $thisresult->TestPID = $thisline[2];
            $thisresult->TestConditionPID = $thisline[3];
            $thisresult->PID = $thisline[4];
            $thisresult->Selection = $thisline[5];
            $thisresult->SelectionOrder = $thisline[6];
            $thisresult->IsNewest = $thisline[7];
            $thisresult->ResultExists = $thisline[8];
            array_push($result, $thisresult);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=SELECTSINGLE order=110 generation=canonical-sql
    public function GetTestConditionSelection($param_TestConditionSelection_PID_where, $param_TestConditionSelection_ProjectPID_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'select TestConditionSelection.ProjectPID, TestConditionSelection.TestGroupPID, TestConditionSelection.TestPID, TestConditionSelection.TestConditionPID, TestConditionSelection.PID, TestConditionSelection.Selection, TestConditionSelection.SelectionOrder, TestConditionSelection.IsNewest, TestConditionSelection.ResultExists from TestConditionSelection' . ' where ' . 'TestConditionSelection.PID = ' . '\'' . $mtooldb->real_escape_string($param_TestConditionSelection_PID_where) . '\'' . ' and ' . 'TestConditionSelection.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($param_TestConditionSelection_ProjectPID_where) . '\'';
        $ret = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new TestConditionSelectionData();
            $thisresult->ProjectPID = $thisline[0];
            $thisresult->TestGroupPID = $thisline[1];
            $thisresult->TestPID = $thisline[2];
            $thisresult->TestConditionPID = $thisline[3];
            $thisresult->PID = $thisline[4];
            $thisresult->Selection = $thisline[5];
            $thisresult->SelectionOrder = $thisline[6];
            $thisresult->IsNewest = $thisline[7];
            $thisresult->ResultExists = $thisline[8];
            return $thisresult;
        }
        return NULL;
    }

    // source_of_truth=sync-bootstrap action_type=INSERT order=140 generation=canonical-sql
    public function InsertTestConditionSelection($TestConditionSelectionObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'insert into TestConditionSelection (ProjectPID, TestGroupPID, TestPID, TestConditionPID, Selection, SelectionOrder, IsNewest, ResultExists) values(' . '\'' . $mtooldb->real_escape_string($TestConditionSelectionObj->ProjectPID) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($TestConditionSelectionObj->TestGroupPID) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($TestConditionSelectionObj->TestPID) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($TestConditionSelectionObj->TestConditionPID) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($TestConditionSelectionObj->Selection) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($TestConditionSelectionObj->SelectionOrder) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($TestConditionSelectionObj->IsNewest) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($TestConditionSelectionObj->ResultExists) . '\'' . ')';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=UPDATE order=156 generation=canonical-sql
    public function UpdateTestConditionSelection($TestConditionSelectionObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'update TestConditionSelection SET ' . 'Selection = ' . '\'' . $mtooldb->real_escape_string($TestConditionSelectionObj->Selection) . '\'' . ', ' . 'SelectionOrder = ' . '\'' . $mtooldb->real_escape_string($TestConditionSelectionObj->SelectionOrder) . '\'' . ', ' . 'IsNewest = ' . '\'' . $mtooldb->real_escape_string($TestConditionSelectionObj->IsNewest) . '\'' . ' where ' . 'TestConditionSelection.PID = ' . '\'' . $mtooldb->real_escape_string($TestConditionSelectionObj->PID) . '\'' . ' and ' . 'TestConditionSelection.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($TestConditionSelectionObj->ProjectPID) . '\'';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=UPDATE order=172 generation=canonical-sql
    public function UpdateTestConditionSelectionSetToOld($TestConditionSelectionObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'update TestConditionSelection SET ' . 'IsNewest = ' . '\'' . $mtooldb->real_escape_string('0') . '\'' . ' where ' . 'TestConditionSelection.PID = ' . '\'' . $mtooldb->real_escape_string($TestConditionSelectionObj->PID) . '\'' . ' and ' . 'TestConditionSelection.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($TestConditionSelectionObj->ProjectPID) . '\'';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=DELETE order=188 generation=canonical-sql
    public function DeleteTestConditionSelection($TestConditionSelectionObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'delete from TestConditionSelection where ' . 'TestConditionSelection.PID = ' . '\'' . $mtooldb->real_escape_string($TestConditionSelectionObj->PID) . '\'' . ' and ' . 'TestConditionSelection.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($TestConditionSelectionObj->ProjectPID) . '\'';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }
}

?>