<?php

// AUTO-GENERATED BASE FILE.
// Do not edit this file manually or with AI/Codex.
// Keep customizations in the wrapper/custom class and use this base file exactly as regenerated by the tool.

require_once __DIR__ . '/../_support/legacy-dbaccess/dbaccess-Test_leftouterjoin_Project.php';

// Generated from canonical DB Access metadata.
// Simple CRUD / joined select methods regenerate SQL when canonical metadata is sufficient.
// Known helper-style methods regenerate canonical PHP bodies when SQL regeneration is not the right fit.
// Remaining unsupported methods continue to delegate to copied legacy support under `_support/legacy-dbaccess/`.

class Test_leftouterjoin_ProjectDBAccessBase extends Test_leftouterjoin_ProjectDBAccessLegacy
{
    // source_of_truth=sync-bootstrap action_type=UNKNOWN order=11 generation=canonical-constructor
    // reason=bootstrap constructor is empty, so runtime owns the no-op constructor directly
    public function __construct()
    {
    }

    // source_of_truth=seed-legacy action_type=SELECTLIST order=14 generation=canonical-sql
    public function GetTestList($param_Test_ProjectPID_where, $param_Test_TestGroupPID_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $result = array();

        $last_sql_command_for_mtooldb = 'select Test.ProjectPID, Test.TestGroupPID, Test.PID, Test.name, Test.UnitTestTargetClassName, Project.name, TestGroup.name from Test left outer join Project on Test.ProjectPID = Project.PID left outer join TestGroup on Test.TestGroupPID = TestGroup.PID' . ' where ' . 'Test.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($param_Test_ProjectPID_where) . '\'' . ' and ' . 'Test.TestGroupPID = ' . '\'' . $mtooldb->real_escape_string($param_Test_TestGroupPID_where) . '\'' . ' order by Test.PID';
        $ret = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new Test_leftouterjoin_ProjectData();
            $thisresult->ProjectPID = $thisline[0];
            $thisresult->TestGroupPID = $thisline[1];
            $thisresult->PID = $thisline[2];
            $thisresult->name = $thisline[3];
            $thisresult->UnitTestTargetClassName = $thisline[4];
            $thisresult->Projectname = $thisline[5];
            $thisresult->TestGroupname = $thisline[6];
            array_push($result, $thisresult);
        }
        return $result;
    }
}

?>