<?php

// AUTO-GENERATED BASE FILE.
// Do not edit this file manually or with AI/Codex.
// Keep customizations in the wrapper/custom class and use this base file exactly as regenerated by the tool.

require_once __DIR__ . '/../_support/legacy-dbaccess/dbaccess-BuildTokenTemplateCache.php';

// Generated from canonical DB Access metadata.
// Simple CRUD / joined select methods regenerate SQL when canonical metadata is sufficient.
// Known helper-style methods regenerate canonical PHP bodies when SQL regeneration is not the right fit.
// Remaining unsupported methods continue to delegate to copied legacy support under `_support/legacy-dbaccess/`.

class BuildTokenTemplateCacheDBAccessBase extends BuildTokenTemplateCacheDBAccessLegacy
{
    // source_of_truth=sync-bootstrap action_type=UNKNOWN order=11 generation=canonical-constructor
    // reason=bootstrap constructor is empty, so runtime owns the no-op constructor directly
    public function __construct()
    {
    }

    // source_of_truth=sync-bootstrap action_type=SELECTSINGLE order=14 generation=canonical-sql
    public function GetBuildTokenTemplateCache($param_BuildTokenTemplateCache_TemplateKey_where, $param_BuildTokenTemplateCache_ProjectPID_where, $param_BuildTokenTemplateCache_BuildTokenPID_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'select BuildTokenTemplateCache.PID, BuildTokenTemplateCache.ProjectPID, BuildTokenTemplateCache.BuildTokenPID, BuildTokenTemplateCache.TemplateKey, BuildTokenTemplateCache.FileExist, BuildTokenTemplateCache.Source from BuildTokenTemplateCache' . ' where ' . 'BuildTokenTemplateCache.TemplateKey = ' . '\'' . $mtooldb->real_escape_string($param_BuildTokenTemplateCache_TemplateKey_where) . '\'' . ' and ' . 'BuildTokenTemplateCache.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($param_BuildTokenTemplateCache_ProjectPID_where) . '\'' . ' and ' . 'BuildTokenTemplateCache.BuildTokenPID = ' . '\'' . $mtooldb->real_escape_string($param_BuildTokenTemplateCache_BuildTokenPID_where) . '\'';
        $ret = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new BuildTokenTemplateCacheData();
            $thisresult->PID = $thisline[0];
            $thisresult->ProjectPID = $thisline[1];
            $thisresult->BuildTokenPID = $thisline[2];
            $thisresult->TemplateKey = $thisline[3];
            $thisresult->FileExist = $thisline[4];
            $thisresult->Source = $thisline[5];
            return $thisresult;
        }
        return NULL;
    }

    // source_of_truth=sync-bootstrap action_type=INSERT order=41 generation=canonical-sql
    public function InsertBuildTokenTemplateCache($BuildTokenTemplateCacheObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'insert into BuildTokenTemplateCache (ProjectPID, BuildTokenPID, TemplateKey, FileExist, Source) values(' . '\'' . $mtooldb->real_escape_string($BuildTokenTemplateCacheObj->ProjectPID) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($BuildTokenTemplateCacheObj->BuildTokenPID) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($BuildTokenTemplateCacheObj->TemplateKey) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($BuildTokenTemplateCacheObj->FileExist) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($BuildTokenTemplateCacheObj->Source) . '\'' . ')';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=DELETE order=57 generation=canonical-sql
    public function DeleteOld()
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'delete from BuildTokenTemplateCache where ' . 'BuildTokenTemplateCache.BuildTokenPID not in ' . '(select PID from BuildToken)';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }
}

?>