<?php

// AUTO-GENERATED BASE FILE.
// Do not edit this file manually or with AI/Codex.
// Keep customizations in the wrapper/custom class and use this base file exactly as regenerated by the tool.

require_once __DIR__ . '/../_support/legacy-dbaccess/dbaccess-TestGroup_leftouterjoin_Project.php';

// Generated from canonical DB Access metadata.
// Simple CRUD / joined select methods regenerate SQL when canonical metadata is sufficient.
// Known helper-style methods regenerate canonical PHP bodies when SQL regeneration is not the right fit.
// Remaining unsupported methods continue to delegate to copied legacy support under `_support/legacy-dbaccess/`.

class TestGroup_leftouterjoin_ProjectDBAccessBase extends TestGroup_leftouterjoin_ProjectDBAccessLegacy
{
    // source_of_truth=sync-bootstrap action_type=UNKNOWN order=11 generation=canonical-constructor
    // reason=bootstrap constructor is empty, so runtime owns the no-op constructor directly
    public function __construct()
    {
    }

    // source_of_truth=seed-legacy action_type=SELECTLIST order=14 generation=canonical-sql
    public function GetTestGroupByOwnerOrUserSecurityList($param_ProjectUser_username_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $result = array();

        $last_sql_command_for_mtooldb = 'select Project.name, TestGroup.ProjectPID, TestGroup.PID, TestGroup.name, TestGroup.UnitTestTemplateBaseDir, TestGroup.UnitTestWorkingDir from Project join ProjectUser on ProjectUser.ProjectPID = Project.PID join TestGroup on ProjectUser.ProjectPID = TestGroup.ProjectPID' . ' where ' . 'ProjectUser.username = ' . '\'' . $mtooldb->real_escape_string($param_ProjectUser_username_where) . '\'' . ' order by TestGroup.name,TestGroup.PID';
        $ret = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new TestGroup_leftouterjoin_ProjectData();
            $thisresult->Projectname = $thisline[0];
            $thisresult->ProjectPID = $thisline[1];
            $thisresult->PID = $thisline[2];
            $thisresult->name = $thisline[3];
            $thisresult->UnitTestTemplateBaseDir = $thisline[4];
            $thisresult->UnitTestWorkingDir = $thisline[5];
            array_push($result, $thisresult);
        }
        return $result;
    }
}

?>