<?php

// AUTO-GENERATED BASE FILE.
// Do not edit this file manually or with AI/Codex.
// Keep customizations in the wrapper class and use this base file exactly as regenerated by the tool.

// Generated from canonical DB Access metadata.
// Base class generated from project_db_access_* metadata.

require_once __DIR__ . '/../_support/mtool_runtime_db.php';


class EbookCatalogItemDBAccessBase
{
    public function __construct()
    {
    }

    // source_of_truth=manual class_source=manual action_type=SELECTLIST order=10 generation=canonical-sql
    public function GetPublicEbookCatalogList($param_EbookCatalogItem_AuthorSlug_where, $param_EbookCatalogItem_GenreSlug_where, $param_EbookCatalogItem_SeriesSlug_where, $param_EbookCatalogItem_BookTitle_where, $limit)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $result = array();

        $last_sql_command_for_mtooldb = 'select distinct EbookCatalogItem.BookId, EbookCatalogItem.BookTitle, EbookCatalogItem.BookSlug, EbookCatalogItem.SeriesName, EbookCatalogItem.AuthorName, EbookCatalogItem.GenreName, EbookCatalogItem.PublishedAt, EbookCatalogItem.Summary, EbookCatalogItem.EpubStatus, EbookCatalogItem.PrimaryEpubUrl from EbookCatalogItem where EbookCatalogItem.Status = ? and EbookCatalogItem.AuthorSlug = ? and EbookCatalogItem.GenreSlug = ? and EbookCatalogItem.SeriesSlug = ? and EbookCatalogItem.BookTitle LIKE ? order by EbookCatalogItem.PublishedAt desc, EbookCatalogItem.BookId desc limit ?';
        $ret = $mtooldb->execute($last_sql_command_for_mtooldb, [
            'published',
            $param_EbookCatalogItem_AuthorSlug_where,
            $param_EbookCatalogItem_GenreSlug_where,
            $param_EbookCatalogItem_SeriesSlug_where,
            $param_EbookCatalogItem_BookTitle_where,
            $limit,
        ]);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new EbookCatalogItemData();
            $thisresult->BookId = $thisline[0];
            $thisresult->BookTitle = $thisline[1];
            $thisresult->BookSlug = $thisline[2];
            $thisresult->SeriesName = $thisline[3];
            $thisresult->AuthorName = $thisline[4];
            $thisresult->GenreName = $thisline[5];
            $thisresult->PublishedAt = $thisline[6];
            $thisresult->Summary = $thisline[7];
            $thisresult->EpubStatus = $thisline[8];
            $thisresult->PrimaryEpubUrl = $thisline[9];
            array_push($result, $thisresult);
        }
        return $result;
    }

    // source_of_truth=manual class_source=manual action_type=SELECTSINGLE order=20 generation=canonical-sql
    public function GetPublicEbookBook($param_EbookCatalogItem_BookSlug_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'select distinct EbookCatalogItem.BookId, EbookCatalogItem.BookTitle, EbookCatalogItem.BookSlug, EbookCatalogItem.SeriesName, EbookCatalogItem.AuthorName, EbookCatalogItem.GenreName, EbookCatalogItem.PublishedAt, EbookCatalogItem.Summary, EbookCatalogItem.EpubStatus, EbookCatalogItem.PrimaryEpubUrl from EbookCatalogItem where EbookCatalogItem.Status = ? and EbookCatalogItem.BookSlug = ?';
        $ret = $mtooldb->execute($last_sql_command_for_mtooldb, [
            'published',
            $param_EbookCatalogItem_BookSlug_where,
        ]);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new EbookCatalogItemData();
            $thisresult->BookId = $thisline[0];
            $thisresult->BookTitle = $thisline[1];
            $thisresult->BookSlug = $thisline[2];
            $thisresult->SeriesName = $thisline[3];
            $thisresult->AuthorName = $thisline[4];
            $thisresult->GenreName = $thisline[5];
            $thisresult->PublishedAt = $thisline[6];
            $thisresult->Summary = $thisline[7];
            $thisresult->EpubStatus = $thisline[8];
            $thisresult->PrimaryEpubUrl = $thisline[9];
            return $thisresult;
        }
        return NULL;
    }
}

?>