name: mtool-sample-sample07-dbaccess-crud-basic-sqlite

services:
  web-admin:
    environment:
      APP_WORK_ROOT: /var/www/work/sample-packs/sample07-dbaccess-crud-basic-sqlite

  web-lab:
    environment:
      APP_WORK_ROOT: /var/www/work/sample-packs/sample07-dbaccess-crud-basic-sqlite
