<?php

// AUTO-GENERATED BASE FILE.
// Do not edit this file manually or with AI/Codex.
// Keep customizations in the wrapper/custom class and use this base file exactly as regenerated by the tool.

require_once __DIR__ . '/../_support/legacy-dbaccess/dbaccess-Req_and_Project.php';

// Generated from canonical DB Access metadata.
// Simple CRUD / joined select methods regenerate SQL when canonical metadata is sufficient.
// Known helper-style methods regenerate canonical PHP bodies when SQL regeneration is not the right fit.
// Remaining unsupported methods continue to delegate to copied legacy support under `_support/legacy-dbaccess/`.

class Req_and_ProjectDBAccessBase extends Req_and_ProjectDBAccessLegacy
{
    // source_of_truth=sync-bootstrap action_type=UNKNOWN order=11 generation=canonical-constructor
    // reason=bootstrap constructor is empty, so runtime owns the no-op constructor directly
    public function __construct()
    {
    }

    // source_of_truth=sync-bootstrap action_type=SELECTLIST order=14 generation=canonical-sql
    public function GetReqbyOwnerOrUserSecurityList($param_ProjectUser_username_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $result = array();

        $last_sql_command_for_mtooldb = 'select Req.PID, Req.TargetProjectPID, Req.UserRequest, Req.Summary, Req.Analyzed, Req.RequestIsBug, Req.RequestIsFunc, Req.RequestIsNonFuncUserbility, Req.RequestIsNonFuncPerformance, Req.RequestIsNonFuncReliability, Req.RequestIsNonFuncSecurity, Req.RequestIsNonFuncServiceability, Req.RequestIsNonFuncInteroperability, Req.RequestIsNonFuncSystemConstraints, Req.Priority, Req.status, Req.AddedDateTime, Req.UpdatedDateTime, Req.StakeHolders, Req.AssignedTo, Req.ScheduledStartDate, Req.Deadline, Project.name from Req join ProjectUser on ProjectUser.ProjectPID = Req.TargetProjectPID left outer join Project on Req.TargetProjectPID = Project.PID' . ' where ' . 'ProjectUser.username = ' . '\'' . $mtooldb->real_escape_string($param_ProjectUser_username_where) . '\'';
        $ret = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new Req_and_ProjectData();
            $thisresult->PID = $thisline[0];
            $thisresult->TargetProjectPID = $thisline[1];
            $thisresult->UserRequest = $thisline[2];
            $thisresult->Summary = $thisline[3];
            $thisresult->Analyzed = $thisline[4];
            $thisresult->RequestIsBug = $thisline[5];
            $thisresult->RequestIsFunc = $thisline[6];
            $thisresult->RequestIsNonFuncUserbility = $thisline[7];
            $thisresult->RequestIsNonFuncPerformance = $thisline[8];
            $thisresult->RequestIsNonFuncReliability = $thisline[9];
            $thisresult->RequestIsNonFuncSecurity = $thisline[10];
            $thisresult->RequestIsNonFuncServiceability = $thisline[11];
            $thisresult->RequestIsNonFuncInteroperability = $thisline[12];
            $thisresult->RequestIsNonFuncSystemConstraints = $thisline[13];
            $thisresult->Priority = $thisline[14];
            $thisresult->status = $thisline[15];
            $thisresult->AddedDateTime = $thisline[16];
            $thisresult->UpdatedDateTime = $thisline[17];
            $thisresult->StakeHolders = $thisline[18];
            $thisresult->AssignedTo = $thisline[19];
            $thisresult->ScheduledStartDate = $thisline[20];
            $thisresult->Deadline = $thisline[21];
            $thisresult->Projectname = $thisline[22];
            array_push($result, $thisresult);
        }
        return $result;
    }
}

?>