<?php

// AUTO-GENERATED BASE FILE.
// Do not edit this file manually or with AI/Codex.
// Keep customizations in the wrapper/custom class and use this base file exactly as regenerated by the tool.

require_once __DIR__ . '/../_support/legacy-dbaccess/dbaccess-dafuncupdatedeletewhere.php';

// Generated from canonical DB Access metadata.
// Simple CRUD / joined select methods regenerate SQL when canonical metadata is sufficient.
// Known helper-style methods regenerate canonical PHP bodies when SQL regeneration is not the right fit.
// Remaining unsupported methods continue to delegate to copied legacy support under `_support/legacy-dbaccess/`.

class dafuncupdatedeletewhereDBAccessBase extends dafuncupdatedeletewhereDBAccessLegacy
{
    // source_of_truth=sync-bootstrap action_type=UNKNOWN order=11 generation=canonical-constructor
    // reason=bootstrap constructor is empty, so runtime owns the no-op constructor directly
    public function __construct()
    {
    }

    // source_of_truth=seed-legacy action_type=SELECTLIST order=14 generation=canonical-sql
    public function GetdafuncupdatedeletewhereList($param_dafuncupdatedeletewhere_ProjectPID_where, $param_dafuncupdatedeletewhere_daPID_where, $param_dafuncupdatedeletewhere_dafuncPID_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $result = array();

        $last_sql_command_for_mtooldb = 'select dafuncupdatedeletewhere.ProjectPID, dafuncupdatedeletewhere.daPID, dafuncupdatedeletewhere.dafuncPID, dafuncupdatedeletewhere.PID, dafuncupdatedeletewhere.targetTableColumnName, dafuncupdatedeletewhere.ParameterType, dafuncupdatedeletewhere.ParameterDataType, dafuncupdatedeletewhere.FixedParameter, dafuncupdatedeletewhere.ORGroup, dafuncupdatedeletewhere.RelationalOperator, dafuncupdatedeletewhere.WhereOrder from dafuncupdatedeletewhere' . ' where ' . 'dafuncupdatedeletewhere.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($param_dafuncupdatedeletewhere_ProjectPID_where) . '\'' . ' and ' . 'dafuncupdatedeletewhere.daPID = ' . '\'' . $mtooldb->real_escape_string($param_dafuncupdatedeletewhere_daPID_where) . '\'' . ' and ' . 'dafuncupdatedeletewhere.dafuncPID = ' . '\'' . $mtooldb->real_escape_string($param_dafuncupdatedeletewhere_dafuncPID_where) . '\'' . ' order by dafuncupdatedeletewhere.WhereOrder,dafuncupdatedeletewhere.PID';
        $ret = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new dafuncupdatedeletewhereData();
            $thisresult->ProjectPID = $thisline[0];
            $thisresult->daPID = $thisline[1];
            $thisresult->dafuncPID = $thisline[2];
            $thisresult->PID = $thisline[3];
            $thisresult->targetTableColumnName = $thisline[4];
            $thisresult->ParameterType = $thisline[5];
            $thisresult->ParameterDataType = $thisline[6];
            $thisresult->FixedParameter = $thisline[7];
            $thisresult->ORGroup = $thisline[8];
            $thisresult->RelationalOperator = $thisline[9];
            $thisresult->WhereOrder = $thisline[10];
            array_push($result, $thisresult);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=SELECTSINGLE order=48 generation=canonical-sql
    public function Getdafuncupdatedeletewhere($param_dafuncupdatedeletewhere_PID_where, $param_dafuncupdatedeletewhere_ProjectPID_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'select dafuncupdatedeletewhere.ProjectPID, dafuncupdatedeletewhere.daPID, dafuncupdatedeletewhere.dafuncPID, dafuncupdatedeletewhere.PID, dafuncupdatedeletewhere.targetTableColumnName, dafuncupdatedeletewhere.ParameterType, dafuncupdatedeletewhere.ParameterDataType, dafuncupdatedeletewhere.FixedParameter, dafuncupdatedeletewhere.ORGroup, dafuncupdatedeletewhere.RelationalOperator, dafuncupdatedeletewhere.WhereOrder from dafuncupdatedeletewhere' . ' where ' . 'dafuncupdatedeletewhere.PID = ' . '\'' . $mtooldb->real_escape_string($param_dafuncupdatedeletewhere_PID_where) . '\'' . ' and ' . 'dafuncupdatedeletewhere.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($param_dafuncupdatedeletewhere_ProjectPID_where) . '\'';
        $ret = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new dafuncupdatedeletewhereData();
            $thisresult->ProjectPID = $thisline[0];
            $thisresult->daPID = $thisline[1];
            $thisresult->dafuncPID = $thisline[2];
            $thisresult->PID = $thisline[3];
            $thisresult->targetTableColumnName = $thisline[4];
            $thisresult->ParameterType = $thisline[5];
            $thisresult->ParameterDataType = $thisline[6];
            $thisresult->FixedParameter = $thisline[7];
            $thisresult->ORGroup = $thisline[8];
            $thisresult->RelationalOperator = $thisline[9];
            $thisresult->WhereOrder = $thisline[10];
            return $thisresult;
        }
        return NULL;
    }

    // source_of_truth=sync-bootstrap action_type=INSERT order=80 generation=canonical-sql
    public function Insertdafuncupdatedeletewhere($dafuncupdatedeletewhereObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'insert into dafuncupdatedeletewhere (ProjectPID, daPID, dafuncPID, targetTableColumnName, ParameterType, ParameterDataType, FixedParameter, ORGroup, RelationalOperator) values(' . '\'' . $mtooldb->real_escape_string($dafuncupdatedeletewhereObj->ProjectPID) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($dafuncupdatedeletewhereObj->daPID) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($dafuncupdatedeletewhereObj->dafuncPID) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($dafuncupdatedeletewhereObj->targetTableColumnName) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($dafuncupdatedeletewhereObj->ParameterType) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($dafuncupdatedeletewhereObj->ParameterDataType) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($dafuncupdatedeletewhereObj->FixedParameter) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($dafuncupdatedeletewhereObj->ORGroup) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($dafuncupdatedeletewhereObj->RelationalOperator) . '\'' . ')';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=UPDATE order=96 generation=canonical-sql
    public function Updatedafuncupdatedeletewhere($dafuncupdatedeletewhereObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'update dafuncupdatedeletewhere SET ' . 'targetTableColumnName = ' . '\'' . $mtooldb->real_escape_string($dafuncupdatedeletewhereObj->targetTableColumnName) . '\'' . ', ' . 'ParameterType = ' . '\'' . $mtooldb->real_escape_string($dafuncupdatedeletewhereObj->ParameterType) . '\'' . ', ' . 'ParameterDataType = ' . '\'' . $mtooldb->real_escape_string($dafuncupdatedeletewhereObj->ParameterDataType) . '\'' . ', ' . 'FixedParameter = ' . '\'' . $mtooldb->real_escape_string($dafuncupdatedeletewhereObj->FixedParameter) . '\'' . ', ' . 'ORGroup = ' . '\'' . $mtooldb->real_escape_string($dafuncupdatedeletewhereObj->ORGroup) . '\'' . ', ' . 'RelationalOperator = ' . '\'' . $mtooldb->real_escape_string($dafuncupdatedeletewhereObj->RelationalOperator) . '\'' . ' where ' . 'dafuncupdatedeletewhere.PID = ' . '\'' . $mtooldb->real_escape_string($dafuncupdatedeletewhereObj->PID) . '\'' . ' and ' . 'dafuncupdatedeletewhere.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($dafuncupdatedeletewhereObj->ProjectPID) . '\'';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=DELETE order=112 generation=canonical-sql
    public function Deletedafuncupdatedeletewhere($param_dafuncupdatedeletewhere_PID_where, $param_dafuncupdatedeletewhere_ProjectPID_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'delete from dafuncupdatedeletewhere where ' . 'dafuncupdatedeletewhere.PID = ' . '\'' . $mtooldb->real_escape_string($param_dafuncupdatedeletewhere_PID_where) . '\'' . ' and ' . 'dafuncupdatedeletewhere.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($param_dafuncupdatedeletewhere_ProjectPID_where) . '\'';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=UPDATE order=128 generation=canonical-sql
    public function UpdatedafuncupdatedeletewhereOrder($param_dafuncupdatedeletewhere_WhereOrder_update, $param_dafuncupdatedeletewhere_PID_where, $param_dafuncupdatedeletewhere_ProjectPID_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'update dafuncupdatedeletewhere SET ' . 'WhereOrder = ' . $param_dafuncupdatedeletewhere_WhereOrder_update . ' where ' . 'dafuncupdatedeletewhere.PID = ' . '\'' . $mtooldb->real_escape_string($param_dafuncupdatedeletewhere_PID_where) . '\'' . ' and ' . 'dafuncupdatedeletewhere.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($param_dafuncupdatedeletewhere_ProjectPID_where) . '\'';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=UPDATE order=144 generation=canonical-sql
    public function UpdateDAPIDforMovingFunction($param_dafuncupdatedeletewhere_daPID_update, $param_dafuncupdatedeletewhere_ProjectPID_where, $param_dafuncupdatedeletewhere_dafuncPID_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'update dafuncupdatedeletewhere SET ' . 'daPID = ' . '\'' . $mtooldb->real_escape_string($param_dafuncupdatedeletewhere_daPID_update) . '\'' . ' where ' . 'dafuncupdatedeletewhere.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($param_dafuncupdatedeletewhere_ProjectPID_where) . '\'' . ' and ' . 'dafuncupdatedeletewhere.dafuncPID = ' . '\'' . $mtooldb->real_escape_string($param_dafuncupdatedeletewhere_dafuncPID_where) . '\'';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }
}

?>