<?php

// AUTO-GENERATED BASE FILE.
// Do not edit this file manually or with AI/Codex.
// Keep customizations in the wrapper/custom class and use this base file exactly as regenerated by the tool.

require_once __DIR__ . '/../_support/legacy-dbaccess/dbaccess-Server.php';

// Generated from canonical DB Access metadata.
// Simple CRUD / joined select methods regenerate SQL when canonical metadata is sufficient.
// Known helper-style methods regenerate canonical PHP bodies when SQL regeneration is not the right fit.
// Remaining unsupported methods continue to delegate to copied legacy support under `_support/legacy-dbaccess/`.

class ServerDBAccessBase extends ServerDBAccessLegacy
{
    // source_of_truth=sync-bootstrap action_type=UNKNOWN order=11 generation=canonical-constructor
    // reason=bootstrap constructor is empty, so runtime owns the no-op constructor directly
    public function __construct()
    {
    }

    // source_of_truth=seed-legacy action_type=SELECTLIST order=14 generation=canonical-sql
    public function GetServerList($param_Server_SettingGroupPID_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $result = array();

        $last_sql_command_for_mtooldb = 'select Server.PID, Server.SettingGroupPID, Server.LocalServerName, Server.IP, Server.IsCommonForAllSettingGroupForUpload, Server.IsCommonForAllSettingGroupForDBServer, Server.IsCommonForAllSettingGroupForDBClient from Server' . ' where ' . 'Server.SettingGroupPID = ' . '\'' . $mtooldb->real_escape_string($param_Server_SettingGroupPID_where) . '\'' . ' order by Server.LocalServerName,Server.IP,Server.PID';
        $ret = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new ServerData();
            $thisresult->PID = $thisline[0];
            $thisresult->SettingGroupPID = $thisline[1];
            $thisresult->LocalServerName = $thisline[2];
            $thisresult->IP = $thisline[3];
            $thisresult->IsCommonForAllSettingGroupForUpload = $thisline[4];
            $thisresult->IsCommonForAllSettingGroupForDBServer = $thisline[5];
            $thisresult->IsCommonForAllSettingGroupForDBClient = $thisline[6];
            array_push($result, $thisresult);
        }
        return $result;
    }

    // source_of_truth=seed-legacy action_type=SELECTLIST order=44 generation=canonical-sql
    public function GetSpecificOrAnyCommonServerList($param_Server_SettingGroupPID_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $result = array();

        $last_sql_command_for_mtooldb = 'select Server.PID, Server.SettingGroupPID, Server.LocalServerName, Server.IP, Server.IsCommonForAllSettingGroupForUpload, Server.IsCommonForAllSettingGroupForDBServer, Server.IsCommonForAllSettingGroupForDBClient from Server' . ' where ' . '(' . 'Server.SettingGroupPID = ' . '\'' . $mtooldb->real_escape_string($param_Server_SettingGroupPID_where) . '\'' . ' or ' . 'Server.IsCommonForAllSettingGroupForUpload = ' . '\'' . $mtooldb->real_escape_string('1') . '\'' . ' or ' . 'Server.IsCommonForAllSettingGroupForDBServer = ' . '\'' . $mtooldb->real_escape_string('1') . '\'' . ' or ' . 'Server.IsCommonForAllSettingGroupForDBClient = ' . '\'' . $mtooldb->real_escape_string('1') . '\'' . ')' . ' order by Server.LocalServerName,Server.IP,Server.PID';
        $ret = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new ServerData();
            $thisresult->PID = $thisline[0];
            $thisresult->SettingGroupPID = $thisline[1];
            $thisresult->LocalServerName = $thisline[2];
            $thisresult->IP = $thisline[3];
            $thisresult->IsCommonForAllSettingGroupForUpload = $thisline[4];
            $thisresult->IsCommonForAllSettingGroupForDBServer = $thisline[5];
            $thisresult->IsCommonForAllSettingGroupForDBClient = $thisline[6];
            array_push($result, $thisresult);
        }
        return $result;
    }

    // source_of_truth=seed-legacy action_type=SELECTLIST order=74 generation=canonical-sql
    public function GetSpecificOrCommonUploadServerList($param_Server_SettingGroupPID_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $result = array();

        $last_sql_command_for_mtooldb = 'select Server.PID, Server.SettingGroupPID, Server.LocalServerName, Server.IP, Server.IsCommonForAllSettingGroupForUpload, Server.IsCommonForAllSettingGroupForDBServer, Server.IsCommonForAllSettingGroupForDBClient from Server' . ' where ' . '(' . 'Server.SettingGroupPID = ' . '\'' . $mtooldb->real_escape_string($param_Server_SettingGroupPID_where) . '\'' . ' or ' . 'Server.IsCommonForAllSettingGroupForUpload = ' . '\'' . $mtooldb->real_escape_string('1') . '\'' . ')' . ' order by Server.IsCommonForAllSettingGroupForUpload desc,Server.LocalServerName,Server.IP,Server.PID';
        $ret = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new ServerData();
            $thisresult->PID = $thisline[0];
            $thisresult->SettingGroupPID = $thisline[1];
            $thisresult->LocalServerName = $thisline[2];
            $thisresult->IP = $thisline[3];
            $thisresult->IsCommonForAllSettingGroupForUpload = $thisline[4];
            $thisresult->IsCommonForAllSettingGroupForDBServer = $thisline[5];
            $thisresult->IsCommonForAllSettingGroupForDBClient = $thisline[6];
            array_push($result, $thisresult);
        }
        return $result;
    }

    // source_of_truth=seed-legacy action_type=SELECTLIST order=104 generation=canonical-sql
    public function GetSpecificOrCommonDBServerList($param_Server_SettingGroupPID_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $result = array();

        $last_sql_command_for_mtooldb = 'select Server.PID, Server.SettingGroupPID, Server.LocalServerName, Server.IP, Server.IsCommonForAllSettingGroupForUpload, Server.IsCommonForAllSettingGroupForDBServer, Server.IsCommonForAllSettingGroupForDBClient from Server' . ' where ' . '(' . 'Server.SettingGroupPID = ' . '\'' . $mtooldb->real_escape_string($param_Server_SettingGroupPID_where) . '\'' . ' or ' . 'Server.IsCommonForAllSettingGroupForDBServer = ' . '\'' . $mtooldb->real_escape_string('1') . '\'' . ')' . ' order by Server.IsCommonForAllSettingGroupForDBServer desc,Server.LocalServerName,Server.IP,Server.PID';
        $ret = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new ServerData();
            $thisresult->PID = $thisline[0];
            $thisresult->SettingGroupPID = $thisline[1];
            $thisresult->LocalServerName = $thisline[2];
            $thisresult->IP = $thisline[3];
            $thisresult->IsCommonForAllSettingGroupForUpload = $thisline[4];
            $thisresult->IsCommonForAllSettingGroupForDBServer = $thisline[5];
            $thisresult->IsCommonForAllSettingGroupForDBClient = $thisline[6];
            array_push($result, $thisresult);
        }
        return $result;
    }

    // source_of_truth=seed-legacy action_type=SELECTLIST order=134 generation=canonical-sql
    public function GetSpecificOrCommonDBClientList($param_Server_SettingGroupPID_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $result = array();

        $last_sql_command_for_mtooldb = 'select Server.PID, Server.SettingGroupPID, Server.LocalServerName, Server.IP, Server.IsCommonForAllSettingGroupForUpload, Server.IsCommonForAllSettingGroupForDBServer, Server.IsCommonForAllSettingGroupForDBClient from Server' . ' where ' . '(' . 'Server.SettingGroupPID = ' . '\'' . $mtooldb->real_escape_string($param_Server_SettingGroupPID_where) . '\'' . ' or ' . 'Server.IsCommonForAllSettingGroupForDBClient = ' . '\'' . $mtooldb->real_escape_string('1') . '\'' . ')' . ' order by Server.IsCommonForAllSettingGroupForDBClient desc,Server.LocalServerName,Server.IP,Server.PID';
        $ret = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new ServerData();
            $thisresult->PID = $thisline[0];
            $thisresult->SettingGroupPID = $thisline[1];
            $thisresult->LocalServerName = $thisline[2];
            $thisresult->IP = $thisline[3];
            $thisresult->IsCommonForAllSettingGroupForUpload = $thisline[4];
            $thisresult->IsCommonForAllSettingGroupForDBServer = $thisline[5];
            $thisresult->IsCommonForAllSettingGroupForDBClient = $thisline[6];
            array_push($result, $thisresult);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=SELECTSINGLE order=164 generation=canonical-sql
    public function GetServer($param_Server_PID_where, $param_Server_SettingGroupPID_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'select Server.PID, Server.SettingGroupPID, Server.LocalServerName, Server.IP, Server.IsCommonForAllSettingGroupForUpload, Server.IsCommonForAllSettingGroupForDBServer, Server.IsCommonForAllSettingGroupForDBClient from Server' . ' where ' . 'Server.PID = ' . '\'' . $mtooldb->real_escape_string($param_Server_PID_where) . '\'' . ' and ' . 'Server.SettingGroupPID = ' . '\'' . $mtooldb->real_escape_string($param_Server_SettingGroupPID_where) . '\'';
        $ret = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new ServerData();
            $thisresult->PID = $thisline[0];
            $thisresult->SettingGroupPID = $thisline[1];
            $thisresult->LocalServerName = $thisline[2];
            $thisresult->IP = $thisline[3];
            $thisresult->IsCommonForAllSettingGroupForUpload = $thisline[4];
            $thisresult->IsCommonForAllSettingGroupForDBServer = $thisline[5];
            $thisresult->IsCommonForAllSettingGroupForDBClient = $thisline[6];
            return $thisresult;
        }
        return NULL;
    }

    // source_of_truth=sync-bootstrap action_type=SELECTSINGLE order=192 generation=canonical-sql
    public function GetServerOfAnySettingGroup($param_Server_PID_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'select Server.PID, Server.SettingGroupPID, Server.LocalServerName, Server.IP, Server.IsCommonForAllSettingGroupForUpload, Server.IsCommonForAllSettingGroupForDBServer, Server.IsCommonForAllSettingGroupForDBClient from Server' . ' where ' . 'Server.PID = ' . '\'' . $mtooldb->real_escape_string($param_Server_PID_where) . '\'';
        $ret = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new ServerData();
            $thisresult->PID = $thisline[0];
            $thisresult->SettingGroupPID = $thisline[1];
            $thisresult->LocalServerName = $thisline[2];
            $thisresult->IP = $thisline[3];
            $thisresult->IsCommonForAllSettingGroupForUpload = $thisline[4];
            $thisresult->IsCommonForAllSettingGroupForDBServer = $thisline[5];
            $thisresult->IsCommonForAllSettingGroupForDBClient = $thisline[6];
            return $thisresult;
        }
        return NULL;
    }

    // source_of_truth=sync-bootstrap action_type=INSERT order=220 generation=canonical-sql
    public function InsertServer($ServerObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'insert into Server (SettingGroupPID, LocalServerName, IP, IsCommonForAllSettingGroupForUpload, IsCommonForAllSettingGroupForDBServer, IsCommonForAllSettingGroupForDBClient) values(' . '\'' . $mtooldb->real_escape_string($ServerObj->SettingGroupPID) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($ServerObj->LocalServerName) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($ServerObj->IP) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($ServerObj->IsCommonForAllSettingGroupForUpload) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($ServerObj->IsCommonForAllSettingGroupForDBServer) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($ServerObj->IsCommonForAllSettingGroupForDBClient) . '\'' . ')';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=UPDATE order=236 generation=canonical-sql
    public function UpdateServer($ServerObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'update Server SET ' . 'LocalServerName = ' . '\'' . $mtooldb->real_escape_string($ServerObj->LocalServerName) . '\'' . ', ' . 'IP = ' . '\'' . $mtooldb->real_escape_string($ServerObj->IP) . '\'' . ', ' . 'IsCommonForAllSettingGroupForUpload = ' . '\'' . $mtooldb->real_escape_string($ServerObj->IsCommonForAllSettingGroupForUpload) . '\'' . ', ' . 'IsCommonForAllSettingGroupForDBServer = ' . '\'' . $mtooldb->real_escape_string($ServerObj->IsCommonForAllSettingGroupForDBServer) . '\'' . ', ' . 'IsCommonForAllSettingGroupForDBClient = ' . '\'' . $mtooldb->real_escape_string($ServerObj->IsCommonForAllSettingGroupForDBClient) . '\'' . ' where ' . 'Server.PID = ' . '\'' . $mtooldb->real_escape_string($ServerObj->PID) . '\'' . ' and ' . 'Server.SettingGroupPID = ' . '\'' . $mtooldb->real_escape_string($ServerObj->SettingGroupPID) . '\'';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=UPDATE order=252 generation=canonical-sql
    public function UpdateServerExceptCommonFlag($ServerObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'update Server SET ' . 'LocalServerName = ' . '\'' . $mtooldb->real_escape_string($ServerObj->LocalServerName) . '\'' . ', ' . 'IP = ' . '\'' . $mtooldb->real_escape_string($ServerObj->IP) . '\'' . ' where ' . 'Server.PID = ' . '\'' . $mtooldb->real_escape_string($ServerObj->PID) . '\'' . ' and ' . 'Server.SettingGroupPID = ' . '\'' . $mtooldb->real_escape_string($ServerObj->SettingGroupPID) . '\'';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=DELETE order=268 generation=canonical-sql
    public function DeleteServer($ServerObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'delete from Server where ' . 'Server.PID = ' . '\'' . $mtooldb->real_escape_string($ServerObj->PID) . '\'' . ' and ' . 'Server.SettingGroupPID = ' . '\'' . $mtooldb->real_escape_string($ServerObj->SettingGroupPID) . '\'';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }
}

?>