<?php

// AUTO-GENERATED BASE FILE.
// Do not edit this file manually or with AI/Codex.
// Keep customizations in the wrapper/custom class and use this base file exactly as regenerated by the tool.

require_once __DIR__ . '/../_support/legacy-dbaccess/dbaccess-LiveCheckResult.php';

// Generated from canonical DB Access metadata.
// Simple CRUD / joined select methods regenerate SQL when canonical metadata is sufficient.
// Known helper-style methods regenerate canonical PHP bodies when SQL regeneration is not the right fit.
// Remaining unsupported methods continue to delegate to copied legacy support under `_support/legacy-dbaccess/`.

class LiveCheckResultDBAccessBase extends LiveCheckResultDBAccessLegacy
{
    // source_of_truth=sync-bootstrap action_type=UNKNOWN order=11 generation=canonical-constructor
    // reason=bootstrap constructor is empty, so runtime owns the no-op constructor directly
    public function __construct()
    {
    }

    // source_of_truth=sync-bootstrap action_type=SELECTLIST order=14 generation=canonical-sql
    public function GetLiveCheckResultList($param_LiveCheckResult_CheckTargetServerName_where, $param_LiveCheckResult_LiveCheckType_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $result = array();

        $last_sql_command_for_mtooldb = 'select LiveCheckResult.PID, LiveCheckResult.CheckDT, LiveCheckResult.CheckTargetURL, LiveCheckResult.CheckOriginServerName, LiveCheckResult.LiveCheckType, LiveCheckResult.LiveCheckResult from LiveCheckResult' . ' where ' . 'LiveCheckResult.CheckTargetServerName = ' . '\'' . $mtooldb->real_escape_string($param_LiveCheckResult_CheckTargetServerName_where) . '\'' . ' and ' . 'LiveCheckResult.LiveCheckType = ' . '\'' . $mtooldb->real_escape_string($param_LiveCheckResult_LiveCheckType_where) . '\'';
        $ret = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new LiveCheckResultData();
            $thisresult->PID = $thisline[0];
            $thisresult->CheckDT = $thisline[1];
            $thisresult->CheckTargetURL = $thisline[2];
            $thisresult->CheckOriginServerName = $thisline[3];
            $thisresult->LiveCheckType = $thisline[4];
            $thisresult->LiveCheckResult = $thisline[5];
            array_push($result, $thisresult);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=SELECTLIST order=43 generation=canonical-sql
    public function GetLiveCheckResultSummaryList($param_LiveCheckResult_CheckDT_where, $param_LiveCheckResult_CheckDT_where2)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $result = array();

        $last_sql_command_for_mtooldb = 'select count(LiveCheckResult.PID), LiveCheckResult.CheckTargetURL, LiveCheckResult.CheckOriginServerName, LiveCheckResult.LiveCheckType, LiveCheckResult.LiveCheckResult from LiveCheckResult' . ' where ' . 'LiveCheckResult.CheckDT >= ' . '\'' . $mtooldb->real_escape_string($param_LiveCheckResult_CheckDT_where) . '\'' . ' and ' . 'LiveCheckResult.CheckDT < ' . '\'' . $mtooldb->real_escape_string($param_LiveCheckResult_CheckDT_where2) . '\'' . ' group by LiveCheckResult.CheckTargetURL, LiveCheckResult.CheckOriginServerName, LiveCheckResult.LiveCheckType, LiveCheckResult.LiveCheckResult';
        $ret = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new LiveCheckResultData();
            $thisresult->PID = $thisline[0];
            $thisresult->CheckTargetURL = $thisline[1];
            $thisresult->CheckOriginServerName = $thisline[2];
            $thisresult->LiveCheckType = $thisline[3];
            $thisresult->LiveCheckResult = $thisline[4];
            array_push($result, $thisresult);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=SELECTSINGLE order=71 generation=canonical-sql
    public function GetLatestSuccessedLiveCheckResult()
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'select min(LiveCheckResult.CheckDT) from LiveCheckResult' . ' where ' . 'LiveCheckResult.LiveCheckResult = ' . '\'' . $mtooldb->real_escape_string('OK') . '\'';
        $ret = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new LiveCheckResultData();
            $thisresult->CheckDT = $thisline[0];
            return $thisresult;
        }
        return NULL;
    }

    // source_of_truth=sync-bootstrap action_type=INSERT order=93 generation=canonical-sql
    public function InsertLiveCheckResult($LiveCheckResultObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'insert into LiveCheckResult (CheckTargetURL, CheckOriginServerName, LiveCheckType, LiveCheckResult) values(' . '\'' . $mtooldb->real_escape_string($LiveCheckResultObj->CheckTargetURL) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($LiveCheckResultObj->CheckOriginServerName) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($LiveCheckResultObj->LiveCheckType) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($LiveCheckResultObj->LiveCheckResult) . '\'' . ')';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=DELETE order=109 generation=canonical-sql
    public function DeleteSuccessedLiveCheckResult($param_LiveCheckResult_CheckDT_where, $param_LiveCheckResult_CheckDT_where2)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'delete from LiveCheckResult where ' . 'LiveCheckResult.CheckDT >= ' . '\'' . $mtooldb->real_escape_string($param_LiveCheckResult_CheckDT_where) . '\'' . ' and ' . 'LiveCheckResult.CheckDT < ' . '\'' . $mtooldb->real_escape_string($param_LiveCheckResult_CheckDT_where2) . '\'' . ' and ' . 'LiveCheckResult.LiveCheckResult = ' . '\'' . $mtooldb->real_escape_string('OK') . '\'';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }
}

?>