<?php

// AUTO-GENERATED BASE FILE.
// Do not edit this file manually or with AI/Codex.
// Keep customizations in the wrapper/custom class and use this base file exactly as regenerated by the tool.

require_once __DIR__ . '/../_support/legacy-dbaccess/dbaccess-dataclass.php';

// Generated from canonical DB Access metadata.
// Simple CRUD / joined select methods regenerate SQL when canonical metadata is sufficient.
// Known helper-style methods regenerate canonical PHP bodies when SQL regeneration is not the right fit.
// Remaining unsupported methods continue to delegate to copied legacy support under `_support/legacy-dbaccess/`.

class dataclassDBAccessBase extends dataclassDBAccessLegacy
{
    // source_of_truth=sync-bootstrap action_type=UNKNOWN order=11 generation=canonical-constructor
    // reason=bootstrap constructor is empty, so runtime owns the no-op constructor directly
    public function __construct()
    {
    }

    // source_of_truth=seed-legacy action_type=SELECTLIST order=14 generation=canonical-sql
    public function GetdataclassList($param_dataclass_ProjectPID_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $result = array();

        $last_sql_command_for_mtooldb = 'select dataclass.ProjectPID, dataclass.PID, dataclass.name, dataclass.StoreBasePath, dataclass.IsAutoload, dataclass.InheritParentDataClassName, dataclass.LastModifiedDT from dataclass' . ' where ' . 'dataclass.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($param_dataclass_ProjectPID_where) . '\'' . ' order by dataclass.name';
        $ret = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new dataclassData();
            $thisresult->ProjectPID = $thisline[0];
            $thisresult->PID = $thisline[1];
            $thisresult->name = $thisline[2];
            $thisresult->StoreBasePath = $thisline[3];
            $thisresult->IsAutoload = $thisline[4];
            $thisresult->InheritParentDataClassName = $thisline[5];
            $thisresult->LastModifiedDT = $thisline[6];
            array_push($result, $thisresult);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=SELECTSINGLE order=44 generation=canonical-sql
    public function Getdataclass($param_dataclass_PID_where, $param_dataclass_ProjectPID_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'select dataclass.ProjectPID, dataclass.PID, dataclass.name, dataclass.StoreBasePath, dataclass.IsAutoload, dataclass.InheritParentDataClassName, dataclass.LastModifiedDT from dataclass' . ' where ' . 'dataclass.PID = ' . '\'' . $mtooldb->real_escape_string($param_dataclass_PID_where) . '\'' . ' and ' . 'dataclass.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($param_dataclass_ProjectPID_where) . '\'';
        $ret = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new dataclassData();
            $thisresult->ProjectPID = $thisline[0];
            $thisresult->PID = $thisline[1];
            $thisresult->name = $thisline[2];
            $thisresult->StoreBasePath = $thisline[3];
            $thisresult->IsAutoload = $thisline[4];
            $thisresult->InheritParentDataClassName = $thisline[5];
            $thisresult->LastModifiedDT = $thisline[6];
            return $thisresult;
        }
        return NULL;
    }

    // source_of_truth=sync-bootstrap action_type=SELECTSINGLE order=72 generation=canonical-sql
    public function GetdataclassByName($param_dataclass_ProjectPID_where, $param_dataclass_name_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'select dataclass.ProjectPID, dataclass.PID, dataclass.name, dataclass.StoreBasePath, dataclass.IsAutoload, dataclass.InheritParentDataClassName, dataclass.LastModifiedDT from dataclass' . ' where ' . 'dataclass.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($param_dataclass_ProjectPID_where) . '\'' . ' and ' . 'dataclass.name = ' . '\'' . $mtooldb->real_escape_string($param_dataclass_name_where) . '\'';
        $ret = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new dataclassData();
            $thisresult->ProjectPID = $thisline[0];
            $thisresult->PID = $thisline[1];
            $thisresult->name = $thisline[2];
            $thisresult->StoreBasePath = $thisline[3];
            $thisresult->IsAutoload = $thisline[4];
            $thisresult->InheritParentDataClassName = $thisline[5];
            $thisresult->LastModifiedDT = $thisline[6];
            return $thisresult;
        }
        return NULL;
    }

    // source_of_truth=sync-bootstrap action_type=INSERT order=100 generation=canonical-sql
    public function Insertdataclass($dataclassObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'insert into dataclass (ProjectPID, name, StoreBasePath, IsAutoload, InheritParentDataClassName) values(' . '\'' . $mtooldb->real_escape_string($dataclassObj->ProjectPID) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($dataclassObj->name) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($dataclassObj->StoreBasePath) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($dataclassObj->IsAutoload) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($dataclassObj->InheritParentDataClassName) . '\'' . ')';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=UPDATE order=116 generation=canonical-sql
    public function Updatedataclass($dataclassObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'update dataclass SET ' . 'name = ' . '\'' . $mtooldb->real_escape_string($dataclassObj->name) . '\'' . ', ' . 'StoreBasePath = ' . '\'' . $mtooldb->real_escape_string($dataclassObj->StoreBasePath) . '\'' . ', ' . 'IsAutoload = ' . '\'' . $mtooldb->real_escape_string($dataclassObj->IsAutoload) . '\'' . ', ' . 'InheritParentDataClassName = ' . '\'' . $mtooldb->real_escape_string($dataclassObj->InheritParentDataClassName) . '\'' . ', ' . 'LastModifiedDT = ' . 'now()' . ' where ' . 'dataclass.PID = ' . '\'' . $mtooldb->real_escape_string($dataclassObj->PID) . '\'' . ' and ' . 'dataclass.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($dataclassObj->ProjectPID) . '\'';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=UPDATE order=132 generation=canonical-sql
    public function UpdateLastModifiedDT($param_dataclass_PID_where, $param_dataclass_ProjectPID_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'update dataclass SET ' . 'LastModifiedDT = ' . 'now()' . ' where ' . 'dataclass.PID = ' . '\'' . $mtooldb->real_escape_string($param_dataclass_PID_where) . '\'' . ' and ' . 'dataclass.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($param_dataclass_ProjectPID_where) . '\'';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=DELETE order=148 generation=canonical-sql
    public function Deletedataclass($param_dataclass_PID_where, $param_dataclass_ProjectPID_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'delete from dataclass where ' . 'dataclass.PID = ' . '\'' . $mtooldb->real_escape_string($param_dataclass_PID_where) . '\'' . ' and ' . 'dataclass.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($param_dataclass_ProjectPID_where) . '\'';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }
}

?>