<?php

// AUTO-GENERATED BASE FILE.
// Do not edit this file manually or with AI/Codex.
// Keep customizations in the wrapper/custom class and use this base file exactly as regenerated by the tool.

require_once __DIR__ . '/../_support/legacy-dbaccess/dbaccess-CompareOutputSearchCache.php';

// Generated from canonical DB Access metadata.
// Simple CRUD / joined select methods regenerate SQL when canonical metadata is sufficient.
// Known helper-style methods regenerate canonical PHP bodies when SQL regeneration is not the right fit.
// Remaining unsupported methods continue to delegate to copied legacy support under `_support/legacy-dbaccess/`.

class CompareOutputSearchCacheDBAccessBase extends CompareOutputSearchCacheDBAccessLegacy
{
    // source_of_truth=sync-bootstrap action_type=UNKNOWN order=11 generation=canonical-constructor
    // reason=bootstrap constructor is empty, so runtime owns the no-op constructor directly
    public function __construct()
    {
    }

    // source_of_truth=seed-legacy action_type=SELECTLIST order=14 generation=canonical-sql
    public function GetCompareOutputSearchCacheList($param_CompareOutputSearchCache_CompareOutputPID_where, $param_CompareOutputSearchCache_ProjectPID_where, $param_CompareOutputSearchCache_DropboxBaseFolderPID_where, $param_CompareOutputSearchCache_SearchKey_DropboxAccessToken_where, $param_CompareOutputSearchCache_SearchKey_DropboxBaseFolderPath_where, $param_CompareOutputSearchCache_SearchKey_DropboxFullPath_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $result = array();

        $last_sql_command_for_mtooldb = 'select CompareOutputSearchCache.PID, CompareOutputSearchCache.CompareOutputPID, CompareOutputSearchCache.ProjectPID, CompareOutputSearchCache.DropboxBaseFolderPID, CompareOutputSearchCache.SearchKey_DropboxAccessToken, CompareOutputSearchCache.SearchKey_DropboxBaseFolderPath, CompareOutputSearchCache.SearchKey_DropboxFullPath, CompareOutputSearchCache.Result_MetaData, CompareOutputSearchCache.Result_DropboxBaseFolder from CompareOutputSearchCache' . ' where ' . 'CompareOutputSearchCache.CompareOutputPID = ' . '\'' . $mtooldb->real_escape_string($param_CompareOutputSearchCache_CompareOutputPID_where) . '\'' . ' and ' . 'CompareOutputSearchCache.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($param_CompareOutputSearchCache_ProjectPID_where) . '\'' . ' and ' . 'CompareOutputSearchCache.DropboxBaseFolderPID = ' . '\'' . $mtooldb->real_escape_string($param_CompareOutputSearchCache_DropboxBaseFolderPID_where) . '\'' . ' and ' . 'CompareOutputSearchCache.SearchKey_DropboxAccessToken = ' . '\'' . $mtooldb->real_escape_string($param_CompareOutputSearchCache_SearchKey_DropboxAccessToken_where) . '\'' . ' and ' . 'CompareOutputSearchCache.SearchKey_DropboxBaseFolderPath = ' . '\'' . $mtooldb->real_escape_string($param_CompareOutputSearchCache_SearchKey_DropboxBaseFolderPath_where) . '\'' . ' and ' . 'CompareOutputSearchCache.SearchKey_DropboxFullPath = ' . '\'' . $mtooldb->real_escape_string($param_CompareOutputSearchCache_SearchKey_DropboxFullPath_where) . '\'' . ' order by CompareOutputSearchCache.SearchKey_DropboxAccessToken,CompareOutputSearchCache.SearchKey_DropboxBaseFolderPath,CompareOutputSearchCache.SearchKey_DropboxFullPath,CompareOutputSearchCache.PID';
        $ret = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new CompareOutputSearchCacheData();
            $thisresult->PID = $thisline[0];
            $thisresult->CompareOutputPID = $thisline[1];
            $thisresult->ProjectPID = $thisline[2];
            $thisresult->DropboxBaseFolderPID = $thisline[3];
            $thisresult->SearchKey_DropboxAccessToken = $thisline[4];
            $thisresult->SearchKey_DropboxBaseFolderPath = $thisline[5];
            $thisresult->SearchKey_DropboxFullPath = $thisline[6];
            $thisresult->Result_MetaData = $thisline[7];
            $thisresult->Result_DropboxBaseFolder = $thisline[8];
            array_push($result, $thisresult);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=INSERT order=46 generation=canonical-sql
    public function InsertCompareOutputSearchCache($CompareOutputSearchCacheObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'insert into CompareOutputSearchCache (CompareOutputPID, ProjectPID, DropboxBaseFolderPID, SearchKey_DropboxAccessToken, SearchKey_DropboxBaseFolderPath, SearchKey_DropboxFullPath, Result_MetaData, Result_DropboxBaseFolder) values(' . '\'' . $mtooldb->real_escape_string($CompareOutputSearchCacheObj->CompareOutputPID) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($CompareOutputSearchCacheObj->ProjectPID) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($CompareOutputSearchCacheObj->DropboxBaseFolderPID) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($CompareOutputSearchCacheObj->SearchKey_DropboxAccessToken) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($CompareOutputSearchCacheObj->SearchKey_DropboxBaseFolderPath) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($CompareOutputSearchCacheObj->SearchKey_DropboxFullPath) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($CompareOutputSearchCacheObj->Result_MetaData) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($CompareOutputSearchCacheObj->Result_DropboxBaseFolder) . '\'' . ')';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=DELETE order=62 generation=canonical-sql
    public function DeleteCompareOutputSearchCache($CompareOutputSearchCacheObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'delete from CompareOutputSearchCache where ' . 'CompareOutputSearchCache.CompareOutputPID = ' . '\'' . $mtooldb->real_escape_string($CompareOutputSearchCacheObj->CompareOutputPID) . '\'' . ' and ' . 'CompareOutputSearchCache.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($CompareOutputSearchCacheObj->ProjectPID) . '\'' . ' and ' . 'CompareOutputSearchCache.DropboxBaseFolderPID = ' . '\'' . $mtooldb->real_escape_string($CompareOutputSearchCacheObj->DropboxBaseFolderPID) . '\'' . ' and ' . 'CompareOutputSearchCache.SearchKey_DropboxAccessToken = ' . '\'' . $mtooldb->real_escape_string($CompareOutputSearchCacheObj->SearchKey_DropboxAccessToken) . '\'' . ' and ' . 'CompareOutputSearchCache.SearchKey_DropboxBaseFolderPath = ' . '\'' . $mtooldb->real_escape_string($CompareOutputSearchCacheObj->SearchKey_DropboxBaseFolderPath) . '\'' . ' and ' . 'CompareOutputSearchCache.SearchKey_DropboxFullPath = ' . '\'' . $mtooldb->real_escape_string($CompareOutputSearchCacheObj->SearchKey_DropboxFullPath) . '\'';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }
}

?>