<?php

// AUTO-GENERATED BASE FILE.
// Do not edit this file manually or with AI/Codex.
// Keep customizations in the wrapper class and use this base file exactly as regenerated by the tool.

// Generated from canonical DB Access metadata.
// Base class generated from project_db_access_* metadata.

require_once __DIR__ . '/../_support/mtool_runtime_db.php';


class EbookMediaAssetDBAccessBase
{
    public function __construct()
    {
    }

    // source_of_truth=manual class_source=manual action_type=SELECTLIST order=10 generation=canonical-sql
    public function GetPublicEbookMediaDeliveryList($param_EbookMediaDelivery_BookSlug_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $result = array();

        $last_sql_command_for_mtooldb = 'select EbookMediaDelivery.DeliveryId, EbookMediaDelivery.BookId, EbookMediaDelivery.BookSlug, EbookMediaDelivery.AssetId, EbookMediaDelivery.AssetSlug, EbookMediaDelivery.AssetKind, EbookMediaDelivery.DisplayRole, EbookMediaDelivery.DisplayName, EbookMediaDelivery.PublicUrl, EbookMediaDelivery.MimeType, EbookMediaDelivery.FileSizeBytes, EbookMediaDelivery.Sha256, EbookMediaDelivery.VersionLabel, EbookMediaDelivery.SortOrder, EbookMediaDelivery.IsPrimaryAsset from EbookMediaDelivery where EbookMediaDelivery.Status = ? and EbookMediaDelivery.BookSlug = ? order by EbookMediaDelivery.SortOrder asc, EbookMediaDelivery.DeliveryId asc';
        $ret = $mtooldb->execute($last_sql_command_for_mtooldb, [
            'published',
            $param_EbookMediaDelivery_BookSlug_where,
        ]);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new EbookMediaDeliveryData();
            $thisresult->DeliveryId = $thisline[0];
            $thisresult->BookId = $thisline[1];
            $thisresult->BookSlug = $thisline[2];
            $thisresult->AssetId = $thisline[3];
            $thisresult->AssetSlug = $thisline[4];
            $thisresult->AssetKind = $thisline[5];
            $thisresult->DisplayRole = $thisline[6];
            $thisresult->DisplayName = $thisline[7];
            $thisresult->PublicUrl = $thisline[8];
            $thisresult->MimeType = $thisline[9];
            $thisresult->FileSizeBytes = $thisline[10];
            $thisresult->Sha256 = $thisline[11];
            $thisresult->VersionLabel = $thisline[12];
            $thisresult->SortOrder = $thisline[13];
            $thisresult->IsPrimaryAsset = $thisline[14];
            array_push($result, $thisresult);
        }
        return $result;
    }

    // source_of_truth=manual class_source=manual action_type=SELECTSINGLE order=20 generation=canonical-sql
    public function GetPublicEbookMediaAsset($param_EbookMediaDelivery_AssetSlug_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'select EbookMediaDelivery.DeliveryId, EbookMediaDelivery.BookId, EbookMediaDelivery.BookSlug, EbookMediaDelivery.AssetId, EbookMediaDelivery.AssetSlug, EbookMediaDelivery.AssetKind, EbookMediaDelivery.DisplayRole, EbookMediaDelivery.DisplayName, EbookMediaDelivery.PublicUrl, EbookMediaDelivery.MimeType, EbookMediaDelivery.FileSizeBytes, EbookMediaDelivery.Sha256, EbookMediaDelivery.VersionLabel, EbookMediaDelivery.SortOrder, EbookMediaDelivery.IsPrimaryAsset from EbookMediaDelivery where EbookMediaDelivery.Status = ? and EbookMediaDelivery.AssetSlug = ?';
        $ret = $mtooldb->execute($last_sql_command_for_mtooldb, [
            'published',
            $param_EbookMediaDelivery_AssetSlug_where,
        ]);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new EbookMediaDeliveryData();
            $thisresult->DeliveryId = $thisline[0];
            $thisresult->BookId = $thisline[1];
            $thisresult->BookSlug = $thisline[2];
            $thisresult->AssetId = $thisline[3];
            $thisresult->AssetSlug = $thisline[4];
            $thisresult->AssetKind = $thisline[5];
            $thisresult->DisplayRole = $thisline[6];
            $thisresult->DisplayName = $thisline[7];
            $thisresult->PublicUrl = $thisline[8];
            $thisresult->MimeType = $thisline[9];
            $thisresult->FileSizeBytes = $thisline[10];
            $thisresult->Sha256 = $thisline[11];
            $thisresult->VersionLabel = $thisline[12];
            $thisresult->SortOrder = $thisline[13];
            $thisresult->IsPrimaryAsset = $thisline[14];
            return $thisresult;
        }
        return NULL;
    }

    // source_of_truth=manual class_source=manual action_type=INSERT order=30 generation=canonical-sql
    public function InsertEbookMediaAsset($EbookMediaAssetObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'insert into EbookMediaAsset (AssetSlug, AssetKind, DisplayName, PublicUrl, StoragePath, MimeType, FileSizeBytes, Sha256, VersionLabel, Status, UpdatedAt) values(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, NOW())';
        $result = $mtooldb->execute($last_sql_command_for_mtooldb, [
            $EbookMediaAssetObj->AssetSlug,
            $EbookMediaAssetObj->AssetKind,
            $EbookMediaAssetObj->DisplayName,
            $EbookMediaAssetObj->PublicUrl,
            $EbookMediaAssetObj->StoragePath,
            $EbookMediaAssetObj->MimeType,
            $EbookMediaAssetObj->FileSizeBytes,
            $EbookMediaAssetObj->Sha256,
            $EbookMediaAssetObj->VersionLabel,
            'draft',
        ]);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }

    // source_of_truth=manual class_source=manual action_type=UPDATE order=40 generation=canonical-sql
    public function UpdateEbookMediaAssetMetadata($EbookMediaAssetObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'update EbookMediaAsset SET DisplayName = ?, PublicUrl = ?, StoragePath = ?, MimeType = ?, FileSizeBytes = ?, Sha256 = ?, VersionLabel = ?, Status = ?, UpdatedAt = NOW() where EbookMediaAsset.Id = ?';
        $result = $mtooldb->execute($last_sql_command_for_mtooldb, [
            $EbookMediaAssetObj->DisplayName,
            $EbookMediaAssetObj->PublicUrl,
            $EbookMediaAssetObj->StoragePath,
            $EbookMediaAssetObj->MimeType,
            $EbookMediaAssetObj->FileSizeBytes,
            $EbookMediaAssetObj->Sha256,
            $EbookMediaAssetObj->VersionLabel,
            $EbookMediaAssetObj->Status,
            $EbookMediaAssetObj->Id,
        ]);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }
}

?>