<?php

// AUTO-GENERATED BASE FILE.
// Do not edit this file manually or with AI/Codex.
// Keep customizations in the wrapper/custom class and use this base file exactly as regenerated by the tool.

// Generated from canonical DB Access metadata.
// Thin DTO generated from canonical select/write metadata.

class SpecialHolidayDataBase
{
    public $PID;
    public $year;
    public $month;
    public $day;
    public $is_confirmed;

    public function __construct()
    {
    }
}

?>
