<?php

// AUTO-GENERATED BASE FILE.
// Do not edit this file manually or with AI/Codex.
// Keep customizations in the wrapper/custom class and use this base file exactly as regenerated by the tool.

require_once __DIR__ . '/../_support/legacy-dbaccess/dbaccess-ApacheSetting.php';

// Generated from canonical DB Access metadata.
// Simple CRUD / joined select methods regenerate SQL when canonical metadata is sufficient.
// Known helper-style methods regenerate canonical PHP bodies when SQL regeneration is not the right fit.
// Remaining unsupported methods continue to delegate to copied legacy support under `_support/legacy-dbaccess/`.

class ApacheSettingDBAccessBase extends ApacheSettingDBAccessLegacy
{
    // source_of_truth=sync-bootstrap action_type=UNKNOWN order=11 generation=canonical-constructor
    // reason=bootstrap constructor is empty, so runtime owns the no-op constructor directly
    public function __construct()
    {
    }

    // source_of_truth=seed-legacy action_type=SELECTLIST order=14 generation=canonical-sql
    public function GetApacheSettingList($param_ApacheSetting_SettingGroupPID_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $result = array();

        $last_sql_command_for_mtooldb = 'select ApacheSetting.PID, ApacheSetting.SettingGroupPID, ApacheSetting.name, ApacheSetting.ServerPID, ApacheSetting.DropboxBaseFolderPID, ApacheSetting.CreateTargetDir, Server.LocalServerName, DropboxBaseFolder.Name, DropboxSetting.PID from ApacheSetting left outer join Server on ApacheSetting.ServerPID = Server.PID left outer join DropboxBaseFolder on ApacheSetting.DropboxBaseFolderPID = DropboxBaseFolder.PID left outer join DropboxSetting on DropboxBaseFolder.DropboxSettingPID = DropboxSetting.PID' . ' where ' . 'ApacheSetting.SettingGroupPID = ' . '\'' . $mtooldb->real_escape_string($param_ApacheSetting_SettingGroupPID_where) . '\'' . ' order by ApacheSetting.name,ApacheSetting.PID';
        $ret = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new ApacheSettingData();
            $thisresult->PID = $thisline[0];
            $thisresult->SettingGroupPID = $thisline[1];
            $thisresult->name = $thisline[2];
            $thisresult->ServerPID = $thisline[3];
            $thisresult->DropboxBaseFolderPID = $thisline[4];
            $thisresult->CreateTargetDir = $thisline[5];
            $thisresult->ServerLocalServerName = $thisline[6];
            $thisresult->DropboxBaseFolderName = $thisline[7];
            $thisresult->DropboxSettingPID = $thisline[8];
            array_push($result, $thisresult);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=SELECTSINGLE order=46 generation=canonical-sql
    public function GetApacheSetting($param_ApacheSetting_PID_where, $param_ApacheSetting_SettingGroupPID_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'select ApacheSetting.PID, ApacheSetting.SettingGroupPID, ApacheSetting.name, ApacheSetting.ServerPID, ApacheSetting.DropboxBaseFolderPID, ApacheSetting.CreateTargetDir, Server.LocalServerName, DropboxBaseFolder.Name, DropboxSetting.PID from ApacheSetting left outer join Server on ApacheSetting.ServerPID = Server.PID left outer join DropboxBaseFolder on ApacheSetting.DropboxBaseFolderPID = DropboxBaseFolder.PID left outer join DropboxSetting on DropboxBaseFolder.DropboxSettingPID = DropboxSetting.PID' . ' where ' . 'ApacheSetting.PID = ' . '\'' . $mtooldb->real_escape_string($param_ApacheSetting_PID_where) . '\'' . ' and ' . 'ApacheSetting.SettingGroupPID = ' . '\'' . $mtooldb->real_escape_string($param_ApacheSetting_SettingGroupPID_where) . '\'';
        $ret = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new ApacheSettingData();
            $thisresult->PID = $thisline[0];
            $thisresult->SettingGroupPID = $thisline[1];
            $thisresult->name = $thisline[2];
            $thisresult->ServerPID = $thisline[3];
            $thisresult->DropboxBaseFolderPID = $thisline[4];
            $thisresult->CreateTargetDir = $thisline[5];
            $thisresult->ServerLocalServerName = $thisline[6];
            $thisresult->DropboxBaseFolderName = $thisline[7];
            $thisresult->DropboxSettingPID = $thisline[8];
            return $thisresult;
        }
        return NULL;
    }

    // source_of_truth=sync-bootstrap action_type=INSERT order=76 generation=canonical-sql
    public function InsertApacheSetting($ApacheSettingObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'insert into ApacheSetting (SettingGroupPID, name, ServerPID, DropboxBaseFolderPID, CreateTargetDir) values(' . '\'' . $mtooldb->real_escape_string($ApacheSettingObj->SettingGroupPID) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($ApacheSettingObj->name) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($ApacheSettingObj->ServerPID) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($ApacheSettingObj->DropboxBaseFolderPID) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($ApacheSettingObj->CreateTargetDir) . '\'' . ')';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=UPDATE order=92 generation=canonical-sql
    public function UpdateApacheSetting($ApacheSettingObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'update ApacheSetting SET ' . 'name = ' . '\'' . $mtooldb->real_escape_string($ApacheSettingObj->name) . '\'' . ', ' . 'ServerPID = ' . '\'' . $mtooldb->real_escape_string($ApacheSettingObj->ServerPID) . '\'' . ', ' . 'DropboxBaseFolderPID = ' . '\'' . $mtooldb->real_escape_string($ApacheSettingObj->DropboxBaseFolderPID) . '\'' . ', ' . 'CreateTargetDir = ' . '\'' . $mtooldb->real_escape_string($ApacheSettingObj->CreateTargetDir) . '\'' . ' where ' . 'ApacheSetting.PID = ' . '\'' . $mtooldb->real_escape_string($ApacheSettingObj->PID) . '\'' . ' and ' . 'ApacheSetting.SettingGroupPID = ' . '\'' . $mtooldb->real_escape_string($ApacheSettingObj->SettingGroupPID) . '\'';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=DELETE order=108 generation=canonical-sql
    public function DeleteApacheSetting($ApacheSettingObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'delete from ApacheSetting where ' . 'ApacheSetting.PID = ' . '\'' . $mtooldb->real_escape_string($ApacheSettingObj->PID) . '\'' . ' and ' . 'ApacheSetting.SettingGroupPID = ' . '\'' . $mtooldb->real_escape_string($ApacheSettingObj->SettingGroupPID) . '\'';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }
}

?>