<?php

// AUTO-GENERATED BASE FILE.
// Do not edit this file manually or with AI/Codex.
// Keep customizations in the wrapper/custom class and use this base file exactly as regenerated by the tool.

require_once __DIR__ . '/../_support/legacy-dbaccess/dbaccess-dbtable.php';

// Generated from canonical DB Access metadata.
// Simple CRUD / joined select methods regenerate SQL when canonical metadata is sufficient.
// Known helper-style methods regenerate canonical PHP bodies when SQL regeneration is not the right fit.
// Remaining unsupported methods continue to delegate to copied legacy support under `_support/legacy-dbaccess/`.

class dbtableDBAccessBase extends dbtableDBAccessLegacy
{
    // source_of_truth=sync-bootstrap action_type=UNKNOWN order=11 generation=canonical-constructor
    // reason=bootstrap constructor is empty, so runtime owns the no-op constructor directly
    public function __construct()
    {
    }

    // source_of_truth=seed-legacy action_type=SELECTLIST order=14 generation=canonical-sql
    public function GetdbtableList($param_dbtable_ProjectPID_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $result = array();

        $last_sql_command_for_mtooldb = 'select dbtable.ProjectPID, dbtable.PID, dbtable.name from dbtable' . ' where ' . 'dbtable.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($param_dbtable_ProjectPID_where) . '\'' . ' order by dbtable.name';
        $ret = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new dbtableData();
            $thisresult->ProjectPID = $thisline[0];
            $thisresult->PID = $thisline[1];
            $thisresult->name = $thisline[2];
            array_push($result, $thisresult);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=SELECTSINGLE order=40 generation=canonical-sql
    public function Getdbtable($param_dbtable_PID_where, $param_dbtable_ProjectPID_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'select dbtable.ProjectPID, dbtable.PID, dbtable.name from dbtable' . ' where ' . 'dbtable.PID = ' . '\'' . $mtooldb->real_escape_string($param_dbtable_PID_where) . '\'' . ' and ' . 'dbtable.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($param_dbtable_ProjectPID_where) . '\'';
        $ret = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new dbtableData();
            $thisresult->ProjectPID = $thisline[0];
            $thisresult->PID = $thisline[1];
            $thisresult->name = $thisline[2];
            return $thisresult;
        }
        return NULL;
    }

    // source_of_truth=sync-bootstrap action_type=SELECTSINGLE order=64 generation=canonical-sql
    public function GetdbtableByName($param_dbtable_ProjectPID_where, $param_dbtable_name_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'select dbtable.ProjectPID, dbtable.PID, dbtable.name from dbtable' . ' where ' . 'dbtable.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($param_dbtable_ProjectPID_where) . '\'' . ' and ' . 'dbtable.name = ' . '\'' . $mtooldb->real_escape_string($param_dbtable_name_where) . '\'';
        $ret = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new dbtableData();
            $thisresult->ProjectPID = $thisline[0];
            $thisresult->PID = $thisline[1];
            $thisresult->name = $thisline[2];
            return $thisresult;
        }
        return NULL;
    }

    // source_of_truth=sync-bootstrap action_type=INSERT order=88 generation=canonical-sql
    public function Insertdbtable($dbtableObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'insert into dbtable (ProjectPID, name) values(' . '\'' . $mtooldb->real_escape_string($dbtableObj->ProjectPID) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($dbtableObj->name) . '\'' . ')';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=UPDATE order=104 generation=canonical-sql
    public function Updatedbtable($dbtableObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'update dbtable SET ' . 'name = ' . '\'' . $mtooldb->real_escape_string($dbtableObj->name) . '\'' . ' where ' . 'dbtable.PID = ' . '\'' . $mtooldb->real_escape_string($dbtableObj->PID) . '\'' . ' and ' . 'dbtable.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($dbtableObj->ProjectPID) . '\'';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=DELETE order=120 generation=canonical-sql
    public function Deletedbtable($param_dbtable_PID_where, $param_dbtable_ProjectPID_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'delete from dbtable where ' . 'dbtable.PID = ' . '\'' . $mtooldb->real_escape_string($param_dbtable_PID_where) . '\'' . ' and ' . 'dbtable.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($param_dbtable_ProjectPID_where) . '\'';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }
}

?>