__INDENT_FOR_CHECK_IF_ALREADY_INSERTED____INDENT_FOR_LIST__	if ($__DB_OBJECT__->errno != 0) {
__INDENT_FOR_CHECK_IF_ALREADY_INSERTED____INDENT_FOR_LIST____ROLLBACK_TRANSACTION__
__INDENT_FOR_CHECK_IF_ALREADY_INSERTED____INDENT_FOR_LIST__		print json_encode(array(
__RESULT_PARAM__
__INDENT_FOR_CHECK_IF_ALREADY_INSERTED____INDENT_FOR_LIST__			"_status"=>"NGinServer",
__INDENT_FOR_CHECK_IF_ALREADY_INSERTED____INDENT_FOR_LIST__			"Message"=>$__DB_OBJECT__->error
__INDENT_FOR_CHECK_IF_ALREADY_INSERTED____INDENT_FOR_LIST__		));
__INDENT_FOR_CHECK_IF_ALREADY_INSERTED____INDENT_FOR_LIST__		exit(0);
__INDENT_FOR_CHECK_IF_ALREADY_INSERTED____INDENT_FOR_LIST__	}
