<?php
// == START OF EDITABLE AREA FOR ABOVE ==
// == END OF EDITABLE AREA FOR ABOVE ==

// THIS CLASS WAS AUTOMATICALLY CREATED BY MTOOL. DON'T EDIT EXCEPT THE EDITABLE AREA.
// [JP] このクラスは自動生成されています。編集可能領域以外は変更しないで下さい。

class __CLASS_BASE_NAME__Proxy__FUNCTION_NAME__RequestParams__CLASS_NAME_SUFFIX__
{
	// Constructor
	function __construct()
	{
__INITIALIZE_PROPERTY__
		// == START OF EDITABLE AREA FOR DEFAULT CONSTRUCTOR ==
		// == END OF EDITABLE AREA FOR DEFAULT CONSTRUCTOR ==
	}

__PROPERTIES__
	// == START OF EDITABLE AREA FOR ADDITIONAL CLASS DEFINITION ==
	// == END OF EDITABLE AREA FOR ADDITIONAL CLASS DEFINITION ==
}

// == START OF EDITABLE AREA FOR BOTTOM ==
// == END OF EDITABLE AREA FOR BOTTOM ==
?>