<?PHP

// THIS CLASS WAS AUTOMATICALLY CREATED BY MTOOL. DON'T EDIT EXCEPT THE EDITABLE AREA.
// [JP] このクラスは自動生成されています。編集可能領域以外は変更しないで下さい。

// == START OF EDITABLE AREA FOR AUTOLOAD TOP ==
// == END OF EDITABLE AREA FOR AUTOLOAD TOP ==

__AUTOMATED_CODE_COMES_HERE__

// == START OF EDITABLE AREA FOR AUTOLOAD BOTTOM ==
// == END OF EDITABLE AREA FOR AUTOLOAD BOTTOM ==

?>