<?php

// AUTO-GENERATED BASE FILE.
// Do not edit this file manually or with AI/Codex.
// Keep customizations in the wrapper/custom class and use this base file exactly as regenerated by the tool.

// Generated from canonical DB Access metadata.
// Thin DTO generated from canonical select/write metadata.

class dafuncSimpleProxySourceOutputTargetDataBase
{
    public $ProjectPID;
    public $daPID;
    public $dafuncPID;
    public $PID;
    public $ProjectSourceOutputPID;
    public $daname;
    public $dafuncname;

    public function __construct()
    {
    }
}

?>
