<?php

// AUTO-GENERATED BASE FILE.
// Do not edit this file manually or with AI/Codex.
// Keep customizations in the wrapper/custom class and use this base file exactly as regenerated by the tool.

// Generated from canonical DB Access metadata.
// Thin DTO generated from canonical select/write metadata.

class daCustomProxyFunc_leftouterjoin_dafunc_and_daDataBase extends daCustomProxyFuncData
{
    public $daname;
    public $dafuncname;
    public $dafuncActionType;
    public $daPID;

    public function __construct()
    {
    }
}

?>
