<?php

// AUTO-GENERATED BASE FILE.
// Do not edit this file manually or with AI/Codex.
// Keep customizations in the wrapper class and use this base file exactly as regenerated by the tool.

// Generated by migrating a legacy data class.
// Generated members are kept in this base file. Former editable areas move to the wrapper file.
// Generated trailing enum-type classes also stay in this base file when present.

class MinutesAndRelatedTablesDataBase extends MinutesData
{
    public $Projectname;
    public $Chattopicname;
    public $ReqUserRequest;
    public $ReqSummary;
    public $Specname;
    public $SpecContentDepth;
    public $SpecContentTitle;
    public $TestGroupname;
    public $Testname;
    public $daname;
    public $Dafuncname;
    public $DafuncActionType;
    public $Dataclassname;
    public $Dbtablename;

    public function __construct()
    {
    }
}

?>
