<?php

// AUTO-GENERATED BASE FILE.
// Do not edit this file manually or with AI/Codex.
// Keep customizations in the wrapper/custom class and use this base file exactly as regenerated by the tool.

// Generated from canonical DB Access metadata.
// Simple CRUD / joined select methods regenerate SQL when canonical metadata is sufficient.
// Known helper-style methods regenerate canonical PHP bodies when SQL regeneration is not the right fit.
// Current canonical runtime generation fully owns this class, so no legacy DBAccess parent is required.

class chattopicAttachmentDBAccessBase
{
    // source_of_truth=sync-bootstrap action_type=UNKNOWN order=11 generation=canonical-constructor
    // reason=bootstrap constructor is empty, so runtime owns the no-op constructor directly
    public function __construct()
    {
    }

    // source_of_truth=sync-bootstrap action_type=SELECTSINGLE order=14 generation=canonical-sql
    public function GetchattopicAttachment($param_chattopicAttachment_PID_where, $param_chattopicAttachment_ProjectPID_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'select chattopicAttachment.ProjectPID, chattopicAttachment.chattopicPID, chattopicAttachment.PID, chattopicAttachment.name from chattopicAttachment' . ' where ' . 'chattopicAttachment.PID = ' . '\'' . $mtooldb->real_escape_string($param_chattopicAttachment_PID_where) . '\'' . ' and ' . 'chattopicAttachment.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($param_chattopicAttachment_ProjectPID_where) . '\'';
        $ret = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new chattopicAttachmentData();
            $thisresult->ProjectPID = $thisline[0];
            $thisresult->chattopicPID = $thisline[1];
            $thisresult->PID = $thisline[2];
            $thisresult->name = $thisline[3];
            return $thisresult;
        }
        return NULL;
    }

    // source_of_truth=seed-legacy action_type=SELECTLIST order=39 generation=canonical-sql
    public function GetchattopicAttachmentList($param_chattopicAttachment_ProjectPID_where, $param_chattopicAttachment_chattopicPID_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $result = array();

        $last_sql_command_for_mtooldb = 'select chattopicAttachment.ProjectPID, chattopicAttachment.chattopicPID, chattopicAttachment.PID, chattopicAttachment.name from chattopicAttachment' . ' where ' . 'chattopicAttachment.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($param_chattopicAttachment_ProjectPID_where) . '\'' . ' and ' . 'chattopicAttachment.chattopicPID = ' . '\'' . $mtooldb->real_escape_string($param_chattopicAttachment_chattopicPID_where) . '\'' . ' order by chattopicAttachment.PID';
        $ret = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new chattopicAttachmentData();
            $thisresult->ProjectPID = $thisline[0];
            $thisresult->chattopicPID = $thisline[1];
            $thisresult->PID = $thisline[2];
            $thisresult->name = $thisline[3];
            array_push($result, $thisresult);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=INSERT order=66 generation=canonical-sql
    public function InsertchattopicAttachment($chattopicAttachmentObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'insert into chattopicAttachment (ProjectPID, chattopicPID, PID, name) values(' . '\'' . $mtooldb->real_escape_string($chattopicAttachmentObj->ProjectPID) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($chattopicAttachmentObj->chattopicPID) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($chattopicAttachmentObj->PID) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($chattopicAttachmentObj->name) . '\'' . ')';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=UPDATE order=82 generation=canonical-sql
    public function UpdatechattopicAttachment($chattopicAttachmentObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'update chattopicAttachment SET ' . 'name = ' . '\'' . $mtooldb->real_escape_string($chattopicAttachmentObj->name) . '\'' . ' where ' . 'chattopicAttachment.PID = ' . '\'' . $mtooldb->real_escape_string($chattopicAttachmentObj->PID) . '\'' . ' and ' . 'chattopicAttachment.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($chattopicAttachmentObj->ProjectPID) . '\'';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=DELETE order=98 generation=canonical-sql
    public function DeletechattopicAttachment($chattopicAttachmentObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'delete from chattopicAttachment where ' . 'chattopicAttachment.PID = ' . '\'' . $mtooldb->real_escape_string($chattopicAttachmentObj->PID) . '\'' . ' and ' . 'chattopicAttachment.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($chattopicAttachmentObj->ProjectPID) . '\'';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }
}

?>