<?php

// AUTO-GENERATED BASE FILE.
// Do not edit this file manually or with AI/Codex.
// Keep customizations in the wrapper/custom class and use this base file exactly as regenerated by the tool.

// Generated from canonical DB Access metadata.
// Simple CRUD / joined select methods regenerate SQL when canonical metadata is sufficient.
// Known helper-style methods regenerate canonical PHP bodies when SQL regeneration is not the right fit.
// Current canonical runtime generation fully owns this class, so no legacy DBAccess parent is required.

class SpecContentDBAccessBase
{
    // source_of_truth=sync-bootstrap action_type=UNKNOWN order=11 generation=canonical-constructor
    // reason=bootstrap constructor is empty, so runtime owns the no-op constructor directly
    public function __construct()
    {
    }

    // source_of_truth=seed-legacy action_type=SELECTLIST order=14 generation=canonical-sql
    public function GetSpecContentList($param_SpecContent_ProjectPID_where, $param_SpecContent_SpecPID_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $result = array();

        $last_sql_command_for_mtooldb = 'select SpecContent.ProjectPID, SpecContent.SpecPID, SpecContent.PID, SpecContent.Depth, SpecContent.ContentOrder, SpecContent.Title, SpecContent.Description from SpecContent' . ' where ' . 'SpecContent.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($param_SpecContent_ProjectPID_where) . '\'' . ' and ' . 'SpecContent.SpecPID = ' . '\'' . $mtooldb->real_escape_string($param_SpecContent_SpecPID_where) . '\'' . ' order by SpecContent.ContentOrder,SpecContent.PID';
        $ret = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new SpecContentData();
            $thisresult->ProjectPID = $thisline[0];
            $thisresult->SpecPID = $thisline[1];
            $thisresult->PID = $thisline[2];
            $thisresult->Depth = $thisline[3];
            $thisresult->ContentOrder = $thisline[4];
            $thisresult->Title = $thisline[5];
            $thisresult->Description = $thisline[6];
            array_push($result, $thisresult);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=SELECTSINGLE order=44 generation=canonical-sql
    public function GetSpecContent($param_SpecContent_PID_where, $param_SpecContent_ProjectPID_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'select SpecContent.ProjectPID, SpecContent.SpecPID, SpecContent.PID, SpecContent.Depth, SpecContent.ContentOrder, SpecContent.Title, SpecContent.Description from SpecContent' . ' where ' . 'SpecContent.PID = ' . '\'' . $mtooldb->real_escape_string($param_SpecContent_PID_where) . '\'' . ' and ' . 'SpecContent.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($param_SpecContent_ProjectPID_where) . '\'';
        $ret = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new SpecContentData();
            $thisresult->ProjectPID = $thisline[0];
            $thisresult->SpecPID = $thisline[1];
            $thisresult->PID = $thisline[2];
            $thisresult->Depth = $thisline[3];
            $thisresult->ContentOrder = $thisline[4];
            $thisresult->Title = $thisline[5];
            $thisresult->Description = $thisline[6];
            return $thisresult;
        }
        return NULL;
    }

    // source_of_truth=sync-bootstrap action_type=INSERT order=72 generation=canonical-sql
    public function InsertSpecContent($SpecContentObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'insert into SpecContent (ProjectPID, SpecPID, Depth, Title, Description) values(' . '\'' . $mtooldb->real_escape_string($SpecContentObj->ProjectPID) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($SpecContentObj->SpecPID) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($SpecContentObj->Depth) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($SpecContentObj->Title) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($SpecContentObj->Description) . '\'' . ')';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=UPDATE order=88 generation=canonical-sql
    public function UpdateSpecContent($SpecContentObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'update SpecContent SET ' . 'Depth = ' . '\'' . $mtooldb->real_escape_string($SpecContentObj->Depth) . '\'' . ', ' . 'Title = ' . '\'' . $mtooldb->real_escape_string($SpecContentObj->Title) . '\'' . ', ' . 'Description = ' . '\'' . $mtooldb->real_escape_string($SpecContentObj->Description) . '\'' . ' where ' . 'SpecContent.PID = ' . '\'' . $mtooldb->real_escape_string($SpecContentObj->PID) . '\'' . ' and ' . 'SpecContent.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($SpecContentObj->ProjectPID) . '\'';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=UPDATE order=104 generation=canonical-sql
    public function UpdateSpecContentOrder($param_SpecContent_ContentOrder_update, $param_SpecContent_PID_where, $param_SpecContent_ProjectPID_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'update SpecContent SET ' . 'ContentOrder = ' . '\'' . $mtooldb->real_escape_string($param_SpecContent_ContentOrder_update) . '\'' . ' where ' . 'SpecContent.PID = ' . '\'' . $mtooldb->real_escape_string($param_SpecContent_PID_where) . '\'' . ' and ' . 'SpecContent.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($param_SpecContent_ProjectPID_where) . '\'';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=DELETE order=120 generation=canonical-sql
    public function DeleteSpecContent($SpecContentObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'delete from SpecContent where ' . 'SpecContent.PID = ' . '\'' . $mtooldb->real_escape_string($SpecContentObj->PID) . '\'' . ' and ' . 'SpecContent.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($SpecContentObj->ProjectPID) . '\'';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }
}

?>