<?php

// AUTO-GENERATED BASE FILE.
// Do not edit this file manually or with AI/Codex.
// Keep customizations in the wrapper/custom class and use this base file exactly as regenerated by the tool.

// Generated from canonical DB Access metadata.
// Simple CRUD / joined select methods regenerate SQL when canonical metadata is sufficient.
// Known helper-style methods regenerate canonical PHP bodies when SQL regeneration is not the right fit.
// Current canonical runtime generation fully owns this class, so no legacy DBAccess parent is required.

class ChattopicDBAccessBase
{
    // source_of_truth=sync-bootstrap action_type=UNKNOWN order=11 generation=canonical-constructor
    // reason=bootstrap constructor is empty, so runtime owns the no-op constructor directly
    public function __construct()
    {
    }

    // source_of_truth=seed-legacy action_type=SELECTLIST order=14 generation=canonical-sql
    public function GetChattopicList($param_Chattopic_ProjectPID_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $result = array();

        $last_sql_command_for_mtooldb = 'select Chattopic.ProjectPID, Chattopic.PID, Chattopic.name, Chattopic.IsOld from Chattopic' . ' where ' . 'Chattopic.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($param_Chattopic_ProjectPID_where) . '\'' . ' order by Chattopic.IsOld,Chattopic.name,Chattopic.PID';
        $ret = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new ChattopicData();
            $thisresult->ProjectPID = $thisline[0];
            $thisresult->PID = $thisline[1];
            $thisresult->name = $thisline[2];
            $thisresult->IsOld = $thisline[3];
            array_push($result, $thisresult);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=SELECTSINGLE order=41 generation=canonical-sql
    public function GetChattopic($param_Chattopic_PID_where, $param_Chattopic_ProjectPID_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'select Chattopic.ProjectPID, Chattopic.PID, Chattopic.name, Chattopic.IsOld from Chattopic' . ' where ' . 'Chattopic.PID = ' . '\'' . $mtooldb->real_escape_string($param_Chattopic_PID_where) . '\'' . ' and ' . 'Chattopic.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($param_Chattopic_ProjectPID_where) . '\'';
        $ret = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new ChattopicData();
            $thisresult->ProjectPID = $thisline[0];
            $thisresult->PID = $thisline[1];
            $thisresult->name = $thisline[2];
            $thisresult->IsOld = $thisline[3];
            return $thisresult;
        }
        return NULL;
    }

    // source_of_truth=sync-bootstrap action_type=INSERT order=66 generation=canonical-sql
    public function InsertChattopic($ChattopicObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'insert into Chattopic (ProjectPID, name, IsOld) values(' . '\'' . $mtooldb->real_escape_string($ChattopicObj->ProjectPID) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($ChattopicObj->name) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($ChattopicObj->IsOld) . '\'' . ')';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=UPDATE order=82 generation=canonical-sql
    public function UpdateChattopic($ChattopicObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'update Chattopic SET ' . 'name = ' . '\'' . $mtooldb->real_escape_string($ChattopicObj->name) . '\'' . ', ' . 'IsOld = ' . '\'' . $mtooldb->real_escape_string($ChattopicObj->IsOld) . '\'' . ' where ' . 'Chattopic.PID = ' . '\'' . $mtooldb->real_escape_string($ChattopicObj->PID) . '\'' . ' and ' . 'Chattopic.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($ChattopicObj->ProjectPID) . '\'';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=DELETE order=98 generation=canonical-sql
    public function DeleteChattopic($ChattopicObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'delete from Chattopic where ' . 'Chattopic.PID = ' . '\'' . $mtooldb->real_escape_string($ChattopicObj->PID) . '\'' . ' and ' . 'Chattopic.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($ChattopicObj->ProjectPID) . '\'';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }
}

?>