<?php

// AUTO-GENERATED BASE FILE.
// Do not edit this file manually or with AI/Codex.
// Keep customizations in the wrapper/custom class and use this base file exactly as regenerated by the tool.

// Generated from canonical DB Access metadata.
// Simple CRUD / joined select methods regenerate SQL when canonical metadata is sufficient.
// Known helper-style methods regenerate canonical PHP bodies when SQL regeneration is not the right fit.
// Current canonical runtime generation fully owns this class, so no legacy DBAccess parent is required.

class ChattopicAttachmentDBAccessBase
{
    // source_of_truth=sync-bootstrap action_type=UNKNOWN order=11 generation=canonical-constructor
    // reason=bootstrap constructor is empty, so runtime owns the no-op constructor directly
    public function __construct()
    {
    }

    // source_of_truth=sync-bootstrap action_type=SELECTSINGLE order=14 generation=canonical-sql
    public function GetChattopicAttachment($param_ChattopicAttachment_PID_where, $param_ChattopicAttachment_ProjectPID_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'select ChattopicAttachment.ProjectPID, ChattopicAttachment.ChattopicPID, ChattopicAttachment.PID, ChattopicAttachment.name from ChattopicAttachment' . ' where ' . 'ChattopicAttachment.PID = ' . '\'' . $mtooldb->real_escape_string($param_ChattopicAttachment_PID_where) . '\'' . ' and ' . 'ChattopicAttachment.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($param_ChattopicAttachment_ProjectPID_where) . '\'';
        $ret = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new ChattopicAttachmentData();
            $thisresult->ProjectPID = $thisline[0];
            $thisresult->ChattopicPID = $thisline[1];
            $thisresult->PID = $thisline[2];
            $thisresult->name = $thisline[3];
            return $thisresult;
        }
        return NULL;
    }

    // source_of_truth=seed-legacy action_type=SELECTLIST order=39 generation=canonical-sql
    public function GetChattopicAttachmentList($param_ChattopicAttachment_ProjectPID_where, $param_ChattopicAttachment_ChattopicPID_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $result = array();

        $last_sql_command_for_mtooldb = 'select ChattopicAttachment.ProjectPID, ChattopicAttachment.ChattopicPID, ChattopicAttachment.PID, ChattopicAttachment.name from ChattopicAttachment' . ' where ' . 'ChattopicAttachment.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($param_ChattopicAttachment_ProjectPID_where) . '\'' . ' and ' . 'ChattopicAttachment.ChattopicPID = ' . '\'' . $mtooldb->real_escape_string($param_ChattopicAttachment_ChattopicPID_where) . '\'' . ' order by ChattopicAttachment.PID';
        $ret = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new ChattopicAttachmentData();
            $thisresult->ProjectPID = $thisline[0];
            $thisresult->ChattopicPID = $thisline[1];
            $thisresult->PID = $thisline[2];
            $thisresult->name = $thisline[3];
            array_push($result, $thisresult);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=INSERT order=66 generation=canonical-sql
    public function InsertChattopicAttachment($ChattopicAttachmentObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'insert into ChattopicAttachment (ProjectPID, ChattopicPID, PID, name) values(' . '\'' . $mtooldb->real_escape_string($ChattopicAttachmentObj->ProjectPID) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($ChattopicAttachmentObj->ChattopicPID) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($ChattopicAttachmentObj->PID) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($ChattopicAttachmentObj->name) . '\'' . ')';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=UPDATE order=82 generation=canonical-sql
    public function UpdateChattopicAttachment($ChattopicAttachmentObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'update ChattopicAttachment SET ' . 'name = ' . '\'' . $mtooldb->real_escape_string($ChattopicAttachmentObj->name) . '\'' . ' where ' . 'ChattopicAttachment.PID = ' . '\'' . $mtooldb->real_escape_string($ChattopicAttachmentObj->PID) . '\'' . ' and ' . 'ChattopicAttachment.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($ChattopicAttachmentObj->ProjectPID) . '\'';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=DELETE order=98 generation=canonical-sql
    public function DeleteChattopicAttachment($ChattopicAttachmentObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'delete from ChattopicAttachment where ' . 'ChattopicAttachment.PID = ' . '\'' . $mtooldb->real_escape_string($ChattopicAttachmentObj->PID) . '\'' . ' and ' . 'ChattopicAttachment.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($ChattopicAttachmentObj->ProjectPID) . '\'';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }
}

?>