<?php

// AUTO-GENERATED BASE FILE.
// Do not edit this file manually or with AI/Codex.
// Keep customizations in the wrapper/custom class and use this base file exactly as regenerated by the tool.

// Generated from canonical DB Access metadata.
// Simple CRUD / joined select methods regenerate SQL when canonical metadata is sufficient.
// Known helper-style methods regenerate canonical PHP bodies when SQL regeneration is not the right fit.
// Current canonical runtime generation fully owns this class, so no legacy DBAccess parent is required.

class DafuncselectwhereDBAccessBase
{
    // source_of_truth=sync-bootstrap action_type=UNKNOWN order=11 generation=canonical-constructor
    // reason=bootstrap constructor is empty, so runtime owns the no-op constructor directly
    public function __construct()
    {
    }

    // source_of_truth=seed-legacy action_type=SELECTLIST order=14 generation=canonical-sql
    public function GetDafuncselectwhereList($param_Dafuncselectwhere_ProjectPID_where, $param_Dafuncselectwhere_daPID_where, $param_Dafuncselectwhere_DafuncPID_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $result = array();

        $last_sql_command_for_mtooldb = 'select Dafuncselectwhere.ProjectPID, Dafuncselectwhere.DaPID, Dafuncselectwhere.DafuncPID, Dafuncselectwhere.PID, Dafuncselectwhere.targetTableName, Dafuncselectwhere.targetTableAliasName, Dafuncselectwhere.targetTableColumnName, Dafuncselectwhere.ParameterType, Dafuncselectwhere.ParameterDataType, Dafuncselectwhere.FixedParameter, Dafuncselectwhere.AnotherTableName, Dafuncselectwhere.AnotherTableAliasName, Dafuncselectwhere.AnotherFieldName, Dafuncselectwhere.JoinType, Dafuncselectwhere.ORGroup, Dafuncselectwhere.RelationalOperator, Dafuncselectwhere.WhereOrder from Dafuncselectwhere' . ' where ' . 'Dafuncselectwhere.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($param_Dafuncselectwhere_ProjectPID_where) . '\'' . ' and ' . 'Dafuncselectwhere.DaPID = ' . '\'' . $mtooldb->real_escape_string($param_Dafuncselectwhere_daPID_where) . '\'' . ' and ' . 'Dafuncselectwhere.DafuncPID = ' . '\'' . $mtooldb->real_escape_string($param_Dafuncselectwhere_DafuncPID_where) . '\'' . ' order by Dafuncselectwhere.WhereOrder,Dafuncselectwhere.PID';
        $ret = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new DafuncselectwhereData();
            $thisresult->ProjectPID = $thisline[0];
            $thisresult->DaPID = $thisline[1];
            $thisresult->DafuncPID = $thisline[2];
            $thisresult->PID = $thisline[3];
            $thisresult->targetTableName = $thisline[4];
            $thisresult->targetTableAliasName = $thisline[5];
            $thisresult->targetTableColumnName = $thisline[6];
            $thisresult->ParameterType = $thisline[7];
            $thisresult->ParameterDataType = $thisline[8];
            $thisresult->FixedParameter = $thisline[9];
            $thisresult->AnotherTableName = $thisline[10];
            $thisresult->AnotherTableAliasName = $thisline[11];
            $thisresult->AnotherFieldName = $thisline[12];
            $thisresult->JoinType = $thisline[13];
            $thisresult->ORGroup = $thisline[14];
            $thisresult->RelationalOperator = $thisline[15];
            $thisresult->WhereOrder = $thisline[16];
            array_push($result, $thisresult);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=SELECTSINGLE order=54 generation=canonical-sql
    public function GetDafuncselectwhere($param_Dafuncselectwhere_PID_where, $param_Dafuncselectwhere_ProjectPID_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'select Dafuncselectwhere.ProjectPID, Dafuncselectwhere.DaPID, Dafuncselectwhere.DafuncPID, Dafuncselectwhere.PID, Dafuncselectwhere.targetTableName, Dafuncselectwhere.targetTableAliasName, Dafuncselectwhere.targetTableColumnName, Dafuncselectwhere.ParameterType, Dafuncselectwhere.ParameterDataType, Dafuncselectwhere.FixedParameter, Dafuncselectwhere.AnotherTableName, Dafuncselectwhere.AnotherTableAliasName, Dafuncselectwhere.AnotherFieldName, Dafuncselectwhere.JoinType, Dafuncselectwhere.ORGroup, Dafuncselectwhere.RelationalOperator, Dafuncselectwhere.WhereOrder from Dafuncselectwhere' . ' where ' . 'Dafuncselectwhere.PID = ' . '\'' . $mtooldb->real_escape_string($param_Dafuncselectwhere_PID_where) . '\'' . ' and ' . 'Dafuncselectwhere.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($param_Dafuncselectwhere_ProjectPID_where) . '\'';
        $ret = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new DafuncselectwhereData();
            $thisresult->ProjectPID = $thisline[0];
            $thisresult->DaPID = $thisline[1];
            $thisresult->DafuncPID = $thisline[2];
            $thisresult->PID = $thisline[3];
            $thisresult->targetTableName = $thisline[4];
            $thisresult->targetTableAliasName = $thisline[5];
            $thisresult->targetTableColumnName = $thisline[6];
            $thisresult->ParameterType = $thisline[7];
            $thisresult->ParameterDataType = $thisline[8];
            $thisresult->FixedParameter = $thisline[9];
            $thisresult->AnotherTableName = $thisline[10];
            $thisresult->AnotherTableAliasName = $thisline[11];
            $thisresult->AnotherFieldName = $thisline[12];
            $thisresult->JoinType = $thisline[13];
            $thisresult->ORGroup = $thisline[14];
            $thisresult->RelationalOperator = $thisline[15];
            $thisresult->WhereOrder = $thisline[16];
            return $thisresult;
        }
        return NULL;
    }

    // source_of_truth=sync-bootstrap action_type=INSERT order=92 generation=canonical-sql
    public function InsertDafuncselectwhere($DafuncselectwhereObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'insert into Dafuncselectwhere (ProjectPID, DaPID, DafuncPID, targetTableName, targetTableAliasName, targetTableColumnName, ParameterType, ParameterDataType, FixedParameter, AnotherTableName, AnotherTableAliasName, AnotherFieldName, JoinType, ORGroup, RelationalOperator) values(' . '\'' . $mtooldb->real_escape_string($DafuncselectwhereObj->ProjectPID) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($DafuncselectwhereObj->DaPID) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($DafuncselectwhereObj->DafuncPID) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($DafuncselectwhereObj->targetTableName) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($DafuncselectwhereObj->targetTableAliasName) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($DafuncselectwhereObj->targetTableColumnName) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($DafuncselectwhereObj->ParameterType) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($DafuncselectwhereObj->ParameterDataType) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($DafuncselectwhereObj->FixedParameter) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($DafuncselectwhereObj->AnotherTableName) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($DafuncselectwhereObj->AnotherTableAliasName) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($DafuncselectwhereObj->AnotherFieldName) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($DafuncselectwhereObj->JoinType) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($DafuncselectwhereObj->ORGroup) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($DafuncselectwhereObj->RelationalOperator) . '\'' . ')';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=UPDATE order=108 generation=canonical-sql
    public function UpdateDafuncselectwhere($DafuncselectwhereObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'update Dafuncselectwhere SET ' . 'targetTableName = ' . '\'' . $mtooldb->real_escape_string($DafuncselectwhereObj->targetTableName) . '\'' . ', ' . 'targetTableAliasName = ' . '\'' . $mtooldb->real_escape_string($DafuncselectwhereObj->targetTableAliasName) . '\'' . ', ' . 'targetTableColumnName = ' . '\'' . $mtooldb->real_escape_string($DafuncselectwhereObj->targetTableColumnName) . '\'' . ', ' . 'ParameterType = ' . '\'' . $mtooldb->real_escape_string($DafuncselectwhereObj->ParameterType) . '\'' . ', ' . 'ParameterDataType = ' . '\'' . $mtooldb->real_escape_string($DafuncselectwhereObj->ParameterDataType) . '\'' . ', ' . 'FixedParameter = ' . '\'' . $mtooldb->real_escape_string($DafuncselectwhereObj->FixedParameter) . '\'' . ', ' . 'AnotherTableName = ' . '\'' . $mtooldb->real_escape_string($DafuncselectwhereObj->AnotherTableName) . '\'' . ', ' . 'AnotherTableAliasName = ' . '\'' . $mtooldb->real_escape_string($DafuncselectwhereObj->AnotherTableAliasName) . '\'' . ', ' . 'AnotherFieldName = ' . '\'' . $mtooldb->real_escape_string($DafuncselectwhereObj->AnotherFieldName) . '\'' . ', ' . 'JoinType = ' . '\'' . $mtooldb->real_escape_string($DafuncselectwhereObj->JoinType) . '\'' . ', ' . 'ORGroup = ' . '\'' . $mtooldb->real_escape_string($DafuncselectwhereObj->ORGroup) . '\'' . ', ' . 'RelationalOperator = ' . '\'' . $mtooldb->real_escape_string($DafuncselectwhereObj->RelationalOperator) . '\'' . ' where ' . 'Dafuncselectwhere.PID = ' . '\'' . $mtooldb->real_escape_string($DafuncselectwhereObj->PID) . '\'' . ' and ' . 'Dafuncselectwhere.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($DafuncselectwhereObj->ProjectPID) . '\'';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=DELETE order=124 generation=canonical-sql
    public function DeleteDafuncselectwhere($param_Dafuncselectwhere_PID_where, $param_Dafuncselectwhere_ProjectPID_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'delete from Dafuncselectwhere where ' . 'Dafuncselectwhere.PID = ' . '\'' . $mtooldb->real_escape_string($param_Dafuncselectwhere_PID_where) . '\'' . ' and ' . 'Dafuncselectwhere.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($param_Dafuncselectwhere_ProjectPID_where) . '\'';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=UPDATE order=140 generation=canonical-sql
    public function UpdateDafuncselectwhereOrder($param_Dafuncselectwhere_WhereOrder_update, $param_Dafuncselectwhere_PID_where, $param_Dafuncselectwhere_ProjectPID_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'update Dafuncselectwhere SET ' . 'WhereOrder = ' . $param_Dafuncselectwhere_WhereOrder_update . ' where ' . 'Dafuncselectwhere.PID = ' . '\'' . $mtooldb->real_escape_string($param_Dafuncselectwhere_PID_where) . '\'' . ' and ' . 'Dafuncselectwhere.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($param_Dafuncselectwhere_ProjectPID_where) . '\'';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=UPDATE order=156 generation=canonical-sql
    public function UpdateDAPIDforMovingFunction($param_Dafuncselectwhere_daPID_update, $param_Dafuncselectwhere_ProjectPID_where, $param_Dafuncselectwhere_DafuncPID_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'update Dafuncselectwhere SET ' . 'DaPID = ' . '\'' . $mtooldb->real_escape_string($param_Dafuncselectwhere_daPID_update) . '\'' . ' where ' . 'Dafuncselectwhere.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($param_Dafuncselectwhere_ProjectPID_where) . '\'' . ' and ' . 'Dafuncselectwhere.DafuncPID = ' . '\'' . $mtooldb->real_escape_string($param_Dafuncselectwhere_DafuncPID_where) . '\'';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }
}

?>