<?php

// AUTO-GENERATED BASE FILE.
// Do not edit this file manually or with AI/Codex.
// Keep customizations in the wrapper/custom class and use this base file exactly as regenerated by the tool.

// Generated from canonical DB Access metadata.
// Simple CRUD / joined select methods regenerate SQL when canonical metadata is sufficient.
// Known helper-style methods regenerate canonical PHP bodies when SQL regeneration is not the right fit.
// Current canonical runtime generation fully owns this class, so no legacy DBAccess parent is required.

class TestPatternSelectionDBAccessBase
{
    // source_of_truth=sync-bootstrap action_type=UNKNOWN order=11 generation=canonical-constructor
    // reason=bootstrap constructor is empty, so runtime owns the no-op constructor directly
    public function __construct()
    {
    }

    // source_of_truth=seed-legacy action_type=SELECTLIST order=14 generation=canonical-sql
    public function GetTestPatternSelectionList($param_TestPatternSelection_ProjectPID_where, $param_TestPatternSelection_TestGroupPID_where, $param_TestPatternSelection_TestPID_where, $param_TestPatternSelection_TestPatternPID_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $result = array();

        $last_sql_command_for_mtooldb = 'select TestPatternSelection.ProjectPID, TestPatternSelection.TestGroupPID, TestPatternSelection.TestPID, TestPatternSelection.TestPatternPID, TestPatternSelection.PID, TestPatternSelection.Selection from TestPatternSelection' . ' where ' . 'TestPatternSelection.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($param_TestPatternSelection_ProjectPID_where) . '\'' . ' and ' . 'TestPatternSelection.TestGroupPID = ' . '\'' . $mtooldb->real_escape_string($param_TestPatternSelection_TestGroupPID_where) . '\'' . ' and ' . 'TestPatternSelection.TestPID = ' . '\'' . $mtooldb->real_escape_string($param_TestPatternSelection_TestPID_where) . '\'' . ' and ' . 'TestPatternSelection.TestPatternPID = ' . '\'' . $mtooldb->real_escape_string($param_TestPatternSelection_TestPatternPID_where) . '\'' . ' order by TestPatternSelection.PID';
        $ret = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new TestPatternSelectionData();
            $thisresult->ProjectPID = $thisline[0];
            $thisresult->TestGroupPID = $thisline[1];
            $thisresult->TestPID = $thisline[2];
            $thisresult->TestPatternPID = $thisline[3];
            $thisresult->PID = $thisline[4];
            $thisresult->Selection = $thisline[5];
            array_push($result, $thisresult);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=SELECTSINGLE order=43 generation=canonical-sql
    public function GetTestPatternSelection($param_TestPatternSelection_PID_where, $param_TestPatternSelection_ProjectPID_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'select TestPatternSelection.ProjectPID, TestPatternSelection.TestGroupPID, TestPatternSelection.TestPID, TestPatternSelection.TestPatternPID, TestPatternSelection.PID, TestPatternSelection.Selection from TestPatternSelection' . ' where ' . 'TestPatternSelection.PID = ' . '\'' . $mtooldb->real_escape_string($param_TestPatternSelection_PID_where) . '\'' . ' and ' . 'TestPatternSelection.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($param_TestPatternSelection_ProjectPID_where) . '\'';
        $ret = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new TestPatternSelectionData();
            $thisresult->ProjectPID = $thisline[0];
            $thisresult->TestGroupPID = $thisline[1];
            $thisresult->TestPID = $thisline[2];
            $thisresult->TestPatternPID = $thisline[3];
            $thisresult->PID = $thisline[4];
            $thisresult->Selection = $thisline[5];
            return $thisresult;
        }
        return NULL;
    }

    // source_of_truth=sync-bootstrap action_type=INSERT order=70 generation=canonical-sql
    public function InsertTestPatternSelection($TestPatternSelectionObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'insert into TestPatternSelection (ProjectPID, TestGroupPID, TestPID, TestPatternPID, Selection) values(' . '\'' . $mtooldb->real_escape_string($TestPatternSelectionObj->ProjectPID) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($TestPatternSelectionObj->TestGroupPID) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($TestPatternSelectionObj->TestPID) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($TestPatternSelectionObj->TestPatternPID) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($TestPatternSelectionObj->Selection) . '\'' . ')';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=UPDATE order=86 generation=canonical-sql
    public function UpdateTestPatternSelection($TestPatternSelectionObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'update TestPatternSelection SET ' . 'Selection = ' . '\'' . $mtooldb->real_escape_string($TestPatternSelectionObj->Selection) . '\'' . ' where ' . 'TestPatternSelection.PID = ' . '\'' . $mtooldb->real_escape_string($TestPatternSelectionObj->PID) . '\'' . ' and ' . 'TestPatternSelection.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($TestPatternSelectionObj->ProjectPID) . '\'';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=DELETE order=102 generation=canonical-sql
    public function DeleteTestPatternSelection($TestPatternSelectionObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'delete from TestPatternSelection where ' . 'TestPatternSelection.PID = ' . '\'' . $mtooldb->real_escape_string($TestPatternSelectionObj->PID) . '\'' . ' and ' . 'TestPatternSelection.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($TestPatternSelectionObj->ProjectPID) . '\'';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }
}

?>