<?php

// AUTO-GENERATED BASE FILE.
// Do not edit this file manually or with AI/Codex.
// Keep customizations in the wrapper/custom class and use this base file exactly as regenerated by the tool.

// Generated from canonical DB Access metadata.
// Simple CRUD / joined select methods regenerate SQL when canonical metadata is sufficient.
// Known helper-style methods regenerate canonical PHP bodies when SQL regeneration is not the right fit.
// Current canonical runtime generation fully owns this class, so no legacy DBAccess parent is required.

class CompareOutputDBAccessBase
{
    // source_of_truth=sync-bootstrap action_type=UNKNOWN order=11 generation=canonical-constructor
    // reason=bootstrap constructor is empty, so runtime owns the no-op constructor directly
    public function __construct()
    {
    }

    // source_of_truth=sync-bootstrap action_type=SELECTLIST order=14 generation=canonical-sql
    public function GetCompareOutputList($param_CompareOutput_ProjectPID_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $result = array();

        $last_sql_command_for_mtooldb = 'select CompareOutput.PID, CompareOutput.ProjectPID, CompareOutput.DropboxBaseFolderPID, CompareOutput.OutputFilePath, CompareOutput.OutputFileType, CompareOutput.ComparePath, CompareOutput.CompareToolFilePath from CompareOutput' . ' where ' . 'CompareOutput.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($param_CompareOutput_ProjectPID_where) . '\'';
        $ret = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new CompareOutputData();
            $thisresult->PID = $thisline[0];
            $thisresult->ProjectPID = $thisline[1];
            $thisresult->DropboxBaseFolderPID = $thisline[2];
            $thisresult->OutputFilePath = $thisline[3];
            $thisresult->OutputFileType = $thisline[4];
            $thisresult->ComparePath = $thisline[5];
            $thisresult->CompareToolFilePath = $thisline[6];
            array_push($result, $thisresult);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=SELECTSINGLE order=44 generation=canonical-sql
    public function GetCompareOutput($param_CompareOutput_PID_where, $param_CompareOutput_ProjectPID_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'select CompareOutput.PID, CompareOutput.ProjectPID, CompareOutput.DropboxBaseFolderPID, CompareOutput.OutputFilePath, CompareOutput.OutputFileType, CompareOutput.ComparePath, CompareOutput.CompareToolFilePath from CompareOutput' . ' where ' . 'CompareOutput.PID = ' . '\'' . $mtooldb->real_escape_string($param_CompareOutput_PID_where) . '\'' . ' and ' . 'CompareOutput.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($param_CompareOutput_ProjectPID_where) . '\'';
        $ret = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new CompareOutputData();
            $thisresult->PID = $thisline[0];
            $thisresult->ProjectPID = $thisline[1];
            $thisresult->DropboxBaseFolderPID = $thisline[2];
            $thisresult->OutputFilePath = $thisline[3];
            $thisresult->OutputFileType = $thisline[4];
            $thisresult->ComparePath = $thisline[5];
            $thisresult->CompareToolFilePath = $thisline[6];
            return $thisresult;
        }
        return NULL;
    }

    // source_of_truth=sync-bootstrap action_type=INSERT order=72 generation=canonical-sql
    public function InsertCompareOutput($CompareOutputObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'insert into CompareOutput (ProjectPID, DropboxBaseFolderPID, OutputFilePath, OutputFileType, ComparePath, CompareToolFilePath) values(' . '\'' . $mtooldb->real_escape_string($CompareOutputObj->ProjectPID) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($CompareOutputObj->DropboxBaseFolderPID) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($CompareOutputObj->OutputFilePath) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($CompareOutputObj->OutputFileType) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($CompareOutputObj->ComparePath) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($CompareOutputObj->CompareToolFilePath) . '\'' . ')';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=UPDATE order=88 generation=canonical-sql
    public function UpdateCompareOutput($CompareOutputObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'update CompareOutput SET ' . 'DropboxBaseFolderPID = ' . '\'' . $mtooldb->real_escape_string($CompareOutputObj->DropboxBaseFolderPID) . '\'' . ', ' . 'OutputFilePath = ' . '\'' . $mtooldb->real_escape_string($CompareOutputObj->OutputFilePath) . '\'' . ', ' . 'OutputFileType = ' . '\'' . $mtooldb->real_escape_string($CompareOutputObj->OutputFileType) . '\'' . ', ' . 'ComparePath = ' . '\'' . $mtooldb->real_escape_string($CompareOutputObj->ComparePath) . '\'' . ', ' . 'CompareToolFilePath = ' . '\'' . $mtooldb->real_escape_string($CompareOutputObj->CompareToolFilePath) . '\'' . ' where ' . 'CompareOutput.PID = ' . '\'' . $mtooldb->real_escape_string($CompareOutputObj->PID) . '\'' . ' and ' . 'CompareOutput.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($CompareOutputObj->ProjectPID) . '\'';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=DELETE order=104 generation=canonical-sql
    public function DeleteCompareOutput($CompareOutputObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'delete from CompareOutput where ' . 'CompareOutput.PID = ' . '\'' . $mtooldb->real_escape_string($CompareOutputObj->PID) . '\'' . ' and ' . 'CompareOutput.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($CompareOutputObj->ProjectPID) . '\'';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }
}

?>