<?php

// AUTO-GENERATED BASE FILE.
// Do not edit this file manually or with AI/Codex.
// Keep customizations in the wrapper/custom class and use this base file exactly as regenerated by the tool.

// Generated from canonical DB Access metadata.
// Simple CRUD / joined select methods regenerate SQL when canonical metadata is sufficient.
// Known helper-style methods regenerate canonical PHP bodies when SQL regeneration is not the right fit.
// Current canonical runtime generation fully owns this class, so no legacy DBAccess parent is required.

class DaCustomProxySourceOutputTargetDBAccessBase
{
    // source_of_truth=sync-bootstrap action_type=UNKNOWN order=11 generation=canonical-constructor
    // reason=bootstrap constructor is empty, so runtime owns the no-op constructor directly
    public function __construct()
    {
    }

    // source_of_truth=sync-bootstrap action_type=SELECTLIST order=14 generation=canonical-sql
    public function GetdaCustomProxySourceOutputTargetList($param_daCustomProxySourceOutputTarget_ProjectPID_where, $param_daCustomProxySourceOutputTarget_daCustomProxyPID_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $result = array();

        $last_sql_command_for_mtooldb = 'select DaCustomProxySourceOutputTarget.ProjectPID, DaCustomProxySourceOutputTarget.DaCustomProxyPID, DaCustomProxySourceOutputTarget.PID, DaCustomProxySourceOutputTarget.ProjectSourceOutputPID from DaCustomProxySourceOutputTarget' . ' where ' . 'DaCustomProxySourceOutputTarget.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($param_daCustomProxySourceOutputTarget_ProjectPID_where) . '\'' . ' and ' . 'DaCustomProxySourceOutputTarget.DaCustomProxyPID = ' . '\'' . $mtooldb->real_escape_string($param_daCustomProxySourceOutputTarget_daCustomProxyPID_where) . '\'';
        $ret = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new DaCustomProxySourceOutputTargetData();
            $thisresult->ProjectPID = $thisline[0];
            $thisresult->DaCustomProxyPID = $thisline[1];
            $thisresult->PID = $thisline[2];
            $thisresult->ProjectSourceOutputPID = $thisline[3];
            array_push($result, $thisresult);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=SELECTSINGLE order=41 generation=canonical-sql
    public function GetdaCustomProxySourceOutputTargetForOneOutputSource($param_daCustomProxySourceOutputTarget_ProjectPID_where, $param_daCustomProxySourceOutputTarget_daCustomProxyPID_where, $param_daCustomProxySourceOutputTarget_ProjectSourceOutputPID_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'select DaCustomProxySourceOutputTarget.ProjectPID, DaCustomProxySourceOutputTarget.DaCustomProxyPID, DaCustomProxySourceOutputTarget.PID, DaCustomProxySourceOutputTarget.ProjectSourceOutputPID from DaCustomProxySourceOutputTarget' . ' where ' . 'DaCustomProxySourceOutputTarget.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($param_daCustomProxySourceOutputTarget_ProjectPID_where) . '\'' . ' and ' . 'DaCustomProxySourceOutputTarget.DaCustomProxyPID = ' . '\'' . $mtooldb->real_escape_string($param_daCustomProxySourceOutputTarget_daCustomProxyPID_where) . '\'' . ' and ' . 'DaCustomProxySourceOutputTarget.ProjectSourceOutputPID = ' . '\'' . $mtooldb->real_escape_string($param_daCustomProxySourceOutputTarget_ProjectSourceOutputPID_where) . '\'';
        $ret = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new DaCustomProxySourceOutputTargetData();
            $thisresult->ProjectPID = $thisline[0];
            $thisresult->DaCustomProxyPID = $thisline[1];
            $thisresult->PID = $thisline[2];
            $thisresult->ProjectSourceOutputPID = $thisline[3];
            return $thisresult;
        }
        return NULL;
    }

    // source_of_truth=sync-bootstrap action_type=INSERT order=66 generation=canonical-sql
    public function InsertdaCustomProxySourceOutputTarget($DaCustomProxySourceOutputTargetObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'insert into DaCustomProxySourceOutputTarget (ProjectPID, DaCustomProxyPID, ProjectSourceOutputPID) values(' . '\'' . $mtooldb->real_escape_string($DaCustomProxySourceOutputTargetObj->ProjectPID) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($DaCustomProxySourceOutputTargetObj->DaCustomProxyPID) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($DaCustomProxySourceOutputTargetObj->ProjectSourceOutputPID) . '\'' . ')';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=DELETE order=82 generation=canonical-sql
    public function DeletedaCustomProxySourceOutputTarget($DaCustomProxySourceOutputTargetObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'delete from DaCustomProxySourceOutputTarget where ' . 'DaCustomProxySourceOutputTarget.PID = ' . '\'' . $mtooldb->real_escape_string($DaCustomProxySourceOutputTargetObj->PID) . '\'' . ' and ' . 'DaCustomProxySourceOutputTarget.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($DaCustomProxySourceOutputTargetObj->ProjectPID) . '\'';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }
}

?>