<?php

// AUTO-GENERATED BASE FILE.
// Do not edit this file manually or with AI/Codex.
// Keep customizations in the wrapper/custom class and use this base file exactly as regenerated by the tool.

// Generated from canonical DB Access metadata.
// Simple CRUD / joined select methods regenerate SQL when canonical metadata is sufficient.
// Known helper-style methods regenerate canonical PHP bodies when SQL regeneration is not the right fit.
// Current canonical runtime generation fully owns this class, so no legacy DBAccess parent is required.

class CompareOutputSearchCacheHintDBAccessBase
{
    // source_of_truth=sync-bootstrap action_type=UNKNOWN order=11 generation=canonical-constructor
    // reason=bootstrap constructor is empty, so runtime owns the no-op constructor directly
    public function __construct()
    {
    }

    // source_of_truth=sync-bootstrap action_type=SELECTSINGLE order=14 generation=canonical-sql
    public function GetCompareOutputSearchCacheHint($param_CompareOutputSearchCacheHint_DropboxSettingPID_where, $param_CompareOutputSearchCacheHint_UpdatedFileWhenUpload_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'select CompareOutputSearchCacheHint.PID, CompareOutputSearchCacheHint.DropboxSettingPID, CompareOutputSearchCacheHint.UpdatedFileWhenUpload, CompareOutputSearchCacheHint.UpdatedDT from CompareOutputSearchCacheHint' . ' where ' . 'CompareOutputSearchCacheHint.DropboxSettingPID = ' . '\'' . $mtooldb->real_escape_string($param_CompareOutputSearchCacheHint_DropboxSettingPID_where) . '\'' . ' and ' . 'CompareOutputSearchCacheHint.UpdatedFileWhenUpload = ' . '\'' . $mtooldb->real_escape_string($param_CompareOutputSearchCacheHint_UpdatedFileWhenUpload_where) . '\'';
        $ret = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new CompareOutputSearchCacheHintData();
            $thisresult->PID = $thisline[0];
            $thisresult->DropboxSettingPID = $thisline[1];
            $thisresult->UpdatedFileWhenUpload = $thisline[2];
            $thisresult->UpdatedDT = $thisline[3];
            return $thisresult;
        }
        return NULL;
    }

    // source_of_truth=sync-bootstrap action_type=INSERT order=39 generation=canonical-sql
    public function InsertCompareOutputSearchCacheHint($CompareOutputSearchCacheHintObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'insert into CompareOutputSearchCacheHint (DropboxSettingPID, UpdatedFileWhenUpload) values(' . '\'' . $mtooldb->real_escape_string($CompareOutputSearchCacheHintObj->DropboxSettingPID) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($CompareOutputSearchCacheHintObj->UpdatedFileWhenUpload) . '\'' . ')';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=DELETE order=55 generation=canonical-sql
    public function DeleteCompareOutputSearchCacheHint($CompareOutputSearchCacheHintObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'delete from CompareOutputSearchCacheHint where ' . 'CompareOutputSearchCacheHint.DropboxSettingPID = ' . '\'' . $mtooldb->real_escape_string($CompareOutputSearchCacheHintObj->DropboxSettingPID) . '\'' . ' and ' . 'CompareOutputSearchCacheHint.UpdatedFileWhenUpload = ' . '\'' . $mtooldb->real_escape_string($CompareOutputSearchCacheHintObj->UpdatedFileWhenUpload) . '\'';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }
}

?>