<?php

// AUTO-GENERATED BASE FILE.
// Do not edit this file manually or with AI/Codex.
// Keep customizations in the wrapper/custom class and use this base file exactly as regenerated by the tool.

// Generated from canonical DB Access metadata.
// Simple CRUD / joined select methods regenerate SQL when canonical metadata is sufficient.
// Known helper-style methods regenerate canonical PHP bodies when SQL regeneration is not the right fit.
// Current canonical runtime generation fully owns this class, so no legacy DBAccess parent is required.

class dafuncDBAccessBase
{
    // source_of_truth=sync-bootstrap action_type=UNKNOWN order=11 generation=canonical-constructor
    // reason=bootstrap constructor is empty, so runtime owns the no-op constructor directly
    public function __construct()
    {
    }

    // source_of_truth=seed-legacy action_type=SELECTLIST order=14 generation=canonical-sql
    public function GetdafuncList($param_dafunc_ProjectPID_where, $param_dafunc_daPID_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $result = array();

        $last_sql_command_for_mtooldb = 'select dafunc.ProjectPID, dafunc.daPID, dafunc.PID, dafunc.name, dafunc.ActionType, dafunc.InsertUpdateDeleteTargetTable, dafunc.InsertUpdateDeleteParamType, dafunc.SelectByDistinct, dafunc.SortOrderColumns, dafunc.DataClassBaseNameForSelectAction, dafunc.FunctionListOrder, dafunc.memo, dafunc.limitParameterType, dafunc.limitFixedParameter, dafunc.ORGroupType, dafunc.SingleProxy_AuthType, dafunc.SingleProxy_SingleGetFuncPID, dafunc.IsBlobTarget from dafunc' . ' where ' . 'dafunc.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($param_dafunc_ProjectPID_where) . '\'' . ' and ' . 'dafunc.daPID = ' . '\'' . $mtooldb->real_escape_string($param_dafunc_daPID_where) . '\'' . ' order by dafunc.FunctionListOrder,dafunc.PID';
        $ret = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new dafuncData();
            $thisresult->ProjectPID = $thisline[0];
            $thisresult->daPID = $thisline[1];
            $thisresult->PID = $thisline[2];
            $thisresult->name = $thisline[3];
            $thisresult->ActionType = $thisline[4];
            $thisresult->InsertUpdateDeleteTargetTable = $thisline[5];
            $thisresult->InsertUpdateDeleteParamType = $thisline[6];
            $thisresult->SelectByDistinct = $thisline[7];
            $thisresult->SortOrderColumns = $thisline[8];
            $thisresult->DataClassBaseNameForSelectAction = $thisline[9];
            $thisresult->FunctionListOrder = $thisline[10];
            $thisresult->memo = $thisline[11];
            $thisresult->limitParameterType = $thisline[12];
            $thisresult->limitFixedParameter = $thisline[13];
            $thisresult->ORGroupType = $thisline[14];
            $thisresult->SingleProxy_AuthType = $thisline[15];
            $thisresult->SingleProxy_SingleGetFuncPID = $thisline[16];
            $thisresult->IsBlobTarget = $thisline[17];
            array_push($result, $thisresult);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=SELECTSINGLE order=55 generation=canonical-sql
    public function Getdafunc($param_dafunc_PID_where, $param_dafunc_ProjectPID_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'select dafunc.ProjectPID, dafunc.daPID, dafunc.PID, dafunc.name, dafunc.ActionType, dafunc.InsertUpdateDeleteTargetTable, dafunc.InsertUpdateDeleteParamType, dafunc.SelectByDistinct, dafunc.SortOrderColumns, dafunc.DataClassBaseNameForSelectAction, dafunc.FunctionListOrder, dafunc.memo, dafunc.limitParameterType, dafunc.limitFixedParameter, dafunc.ORGroupType, dafunc.SingleProxy_AuthType, dafunc.SingleProxy_SingleGetFuncPID, dafunc.IsBlobTarget from dafunc' . ' where ' . 'dafunc.PID = ' . '\'' . $mtooldb->real_escape_string($param_dafunc_PID_where) . '\'' . ' and ' . 'dafunc.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($param_dafunc_ProjectPID_where) . '\'';
        $ret = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new dafuncData();
            $thisresult->ProjectPID = $thisline[0];
            $thisresult->daPID = $thisline[1];
            $thisresult->PID = $thisline[2];
            $thisresult->name = $thisline[3];
            $thisresult->ActionType = $thisline[4];
            $thisresult->InsertUpdateDeleteTargetTable = $thisline[5];
            $thisresult->InsertUpdateDeleteParamType = $thisline[6];
            $thisresult->SelectByDistinct = $thisline[7];
            $thisresult->SortOrderColumns = $thisline[8];
            $thisresult->DataClassBaseNameForSelectAction = $thisline[9];
            $thisresult->FunctionListOrder = $thisline[10];
            $thisresult->memo = $thisline[11];
            $thisresult->limitParameterType = $thisline[12];
            $thisresult->limitFixedParameter = $thisline[13];
            $thisresult->ORGroupType = $thisline[14];
            $thisresult->SingleProxy_AuthType = $thisline[15];
            $thisresult->SingleProxy_SingleGetFuncPID = $thisline[16];
            $thisresult->IsBlobTarget = $thisline[17];
            return $thisresult;
        }
        return NULL;
    }

    // source_of_truth=sync-bootstrap action_type=INSERT order=94 generation=canonical-sql
    public function Insertdafunc($dafuncObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'insert into dafunc (ProjectPID, daPID, name, ActionType, InsertUpdateDeleteTargetTable, InsertUpdateDeleteParamType, SelectByDistinct, SortOrderColumns, DataClassBaseNameForSelectAction, memo, limitParameterType, limitFixedParameter, ORGroupType, IsBlobTarget) values(' . '\'' . $mtooldb->real_escape_string($dafuncObj->ProjectPID) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($dafuncObj->daPID) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($dafuncObj->name) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($dafuncObj->ActionType) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($dafuncObj->InsertUpdateDeleteTargetTable) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($dafuncObj->InsertUpdateDeleteParamType) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($dafuncObj->SelectByDistinct) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($dafuncObj->SortOrderColumns) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($dafuncObj->DataClassBaseNameForSelectAction) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($dafuncObj->memo) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($dafuncObj->limitParameterType) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($dafuncObj->limitFixedParameter) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($dafuncObj->ORGroupType) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($dafuncObj->IsBlobTarget) . '\'' . ')';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=UPDATE order=110 generation=canonical-sql
    public function Updatedafunc($dafuncObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'update dafunc SET ' . 'name = ' . '\'' . $mtooldb->real_escape_string($dafuncObj->name) . '\'' . ', ' . 'ActionType = ' . '\'' . $mtooldb->real_escape_string($dafuncObj->ActionType) . '\'' . ', ' . 'InsertUpdateDeleteTargetTable = ' . '\'' . $mtooldb->real_escape_string($dafuncObj->InsertUpdateDeleteTargetTable) . '\'' . ', ' . 'InsertUpdateDeleteParamType = ' . '\'' . $mtooldb->real_escape_string($dafuncObj->InsertUpdateDeleteParamType) . '\'' . ', ' . 'SelectByDistinct = ' . '\'' . $mtooldb->real_escape_string($dafuncObj->SelectByDistinct) . '\'' . ', ' . 'SortOrderColumns = ' . '\'' . $mtooldb->real_escape_string($dafuncObj->SortOrderColumns) . '\'' . ', ' . 'DataClassBaseNameForSelectAction = ' . '\'' . $mtooldb->real_escape_string($dafuncObj->DataClassBaseNameForSelectAction) . '\'' . ', ' . 'memo = ' . '\'' . $mtooldb->real_escape_string($dafuncObj->memo) . '\'' . ', ' . 'limitParameterType = ' . '\'' . $mtooldb->real_escape_string($dafuncObj->limitParameterType) . '\'' . ', ' . 'limitFixedParameter = ' . '\'' . $mtooldb->real_escape_string($dafuncObj->limitFixedParameter) . '\'' . ', ' . 'ORGroupType = ' . '\'' . $mtooldb->real_escape_string($dafuncObj->ORGroupType) . '\'' . ', ' . 'IsBlobTarget = ' . '\'' . $mtooldb->real_escape_string($dafuncObj->IsBlobTarget) . '\'' . ' where ' . 'dafunc.PID = ' . '\'' . $mtooldb->real_escape_string($dafuncObj->PID) . '\'' . ' and ' . 'dafunc.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($dafuncObj->ProjectPID) . '\'';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=UPDATE order=126 generation=canonical-sql
    public function UpdateSingleProxySetting($dafuncObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'update dafunc SET ' . 'SingleProxy_AuthType = ' . '\'' . $mtooldb->real_escape_string($dafuncObj->SingleProxy_AuthType) . '\'' . ', ' . 'SingleProxy_SingleGetFuncPID = ' . '\'' . $mtooldb->real_escape_string($dafuncObj->SingleProxy_SingleGetFuncPID) . '\'' . ' where ' . 'dafunc.PID = ' . '\'' . $mtooldb->real_escape_string($dafuncObj->PID) . '\'' . ' and ' . 'dafunc.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($dafuncObj->ProjectPID) . '\'';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=DELETE order=142 generation=canonical-sql
    public function Deletedafunc($param_dafunc_PID_where, $param_dafunc_ProjectPID_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'delete from dafunc where ' . 'dafunc.PID = ' . '\'' . $mtooldb->real_escape_string($param_dafunc_PID_where) . '\'' . ' and ' . 'dafunc.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($param_dafunc_ProjectPID_where) . '\'';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=UPDATE order=158 generation=canonical-sql
    public function UpdatedafuncSortOrderColumns($dafuncObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'update dafunc SET ' . 'SortOrderColumns = ' . '\'' . $mtooldb->real_escape_string($dafuncObj->SortOrderColumns) . '\'' . ' where ' . 'dafunc.PID = ' . '\'' . $mtooldb->real_escape_string($dafuncObj->PID) . '\'' . ' and ' . 'dafunc.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($dafuncObj->ProjectPID) . '\'';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=UPDATE order=174 generation=canonical-sql
    public function UpdatedafuncFunctionListOrder($param_dafunc_FunctionListOrder_update, $param_dafunc_PID_where, $param_dafunc_ProjectPID_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'update dafunc SET ' . 'FunctionListOrder = ' . $param_dafunc_FunctionListOrder_update . ' where ' . 'dafunc.PID = ' . '\'' . $mtooldb->real_escape_string($param_dafunc_PID_where) . '\'' . ' and ' . 'dafunc.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($param_dafunc_ProjectPID_where) . '\'';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=UPDATE order=190 generation=canonical-sql
    public function UpdateDAPIDforMovingFunction($param_dafunc_daPID_update, $param_dafunc_ProjectPID_where, $param_dafunc_PID_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'update dafunc SET ' . 'daPID = ' . '\'' . $mtooldb->real_escape_string($param_dafunc_daPID_update) . '\'' . ' where ' . 'dafunc.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($param_dafunc_ProjectPID_where) . '\'' . ' and ' . 'dafunc.PID = ' . '\'' . $mtooldb->real_escape_string($param_dafunc_PID_where) . '\'';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }
}

?>