<?php

// AUTO-GENERATED BASE FILE.
// Do not edit this file manually or with AI/Codex.
// Keep customizations in the wrapper/custom class and use this base file exactly as regenerated by the tool.

// Generated from canonical DB Access metadata.
// Simple CRUD / joined select methods regenerate SQL when canonical metadata is sufficient.
// Known helper-style methods regenerate canonical PHP bodies when SQL regeneration is not the right fit.
// Current canonical runtime generation fully owns this class, so no legacy DBAccess parent is required.

class DafuncinserttargetfieldsDBAccessBase
{
    // source_of_truth=sync-bootstrap action_type=UNKNOWN order=11 generation=canonical-constructor
    // reason=bootstrap constructor is empty, so runtime owns the no-op constructor directly
    public function __construct()
    {
    }

    // source_of_truth=seed-legacy action_type=SELECTLIST order=14 generation=canonical-sql
    public function GetDafuncinserttargetfieldsList($param_Dafuncinserttargetfields_ProjectPID_where, $param_Dafuncinserttargetfields_daPID_where, $param_Dafuncinserttargetfields_DafuncPID_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $result = array();

        $last_sql_command_for_mtooldb = 'select Dafuncinserttargetfields.ProjectPID, Dafuncinserttargetfields.DaPID, Dafuncinserttargetfields.DafuncPID, Dafuncinserttargetfields.PID, Dafuncinserttargetfields.targetTableColumnName, Dafuncinserttargetfields.ParameterType, Dafuncinserttargetfields.ParameterDataType, Dafuncinserttargetfields.FixedParameter from Dafuncinserttargetfields' . ' where ' . 'Dafuncinserttargetfields.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($param_Dafuncinserttargetfields_ProjectPID_where) . '\'' . ' and ' . 'Dafuncinserttargetfields.DaPID = ' . '\'' . $mtooldb->real_escape_string($param_Dafuncinserttargetfields_daPID_where) . '\'' . ' and ' . 'Dafuncinserttargetfields.DafuncPID = ' . '\'' . $mtooldb->real_escape_string($param_Dafuncinserttargetfields_DafuncPID_where) . '\'' . ' order by Dafuncinserttargetfields.FieldListOrder,Dafuncinserttargetfields.ProjectPID,Dafuncinserttargetfields.DaPID,Dafuncinserttargetfields.DafuncPID,Dafuncinserttargetfields.PID';
        $ret = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new DafuncinserttargetfieldsData();
            $thisresult->ProjectPID = $thisline[0];
            $thisresult->DaPID = $thisline[1];
            $thisresult->DafuncPID = $thisline[2];
            $thisresult->PID = $thisline[3];
            $thisresult->targetTableColumnName = $thisline[4];
            $thisresult->ParameterType = $thisline[5];
            $thisresult->ParameterDataType = $thisline[6];
            $thisresult->FixedParameter = $thisline[7];
            array_push($result, $thisresult);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=SELECTSINGLE order=45 generation=canonical-sql
    public function GetDafuncinserttargetfields($param_Dafuncinserttargetfields_PID_where, $param_Dafuncinserttargetfields_ProjectPID_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'select Dafuncinserttargetfields.ProjectPID, Dafuncinserttargetfields.DaPID, Dafuncinserttargetfields.DafuncPID, Dafuncinserttargetfields.PID, Dafuncinserttargetfields.targetTableColumnName, Dafuncinserttargetfields.ParameterType, Dafuncinserttargetfields.ParameterDataType, Dafuncinserttargetfields.FixedParameter from Dafuncinserttargetfields' . ' where ' . 'Dafuncinserttargetfields.PID = ' . '\'' . $mtooldb->real_escape_string($param_Dafuncinserttargetfields_PID_where) . '\'' . ' and ' . 'Dafuncinserttargetfields.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($param_Dafuncinserttargetfields_ProjectPID_where) . '\'';
        $ret = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new DafuncinserttargetfieldsData();
            $thisresult->ProjectPID = $thisline[0];
            $thisresult->DaPID = $thisline[1];
            $thisresult->DafuncPID = $thisline[2];
            $thisresult->PID = $thisline[3];
            $thisresult->targetTableColumnName = $thisline[4];
            $thisresult->ParameterType = $thisline[5];
            $thisresult->ParameterDataType = $thisline[6];
            $thisresult->FixedParameter = $thisline[7];
            return $thisresult;
        }
        return NULL;
    }

    // source_of_truth=sync-bootstrap action_type=INSERT order=74 generation=canonical-sql
    public function InsertDafuncinserttargetfields($DafuncinserttargetfieldsObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'insert into Dafuncinserttargetfields (ProjectPID, DaPID, DafuncPID, targetTableColumnName, ParameterType, ParameterDataType, FixedParameter) values(' . '\'' . $mtooldb->real_escape_string($DafuncinserttargetfieldsObj->ProjectPID) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($DafuncinserttargetfieldsObj->DaPID) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($DafuncinserttargetfieldsObj->DafuncPID) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($DafuncinserttargetfieldsObj->targetTableColumnName) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($DafuncinserttargetfieldsObj->ParameterType) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($DafuncinserttargetfieldsObj->ParameterDataType) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($DafuncinserttargetfieldsObj->FixedParameter) . '\'' . ')';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=UPDATE order=90 generation=canonical-sql
    public function UpdateDafuncinserttargetfields($DafuncinserttargetfieldsObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'update Dafuncinserttargetfields SET ' . 'targetTableColumnName = ' . '\'' . $mtooldb->real_escape_string($DafuncinserttargetfieldsObj->targetTableColumnName) . '\'' . ', ' . 'ParameterType = ' . '\'' . $mtooldb->real_escape_string($DafuncinserttargetfieldsObj->ParameterType) . '\'' . ', ' . 'ParameterDataType = ' . '\'' . $mtooldb->real_escape_string($DafuncinserttargetfieldsObj->ParameterDataType) . '\'' . ', ' . 'FixedParameter = ' . '\'' . $mtooldb->real_escape_string($DafuncinserttargetfieldsObj->FixedParameter) . '\'' . ' where ' . 'Dafuncinserttargetfields.PID = ' . '\'' . $mtooldb->real_escape_string($DafuncinserttargetfieldsObj->PID) . '\'' . ' and ' . 'Dafuncinserttargetfields.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($DafuncinserttargetfieldsObj->ProjectPID) . '\'';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=UPDATE order=106 generation=canonical-sql
    public function UpdateSelectTargetFieldListOrder($param_Dafuncinserttargetfields_FieldListOrder_update, $param_Dafuncinserttargetfields_PID_where, $param_Dafuncinserttargetfields_ProjectPID_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'update Dafuncinserttargetfields SET ' . 'FieldListOrder = ' . '\'' . $mtooldb->real_escape_string($param_Dafuncinserttargetfields_FieldListOrder_update) . '\'' . ' where ' . 'Dafuncinserttargetfields.PID = ' . '\'' . $mtooldb->real_escape_string($param_Dafuncinserttargetfields_PID_where) . '\'' . ' and ' . 'Dafuncinserttargetfields.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($param_Dafuncinserttargetfields_ProjectPID_where) . '\'';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=DELETE order=122 generation=canonical-sql
    public function DeleteDafuncinserttargetfields($param_Dafuncinserttargetfields_PID_where, $param_Dafuncinserttargetfields_ProjectPID_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'delete from Dafuncinserttargetfields where ' . 'Dafuncinserttargetfields.PID = ' . '\'' . $mtooldb->real_escape_string($param_Dafuncinserttargetfields_PID_where) . '\'' . ' and ' . 'Dafuncinserttargetfields.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($param_Dafuncinserttargetfields_ProjectPID_where) . '\'';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=UPDATE order=138 generation=canonical-sql
    public function UpdateDAPIDforMovingFunction($param_Dafuncinserttargetfields_daPID_update, $param_Dafuncinserttargetfields_ProjectPID_where, $param_Dafuncinserttargetfields_DafuncPID_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'update Dafuncinserttargetfields SET ' . 'DaPID = ' . '\'' . $mtooldb->real_escape_string($param_Dafuncinserttargetfields_daPID_update) . '\'' . ' where ' . 'Dafuncinserttargetfields.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($param_Dafuncinserttargetfields_ProjectPID_where) . '\'' . ' and ' . 'Dafuncinserttargetfields.DafuncPID = ' . '\'' . $mtooldb->real_escape_string($param_Dafuncinserttargetfields_DafuncPID_where) . '\'';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }
}

?>