<?php

// AUTO-GENERATED BASE FILE.
// Do not edit this file manually or with AI/Codex.
// Keep customizations in the wrapper/custom class and use this base file exactly as regenerated by the tool.

// Generated from canonical DB Access metadata.
// Simple CRUD / joined select methods regenerate SQL when canonical metadata is sufficient.
// Known helper-style methods regenerate canonical PHP bodies when SQL regeneration is not the right fit.
// Current canonical runtime generation fully owns this class, so no legacy DBAccess parent is required.

class ProjectHostSettingDBAccessBase
{
    // source_of_truth=sync-bootstrap action_type=UNKNOWN order=11 generation=canonical-constructor
    // reason=bootstrap constructor is empty, so runtime owns the no-op constructor directly
    public function __construct()
    {
    }

    // source_of_truth=sync-bootstrap action_type=SELECTLIST order=14 generation=canonical-sql
    public function GetProjectHostSettingByProjectList($param_ProjectHostSetting_ProjectPID_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $result = array();

        $last_sql_command_for_mtooldb = 'select ProjectHostSetting.ProjectPID, ProjectHostSetting.PID, ProjectHostSetting.ApacheSettingPID, ProjectHostSetting.ApacheHostSettingPID, ApacheSetting.name, ApacheHostSetting.VirtualHostName, ApacheHostSettingTemplate.name, Server.LocalServerName from ProjectHostSetting left outer join ApacheSetting on ProjectHostSetting.ApacheSettingPID = ApacheSetting.PID left outer join ApacheHostSetting on ProjectHostSetting.ApacheHostSettingPID = ApacheHostSetting.PID and ProjectHostSetting.ApacheSettingPID = ApacheHostSetting.ApacheSettingPID left outer join ApacheHostSettingTemplate on ApacheHostSetting.ApacheHostSettingTemplatePID = ApacheHostSettingTemplate.PID left outer join Server on ApacheSetting.ServerPID = Server.PID' . ' where ' . 'ProjectHostSetting.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($param_ProjectHostSetting_ProjectPID_where) . '\'';
        $ret = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new ProjectHostSettingData();
            $thisresult->ProjectPID = $thisline[0];
            $thisresult->PID = $thisline[1];
            $thisresult->ApacheSettingPID = $thisline[2];
            $thisresult->ApacheHostSettingPID = $thisline[3];
            $thisresult->ApacheSettingname = $thisline[4];
            $thisresult->ApacheHostSettingVirtualHostName = $thisline[5];
            $thisresult->ApacheHostSettingTemplatename = $thisline[6];
            $thisresult->ServerLocalServerName = $thisline[7];
            array_push($result, $thisresult);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=INSERT order=45 generation=canonical-sql
    public function InsertProjectHostSetting($ProjectHostSettingObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'insert into ProjectHostSetting (ProjectPID, ApacheSettingPID, ApacheHostSettingPID) values(' . '\'' . $mtooldb->real_escape_string($ProjectHostSettingObj->ProjectPID) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($ProjectHostSettingObj->ApacheSettingPID) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($ProjectHostSettingObj->ApacheHostSettingPID) . '\'' . ')';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=DELETE order=61 generation=canonical-sql
    public function DeleteProjectHostSetting($ProjectHostSettingObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'delete from ProjectHostSetting where ' . 'ProjectHostSetting.PID = ' . '\'' . $mtooldb->real_escape_string($ProjectHostSettingObj->PID) . '\'' . ' and ' . 'ProjectHostSetting.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($ProjectHostSettingObj->ProjectPID) . '\'';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }
}

?>