<?php

// AUTO-GENERATED BASE FILE.
// Do not edit this file manually or with AI/Codex.
// Keep customizations in the wrapper/custom class and use this base file exactly as regenerated by the tool.

// Generated from canonical DB Access metadata.
// Simple CRUD / joined select methods regenerate SQL when canonical metadata is sufficient.
// Known helper-style methods regenerate canonical PHP bodies when SQL regeneration is not the right fit.
// Current canonical runtime generation fully owns this class, so no legacy DBAccess parent is required.

class UploadGroupAssignedUserDBAccessBase
{
    // source_of_truth=sync-bootstrap action_type=UNKNOWN order=11 generation=canonical-constructor
    // reason=bootstrap constructor is empty, so runtime owns the no-op constructor directly
    public function __construct()
    {
    }

    // source_of_truth=sync-bootstrap action_type=SELECTLIST order=14 generation=canonical-sql
    public function GetUploadGroupAssignedUserList($param_UploadGroupAssignedUser_UploadGroupPID_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $result = array();

        $last_sql_command_for_mtooldb = 'select UploadGroupAssignedUser.PID, UploadGroupAssignedUser.UploadGroupPID, UploadGroupAssignedUser.username from UploadGroupAssignedUser' . ' where ' . 'UploadGroupAssignedUser.UploadGroupPID = ' . '\'' . $mtooldb->real_escape_string($param_UploadGroupAssignedUser_UploadGroupPID_where) . '\'';
        $ret = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new UploadGroupAssignedUserData();
            $thisresult->PID = $thisline[0];
            $thisresult->UploadGroupPID = $thisline[1];
            $thisresult->username = $thisline[2];
            array_push($result, $thisresult);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=INSERT order=40 generation=canonical-sql
    public function InsertUploadGroupAssignedUser($UploadGroupAssignedUserObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'insert into UploadGroupAssignedUser (UploadGroupPID, username) values(' . '\'' . $mtooldb->real_escape_string($UploadGroupAssignedUserObj->UploadGroupPID) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($UploadGroupAssignedUserObj->username) . '\'' . ')';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=DELETE order=56 generation=canonical-sql
    public function DeleteUploadGroupAssignedUser($UploadGroupAssignedUserObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'delete from UploadGroupAssignedUser where ' . 'UploadGroupAssignedUser.UploadGroupPID = ' . '\'' . $mtooldb->real_escape_string($UploadGroupAssignedUserObj->UploadGroupPID) . '\'' . ' and ' . 'UploadGroupAssignedUser.username = ' . '\'' . $mtooldb->real_escape_string($UploadGroupAssignedUserObj->username) . '\'';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }
}

?>