<?php

// AUTO-GENERATED BASE FILE.
// Do not edit this file manually or with AI/Codex.
// Keep customizations in the wrapper/custom class and use this base file exactly as regenerated by the tool.

// Generated from canonical DB Access metadata.
// Simple CRUD / joined select methods regenerate SQL when canonical metadata is sufficient.
// Known helper-style methods regenerate canonical PHP bodies when SQL regeneration is not the right fit.
// Current canonical runtime generation fully owns this class, so no legacy DBAccess parent is required.

class ProjectUserDBAccessBase
{
    // source_of_truth=sync-bootstrap action_type=UNKNOWN order=11 generation=canonical-constructor
    // reason=bootstrap constructor is empty, so runtime owns the no-op constructor directly
    public function __construct()
    {
    }

    // source_of_truth=sync-bootstrap action_type=SELECTLIST order=14 generation=canonical-sql
    public function GetProjectOwnerList($param_ProjectUser_ProjectPID_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $result = array();

        $last_sql_command_for_mtooldb = 'select ProjectUser.ProjectPID, ProjectUser.PID, ProjectUser.username, ProjectUser.IsOwner, ProjectUser.dbtoolRead, ProjectUser.dbtoolWrite, ProjectUser.HtmlRead, ProjectUser.HtmlWrite, ProjectUser.testtoolRead, ProjectUser.testtoolWrite, ProjectUser.spectoolRead, ProjectUser.spectoolWrite, ProjectUser.ReqRead, ProjectUser.ReqWrite, ProjectUser.ChatRead, ProjectUser.ChatWrite, ProjectUser.MinutesRead, ProjectUser.MinutesWrite, ProjectUser.UploadRead, ProjectUser.UploadWrite from ProjectUser' . ' where ' . 'ProjectUser.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($param_ProjectUser_ProjectPID_where) . '\'' . ' and ' . 'ProjectUser.IsOwner = ' . '\'' . $mtooldb->real_escape_string('t') . '\'';
        $ret = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new ProjectUserData();
            $thisresult->ProjectPID = $thisline[0];
            $thisresult->PID = $thisline[1];
            $thisresult->username = $thisline[2];
            $thisresult->IsOwner = $thisline[3];
            $thisresult->dbtoolRead = $thisline[4];
            $thisresult->dbtoolWrite = $thisline[5];
            $thisresult->HtmlRead = $thisline[6];
            $thisresult->HtmlWrite = $thisline[7];
            $thisresult->testtoolRead = $thisline[8];
            $thisresult->testtoolWrite = $thisline[9];
            $thisresult->spectoolRead = $thisline[10];
            $thisresult->spectoolWrite = $thisline[11];
            $thisresult->ReqRead = $thisline[12];
            $thisresult->ReqWrite = $thisline[13];
            $thisresult->ChatRead = $thisline[14];
            $thisresult->ChatWrite = $thisline[15];
            $thisresult->MinutesRead = $thisline[16];
            $thisresult->MinutesWrite = $thisline[17];
            $thisresult->UploadRead = $thisline[18];
            $thisresult->UploadWrite = $thisline[19];
            array_push($result, $thisresult);
        }
        return $result;
    }

    // source_of_truth=seed-legacy action_type=SELECTLIST order=57 generation=canonical-sql
    public function GetProjectUserList($param_ProjectUser_ProjectPID_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $result = array();

        $last_sql_command_for_mtooldb = 'select ProjectUser.ProjectPID, ProjectUser.PID, ProjectUser.username, ProjectUser.IsOwner, ProjectUser.dbtoolRead, ProjectUser.dbtoolWrite, ProjectUser.HtmlRead, ProjectUser.HtmlWrite, ProjectUser.testtoolRead, ProjectUser.testtoolWrite, ProjectUser.spectoolRead, ProjectUser.spectoolWrite, ProjectUser.ReqRead, ProjectUser.ReqWrite, ProjectUser.ChatRead, ProjectUser.ChatWrite, ProjectUser.MinutesRead, ProjectUser.MinutesWrite, ProjectUser.UploadRead, ProjectUser.UploadWrite from ProjectUser' . ' where ' . 'ProjectUser.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($param_ProjectUser_ProjectPID_where) . '\'' . ' and ' . 'ProjectUser.IsOwner = ' . '\'' . $mtooldb->real_escape_string('f') . '\'' . ' order by ProjectUser.username';
        $ret = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new ProjectUserData();
            $thisresult->ProjectPID = $thisline[0];
            $thisresult->PID = $thisline[1];
            $thisresult->username = $thisline[2];
            $thisresult->IsOwner = $thisline[3];
            $thisresult->dbtoolRead = $thisline[4];
            $thisresult->dbtoolWrite = $thisline[5];
            $thisresult->HtmlRead = $thisline[6];
            $thisresult->HtmlWrite = $thisline[7];
            $thisresult->testtoolRead = $thisline[8];
            $thisresult->testtoolWrite = $thisline[9];
            $thisresult->spectoolRead = $thisline[10];
            $thisresult->spectoolWrite = $thisline[11];
            $thisresult->ReqRead = $thisline[12];
            $thisresult->ReqWrite = $thisline[13];
            $thisresult->ChatRead = $thisline[14];
            $thisresult->ChatWrite = $thisline[15];
            $thisresult->MinutesRead = $thisline[16];
            $thisresult->MinutesWrite = $thisline[17];
            $thisresult->UploadRead = $thisline[18];
            $thisresult->UploadWrite = $thisline[19];
            array_push($result, $thisresult);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=SELECTLIST order=100 generation=canonical-sql
    public function GetProjectOwnerOrUserList($param_ProjectUser_ProjectPID_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $result = array();

        $last_sql_command_for_mtooldb = 'select ProjectUser.ProjectPID, ProjectUser.PID, ProjectUser.username, ProjectUser.IsOwner, ProjectUser.dbtoolRead, ProjectUser.dbtoolWrite, ProjectUser.HtmlRead, ProjectUser.HtmlWrite, ProjectUser.testtoolRead, ProjectUser.testtoolWrite, ProjectUser.spectoolRead, ProjectUser.spectoolWrite, ProjectUser.ReqRead, ProjectUser.ReqWrite, ProjectUser.ChatRead, ProjectUser.ChatWrite, ProjectUser.MinutesRead, ProjectUser.MinutesWrite, ProjectUser.UploadRead, ProjectUser.UploadWrite from ProjectUser' . ' where ' . 'ProjectUser.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($param_ProjectUser_ProjectPID_where) . '\'';
        $ret = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new ProjectUserData();
            $thisresult->ProjectPID = $thisline[0];
            $thisresult->PID = $thisline[1];
            $thisresult->username = $thisline[2];
            $thisresult->IsOwner = $thisline[3];
            $thisresult->dbtoolRead = $thisline[4];
            $thisresult->dbtoolWrite = $thisline[5];
            $thisresult->HtmlRead = $thisline[6];
            $thisresult->HtmlWrite = $thisline[7];
            $thisresult->testtoolRead = $thisline[8];
            $thisresult->testtoolWrite = $thisline[9];
            $thisresult->spectoolRead = $thisline[10];
            $thisresult->spectoolWrite = $thisline[11];
            $thisresult->ReqRead = $thisline[12];
            $thisresult->ReqWrite = $thisline[13];
            $thisresult->ChatRead = $thisline[14];
            $thisresult->ChatWrite = $thisline[15];
            $thisresult->MinutesRead = $thisline[16];
            $thisresult->MinutesWrite = $thisline[17];
            $thisresult->UploadRead = $thisline[18];
            $thisresult->UploadWrite = $thisline[19];
            array_push($result, $thisresult);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=SELECTSINGLE order=143 generation=canonical-sql
    public function GetProjectOwner($param_ProjectUser_ProjectPID_where, $param_ProjectUser_username_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'select ProjectUser.ProjectPID, ProjectUser.PID, ProjectUser.username, ProjectUser.IsOwner, ProjectUser.dbtoolRead, ProjectUser.dbtoolWrite, ProjectUser.HtmlRead, ProjectUser.HtmlWrite, ProjectUser.testtoolRead, ProjectUser.testtoolWrite, ProjectUser.spectoolRead, ProjectUser.spectoolWrite, ProjectUser.ReqRead, ProjectUser.ReqWrite, ProjectUser.ChatRead, ProjectUser.ChatWrite, ProjectUser.MinutesRead, ProjectUser.MinutesWrite, ProjectUser.UploadRead, ProjectUser.UploadWrite from ProjectUser' . ' where ' . 'ProjectUser.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($param_ProjectUser_ProjectPID_where) . '\'' . ' and ' . 'ProjectUser.username = ' . '\'' . $mtooldb->real_escape_string($param_ProjectUser_username_where) . '\'' . ' and ' . 'ProjectUser.IsOwner = ' . '\'' . $mtooldb->real_escape_string('t') . '\'';
        $ret = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new ProjectUserData();
            $thisresult->ProjectPID = $thisline[0];
            $thisresult->PID = $thisline[1];
            $thisresult->username = $thisline[2];
            $thisresult->IsOwner = $thisline[3];
            $thisresult->dbtoolRead = $thisline[4];
            $thisresult->dbtoolWrite = $thisline[5];
            $thisresult->HtmlRead = $thisline[6];
            $thisresult->HtmlWrite = $thisline[7];
            $thisresult->testtoolRead = $thisline[8];
            $thisresult->testtoolWrite = $thisline[9];
            $thisresult->spectoolRead = $thisline[10];
            $thisresult->spectoolWrite = $thisline[11];
            $thisresult->ReqRead = $thisline[12];
            $thisresult->ReqWrite = $thisline[13];
            $thisresult->ChatRead = $thisline[14];
            $thisresult->ChatWrite = $thisline[15];
            $thisresult->MinutesRead = $thisline[16];
            $thisresult->MinutesWrite = $thisline[17];
            $thisresult->UploadRead = $thisline[18];
            $thisresult->UploadWrite = $thisline[19];
            return $thisresult;
        }
        return NULL;
    }

    // source_of_truth=sync-bootstrap action_type=SELECTLIST order=184 generation=canonical-sql
    public function GetProjectOwnerOfTheUserList($param_ProjectUser_username_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $result = array();

        $last_sql_command_for_mtooldb = 'select ProjectUser.ProjectPID, ProjectUser.PID, ProjectUser.username, ProjectUser.IsOwner, ProjectUser.dbtoolRead, ProjectUser.dbtoolWrite, ProjectUser.HtmlRead, ProjectUser.HtmlWrite, ProjectUser.testtoolRead, ProjectUser.testtoolWrite, ProjectUser.spectoolRead, ProjectUser.spectoolWrite, ProjectUser.ReqRead, ProjectUser.ReqWrite, ProjectUser.ChatRead, ProjectUser.ChatWrite, ProjectUser.MinutesRead, ProjectUser.MinutesWrite, ProjectUser.UploadRead, ProjectUser.UploadWrite from ProjectUser join Project on ProjectUser.ProjectPID = Project.PID' . ' where ' . 'ProjectUser.username = ' . '\'' . $mtooldb->real_escape_string($param_ProjectUser_username_where) . '\'' . ' and ' . 'ProjectUser.IsOwner = ' . '\'' . $mtooldb->real_escape_string('t') . '\'';
        $ret = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new ProjectUserData();
            $thisresult->ProjectPID = $thisline[0];
            $thisresult->PID = $thisline[1];
            $thisresult->username = $thisline[2];
            $thisresult->IsOwner = $thisline[3];
            $thisresult->dbtoolRead = $thisline[4];
            $thisresult->dbtoolWrite = $thisline[5];
            $thisresult->HtmlRead = $thisline[6];
            $thisresult->HtmlWrite = $thisline[7];
            $thisresult->testtoolRead = $thisline[8];
            $thisresult->testtoolWrite = $thisline[9];
            $thisresult->spectoolRead = $thisline[10];
            $thisresult->spectoolWrite = $thisline[11];
            $thisresult->ReqRead = $thisline[12];
            $thisresult->ReqWrite = $thisline[13];
            $thisresult->ChatRead = $thisline[14];
            $thisresult->ChatWrite = $thisline[15];
            $thisresult->MinutesRead = $thisline[16];
            $thisresult->MinutesWrite = $thisline[17];
            $thisresult->UploadRead = $thisline[18];
            $thisresult->UploadWrite = $thisline[19];
            array_push($result, $thisresult);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=SELECTSINGLE order=227 generation=canonical-sql
    public function GetProjectOwnerOrUser($param_ProjectUser_ProjectPID_where, $param_ProjectUser_username_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'select ProjectUser.ProjectPID, ProjectUser.PID, ProjectUser.username, ProjectUser.IsOwner, ProjectUser.dbtoolRead, ProjectUser.dbtoolWrite, ProjectUser.HtmlRead, ProjectUser.HtmlWrite, ProjectUser.testtoolRead, ProjectUser.testtoolWrite, ProjectUser.spectoolRead, ProjectUser.spectoolWrite, ProjectUser.ReqRead, ProjectUser.ReqWrite, ProjectUser.ChatRead, ProjectUser.ChatWrite, ProjectUser.MinutesRead, ProjectUser.MinutesWrite, ProjectUser.UploadRead, ProjectUser.UploadWrite from ProjectUser' . ' where ' . 'ProjectUser.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($param_ProjectUser_ProjectPID_where) . '\'' . ' and ' . 'ProjectUser.username = ' . '\'' . $mtooldb->real_escape_string($param_ProjectUser_username_where) . '\'';
        $ret = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new ProjectUserData();
            $thisresult->ProjectPID = $thisline[0];
            $thisresult->PID = $thisline[1];
            $thisresult->username = $thisline[2];
            $thisresult->IsOwner = $thisline[3];
            $thisresult->dbtoolRead = $thisline[4];
            $thisresult->dbtoolWrite = $thisline[5];
            $thisresult->HtmlRead = $thisline[6];
            $thisresult->HtmlWrite = $thisline[7];
            $thisresult->testtoolRead = $thisline[8];
            $thisresult->testtoolWrite = $thisline[9];
            $thisresult->spectoolRead = $thisline[10];
            $thisresult->spectoolWrite = $thisline[11];
            $thisresult->ReqRead = $thisline[12];
            $thisresult->ReqWrite = $thisline[13];
            $thisresult->ChatRead = $thisline[14];
            $thisresult->ChatWrite = $thisline[15];
            $thisresult->MinutesRead = $thisline[16];
            $thisresult->MinutesWrite = $thisline[17];
            $thisresult->UploadRead = $thisline[18];
            $thisresult->UploadWrite = $thisline[19];
            return $thisresult;
        }
        return NULL;
    }

    // source_of_truth=sync-bootstrap action_type=INSERT order=268 generation=canonical-sql
    public function InsertProjectOwnerOrUser($ProjectUserObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'insert into ProjectUser (ProjectPID, username, IsOwner, dbtoolRead, dbtoolWrite, HtmlRead, HtmlWrite, testtoolRead, testtoolWrite, spectoolRead, spectoolWrite, ReqRead, ReqWrite, ChatRead, ChatWrite, MinutesRead, MinutesWrite, UploadRead, UploadWrite) values(' . '\'' . $mtooldb->real_escape_string($ProjectUserObj->ProjectPID) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($ProjectUserObj->username) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($ProjectUserObj->IsOwner) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($ProjectUserObj->dbtoolRead) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($ProjectUserObj->dbtoolWrite) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($ProjectUserObj->HtmlRead) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($ProjectUserObj->HtmlWrite) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($ProjectUserObj->testtoolRead) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($ProjectUserObj->testtoolWrite) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($ProjectUserObj->spectoolRead) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($ProjectUserObj->spectoolWrite) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($ProjectUserObj->ReqRead) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($ProjectUserObj->ReqWrite) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($ProjectUserObj->ChatRead) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($ProjectUserObj->ChatWrite) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($ProjectUserObj->MinutesRead) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($ProjectUserObj->MinutesWrite) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($ProjectUserObj->UploadRead) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($ProjectUserObj->UploadWrite) . '\'' . ')';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=UPDATE order=284 generation=canonical-sql
    public function UpdateProjectOwnerOrUserBasicInfo($ProjectUserObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'update ProjectUser SET ' . 'IsOwner = ' . '\'' . $mtooldb->real_escape_string($ProjectUserObj->IsOwner) . '\'' . ' where ' . 'ProjectUser.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($ProjectUserObj->ProjectPID) . '\'' . ' and ' . 'ProjectUser.username = ' . '\'' . $mtooldb->real_escape_string($ProjectUserObj->username) . '\'';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=UPDATE order=300 generation=canonical-sql
    public function UpdateProjectUserDetail($ProjectUserObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'update ProjectUser SET ' . 'dbtoolRead = ' . '\'' . $mtooldb->real_escape_string($ProjectUserObj->dbtoolRead) . '\'' . ', ' . 'dbtoolWrite = ' . '\'' . $mtooldb->real_escape_string($ProjectUserObj->dbtoolWrite) . '\'' . ', ' . 'HtmlRead = ' . '\'' . $mtooldb->real_escape_string($ProjectUserObj->HtmlRead) . '\'' . ', ' . 'HtmlWrite = ' . '\'' . $mtooldb->real_escape_string($ProjectUserObj->HtmlWrite) . '\'' . ', ' . 'testtoolRead = ' . '\'' . $mtooldb->real_escape_string($ProjectUserObj->testtoolRead) . '\'' . ', ' . 'testtoolWrite = ' . '\'' . $mtooldb->real_escape_string($ProjectUserObj->testtoolWrite) . '\'' . ', ' . 'spectoolRead = ' . '\'' . $mtooldb->real_escape_string($ProjectUserObj->spectoolRead) . '\'' . ', ' . 'spectoolWrite = ' . '\'' . $mtooldb->real_escape_string($ProjectUserObj->spectoolWrite) . '\'' . ', ' . 'ReqRead = ' . '\'' . $mtooldb->real_escape_string($ProjectUserObj->ReqRead) . '\'' . ', ' . 'ReqWrite = ' . '\'' . $mtooldb->real_escape_string($ProjectUserObj->ReqWrite) . '\'' . ', ' . 'ChatRead = ' . '\'' . $mtooldb->real_escape_string($ProjectUserObj->ChatRead) . '\'' . ', ' . 'ChatWrite = ' . '\'' . $mtooldb->real_escape_string($ProjectUserObj->ChatWrite) . '\'' . ', ' . 'MinutesRead = ' . '\'' . $mtooldb->real_escape_string($ProjectUserObj->MinutesRead) . '\'' . ', ' . 'MinutesWrite = ' . '\'' . $mtooldb->real_escape_string($ProjectUserObj->MinutesWrite) . '\'' . ', ' . 'UploadRead = ' . '\'' . $mtooldb->real_escape_string($ProjectUserObj->UploadRead) . '\'' . ', ' . 'UploadWrite = ' . '\'' . $mtooldb->real_escape_string($ProjectUserObj->UploadWrite) . '\'' . ' where ' . 'ProjectUser.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($ProjectUserObj->ProjectPID) . '\'' . ' and ' . 'ProjectUser.username = ' . '\'' . $mtooldb->real_escape_string($ProjectUserObj->username) . '\'';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=DELETE order=316 generation=canonical-sql
    public function DeleteProjectOwnerOrUser($ProjectUserObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'delete from ProjectUser where ' . 'ProjectUser.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($ProjectUserObj->ProjectPID) . '\'' . ' and ' . 'ProjectUser.username = ' . '\'' . $mtooldb->real_escape_string($ProjectUserObj->username) . '\'';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=DELETE order=332 generation=canonical-sql
    public function DeleteUnmatchedProjectUser()
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'delete from ProjectUser where ' . 'ProjectUser.ProjectPID not in ' . '(select PID from Project)';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }
}

?>