<?php

// AUTO-GENERATED BASE FILE.
// Do not edit this file manually or with AI/Codex.
// Keep customizations in the wrapper/custom class and use this base file exactly as regenerated by the tool.

// Generated from canonical DB Access metadata.
// Simple CRUD / joined select methods regenerate SQL when canonical metadata is sufficient.
// Known helper-style methods regenerate canonical PHP bodies when SQL regeneration is not the right fit.
// Current canonical runtime generation fully owns this class, so no legacy DBAccess parent is required.

class daCustomProxyFuncDBAccessBase
{
    // source_of_truth=sync-bootstrap action_type=UNKNOWN order=11 generation=canonical-constructor
    // reason=bootstrap constructor is empty, so runtime owns the no-op constructor directly
    public function __construct()
    {
    }

    // source_of_truth=seed-legacy action_type=SELECTLIST order=14 generation=canonical-sql
    public function GetdaCustomProxyFuncList($param_daCustomProxyFunc_ProjectPID_where, $param_daCustomProxyFunc_daCustomProxyPID_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $result = array();

        $last_sql_command_for_mtooldb = 'select daCustomProxyFunc.ProjectPID, daCustomProxyFunc.daCustomProxyPID, daCustomProxyFunc.PID, daCustomProxyFunc.dafuncPID, daCustomProxyFunc.IsList, daCustomProxyFunc.FunctionListOrder, daCustomProxyFunc.AddIndentCount, daCustomProxyFunc.AddIndentType from daCustomProxyFunc' . ' where ' . 'daCustomProxyFunc.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($param_daCustomProxyFunc_ProjectPID_where) . '\'' . ' and ' . 'daCustomProxyFunc.daCustomProxyPID = ' . '\'' . $mtooldb->real_escape_string($param_daCustomProxyFunc_daCustomProxyPID_where) . '\'' . ' order by daCustomProxyFunc.FunctionListOrder,daCustomProxyFunc.PID';
        $ret = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new daCustomProxyFuncData();
            $thisresult->ProjectPID = $thisline[0];
            $thisresult->daCustomProxyPID = $thisline[1];
            $thisresult->PID = $thisline[2];
            $thisresult->dafuncPID = $thisline[3];
            $thisresult->IsList = $thisline[4];
            $thisresult->FunctionListOrder = $thisline[5];
            $thisresult->AddIndentCount = $thisline[6];
            $thisresult->AddIndentType = $thisline[7];
            array_push($result, $thisresult);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=SELECTSINGLE order=45 generation=canonical-sql
    public function GetdaCustomProxyFunc($param_daCustomProxyFunc_PID_where, $param_daCustomProxyFunc_ProjectPID_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'select daCustomProxyFunc.ProjectPID, daCustomProxyFunc.daCustomProxyPID, daCustomProxyFunc.PID, daCustomProxyFunc.dafuncPID, daCustomProxyFunc.IsList, daCustomProxyFunc.FunctionListOrder, daCustomProxyFunc.AddIndentCount, daCustomProxyFunc.AddIndentType from daCustomProxyFunc' . ' where ' . 'daCustomProxyFunc.PID = ' . '\'' . $mtooldb->real_escape_string($param_daCustomProxyFunc_PID_where) . '\'' . ' and ' . 'daCustomProxyFunc.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($param_daCustomProxyFunc_ProjectPID_where) . '\'';
        $ret = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new daCustomProxyFuncData();
            $thisresult->ProjectPID = $thisline[0];
            $thisresult->daCustomProxyPID = $thisline[1];
            $thisresult->PID = $thisline[2];
            $thisresult->dafuncPID = $thisline[3];
            $thisresult->IsList = $thisline[4];
            $thisresult->FunctionListOrder = $thisline[5];
            $thisresult->AddIndentCount = $thisline[6];
            $thisresult->AddIndentType = $thisline[7];
            return $thisresult;
        }
        return NULL;
    }

    // source_of_truth=sync-bootstrap action_type=SELECTLIST order=74 generation=canonical-sql
    public function GetdaCustomProxyFuncByDAFuncList($param_daCustomProxyFunc_dafuncPID_where, $param_daCustomProxyFunc_ProjectPID_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $result = array();

        $last_sql_command_for_mtooldb = 'select daCustomProxyFunc.ProjectPID, daCustomProxyFunc.daCustomProxyPID, daCustomProxyFunc.PID, daCustomProxyFunc.dafuncPID, daCustomProxyFunc.IsList, daCustomProxyFunc.FunctionListOrder, daCustomProxyFunc.AddIndentCount, daCustomProxyFunc.AddIndentType from daCustomProxyFunc' . ' where ' . 'daCustomProxyFunc.dafuncPID = ' . '\'' . $mtooldb->real_escape_string($param_daCustomProxyFunc_dafuncPID_where) . '\'' . ' and ' . 'daCustomProxyFunc.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($param_daCustomProxyFunc_ProjectPID_where) . '\'';
        $ret = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new daCustomProxyFuncData();
            $thisresult->ProjectPID = $thisline[0];
            $thisresult->daCustomProxyPID = $thisline[1];
            $thisresult->PID = $thisline[2];
            $thisresult->dafuncPID = $thisline[3];
            $thisresult->IsList = $thisline[4];
            $thisresult->FunctionListOrder = $thisline[5];
            $thisresult->AddIndentCount = $thisline[6];
            $thisresult->AddIndentType = $thisline[7];
            array_push($result, $thisresult);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=INSERT order=105 generation=canonical-sql
    public function InsertdaCustomProxyFunc($daCustomProxyFuncObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'insert into daCustomProxyFunc (ProjectPID, daCustomProxyPID, dafuncPID, IsList, AddIndentCount, AddIndentType) values(' . '\'' . $mtooldb->real_escape_string($daCustomProxyFuncObj->ProjectPID) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($daCustomProxyFuncObj->daCustomProxyPID) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($daCustomProxyFuncObj->dafuncPID) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($daCustomProxyFuncObj->IsList) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($daCustomProxyFuncObj->AddIndentCount) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($daCustomProxyFuncObj->AddIndentType) . '\'' . ')';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=UPDATE order=121 generation=canonical-sql
    public function UpdatedaCustomProxyFunc($daCustomProxyFuncObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'update daCustomProxyFunc SET ' . 'dafuncPID = ' . '\'' . $mtooldb->real_escape_string($daCustomProxyFuncObj->dafuncPID) . '\'' . ', ' . 'IsList = ' . '\'' . $mtooldb->real_escape_string($daCustomProxyFuncObj->IsList) . '\'' . ', ' . 'AddIndentCount = ' . '\'' . $mtooldb->real_escape_string($daCustomProxyFuncObj->AddIndentCount) . '\'' . ', ' . 'AddIndentType = ' . '\'' . $mtooldb->real_escape_string($daCustomProxyFuncObj->AddIndentType) . '\'' . ' where ' . 'daCustomProxyFunc.PID = ' . '\'' . $mtooldb->real_escape_string($daCustomProxyFuncObj->PID) . '\'' . ' and ' . 'daCustomProxyFunc.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($daCustomProxyFuncObj->ProjectPID) . '\'';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=DELETE order=137 generation=canonical-sql
    public function DeletedaCustomProxyFunc($daCustomProxyFuncObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'delete from daCustomProxyFunc where ' . 'daCustomProxyFunc.PID = ' . '\'' . $mtooldb->real_escape_string($daCustomProxyFuncObj->PID) . '\'' . ' and ' . 'daCustomProxyFunc.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($daCustomProxyFuncObj->ProjectPID) . '\'';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=UPDATE order=153 generation=canonical-sql
    public function UpdatedaCustomProxyFuncFunctionListOrder($param_daCustomProxyFunc_FunctionListOrder_update, $param_daCustomProxyFunc_PID_where, $param_daCustomProxyFunc_ProjectPID_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'update daCustomProxyFunc SET ' . 'FunctionListOrder = ' . $param_daCustomProxyFunc_FunctionListOrder_update . ' where ' . 'daCustomProxyFunc.PID = ' . '\'' . $mtooldb->real_escape_string($param_daCustomProxyFunc_PID_where) . '\'' . ' and ' . 'daCustomProxyFunc.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($param_daCustomProxyFunc_ProjectPID_where) . '\'';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }
}

?>