<?php

// AUTO-GENERATED BASE FILE.
// Do not edit this file manually or with AI/Codex.
// Keep customizations in the wrapper/custom class and use this base file exactly as regenerated by the tool.

// Generated from canonical DB Access metadata.
// Simple CRUD / joined select methods regenerate SQL when canonical metadata is sufficient.
// Known helper-style methods regenerate canonical PHP bodies when SQL regeneration is not the right fit.
// Current canonical runtime generation fully owns this class, so no legacy DBAccess parent is required.

class CompareOutputAdditionalPathDBAccessBase
{
    // source_of_truth=sync-bootstrap action_type=UNKNOWN order=11 generation=canonical-constructor
    // reason=bootstrap constructor is empty, so runtime owns the no-op constructor directly
    public function __construct()
    {
    }

    // source_of_truth=sync-bootstrap action_type=SELECTLIST order=14 generation=canonical-sql
    public function GetCompareOutputAdditionalPathList($param_CompareOutputAdditionalPath_CompareOutputPID_where, $param_CompareOutputAdditionalPath_ProjectPID_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $result = array();

        $last_sql_command_for_mtooldb = 'select CompareOutputAdditionalPath.PID, CompareOutputAdditionalPath.CompareOutputPID, CompareOutputAdditionalPath.ProjectPID, CompareOutputAdditionalPath.PathA_DropboxBaseFolderPID, CompareOutputAdditionalPath.PathA, CompareOutputAdditionalPath.PathB_DropboxBaseFolderPID, CompareOutputAdditionalPath.PathB, CompareOutputAdditionalPath.IsSameFilenameOnly, DropboxBaseFolderA.Name, DropboxBaseFolderB.Name from CompareOutputAdditionalPath left outer join DropboxBaseFolder as DropboxBaseFolderA on CompareOutputAdditionalPath.PathA_DropboxBaseFolderPID = DropboxBaseFolderA.PID left outer join DropboxBaseFolder as DropboxBaseFolderB on CompareOutputAdditionalPath.PathB_DropboxBaseFolderPID = DropboxBaseFolderB.PID' . ' where ' . 'CompareOutputAdditionalPath.CompareOutputPID = ' . '\'' . $mtooldb->real_escape_string($param_CompareOutputAdditionalPath_CompareOutputPID_where) . '\'' . ' and ' . 'CompareOutputAdditionalPath.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($param_CompareOutputAdditionalPath_ProjectPID_where) . '\'';
        $ret = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new CompareOutputAdditionalPathData();
            $thisresult->PID = $thisline[0];
            $thisresult->CompareOutputPID = $thisline[1];
            $thisresult->ProjectPID = $thisline[2];
            $thisresult->PathA_DropboxBaseFolderPID = $thisline[3];
            $thisresult->PathA = $thisline[4];
            $thisresult->PathB_DropboxBaseFolderPID = $thisline[5];
            $thisresult->PathB = $thisline[6];
            $thisresult->IsSameFilenameOnly = $thisline[7];
            $thisresult->DropboxBaseFolderAName = $thisline[8];
            $thisresult->DropboxBaseFolderBName = $thisline[9];
            array_push($result, $thisresult);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=SELECTSINGLE order=47 generation=canonical-sql
    public function GetCompareOutputAdditionalPath($param_CompareOutputAdditionalPath_PID_where, $param_CompareOutputAdditionalPath_CompareOutputPID_where, $param_CompareOutputAdditionalPath_ProjectPID_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'select CompareOutputAdditionalPath.PID, CompareOutputAdditionalPath.CompareOutputPID, CompareOutputAdditionalPath.ProjectPID, CompareOutputAdditionalPath.PathA_DropboxBaseFolderPID, CompareOutputAdditionalPath.PathA, CompareOutputAdditionalPath.PathB_DropboxBaseFolderPID, CompareOutputAdditionalPath.PathB, CompareOutputAdditionalPath.IsSameFilenameOnly, DropboxBaseFolderA.Name, DropboxBaseFolderB.Name from CompareOutputAdditionalPath left outer join DropboxBaseFolder as DropboxBaseFolderA on CompareOutputAdditionalPath.PathA_DropboxBaseFolderPID = DropboxBaseFolderA.PID left outer join DropboxBaseFolder as DropboxBaseFolderB on CompareOutputAdditionalPath.PathB_DropboxBaseFolderPID = DropboxBaseFolderB.PID' . ' where ' . 'CompareOutputAdditionalPath.PID = ' . '\'' . $mtooldb->real_escape_string($param_CompareOutputAdditionalPath_PID_where) . '\'' . ' and ' . 'CompareOutputAdditionalPath.CompareOutputPID = ' . '\'' . $mtooldb->real_escape_string($param_CompareOutputAdditionalPath_CompareOutputPID_where) . '\'' . ' and ' . 'CompareOutputAdditionalPath.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($param_CompareOutputAdditionalPath_ProjectPID_where) . '\'';
        $ret = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new CompareOutputAdditionalPathData();
            $thisresult->PID = $thisline[0];
            $thisresult->CompareOutputPID = $thisline[1];
            $thisresult->ProjectPID = $thisline[2];
            $thisresult->PathA_DropboxBaseFolderPID = $thisline[3];
            $thisresult->PathA = $thisline[4];
            $thisresult->PathB_DropboxBaseFolderPID = $thisline[5];
            $thisresult->PathB = $thisline[6];
            $thisresult->IsSameFilenameOnly = $thisline[7];
            $thisresult->DropboxBaseFolderAName = $thisline[8];
            $thisresult->DropboxBaseFolderBName = $thisline[9];
            return $thisresult;
        }
        return NULL;
    }

    // source_of_truth=sync-bootstrap action_type=INSERT order=78 generation=canonical-sql
    public function InsertCompareOutputAdditionalPath($CompareOutputAdditionalPathObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'insert into CompareOutputAdditionalPath (CompareOutputPID, ProjectPID, PathA_DropboxBaseFolderPID, PathA, PathB_DropboxBaseFolderPID, PathB, IsSameFilenameOnly) values(' . '\'' . $mtooldb->real_escape_string($CompareOutputAdditionalPathObj->CompareOutputPID) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($CompareOutputAdditionalPathObj->ProjectPID) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($CompareOutputAdditionalPathObj->PathA_DropboxBaseFolderPID) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($CompareOutputAdditionalPathObj->PathA) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($CompareOutputAdditionalPathObj->PathB_DropboxBaseFolderPID) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($CompareOutputAdditionalPathObj->PathB) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($CompareOutputAdditionalPathObj->IsSameFilenameOnly) . '\'' . ')';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=UPDATE order=94 generation=canonical-sql
    public function UpdateCompareOutputAdditionalPath($CompareOutputAdditionalPathObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'update CompareOutputAdditionalPath SET ' . 'PathA_DropboxBaseFolderPID = ' . '\'' . $mtooldb->real_escape_string($CompareOutputAdditionalPathObj->PathA_DropboxBaseFolderPID) . '\'' . ', ' . 'PathA = ' . '\'' . $mtooldb->real_escape_string($CompareOutputAdditionalPathObj->PathA) . '\'' . ', ' . 'PathB_DropboxBaseFolderPID = ' . '\'' . $mtooldb->real_escape_string($CompareOutputAdditionalPathObj->PathB_DropboxBaseFolderPID) . '\'' . ', ' . 'PathB = ' . '\'' . $mtooldb->real_escape_string($CompareOutputAdditionalPathObj->PathB) . '\'' . ', ' . 'IsSameFilenameOnly = ' . '\'' . $mtooldb->real_escape_string($CompareOutputAdditionalPathObj->IsSameFilenameOnly) . '\'' . ' where ' . 'CompareOutputAdditionalPath.PID = ' . '\'' . $mtooldb->real_escape_string($CompareOutputAdditionalPathObj->PID) . '\'' . ' and ' . 'CompareOutputAdditionalPath.CompareOutputPID = ' . '\'' . $mtooldb->real_escape_string($CompareOutputAdditionalPathObj->CompareOutputPID) . '\'' . ' and ' . 'CompareOutputAdditionalPath.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($CompareOutputAdditionalPathObj->ProjectPID) . '\'';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=DELETE order=110 generation=canonical-sql
    public function DeleteCompareOutputAdditionalPath($CompareOutputAdditionalPathObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'delete from CompareOutputAdditionalPath where ' . 'CompareOutputAdditionalPath.PID = ' . '\'' . $mtooldb->real_escape_string($CompareOutputAdditionalPathObj->PID) . '\'' . ' and ' . 'CompareOutputAdditionalPath.CompareOutputPID = ' . '\'' . $mtooldb->real_escape_string($CompareOutputAdditionalPathObj->CompareOutputPID) . '\'' . ' and ' . 'CompareOutputAdditionalPath.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($CompareOutputAdditionalPathObj->ProjectPID) . '\'';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }
}

?>