name: mtool-sample-sample04-dataclass-parent-child-basic-sqlite

services:
  web-admin:
    environment:
      APP_WORK_ROOT: /var/www/work/sample-packs/sample04-dataclass-parent-child-basic-sqlite

  web-lab:
    environment:
      APP_WORK_ROOT: /var/www/work/sample-packs/sample04-dataclass-parent-child-basic-sqlite
