<?php

// AUTO-GENERATED BASE FILE.
// Do not edit this file manually or with AI/Codex.
// Keep customizations in the wrapper class and use this base file exactly as regenerated by the tool.

// Generated from canonical data class metadata.
// Base DTO generated from dataclass / dataclassfields.

class CapstoneTaskDataBase
{
    public $Id;
    public $Title;
    public $Status;
    public $OwnerName;
    public $Priority;
    public $DueDate;
    public $UpdatedAt;

    public function __construct()
    {
    }
}

?>