
#ifndef __CLASS_BASE_NAME__ProxyClient_h
#define __CLASS_BASE_NAME__ProxyClient_h

#import <UIKit/UIKit.h>
#import "DegoDBCommonLib.h"
__INCLUDE_HEADER_FOR_FUNCTION__

// == START OF EDITABLE AREA FOR ABOVE ==
// == END OF EDITABLE AREA FOR ABOVE ==

// THIS CLASS WAS AUTOMATICALLY CREATED BY MTOOL. DON'T EDIT EXCEPT THE EDITABLE AREA.
// [JP] このクラスは自動生成されています。編集可能領域以外は変更しないで下さい。

__DEFINE_DELEGATE__
@interface __CLASS_BASE_NAME__ProxyClient : ProxyClientBase
{
    // == START OF EDITABLE AREA FOR ADDITIONAL VARIABLE DEFINITION ==
    // == END OF EDITABLE AREA FOR ADDITIONAL VARIABLE DEFINITION ==
}

- (id) init;
- (id) initWithBaseURL:(NSString*)baseURL;

__FUNCTIONS__

// == START OF EDITABLE AREA FOR ADDITIONAL CLASS INTERFACE DEFINITION ==
// == END OF EDITABLE AREA FOR ADDITIONAL CLASS INTERFACE DEFINITION ==

@end

// == START OF EDITABLE AREA FOR BOTTOM ==
// == END OF EDITABLE AREA FOR BOTTOM ==

#endif /* __CLASS_BASE_NAME__ProxyClient_h */
