
#ifndef __CLASS_BASE_NAME__Proxy__FUNCTION_NAME__RequestParams__CLASS_NAME_SUFFIX___h
#define __CLASS_BASE_NAME__Proxy__FUNCTION_NAME__RequestParams__CLASS_NAME_SUFFIX___h

#import <UIKit/UIKit.h>
#import "DegoDBCommonLib.h"
__INCLUDE_FOR_PROPERTY___

// == START OF EDITABLE AREA FOR ABOVE ==
// == END OF EDITABLE AREA FOR ABOVE ==

// THIS CLASS WAS AUTOMATICALLY CREATED BY MTOOL. DON'T EDIT EXCEPT THE EDITABLE AREA.
// [JP] このクラスは自動生成されています。編集可能領域以外は変更しないで下さい。

@interface __CLASS_BASE_NAME__Proxy__FUNCTION_NAME__RequestParams__CLASS_NAME_SUFFIX__ : ProxyClientRequestBase
{
    // == START OF EDITABLE AREA FOR ADDITIONAL VARIABLE DEFINITION ==
    // == END OF EDITABLE AREA FOR ADDITIONAL VARIABLE DEFINITION ==
}

__PROPERTIES__

- (id) init;
- (NSDictionary*)Serialize;

// == START OF EDITABLE AREA FOR ADDITIONAL CLASS INTERFACE DEFINITION ==
// == END OF EDITABLE AREA FOR ADDITIONAL CLASS INTERFACE DEFINITION ==

@end

// == START OF EDITABLE AREA FOR BOTTOM ==
// == END OF EDITABLE AREA FOR BOTTOM ==

#endif /* __CLASS_BASE_NAME__Proxy__FUNCTION_NAME__RequestParams__CLASS_NAME_SUFFIX___h */
