
#ifndef __CLASS_NAME___h
#define __CLASS_NAME___h

#import <UIKit/UIKit.h>
#import "DegoDBCommonLib.h"
#import "__BASE_CLASS_NAME__.h"

// == START OF EDITABLE AREA FOR ABOVE ==
// == END OF EDITABLE AREA FOR ABOVE ==

// THIS CLASS WAS AUTOMATICALLY CREATED BY MTOOL. DON'T EDIT EXCEPT THE EDITABLE AREA.
// [JP] このクラスは自動生成されています。編集可能領域以外は変更しないで下さい。

@interface __CLASS_NAME__ : NSMutableArray<__BASE_CLASS_NAME__*>
{
__ARRAY_DEFINE__

    // == START OF EDITABLE AREA FOR ADDITIONAL VARIABLE DEFINITION ==
    // == END OF EDITABLE AREA FOR ADDITIONAL VARIABLE DEFINITION ==
}

- (id) init;
- (NSArray<NSDictionary*>*)Serialize;

// == START OF EDITABLE AREA FOR ADDITIONAL CLASS INTERFACE DEFINITION ==
// == END OF EDITABLE AREA FOR ADDITIONAL CLASS INTERFACE DEFINITION ==

@end

// == START OF EDITABLE AREA FOR BOTTOM ==
// == END OF EDITABLE AREA FOR BOTTOM ==

#endif /* __CLASS_NAME___h */
