<?php

// AUTO-GENERATED BASE FILE.
// Do not edit this file manually or with AI/Codex.
// Keep customizations in the wrapper class and use this base file exactly as regenerated by the tool.

// Generated from canonical DB Access metadata.
// Base class generated from project_db_access_* metadata.

require_once __DIR__ . '/../_support/mtool_runtime_db.php';


class ContentArticleDBAccessBase
{
    public function __construct()
    {
    }

    // source_of_truth=manual class_source=manual action_type=SELECTLIST order=10 generation=canonical-sql
    public function GetPublishedContentArticleList($limit)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $result = array();

        $last_sql_command_for_mtooldb = 'select content_article.id, content_article.title, content_article.slug, content_article.category_name, content_article.author_name, content_article.published_at, content_article.summary from content_article where content_article.status = ? order by content_article.published_at desc, content_article.id desc limit ?';
        $ret = $mtooldb->execute($last_sql_command_for_mtooldb, [
            'published',
            $limit,
        ]);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new ContentArticleData();
            $thisresult->id = $thisline[0];
            $thisresult->title = $thisline[1];
            $thisresult->slug = $thisline[2];
            $thisresult->categoryName = $thisline[3];
            $thisresult->authorName = $thisline[4];
            $thisresult->publishedAt = $thisline[5];
            $thisresult->summary = $thisline[6];
            array_push($result, $thisresult);
        }
        return $result;
    }

    // source_of_truth=manual class_source=manual action_type=SELECTSINGLE order=20 generation=canonical-sql
    public function GetPublishedContentArticle($param_ContentArticle_Slug_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'select content_article.id, content_article.title, content_article.slug, content_article.category_name, content_article.author_name, content_article.published_at, content_article.summary, content_article.body from content_article where content_article.status = ? and content_article.slug = ?';
        $ret = $mtooldb->execute($last_sql_command_for_mtooldb, [
            'published',
            $param_ContentArticle_Slug_where,
        ]);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new ContentArticleData();
            $thisresult->id = $thisline[0];
            $thisresult->title = $thisline[1];
            $thisresult->slug = $thisline[2];
            $thisresult->categoryName = $thisline[3];
            $thisresult->authorName = $thisline[4];
            $thisresult->publishedAt = $thisline[5];
            $thisresult->summary = $thisline[6];
            $thisresult->body = $thisline[7];
            return $thisresult;
        }
        return NULL;
    }
}

?>