#!/usr/bin/env php
<?php

declare(strict_types=1);

/**
 * Focused sample22 Firebird DBAccess smoke.
 *
 * Proves the generated sample22 ebook chapter workflow DBAccess can read the
 * published chapter read model and perform draft workflow state transitions
 * against a Firebird profile without changing generated classes.
 *
 * @param list<string> $argv
 * @return array{help:bool,dsn:string,user:string,password:string,pretty:bool,error:string}
 */
function app_cli_sample22_firebird_parse_args(array $argv): array
{
    $parsed = [
        'help' => false,
        'dsn' => trim((string) getenv('MTOOL_FIREBIRD_DSN')),
        'user' => trim((string) (getenv('MTOOL_FIREBIRD_USER') ?: '')),
        'password' => (string) (getenv('MTOOL_FIREBIRD_PASSWORD') ?: ''),
        'pretty' => false,
        'error' => '',
    ];

    foreach (array_slice($argv, 1) as $argument) {
        if ($argument === '--help' || $argument === '-h') {
            $parsed['help'] = true;
            continue;
        }
        if ($argument === '--pretty') {
            $parsed['pretty'] = true;
            continue;
        }
        if (str_starts_with($argument, '--dsn=')) {
            $parsed['dsn'] = trim(substr($argument, strlen('--dsn=')));
            continue;
        }
        if (str_starts_with($argument, '--user=')) {
            $parsed['user'] = trim(substr($argument, strlen('--user=')));
            continue;
        }
        if (str_starts_with($argument, '--password=')) {
            $parsed['password'] = substr($argument, strlen('--password='));
            continue;
        }

        $parsed['error'] = 'unsupported argument: ' . $argument;
        return $parsed;
    }

    return $parsed;
}

function app_cli_sample22_firebird_usage(): string
{
    return <<<TEXT
Usage:
  php mtool/scripts/check_sample22_firebird_dbaccess_smoke.php --dsn='firebird:dbname=...' --user=USER --password=PASSWORD [--pretty]

Environment:
  MTOOL_FIREBIRD_DSN
  MTOOL_FIREBIRD_USER
  MTOOL_FIREBIRD_PASSWORD

Notes:
  - Requires PHP PDO_FIREBIRD.
  - Uses the generated sample22 DBAccess classes unchanged.
  - Use only against a disposable smoke database.
  - Not part of normal make test.
TEXT;
}

/** @return array<string,mixed> */
function app_sample22_firebird_smoke_result(
    bool $ok,
    string $stage,
    string $error,
    array $details = [],
    bool $mutationPerformed = false,
): array {
    return [
        'ok' => $ok,
        'stage' => $stage,
        'error' => $error,
        'mutation_performed' => $mutationPerformed,
        'details' => $details,
    ];
}

/** @return list<string> */
function app_sample22_firebird_drop_tables(): array
{
    return [
        'EBOOK_WORKFLOW_PUBLISHED_CHAPTER',
        'EBOOK_WORKFLOW_CHAPTER',
        'EBOOK_WORKFLOW_BOOK',
    ];
}

function app_sample22_firebird_create_schema(PDO $pdo): void
{
    $pdo->exec(
        'CREATE TABLE EBOOK_WORKFLOW_BOOK (
            ID INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
            TITLE VARCHAR(255) NOT NULL,
            SLUG VARCHAR(180) NOT NULL UNIQUE,
            STATUS VARCHAR(32) NOT NULL,
            PUBLISHED_AT TIMESTAMP
        )'
    );
    $pdo->exec(
        'CREATE TABLE EBOOK_WORKFLOW_CHAPTER (
            ID INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
            EBOOK_WORKFLOW_BOOK_ID INTEGER NOT NULL,
            CHAPTER_TITLE VARCHAR(255) NOT NULL,
            CHAPTER_SLUG VARCHAR(180) NOT NULL,
            STATUS VARCHAR(32) NOT NULL,
            SPINE_ORDER INTEGER NOT NULL,
            NAV_LABEL VARCHAR(255) NOT NULL,
            EPUB_RESOURCE_PATH VARCHAR(500) NOT NULL,
            BODY_MARKDOWN BLOB SUB_TYPE TEXT NOT NULL,
            PUBLISHED_AT TIMESTAMP,
            UPDATED_AT TIMESTAMP NOT NULL,
            CONSTRAINT FK_SAMPLE22_CHAPTER_BOOK FOREIGN KEY (EBOOK_WORKFLOW_BOOK_ID) REFERENCES EBOOK_WORKFLOW_BOOK (ID)
        )'
    );
    $pdo->exec(
        'CREATE TABLE EBOOK_WORKFLOW_PUBLISHED_CHAPTER (
            CHAPTER_ID INTEGER NOT NULL PRIMARY KEY,
            BOOK_ID INTEGER NOT NULL,
            BOOK_SLUG VARCHAR(180) NOT NULL,
            CHAPTER_TITLE VARCHAR(255) NOT NULL,
            CHAPTER_SLUG VARCHAR(180) NOT NULL,
            STATUS VARCHAR(32) NOT NULL,
            SPINE_ORDER INTEGER NOT NULL,
            NAV_LABEL VARCHAR(255) NOT NULL,
            EPUB_RESOURCE_PATH VARCHAR(500) NOT NULL,
            BODY_MARKDOWN BLOB SUB_TYPE TEXT NOT NULL,
            PUBLISHED_AT TIMESTAMP
        )'
    );
}

function app_sample22_firebird_seed(PDO $pdo): void
{
    $bookInsert = $pdo->prepare('INSERT INTO EBOOK_WORKFLOW_BOOK (ID, TITLE, SLUG, STATUS, PUBLISHED_AT) VALUES (?, ?, ?, ?, ?)');
    $bookInsert->execute([1, 'Workflow Book', 'workflow-book', 'published', '2026-06-21 09:00:00']);
    $bookInsert->execute([2, 'Draft Workflow Book', 'draft-workflow-book', 'draft', null]);

    $chapterInsert = $pdo->prepare(
        'INSERT INTO EBOOK_WORKFLOW_CHAPTER (
            ID, EBOOK_WORKFLOW_BOOK_ID, CHAPTER_TITLE, CHAPTER_SLUG, STATUS, SPINE_ORDER, NAV_LABEL,
            EPUB_RESOURCE_PATH, BODY_MARKDOWN, PUBLISHED_AT, UPDATED_AT
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'
    );
    $chapterInsert->execute([1, 1, 'Opening', 'opening', 'published', 1, 'Opening', 'chapters/opening.xhtml', '# Opening', '2026-06-21 09:10:00', '2026-06-21 09:15:00']);
    $chapterInsert->execute([2, 1, 'Middle', 'middle', 'published', 2, 'Middle', 'chapters/middle.xhtml', '# Middle', '2026-06-21 09:20:00', '2026-06-21 09:25:00']);
    $chapterInsert->execute([3, 1, 'Draft Chapter', 'draft-chapter', 'draft', 3, 'Draft', 'chapters/draft.xhtml', '# Draft', null, '2026-06-21 09:30:00']);

    $publishedInsert = $pdo->prepare(
        'INSERT INTO EBOOK_WORKFLOW_PUBLISHED_CHAPTER (
            CHAPTER_ID, BOOK_ID, BOOK_SLUG, CHAPTER_TITLE, CHAPTER_SLUG, STATUS, SPINE_ORDER, NAV_LABEL,
            EPUB_RESOURCE_PATH, BODY_MARKDOWN, PUBLISHED_AT
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'
    );
    $publishedInsert->execute([1, 1, 'workflow-book', 'Opening', 'opening', 'published', 1, 'Opening', 'chapters/opening.xhtml', '# Opening', '2026-06-21 09:10:00']);
    $publishedInsert->execute([2, 1, 'workflow-book', 'Middle', 'middle', 'published', 2, 'Middle', 'chapters/middle.xhtml', '# Middle', '2026-06-21 09:20:00']);

    $pdo->exec('ALTER TABLE EBOOK_WORKFLOW_BOOK ALTER ID RESTART WITH 3');
    $pdo->exec('ALTER TABLE EBOOK_WORKFLOW_CHAPTER ALTER ID RESTART WITH 4');
}

/** @return array<string,mixed> */
function app_sample22_firebird_dbaccess_smoke(string $dsn, string $user, string $password): array
{
    if (!extension_loaded('pdo_firebird')) {
        return app_sample22_firebird_smoke_result(
            false,
            'runtime_preflight',
            'pdo_firebird_extension_missing',
            [
                'loaded_pdo_drivers' => PDO::getAvailableDrivers(),
                'required_driver' => 'firebird',
            ],
        );
    }
    if (trim($dsn) === '') {
        return app_sample22_firebird_smoke_result(false, 'runtime_preflight', 'firebird_dsn_required');
    }

    try {
        $pdo = new PDO(
            $dsn,
            $user,
            $password,
            [
                PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
                PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
                PDO::ATTR_EMULATE_PREPARES => false,
            ],
        );

        foreach (app_sample22_firebird_drop_tables() as $tableName) {
            try {
                $pdo->exec('DROP TABLE ' . $tableName);
            } catch (Throwable) {
                // Disposable smoke tables may not exist.
            }
        }

        app_sample22_firebird_create_schema($pdo);
        app_sample22_firebird_seed($pdo);

        putenv('MTOOL_RUNTIME_DB_DSN=' . $dsn);
        putenv('MTOOL_RUNTIME_DB_USER=' . $user);
        putenv('MTOOL_RUNTIME_DB_PASSWORD=' . $password);

        require_once dirname(__DIR__, 2) . '/sample/tutorials/sample22-ebook-chapter-workflow-demo/reference/DATACLASS-PHP/data-EbookWorkflowChapter.php';
        require_once dirname(__DIR__, 2) . '/sample/tutorials/sample22-ebook-chapter-workflow-demo/reference/DATACLASS-PHP/data-EbookWorkflowPublishedChapter.php';
        require_once dirname(__DIR__, 2) . '/sample/tutorials/sample22-ebook-chapter-workflow-demo/reference/DBACCESS-PHP/dbaccess-EbookWorkflowChapter.php';

        $dbAccess = new EbookWorkflowChapterDBAccess();
        $publishedRows = $dbAccess->GetPublishedEbookWorkflowChapterList('workflow-book');
        if (!is_array($publishedRows)) {
            return app_sample22_firebird_smoke_result(false, 'published_list', 'dbaccess_returned_non_array', [
                'type' => get_debug_type($publishedRows),
            ], true);
        }
        $publishedSummary = array_map(
            static fn (object $row): array => [
                'chapterId' => (int) ($row->chapterId ?? 0),
                'chapterSlug' => (string) ($row->chapterSlug ?? ''),
                'spineOrder' => (int) ($row->spineOrder ?? 0),
            ],
            $publishedRows,
        );
        $expectedPublishedSummary = [
            ['chapterId' => 1, 'chapterSlug' => 'opening', 'spineOrder' => 1],
            ['chapterId' => 2, 'chapterSlug' => 'middle', 'spineOrder' => 2],
        ];
        if ($publishedSummary !== $expectedPublishedSummary) {
            return app_sample22_firebird_smoke_result(false, 'published_list', 'unexpected_published_rows', [
                'expected' => $expectedPublishedSummary,
                'actual' => $publishedSummary,
            ], true);
        }

        $publishedDetail = $dbAccess->GetPublishedEbookWorkflowChapter('workflow-book', 'opening');
        if (
            !$publishedDetail instanceof EbookWorkflowPublishedChapterData
            || (string) $publishedDetail->bodyMarkdown !== '# Opening'
        ) {
            return app_sample22_firebird_smoke_result(false, 'published_detail', 'unexpected_published_detail', [
                'type' => get_debug_type($publishedDetail),
                'body_markdown' => is_object($publishedDetail) ? (string) ($publishedDetail->bodyMarkdown ?? '') : null,
            ], true);
        }

        $newChapter = new EbookWorkflowChapterData();
        $newChapter->ebookWorkflowBookId = 1;
        $newChapter->chapterTitle = 'Inserted Workflow Chapter';
        $newChapter->chapterSlug = 'inserted-workflow-chapter';
        $newChapter->spineOrder = 4;
        $newChapter->navLabel = 'Inserted';
        $newChapter->epubResourcePath = 'chapters/inserted.xhtml';
        $newChapter->bodyMarkdown = '# Inserted';
        $insertResult = $dbAccess->InsertEbookWorkflowChapter($newChapter);
        if ($insertResult === false) {
            return app_sample22_firebird_smoke_result(false, 'insert_draft', 'insert_failed', [], true);
        }
        $insertedCount = (int) $pdo
            ->query("SELECT COUNT(*) FROM EBOOK_WORKFLOW_CHAPTER WHERE CHAPTER_SLUG = 'inserted-workflow-chapter' AND STATUS = 'draft'")
            ->fetchColumn();
        if ($insertedCount !== 1) {
            return app_sample22_firebird_smoke_result(false, 'insert_draft_readback', 'inserted_draft_missing', [
                'inserted_count' => $insertedCount,
            ], true);
        }

        $draftUpdate = new EbookWorkflowChapterData();
        $draftUpdate->id = 3;
        $draftUpdate->chapterTitle = 'Draft Chapter Updated';
        $draftUpdate->navLabel = 'Draft Updated';
        $draftUpdate->epubResourcePath = 'chapters/draft-updated.xhtml';
        $draftUpdate->bodyMarkdown = '# Draft Updated';
        $updateResult = $dbAccess->UpdateEbookWorkflowChapterDraft($draftUpdate);
        if ($updateResult === false) {
            return app_sample22_firebird_smoke_result(false, 'update_draft', 'update_draft_failed', [], true);
        }

        $orderUpdate = new EbookWorkflowChapterData();
        $orderUpdate->id = 3;
        $orderUpdate->spineOrder = 5;
        $orderUpdate->navLabel = 'Draft Ordered';
        $orderUpdate->epubResourcePath = 'chapters/draft-ordered.xhtml';
        $orderResult = $dbAccess->UpdateEbookWorkflowChapterOrder($orderUpdate);
        if ($orderResult === false) {
            return app_sample22_firebird_smoke_result(false, 'update_order', 'update_order_failed', [], true);
        }

        $publishUpdate = new EbookWorkflowChapterData();
        $publishUpdate->id = 3;
        $publishResult = $dbAccess->PublishEbookWorkflowChapter($publishUpdate);
        if ($publishResult === false) {
            return app_sample22_firebird_smoke_result(false, 'publish', 'publish_failed', [], true);
        }

        $workflowRow = $pdo
            ->query('SELECT STATUS, CHAPTER_TITLE, SPINE_ORDER, NAV_LABEL, EPUB_RESOURCE_PATH, BODY_MARKDOWN, PUBLISHED_AT, UPDATED_AT FROM EBOOK_WORKFLOW_CHAPTER WHERE ID = 3')
            ->fetch(PDO::FETCH_ASSOC);
        if (
            !is_array($workflowRow)
            || (string) ($workflowRow['STATUS'] ?? '') !== 'published'
            || (string) ($workflowRow['CHAPTER_TITLE'] ?? '') !== 'Draft Chapter Updated'
            || (int) ($workflowRow['SPINE_ORDER'] ?? 0) !== 5
            || (string) ($workflowRow['NAV_LABEL'] ?? '') !== 'Draft Ordered'
            || (string) ($workflowRow['EPUB_RESOURCE_PATH'] ?? '') !== 'chapters/draft-ordered.xhtml'
            || (string) ($workflowRow['BODY_MARKDOWN'] ?? '') !== '# Draft Updated'
            || (string) ($workflowRow['PUBLISHED_AT'] ?? '') === ''
            || (string) ($workflowRow['UPDATED_AT'] ?? '') === ''
        ) {
            return app_sample22_firebird_smoke_result(false, 'workflow_readback', 'workflow_row_unexpected', [
                'row' => $workflowRow,
            ], true);
        }

        return app_sample22_firebird_smoke_result(true, 'ok', '', [
            'sample' => 'sample22-ebook-chapter-workflow-demo',
            'pdo_driver' => (string) $pdo->getAttribute(PDO::ATTR_DRIVER_NAME),
            'tables' => array_values(app_sample22_firebird_drop_tables()),
            'published_rows' => $publishedSummary,
            'published_detail_slug' => (string) $publishedDetail->chapterSlug,
            'inserted_draft_rows' => $insertedCount,
            'workflow_status_after_publish' => (string) ($workflowRow['STATUS'] ?? ''),
            'workflow_spine_order_after_order' => (int) ($workflowRow['SPINE_ORDER'] ?? 0),
        ], true);
    } catch (Throwable $throwable) {
        return app_sample22_firebird_smoke_result(false, 'connection_or_dbaccess', $throwable->getMessage(), [
            'dsn_prefix' => preg_replace('/=.*/', '=...', $dsn),
        ], true);
    }
}

$parsed = app_cli_sample22_firebird_parse_args($argv);
if ($parsed['help']) {
    fwrite(STDOUT, app_cli_sample22_firebird_usage() . PHP_EOL);
    exit(0);
}
if ($parsed['error'] !== '') {
    fwrite(STDERR, $parsed['error'] . PHP_EOL . PHP_EOL . app_cli_sample22_firebird_usage() . PHP_EOL);
    exit(64);
}

$result = app_sample22_firebird_dbaccess_smoke(
    $parsed['dsn'],
    $parsed['user'],
    $parsed['password'],
);

fwrite(
    $result['ok'] ? STDOUT : STDERR,
    json_encode(
        $result,
        JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES | ($parsed['pretty'] ? JSON_PRETTY_PRINT : 0),
    ) . PHP_EOL,
);

exit($result['ok'] ? 0 : 1);
