<?php

// AUTO-GENERATED BASE FILE.
// Do not edit this file manually or with AI/Codex.
// Keep customizations in the wrapper/custom class and use this base file exactly as regenerated by the tool.

// Generated from canonical DB Access metadata.
// Thin DTO generated from canonical select/write metadata.

class UploadGroupAssignedServerPathDataBase
{
    public $PID;
    public $UploadGroupPID;
    public $UploadServerPID;
    public $UploadServerPathPID;
    public $ListOrder;
    public $UploadServerPathDropboxPath;
    public $UploadServerPathLocalPath;
    public $UploadServerPathShowDeepCountLimit;
    public $DropboxSettingname;
    public $DropboxSettingAccessToken;
    public $DropboxSettingPID;
    public $UploadServerUploaderURL;
    public $ServerLocalServerName;
    public $DropboxBaseFolderName;
    public $DropboxBaseFolderPID;
    public $UploadServerPathCategoryName;

    public function __construct()
    {
    }
}

?>
