<?php

// AUTO-GENERATED BASE FILE.
// Do not edit this file manually or with AI/Codex.
// Keep customizations in the wrapper/custom class and use this base file exactly as regenerated by the tool.

require_once __DIR__ . '/../_support/legacy-dbaccess/dbaccess-DropboxBaseFolderUser.php';

// Generated from canonical DB Access metadata.
// Simple CRUD / joined select methods regenerate SQL when canonical metadata is sufficient.
// Known helper-style methods regenerate canonical PHP bodies when SQL regeneration is not the right fit.
// Remaining unsupported methods continue to delegate to copied legacy support under `_support/legacy-dbaccess/`.

class DropboxBaseFolderUserDBAccessBase extends DropboxBaseFolderUserDBAccessLegacy
{
    // source_of_truth=sync-bootstrap action_type=UNKNOWN order=11 generation=canonical-constructor
    // reason=bootstrap constructor is empty, so runtime owns the no-op constructor directly
    public function __construct()
    {
    }

    // source_of_truth=sync-bootstrap action_type=SELECTLIST order=14 generation=canonical-sql
    public function GetDropboxBaseFolderUserList($param_DropboxBaseFolderUser_DropboxBaseFolderPID_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $result = array();

        $last_sql_command_for_mtooldb = 'select DropboxBaseFolderUser.PID, DropboxBaseFolderUser.DropboxBaseFolderPID, DropboxBaseFolderUser.username, DropboxBaseFolderUser.EmailForDropboxSharing, DropboxBaseFolderUser.IsReadOnly, DropboxBaseFolder.Name, DropboxSetting.AccessToken from DropboxBaseFolderUser left outer join DropboxBaseFolder on DropboxBaseFolderUser.DropboxBaseFolderPID = DropboxBaseFolder.PID left outer join DropboxSetting on DropboxBaseFolder.SettingGroupPID = DropboxSetting.PID' . ' where ' . 'DropboxBaseFolderUser.DropboxBaseFolderPID = ' . '\'' . $mtooldb->real_escape_string($param_DropboxBaseFolderUser_DropboxBaseFolderPID_where) . '\'';
        $ret = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new DropboxBaseFolderUserData();
            $thisresult->PID = $thisline[0];
            $thisresult->DropboxBaseFolderPID = $thisline[1];
            $thisresult->username = $thisline[2];
            $thisresult->EmailForDropboxSharing = $thisline[3];
            $thisresult->IsReadOnly = $thisline[4];
            $thisresult->DropboxBaseFolderName = $thisline[5];
            $thisresult->DropboxSettingAccessToken = $thisline[6];
            array_push($result, $thisresult);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=SELECTSINGLE order=44 generation=canonical-sql
    public function GetDropboxBaseFolderUser($param_DropboxBaseFolderUser_DropboxBaseFolderPID_where, $param_DropboxBaseFolderUser_username_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'select DropboxBaseFolderUser.PID, DropboxBaseFolderUser.DropboxBaseFolderPID, DropboxBaseFolderUser.username, DropboxBaseFolderUser.EmailForDropboxSharing, DropboxBaseFolderUser.IsReadOnly, DropboxBaseFolder.Name, DropboxSetting.AccessToken from DropboxBaseFolderUser left outer join DropboxBaseFolder on DropboxBaseFolderUser.DropboxBaseFolderPID = DropboxBaseFolder.PID left outer join DropboxSetting on DropboxBaseFolder.SettingGroupPID = DropboxSetting.PID' . ' where ' . 'DropboxBaseFolderUser.DropboxBaseFolderPID = ' . '\'' . $mtooldb->real_escape_string($param_DropboxBaseFolderUser_DropboxBaseFolderPID_where) . '\'' . ' and ' . 'DropboxBaseFolderUser.username = ' . '\'' . $mtooldb->real_escape_string($param_DropboxBaseFolderUser_username_where) . '\'';
        $ret = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new DropboxBaseFolderUserData();
            $thisresult->PID = $thisline[0];
            $thisresult->DropboxBaseFolderPID = $thisline[1];
            $thisresult->username = $thisline[2];
            $thisresult->EmailForDropboxSharing = $thisline[3];
            $thisresult->IsReadOnly = $thisline[4];
            $thisresult->DropboxBaseFolderName = $thisline[5];
            $thisresult->DropboxSettingAccessToken = $thisline[6];
            return $thisresult;
        }
        return NULL;
    }

    // source_of_truth=sync-bootstrap action_type=INSERT order=72 generation=canonical-sql
    public function InsertDropboxBaseFolderUser($DropboxBaseFolderUserObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'insert into DropboxBaseFolderUser (DropboxBaseFolderPID, username, EmailForDropboxSharing, IsReadOnly) values(' . '\'' . $mtooldb->real_escape_string($DropboxBaseFolderUserObj->DropboxBaseFolderPID) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($DropboxBaseFolderUserObj->username) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($DropboxBaseFolderUserObj->EmailForDropboxSharing) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($DropboxBaseFolderUserObj->IsReadOnly) . '\'' . ')';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=UPDATE order=88 generation=canonical-sql
    public function UpdateDropboxBaseFolderUser($DropboxBaseFolderUserObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'update DropboxBaseFolderUser SET ' . 'DropboxBaseFolderPID = ' . '\'' . $mtooldb->real_escape_string($DropboxBaseFolderUserObj->DropboxBaseFolderPID) . '\'' . ', ' . 'username = ' . '\'' . $mtooldb->real_escape_string($DropboxBaseFolderUserObj->username) . '\'' . ', ' . 'EmailForDropboxSharing = ' . '\'' . $mtooldb->real_escape_string($DropboxBaseFolderUserObj->EmailForDropboxSharing) . '\'' . ', ' . 'IsReadOnly = ' . '\'' . $mtooldb->real_escape_string($DropboxBaseFolderUserObj->IsReadOnly) . '\'' . ' where ' . 'DropboxBaseFolderUser.DropboxBaseFolderPID = ' . '\'' . $mtooldb->real_escape_string($DropboxBaseFolderUserObj->DropboxBaseFolderPID) . '\'' . ' and ' . 'DropboxBaseFolderUser.username = ' . '\'' . $mtooldb->real_escape_string($DropboxBaseFolderUserObj->username) . '\'';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=DELETE order=104 generation=canonical-sql
    public function DeleteDropboxBaseFolderUser($DropboxBaseFolderUserObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'delete from DropboxBaseFolderUser where ' . 'DropboxBaseFolderUser.DropboxBaseFolderPID = ' . '\'' . $mtooldb->real_escape_string($DropboxBaseFolderUserObj->DropboxBaseFolderPID) . '\'' . ' and ' . 'DropboxBaseFolderUser.username = ' . '\'' . $mtooldb->real_escape_string($DropboxBaseFolderUserObj->username) . '\'';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }
}

?>