<?php

// AUTO-GENERATED BASE FILE.
// Do not edit this file manually or with AI/Codex.
// Keep customizations in the wrapper class and use this base file exactly as regenerated by the tool.

// Generated from canonical DB Access metadata.
// Base class generated from project_db_access_* metadata.

require_once __DIR__ . '/../_support/mtool_runtime_db.php';


class EbookCmsBookDBAccessBase
{
    public function __construct()
    {
    }

    // source_of_truth=manual class_source=manual action_type=SELECTLIST order=10 generation=canonical-sql
    public function GetPublicEbookCmsBookList($limit)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $result = array();

        $last_sql_command_for_mtooldb = 'select EbookCmsBook.Id, EbookCmsBook.Title, EbookCmsBook.Slug, EbookCmsBook.AuthorName, EbookCmsBook.GenreName, EbookCmsBook.CoverImageUrl, EbookCmsBook.Summary from EbookCmsBook where EbookCmsBook.Status = ? order by EbookCmsBook.PublishedAt desc, EbookCmsBook.Id desc limit ?';
        $ret = $mtooldb->execute($last_sql_command_for_mtooldb, [
            'published',
            $limit,
        ]);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new EbookCmsBookData();
            $thisresult->Id = $thisline[0];
            $thisresult->Title = $thisline[1];
            $thisresult->Slug = $thisline[2];
            $thisresult->AuthorName = $thisline[3];
            $thisresult->GenreName = $thisline[4];
            $thisresult->CoverImageUrl = $thisline[5];
            $thisresult->Summary = $thisline[6];
            array_push($result, $thisresult);
        }
        return $result;
    }

    // source_of_truth=manual class_source=manual action_type=SELECTSINGLE order=20 generation=canonical-sql
    public function GetPublicEbookCmsBook($param_EbookCmsBook_Slug_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'select EbookCmsBook.Id, EbookCmsBook.Title, EbookCmsBook.Slug, EbookCmsBook.AuthorName, EbookCmsBook.GenreName, EbookCmsBook.CoverImageUrl, EbookCmsBook.Summary from EbookCmsBook where EbookCmsBook.Status = ? and EbookCmsBook.Slug = ?';
        $ret = $mtooldb->execute($last_sql_command_for_mtooldb, [
            'published',
            $param_EbookCmsBook_Slug_where,
        ]);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new EbookCmsBookData();
            $thisresult->Id = $thisline[0];
            $thisresult->Title = $thisline[1];
            $thisresult->Slug = $thisline[2];
            $thisresult->AuthorName = $thisline[3];
            $thisresult->GenreName = $thisline[4];
            $thisresult->CoverImageUrl = $thisline[5];
            $thisresult->Summary = $thisline[6];
            return $thisresult;
        }
        return NULL;
    }

    // source_of_truth=manual class_source=manual action_type=SELECTLIST order=30 generation=canonical-sql
    public function GetPublicEbookCmsChapterList($param_EbookCmsChapter_BookSlug_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $result = array();

        $last_sql_command_for_mtooldb = 'select EbookCmsChapter.Id, EbookCmsChapter.BookSlug, EbookCmsChapter.ChapterTitle, EbookCmsChapter.ChapterSlug, EbookCmsChapter.SpineOrder from EbookCmsChapter where EbookCmsChapter.Status = ? and EbookCmsChapter.BookSlug = ? order by EbookCmsChapter.SpineOrder asc, EbookCmsChapter.Id asc';
        $ret = $mtooldb->execute($last_sql_command_for_mtooldb, [
            'published',
            $param_EbookCmsChapter_BookSlug_where,
        ]);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new EbookCmsChapterData();
            $thisresult->Id = $thisline[0];
            $thisresult->BookSlug = $thisline[1];
            $thisresult->ChapterTitle = $thisline[2];
            $thisresult->ChapterSlug = $thisline[3];
            $thisresult->SpineOrder = $thisline[4];
            array_push($result, $thisresult);
        }
        return $result;
    }

    // source_of_truth=manual class_source=manual action_type=SELECTSINGLE order=40 generation=canonical-sql
    public function GetPublicEbookCmsChapter($param_EbookCmsChapter_BookSlug_where, $param_EbookCmsChapter_ChapterSlug_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'select EbookCmsChapter.Id, EbookCmsChapter.BookSlug, EbookCmsChapter.ChapterTitle, EbookCmsChapter.ChapterSlug, EbookCmsChapter.SpineOrder, EbookCmsChapter.BodyMarkdown from EbookCmsChapter where EbookCmsChapter.Status = ? and EbookCmsChapter.BookSlug = ? and EbookCmsChapter.ChapterSlug = ?';
        $ret = $mtooldb->execute($last_sql_command_for_mtooldb, [
            'published',
            $param_EbookCmsChapter_BookSlug_where,
            $param_EbookCmsChapter_ChapterSlug_where,
        ]);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new EbookCmsChapterData();
            $thisresult->Id = $thisline[0];
            $thisresult->BookSlug = $thisline[1];
            $thisresult->ChapterTitle = $thisline[2];
            $thisresult->ChapterSlug = $thisline[3];
            $thisresult->SpineOrder = $thisline[4];
            $thisresult->BodyMarkdown = $thisline[5];
            return $thisresult;
        }
        return NULL;
    }

    // source_of_truth=manual class_source=manual action_type=SELECTLIST order=50 generation=canonical-sql
    public function GetPublicEbookCmsEpubDeliveryList($param_EbookCmsBook_Slug_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $result = array();

        $last_sql_command_for_mtooldb = 'select EbookCmsBook.Id, EbookCmsBook.Slug, EbookCmsBook.Title, EbookCmsBook.EpubDownloadUrl, EbookCmsBook.EpubMimeType, EbookCmsBook.EpubSha256 from EbookCmsBook where EbookCmsBook.Status = ? and EbookCmsBook.Slug = ? order by EbookCmsBook.Id asc';
        $ret = $mtooldb->execute($last_sql_command_for_mtooldb, [
            'published',
            $param_EbookCmsBook_Slug_where,
        ]);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new EbookCmsBookData();
            $thisresult->Id = $thisline[0];
            $thisresult->Slug = $thisline[1];
            $thisresult->Title = $thisline[2];
            $thisresult->EpubDownloadUrl = $thisline[3];
            $thisresult->EpubMimeType = $thisline[4];
            $thisresult->EpubSha256 = $thisline[5];
            array_push($result, $thisresult);
        }
        return $result;
    }

    // source_of_truth=manual class_source=manual action_type=SELECTSINGLE order=60 generation=canonical-sql
    public function GetEditorEbookCmsChapter($param_EbookCmsChapter_Id_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'select EbookCmsChapter.Id, EbookCmsChapter.EbookCmsBookId, EbookCmsChapter.BookSlug, EbookCmsChapter.ChapterTitle, EbookCmsChapter.ChapterSlug, EbookCmsChapter.Status, EbookCmsChapter.SpineOrder, EbookCmsChapter.BodyMarkdown, EbookCmsChapter.PublishedAt, EbookCmsChapter.UpdatedAt from EbookCmsChapter where EbookCmsChapter.Id = ?';
        $ret = $mtooldb->execute($last_sql_command_for_mtooldb, [
            $param_EbookCmsChapter_Id_where,
        ]);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new EbookCmsChapterData();
            $thisresult->Id = $thisline[0];
            $thisresult->EbookCmsBookId = $thisline[1];
            $thisresult->BookSlug = $thisline[2];
            $thisresult->ChapterTitle = $thisline[3];
            $thisresult->ChapterSlug = $thisline[4];
            $thisresult->Status = $thisline[5];
            $thisresult->SpineOrder = $thisline[6];
            $thisresult->BodyMarkdown = $thisline[7];
            $thisresult->PublishedAt = $thisline[8];
            $thisresult->UpdatedAt = $thisline[9];
            return $thisresult;
        }
        return NULL;
    }

    // source_of_truth=manual class_source=manual action_type=UPDATE order=70 generation=canonical-sql
    public function UpdateEditorEbookCmsChapterDraft($EbookCmsChapterObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'update EbookCmsChapter SET ChapterTitle = ?, ChapterSlug = ?, SpineOrder = ?, BodyMarkdown = ?, UpdatedAt = NOW() where EbookCmsChapter.Id = ?';
        $result = $mtooldb->execute($last_sql_command_for_mtooldb, [
            $EbookCmsChapterObj->ChapterTitle,
            $EbookCmsChapterObj->ChapterSlug,
            $EbookCmsChapterObj->SpineOrder,
            $EbookCmsChapterObj->BodyMarkdown,
            $EbookCmsChapterObj->Id,
        ]);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }

    // source_of_truth=manual class_source=manual action_type=UPDATE order=80 generation=canonical-sql
    public function PublishEditorEbookCmsChapter($EbookCmsChapterObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'update EbookCmsChapter SET Status = ?, PublishedAt = NOW(), UpdatedAt = NOW() where EbookCmsChapter.Id = ?';
        $result = $mtooldb->execute($last_sql_command_for_mtooldb, [
            'published',
            $EbookCmsChapterObj->Id,
        ]);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }
}

?>