<?php

// == START OF EDITABLE AREA FOR "Initilaize" ==
// == END OF EDITABLE AREA FOR "Initilaize" ==

function __RESOURCE_FUNCTION_PREFIX__getres__RESOURCE_FUNCTION_SUFFIX__($name)
{
	global $english_mode;
	global $lang;
	global $LANG_JAPANESE, $LANG_ENGLISH, $LANG_CHINESE, $LANG_TRAITIONAL_CHINESE, $LANG_KOREAN, $LANG_SPANISH, $LANG_PORTUGUESE, $LANG_FRENCH, $LANG_HINDI, $LANG_ARABIC, $LANG_PERSIAN, $LANG_GERMAN, $LANG_RUSSIAN, $LANG_MALAY, $LANG_TAMIL, $LANG_ITALIAN, $LANG_BENGALI, $LANG_TURKISH, $LANG_VIETNAMESE, $LANG_POLISH, $LANG_JAVANESE, $LANG_PUNJABI, $LANG_THAI, $LANG_TELUGU, $LANG_MARATHI, $LANG_URDU, $LANG_GUJARATI, $LANG_UKRAINIAN, $LANG_MALAYALAM, $LANG_KANNADA, $LANG_SUNDANESE, $LANG_KURDISH, $LANG_PASHTO, $LANG_ROMANIAN, $LANG_INDONESIAN, $LANG_SINDHI, $LANG_AFRIKAANS, $LANG_SWAHILI, $LANG_LAO, $LANG_DUTCH, $LANG_TAGALOG, $LANG_NEPALI, $LANG_HANGARIAN, $LANG_CZECH, $LANG_GREEK, $LANG_SWEDISH, $LANG_KAZAKH, $LANG_FINNISH, $LANG_DANISH, $LANG_HEBREW, $LANG_NORWEGIAN;
	global $DOMAINNAMECAPTION_JP, $DOMAINNAMECAPTION_EN, $DOMAINNAMECAPTION_ZH, $DOMAINNAMECAPTION_TZH, $DOMAINNAMECAPTION_KO, $DOMAINNAMECAPTION_ES, $DOMAINNAMECAPTION_PT, $DOMAINNAMECAPTION_FR, $DOMAINNAMECAPTION_HI, $DOMAINNAMECAPTION_AR, $DOMAINNAMECAPTION_FA, $DOMAINNAMECAPTION_DE, $DOMAINNAMECAPTION_RU, $DOMAINNAMECAPTION_MS, $DOMAINNAMECAPTION_TA, $DOMAINNAMECAPTION_IT, $DOMAINNAMECAPTION_BN, $DOMAINNAMECAPTION_TR, $DOMAINNAMECAPTION_VI, $DOMAINNAMECAPTION_PL, $DOMAINNAMECAPTION_JV, $DOMAINNAMECAPTION_PA, $DOMAINNAMECAPTION_TH, $DOMAINNAMECAPTION_TE, $DOMAINNAMECAPTION_MR, $DOMAINNAMECAPTION_UR, $DOMAINNAMECAPTION_GU, $DOMAINNAMECAPTION_UK, $DOMAINNAMECAPTION_ML, $DOMAINNAMECAPTION_KN, $DOMAINNAMECAPTION_SU, $DOMAINNAMECAPTION_KU, $DOMAINNAMECAPTION_PS, $DOMAINNAMECAPTION_RO, $DOMAINNAMECAPTION_ID, $DOMAINNAMECAPTION_SD, $DOMAINNAMECAPTION_AF, $DOMAINNAMECAPTION_SW, $DOMAINNAMECAPTION_LO, $DOMAINNAMECAPTION_NL, $DOMAINNAMECAPTION_TL, $DOMAINNAMECAPTION_NE, $DOMAINNAMECAPTION_HU, $DOMAINNAMECAPTION_CS, $DOMAINNAMECAPTION_EL, $DOMAINNAMECAPTION_SV, $DOMAINNAMECAPTION_KK, $DOMAINNAMECAPTION_FI, $DOMAINNAMECAPTION_DA, $DOMAINNAMECAPTION_HE, $DOMAINNAMECAPTION_NO;

	switch ($name) {
__LANGUAGE_RESOURCE_LIST__
	}
	// == START OF EDITABLE AREA FOR "Default Result" ==
	// == END OF EDITABLE AREA FOR "Default Result" ==
}

?>
