<?php

// AUTO-GENERATED BASE FILE.
// Do not edit this file manually or with AI/Codex.
// Keep customizations in the wrapper class and use this base file exactly as regenerated by the tool.

// Generated from canonical data class metadata.
// Base DTO generated from dataclass / dataclassfields.

class EbookBookDataBase
{
    public $Id;
    public $EbookSeriesId;
    public $Title;
    public $Slug;
    public $Status;
    public $PublishedAt;
    public $Summary;
    public $EpubStatus;
    public $PrimaryEpubUrl;
    public $UpdatedAt;

    public function __construct()
    {
    }
}

?>