<?php

// AUTO-GENERATED BASE FILE.
// Do not edit this file manually or with AI/Codex.
// Keep customizations in the wrapper class and use this base file exactly as regenerated by the tool.

// Generated from canonical data class metadata.
// Base DTO generated from dataclass / dataclassfields.

class EbookCatalogItemDataBase
{
    public $BookId;
    public $BookTitle;
    public $BookSlug;
    public $Status;
    public $SeriesName;
    public $SeriesSlug;
    public $AuthorName;
    public $AuthorSlug;
    public $GenreName;
    public $GenreSlug;
    public $PublishedAt;
    public $Summary;
    public $EpubStatus;
    public $PrimaryEpubUrl;

    public function __construct()
    {
    }
}

?>