name: mtool-sample-sample03-dataclass-lookup-and-helper-sqlite

services:
  web-admin:
    environment:
      APP_WORK_ROOT: /var/www/work/sample-packs/sample03-dataclass-lookup-and-helper-sqlite

  web-lab:
    environment:
      APP_WORK_ROOT: /var/www/work/sample-packs/sample03-dataclass-lookup-and-helper-sqlite
