<?php

// AUTO-GENERATED BASE FILE.
// Do not edit this file manually or with AI/Codex.
// Keep customizations in the wrapper class and use this base file exactly as regenerated by the tool.

// Generated by migrating a legacy data class.
// Generated members are kept in this base file. Former editable areas move to the wrapper file.
// Generated trailing enum-type classes also stay in this base file when present.

class htmlTemplateDataBase
{
    public $PID;
    public $TargetType;
    public $ParentHtmlTemplatePID;
    public $name;
    public $ProgramLanguage;
    public $FileName;
    public $Comment;

    public function __construct()
    {
    }
}

class SortedhtmlTemplateDataContainer
{
	public $htmlTemplate;
	public $ChildList;
}

class htmlTemplateTargetTypeEnum
{
	static $UNKNOWN = "Unknown";
	static $HTML = "html";
	static $DB = "db";
	static $PROXYSERVER = "proxyserver";
	static $PROXYCLIENT = "proxyclient";
	static $DBAASPROXYSERVER = "dbaasproxyserver";
	static $DBAASPROXYCLIENT = "dbaasproxyclient";
	static $UNITTEST = "unittest";
	static $UPLOADSETTING = "uploadsetting";
	static $LANGUAGERESOURCE = "LanguageResource";
}

class htmlTemplateProgramLanguageEnum
{
	static $UNKNOWN = "Unknown";
	static $PHP = "php";
	static $CS = "cs";
	static $JAVA = "java";
	static $OBJECTIVECH = "objectivech";
	static $OBJECTIVECM = "objectivecm";
	static $SWIFT = "swift";
}


?>
