<?php

// AUTO-GENERATED BASE FILE.
// Do not edit this file manually or with AI/Codex.
// Keep customizations in the wrapper/custom class and use this base file exactly as regenerated by the tool.

require_once __DIR__ . '/../_support/legacy-dbaccess/dbaccess-InternalUser.php';

// Generated from canonical DB Access metadata.
// Simple CRUD / joined select methods regenerate SQL when canonical metadata is sufficient.
// Known helper-style methods regenerate canonical PHP bodies when SQL regeneration is not the right fit.
// Remaining unsupported methods continue to delegate to copied legacy support under `_support/legacy-dbaccess/`.

class InternalUserDBAccessBase extends InternalUserDBAccessLegacy
{
    // source_of_truth=sync-bootstrap action_type=UNKNOWN order=11 generation=canonical-constructor
    // reason=bootstrap constructor is empty, so runtime owns the no-op constructor directly
    public function __construct()
    {
    }

    // source_of_truth=sync-bootstrap action_type=SELECTLIST order=14 generation=canonical-sql
    public function GetInternalUserList()
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $result = array();

        $last_sql_command_for_mtooldb = 'select InternalUser.PID, InternalUser.username, InternalUser.IsSystemAdmin from InternalUser';
        $ret = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new InternalUserData();
            $thisresult->PID = $thisline[0];
            $thisresult->username = $thisline[1];
            $thisresult->IsSystemAdmin = $thisline[2];
            array_push($result, $thisresult);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=SELECTSINGLE order=40 generation=canonical-sql
    public function GetInternalUser($param_InternalUser_username_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'select InternalUser.PID, InternalUser.username, InternalUser.IsSystemAdmin from InternalUser' . ' where ' . 'InternalUser.username = ' . '\'' . $mtooldb->real_escape_string($param_InternalUser_username_where) . '\'';
        $ret = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new InternalUserData();
            $thisresult->PID = $thisline[0];
            $thisresult->username = $thisline[1];
            $thisresult->IsSystemAdmin = $thisline[2];
            return $thisresult;
        }
        return NULL;
    }

    // source_of_truth=sync-bootstrap action_type=INSERT order=64 generation=canonical-sql
    public function InsertInternalUser($InternalUserObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'insert into InternalUser (username, IsSystemAdmin) values(' . '\'' . $mtooldb->real_escape_string($InternalUserObj->username) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($InternalUserObj->IsSystemAdmin) . '\'' . ')';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=UPDATE order=80 generation=canonical-sql
    public function UpdateInternalUser($InternalUserObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'update InternalUser SET ' . 'username = ' . '\'' . $mtooldb->real_escape_string($InternalUserObj->username) . '\'' . ', ' . 'IsSystemAdmin = ' . '\'' . $mtooldb->real_escape_string($InternalUserObj->IsSystemAdmin) . '\'' . ' where ' . 'InternalUser.username = ' . '\'' . $mtooldb->real_escape_string($InternalUserObj->username) . '\'';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=DELETE order=96 generation=canonical-sql
    public function DeleteInternalUser($InternalUserObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'delete from InternalUser where ' . 'InternalUser.username = ' . '\'' . $mtooldb->real_escape_string($InternalUserObj->username) . '\'';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }
}

?>