name: mtool-sample-sample18-mini-task-board-demo-sqlite

services:
  web-admin:
    environment:
      APP_WORK_ROOT: /var/www/work/sample-packs/sample18-mini-task-board-demo-sqlite

  web-lab:
    environment:
      APP_WORK_ROOT: /var/www/work/sample-packs/sample18-mini-task-board-demo-sqlite
