<?php

// AUTO-GENERATED BASE FILE.
// Do not edit this file manually or with AI/Codex.
// Keep customizations in the wrapper class and use this base file exactly as regenerated by the tool.

// Generated from canonical DB Access metadata.
// Base class generated from project_db_access_* metadata.

require_once __DIR__ . '/../_support/mtool_runtime_db.php';


class EbookReaderBookDBAccessBase
{
    public function __construct()
    {
    }

    // source_of_truth=manual class_source=manual action_type=SELECTLIST order=10 generation=canonical-sql
    public function GetPublicEbookReaderBookList($limit)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $result = array();

        $last_sql_command_for_mtooldb = 'select EbookReaderBook.Id, EbookReaderBook.Title, EbookReaderBook.Slug, EbookReaderBook.AuthorName, EbookReaderBook.GenreName, EbookReaderBook.Summary from EbookReaderBook where EbookReaderBook.Status = ? order by EbookReaderBook.PublishedAt desc, EbookReaderBook.Id desc limit ?';
        $ret = $mtooldb->execute($last_sql_command_for_mtooldb, [
            'published',
            $limit,
        ]);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new EbookReaderBookData();
            $thisresult->Id = $thisline[0];
            $thisresult->Title = $thisline[1];
            $thisresult->Slug = $thisline[2];
            $thisresult->AuthorName = $thisline[3];
            $thisresult->GenreName = $thisline[4];
            $thisresult->Summary = $thisline[5];
            array_push($result, $thisresult);
        }
        return $result;
    }

    // source_of_truth=manual class_source=manual action_type=SELECTSINGLE order=20 generation=canonical-sql
    public function GetPublicEbookReaderBook($param_EbookReaderBook_Slug_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'select EbookReaderBook.Id, EbookReaderBook.Title, EbookReaderBook.Slug, EbookReaderBook.AuthorName, EbookReaderBook.GenreName, EbookReaderBook.Summary from EbookReaderBook where EbookReaderBook.Status = ? and EbookReaderBook.Slug = ?';
        $ret = $mtooldb->execute($last_sql_command_for_mtooldb, [
            'published',
            $param_EbookReaderBook_Slug_where,
        ]);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new EbookReaderBookData();
            $thisresult->Id = $thisline[0];
            $thisresult->Title = $thisline[1];
            $thisresult->Slug = $thisline[2];
            $thisresult->AuthorName = $thisline[3];
            $thisresult->GenreName = $thisline[4];
            $thisresult->Summary = $thisline[5];
            return $thisresult;
        }
        return NULL;
    }

    // source_of_truth=manual class_source=manual action_type=SELECTLIST order=30 generation=canonical-sql
    public function GetPublicEbookReaderChapterList($param_EbookReaderChapter_BookSlug_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $result = array();

        $last_sql_command_for_mtooldb = 'select EbookReaderChapter.Id, EbookReaderChapter.BookSlug, EbookReaderChapter.ChapterTitle, EbookReaderChapter.ChapterSlug, EbookReaderChapter.SpineOrder from EbookReaderChapter where EbookReaderChapter.Status = ? and EbookReaderChapter.BookSlug = ? order by EbookReaderChapter.SpineOrder asc, EbookReaderChapter.Id asc';
        $ret = $mtooldb->execute($last_sql_command_for_mtooldb, [
            'published',
            $param_EbookReaderChapter_BookSlug_where,
        ]);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new EbookReaderChapterData();
            $thisresult->Id = $thisline[0];
            $thisresult->BookSlug = $thisline[1];
            $thisresult->ChapterTitle = $thisline[2];
            $thisresult->ChapterSlug = $thisline[3];
            $thisresult->SpineOrder = $thisline[4];
            array_push($result, $thisresult);
        }
        return $result;
    }

    // source_of_truth=manual class_source=manual action_type=SELECTSINGLE order=40 generation=canonical-sql
    public function GetPublicEbookReaderChapter($param_EbookReaderChapter_BookSlug_where, $param_EbookReaderChapter_ChapterSlug_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'select EbookReaderChapter.Id, EbookReaderChapter.BookSlug, EbookReaderChapter.ChapterTitle, EbookReaderChapter.ChapterSlug, EbookReaderChapter.SpineOrder, EbookReaderChapter.BodyMarkdown from EbookReaderChapter where EbookReaderChapter.Status = ? and EbookReaderChapter.BookSlug = ? and EbookReaderChapter.ChapterSlug = ?';
        $ret = $mtooldb->execute($last_sql_command_for_mtooldb, [
            'published',
            $param_EbookReaderChapter_BookSlug_where,
            $param_EbookReaderChapter_ChapterSlug_where,
        ]);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new EbookReaderChapterData();
            $thisresult->Id = $thisline[0];
            $thisresult->BookSlug = $thisline[1];
            $thisresult->ChapterTitle = $thisline[2];
            $thisresult->ChapterSlug = $thisline[3];
            $thisresult->SpineOrder = $thisline[4];
            $thisresult->BodyMarkdown = $thisline[5];
            return $thisresult;
        }
        return NULL;
    }

    // source_of_truth=manual class_source=manual action_type=SELECTLIST order=50 generation=canonical-sql
    public function GetPublicEbookReaderMediaDeliveryList($param_EbookReaderMediaDelivery_BookSlug_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $result = array();

        $last_sql_command_for_mtooldb = 'select EbookReaderMediaDelivery.Id, EbookReaderMediaDelivery.BookSlug, EbookReaderMediaDelivery.AssetSlug, EbookReaderMediaDelivery.AssetKind, EbookReaderMediaDelivery.DisplayName, EbookReaderMediaDelivery.PublicUrl, EbookReaderMediaDelivery.MimeType, EbookReaderMediaDelivery.FileSizeBytes, EbookReaderMediaDelivery.Sha256, EbookReaderMediaDelivery.VersionLabel from EbookReaderMediaDelivery where EbookReaderMediaDelivery.Status = ? and EbookReaderMediaDelivery.BookSlug = ? order by EbookReaderMediaDelivery.Id asc';
        $ret = $mtooldb->execute($last_sql_command_for_mtooldb, [
            'published',
            $param_EbookReaderMediaDelivery_BookSlug_where,
        ]);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new EbookReaderMediaDeliveryData();
            $thisresult->Id = $thisline[0];
            $thisresult->BookSlug = $thisline[1];
            $thisresult->AssetSlug = $thisline[2];
            $thisresult->AssetKind = $thisline[3];
            $thisresult->DisplayName = $thisline[4];
            $thisresult->PublicUrl = $thisline[5];
            $thisresult->MimeType = $thisline[6];
            $thisresult->FileSizeBytes = $thisline[7];
            $thisresult->Sha256 = $thisline[8];
            $thisresult->VersionLabel = $thisline[9];
            array_push($result, $thisresult);
        }
        return $result;
    }
}

?>