<?php

// AUTO-GENERATED BASE FILE.
// Do not edit this file manually or with AI/Codex.
// Keep customizations in the wrapper class and use this base file exactly as regenerated by the tool.

// Generated by migrating a legacy data class.
// Generated members are kept in this base file. Former editable areas move to the wrapper file.
// Generated trailing enum-type classes also stay in this base file when present.

class ProjectDataBase
{
    public $PID;
    public $name;
    public $StorageType;
    public $DropboxBaseFolderPID;
    public $DBType;
    public $DBUserPID;
    public $SQLServerConnectionString;
    public $SettingDir;
    public $DBManagerURL;
    public $TokenForProxyAccess;
    public $proxy_header_of_access_control_allow_origin;
    public $proxy_header_of_access_control_allow_headers;
    public $option_automatically_create_simple_proxy;
    public $option_automatically_create_custom_proxy;
    public $option_show_proxy_link;
    public $option_auto_upload_after_build;
    public $option_show_source;
    public $option_show_detail;
    public $option_show_recommended_column_warning;
    public $option_all_source_include;
    public $option_user_can_change_da_func_order;
    public $option_show_source_output_setting;
    public $option_restrict_proxy_server_to_single;
    public $option_show_language_resource;
    public $option_build_dataclass_for_proxy_client_only_if_proxy_exist;
    public $option_show_output_temp_folder_on_build;
    public $option_default_output_temp_folder_on_build_is_true;
    public $option_IsCompareOutputTarget;
    public $DropboxSettingname;
    public $DropboxSettingAccessToken;
    public $DBConnectionDBServerType;
    public $DBConnectionDBName;
    public $DBConnectionObjectNameForPHP;
    public $ServerLocalServerName;
    public $ServerIP;
    public $DBUserUser;
    public $DBUserPassword;
    public $DropboxBaseFolderName;

    public function __construct()
    {
    }
}

class ProjectStorageTypeEnum
{
	static $UNKNOWN = "Unknown";
	static $DROPBOX = "DropBox";
}

class ProjectDBTypeEnum
{
	static $UNKNOWN = "Unknown";
	static $DEFAULT = "";
	static $MYSQLONCLOUD = "MySQLOnCloud";
	static $SQLSERVER = "SQLServer";
}


?>