<?php

// AUTO-GENERATED BASE FILE.
// Do not edit this file manually or with AI/Codex.
// Keep customizations in the wrapper class and use this base file exactly as regenerated by the tool.

// Generated by migrating a legacy data class.
// Generated members are kept in this base file. Former editable areas move to the wrapper file.
// Generated trailing enum-type classes also stay in this base file when present.

class ProjectSourceOutputDataBase
{
    public $ProjectPID;
    public $PID;
    public $ProgramLanguage;
    public $CustomFileExtention;
    public $ClassType;
    public $ReleaseTargetType;
    public $SourceTemplateDir;
    public $SourceOutputDir;
    public $SourceTempOutputDir;
    public $ProxyBaseURL;
    public $UnitTestTemplateDir;
    public $UnitTestOutputDir;
    public $AutoloadFilenameSuffix;
    public $TargetServerProjectSourceOutputPID;
    public $ProjectSourceOutputListOrder;
    public $SourceTextCharCode;
    public $CSNameSpace;
    public $JavaPackageName;
    public $DropboxBaseFolderPID;
    public $AutoLoadFilePathForPHP;
    public $JavaFunctionType;
    public $DotNetLanguageResourceType;
    public $TargtServerPSOProgramLanguage;
    public $TargtServerPSOCustomFileExtention;
    public $TargtServerPSOProxyBaseURL;
    public $DropboxBaseFolderName;

    public function __construct()
    {
    }
}

?>
