<?php

// AUTO-GENERATED BASE FILE.
// Do not edit this file manually or with AI/Codex.
// Keep customizations in the wrapper/custom class and use this base file exactly as regenerated by the tool.

// Generated from canonical DB Access metadata.
// Thin DTO generated from canonical select/write metadata.

class dataclassfieldsDataBase
{
    public $ProjectPID;
    public $dataclassPID;
    public $PID;
    public $name;
    public $datatype;
    public $FieldListOrder;
    public $RefDataClassName;
    public $RefDataClassFieldName;

    public function __construct()
    {
    }
}

?>
