<?php

// AUTO-GENERATED BASE FILE.
// Do not edit this file manually or with AI/Codex.
// Keep customizations in the wrapper/custom class and use this base file exactly as regenerated by the tool.

require_once __DIR__ . '/../_support/legacy-dbaccess/dbaccess-da.php';

// Generated from canonical DB Access metadata.
// Simple CRUD / joined select methods regenerate SQL when canonical metadata is sufficient.
// Known helper-style methods regenerate canonical PHP bodies when SQL regeneration is not the right fit.
// Remaining unsupported methods continue to delegate to copied legacy support under `_support/legacy-dbaccess/`.

class daDBAccessBase extends daDBAccessLegacy
{
    // source_of_truth=sync-bootstrap action_type=UNKNOWN order=11 generation=canonical-constructor
    // reason=bootstrap constructor is empty, so runtime owns the no-op constructor directly
    public function __construct()
    {
    }

    // source_of_truth=seed-legacy action_type=SELECTLIST order=14 generation=canonical-sql
    public function GetdaList($param_da_ProjectPID_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $result = array();

        $last_sql_command_for_mtooldb = 'select da.ProjectPID, da.PID, da.name, da.StoreBasePath, da.IsAutoload, da.LastModifiedDT from da' . ' where ' . 'da.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($param_da_ProjectPID_where) . '\'' . ' order by da.name,da.PID';
        $ret = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new daData();
            $thisresult->ProjectPID = $thisline[0];
            $thisresult->PID = $thisline[1];
            $thisresult->name = $thisline[2];
            $thisresult->StoreBasePath = $thisline[3];
            $thisresult->IsAutoload = $thisline[4];
            $thisresult->LastModifiedDT = $thisline[5];
            array_push($result, $thisresult);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=SELECTSINGLE order=43 generation=canonical-sql
    public function Getda($param_da_PID_where, $param_da_ProjectPID_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'select da.ProjectPID, da.PID, da.name, da.StoreBasePath, da.IsAutoload, da.LastModifiedDT from da' . ' where ' . 'da.PID = ' . '\'' . $mtooldb->real_escape_string($param_da_PID_where) . '\'' . ' and ' . 'da.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($param_da_ProjectPID_where) . '\'';
        $ret = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new daData();
            $thisresult->ProjectPID = $thisline[0];
            $thisresult->PID = $thisline[1];
            $thisresult->name = $thisline[2];
            $thisresult->StoreBasePath = $thisline[3];
            $thisresult->IsAutoload = $thisline[4];
            $thisresult->LastModifiedDT = $thisline[5];
            return $thisresult;
        }
        return NULL;
    }

    // source_of_truth=sync-bootstrap action_type=SELECTSINGLE order=70 generation=canonical-sql
    public function GetdaByName($param_da_ProjectPID_where, $param_da_name_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'select da.ProjectPID, da.PID, da.name, da.StoreBasePath, da.IsAutoload, da.LastModifiedDT from da' . ' where ' . 'da.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($param_da_ProjectPID_where) . '\'' . ' and ' . 'da.name = ' . '\'' . $mtooldb->real_escape_string($param_da_name_where) . '\'';
        $ret = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new daData();
            $thisresult->ProjectPID = $thisline[0];
            $thisresult->PID = $thisline[1];
            $thisresult->name = $thisline[2];
            $thisresult->StoreBasePath = $thisline[3];
            $thisresult->IsAutoload = $thisline[4];
            $thisresult->LastModifiedDT = $thisline[5];
            return $thisresult;
        }
        return NULL;
    }

    // source_of_truth=sync-bootstrap action_type=INSERT order=97 generation=canonical-sql
    public function Insertda($daObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'insert into da (ProjectPID, name, StoreBasePath, IsAutoload) values(' . '\'' . $mtooldb->real_escape_string($daObj->ProjectPID) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($daObj->name) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($daObj->StoreBasePath) . '\'' . ', ' . '\'' . $mtooldb->real_escape_string($daObj->IsAutoload) . '\'' . ')';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=UPDATE order=113 generation=canonical-sql
    public function Updateda($daObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'update da SET ' . 'name = ' . '\'' . $mtooldb->real_escape_string($daObj->name) . '\'' . ', ' . 'StoreBasePath = ' . '\'' . $mtooldb->real_escape_string($daObj->StoreBasePath) . '\'' . ', ' . 'IsAutoload = ' . '\'' . $mtooldb->real_escape_string($daObj->IsAutoload) . '\'' . ', ' . 'LastModifiedDT = ' . 'now()' . ' where ' . 'da.PID = ' . '\'' . $mtooldb->real_escape_string($daObj->PID) . '\'' . ' and ' . 'da.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($daObj->ProjectPID) . '\'';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=UPDATE order=129 generation=canonical-sql
    public function UpdateLastModifiedDT($param_da_PID_where, $param_da_ProjectPID_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'update da SET ' . 'LastModifiedDT = ' . 'now()' . ' where ' . 'da.PID = ' . '\'' . $mtooldb->real_escape_string($param_da_PID_where) . '\'' . ' and ' . 'da.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($param_da_ProjectPID_where) . '\'';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }

    // source_of_truth=sync-bootstrap action_type=DELETE order=145 generation=canonical-sql
    public function Deleteda($param_da_PID_where, $param_da_ProjectPID_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'delete from da where ' . 'da.PID = ' . '\'' . $mtooldb->real_escape_string($param_da_PID_where) . '\'' . ' and ' . 'da.ProjectPID = ' . '\'' . $mtooldb->real_escape_string($param_da_ProjectPID_where) . '\'';
        $result = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }
}

?>