<?php

// AUTO-GENERATED BASE FILE.
// Do not edit this file manually or with AI/Codex.
// Keep customizations in the wrapper class and use this base file exactly as regenerated by the tool.

// Generated from canonical DataClass metadata.
// Base DTO generated from DataClass / DataClass fields.

class {{CLASS_SIGNATURE}}
{
{{DECLARED_PROPERTIES_SECTION}}    public function __construct()
    {
    }
}

?>
