<?php

// AUTO-GENERATED BASE FILE.
// Do not edit this file manually or with AI/Codex.
// Keep customizations in the wrapper class and use this base file exactly as regenerated by the tool.

// Generated from canonical data class metadata.
// Base DTO generated from dataclass / dataclassfields.

class ArticleJsonModelDataBase
{
    public $Id;
    public $JsonAuthorId;
    public $JsonCategoryId;
    public $Title;
    public $Slug;
    public $Status;
    public $PublishedAt;
    public $Body;

    public function __construct()
    {
    }
}

?>