
__INCLUDE_PROXY_REQUEST_PARAMS_HEADER__

// == START OF EDITABLE AREA FOR ABOVE ==
// == END OF EDITABLE AREA FOR ABOVE ==

// THIS CLASS WAS AUTOMATICALLY CREATED BY MTOOL. DON'T EDIT EXCEPT THE EDITABLE AREA.
// [JP] このクラスは自動生成されています。編集可能領域以外は変更しないで下さい。

@implementation __CLASS_BASE_NAME__Proxy__FUNCTION_NAME__RequestParams__CLASS_NAME_SUFFIX__

- (id) init
{
    self = [super init];
    if (self != nil) {
__INITIALIZE_PROPERTY__
        // == START OF EDITABLE AREA FOR INIT ==
        // == END OF EDITABLE AREA FOR INIT ==
    }
    return self;
}
- (NSDictionary*)Serialize
{
__SERIALIZE__
__SERIALIZE_DEFINE__
    // == START OF EDITABLE AREA FOR SERIALIZE ==
    // == END OF EDITABLE AREA FOR SERIALIZE ==
    return dic;
}

// == START OF EDITABLE AREA FOR ADDITIONAL CLASS IMPLEMENTATION DEFINITION ==
// == END OF EDITABLE AREA FOR ADDITIONAL CLASS IMPLEMENTATION DEFINITION ==

@end

// == START OF EDITABLE AREA FOR BOTTOM ==
// == END OF EDITABLE AREA FOR BOTTOM ==

