<?php

// AUTO-GENERATED BASE FILE.
// Do not edit this file manually or with AI/Codex.
// Keep customizations in the wrapper class and use this base file exactly as regenerated by the tool.

// Generated from canonical data class metadata.
// Base DTO generated from dataclass / dataclassfields.

class NoticeDataBase
{
    public $Id;
    public $Title;
    public $Body;
    public $SortOrder;

    public function __construct()
    {
    }
}

?>