<?php

// AUTO-GENERATED BASE FILE.
// Do not edit this file manually or with AI/Codex.
// Keep customizations in the wrapper class and use this base file exactly as regenerated by the tool.

// Generated from canonical DB Access metadata.
// Base class generated from project_db_access_* metadata.

class BlogPostDBAccessBase
{
    public function __construct()
    {
    }

    // source_of_truth=manual class_source=manual action_type=SELECTLIST order=10 generation=canonical-sql
    public function GetPublishedBlogPostAuthorSummaryList()
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $result = array();

        $last_sql_command_for_mtooldb = 'select BlogPost.Id, BlogPost.Title, BlogAuthor.Id, BlogAuthor.Name from BlogPost join BlogAuthor on BlogPost.BlogAuthorId = BlogAuthor.Id' . ' where ' . 'BlogPost.Status = ' . '\'' . $mtooldb->real_escape_string('published') . '\'' . ' and ' . 'BlogAuthor.IsActive = ' . '1' . ' order by BlogPost.Id asc';
        $ret = $mtooldb->query($last_sql_command_for_mtooldb);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new BlogPostAuthorSummaryData();
            $thisresult->BlogPostId = $thisline[0];
            $thisresult->BlogPostTitle = $thisline[1];
            $thisresult->BlogAuthorId = $thisline[2];
            $thisresult->BlogAuthorName = $thisline[3];
            array_push($result, $thisresult);
        }
        return $result;
    }
}

?>