<?php

// AUTO-GENERATED BASE FILE.
// Do not edit this file manually or with AI/Codex.
// Keep customizations in the wrapper class and use this base file exactly as regenerated by the tool.

// Generated from canonical DB Access metadata.
// Base class generated from project_db_access_* metadata.

require_once __DIR__ . '/../_support/mtool_runtime_db.php';


class TodoItemDBAccessBase
{
    public function __construct()
    {
    }

    // source_of_truth=manual class_source=manual action_type=INSERT order=10 generation=canonical-sql
    public function InsertTodoItem($TodoItemObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'insert into TodoItem (Title, Status, Body) values(?, ?, ?)';
        $result = $mtooldb->execute($last_sql_command_for_mtooldb, [
            $TodoItemObj->Title,
            $TodoItemObj->Status,
            $TodoItemObj->Body,
        ]);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }

    // source_of_truth=manual class_source=manual action_type=UPDATE order=20 generation=canonical-sql
    public function UpdateTodoItem($TodoItemObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'update TodoItem SET Title = ?, Status = ?, Body = ? where TodoItem.Id = ?';
        $result = $mtooldb->execute($last_sql_command_for_mtooldb, [
            $TodoItemObj->Title,
            $TodoItemObj->Status,
            $TodoItemObj->Body,
            $TodoItemObj->Id,
        ]);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }

    // source_of_truth=manual class_source=manual action_type=DELETE order=30 generation=canonical-sql
    public function DeleteTodoItem($TodoItemObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'delete from TodoItem where TodoItem.Id = ?';
        $result = $mtooldb->execute($last_sql_command_for_mtooldb, [
            $TodoItemObj->Id,
        ]);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }
}

?>