name: mtool-sample-sample14-custom-proxy-runtime-sqlite

services:
  web-admin:
    environment:
      APP_WORK_ROOT: /var/www/work/sample-packs/sample14-custom-proxy-runtime-sqlite

  web-lab:
    environment:
      APP_WORK_ROOT: /var/www/work/sample-packs/sample14-custom-proxy-runtime-sqlite
