<?php

declare(strict_types=1);

require_once __DIR__ . '/user_db_contract.php';

function app_user_db_contract_runtime_usage(): string
{
    return <<<'TXT'
usage:
  php mtool/scripts/user_db_contract_runtime_smoke.php --dbaccess-root=PATH --dataclass-root=PATH --dialect=mysql|sqlite|pgsql --output=PATH [--sample=KEY] [--sqlite-path=PATH] [--pretty]

TXT;
}

/**
 * @return array<string,mixed>
 */
function app_user_db_contract_runtime_parse_options(array $argv): array
{
    $options = [
        'pretty' => false,
        'sample' => 'sample10-dbaccess-mini-crud-flow',
    ];
    foreach (array_slice($argv, 1) as $argument) {
        if ($argument === '--pretty') {
            $options['pretty'] = true;
            continue;
        }

        if (str_starts_with($argument, '--') && str_contains($argument, '=')) {
            [$key, $value] = explode('=', substr($argument, 2), 2);
            $options[$key] = $value;
            continue;
        }

        throw new InvalidArgumentException('unsupported argument: ' . $argument);
    }

    return $options;
}

/**
 * @return array<string,mixed>
 */
function app_user_db_contract_runtime_sample_definition(string $sample): array
{
    if ($sample === 'sample10-dbaccess-mini-crud-flow') {
        return app_user_db_contract_runtime_sample10_definition();
    }

    if ($sample === 'sample18-mini-task-board-demo') {
        return app_user_db_contract_runtime_sample18_definition();
    }

    if ($sample === 'sample19-json-first-content-model-demo') {
        return app_user_db_contract_runtime_sample19_definition();
    }

    if ($sample === 'sample21-ebook-catalog-api-demo') {
        return app_user_db_contract_runtime_sample21_definition();
    }

    if ($sample === 'sample22-ebook-chapter-workflow-demo') {
        return app_user_db_contract_runtime_sample22_definition();
    }

    if ($sample === 'sample23-ebook-media-metadata-demo') {
        return app_user_db_contract_runtime_sample23_definition();
    }

    if ($sample === 'sample24-ebook-public-reader-site-demo') {
        return app_user_db_contract_runtime_sample24_definition();
    }

    if ($sample === 'sample25-ebook-editor-auth-cms-demo') {
        return app_user_db_contract_runtime_sample25_definition();
    }

    if ($sample === 'sample26-ebook-headless-cms-capstone') {
        return app_user_db_contract_runtime_sample26_definition();
    }

    if ($sample === 'sample06-dbaccess-filter-sort-page') {
        return app_user_db_contract_runtime_sample06_definition();
    }

    if ($sample === 'sample08-dbaccess-join-read-model') {
        return app_user_db_contract_runtime_sample08_definition();
    }

    if ($sample === 'sample09-dbaccess-aggregate-report') {
        return app_user_db_contract_runtime_sample09_definition();
    }

    throw new InvalidArgumentException('unsupported runtime contract sample: ' . $sample);
}

/**
 * @return array<string,mixed>
 */
function app_user_db_contract_runtime_sample18_definition(): array
{
    return [
        'sample' => 'sample18-mini-task-board-demo',
        'dataclass_files' => [
            'data-TaskCard.php',
        ],
        'dbaccess_files' => [
            'dbaccess-TaskCard.php',
        ],
        'fixture_sql' => [
            'mysql' => [
                'DROP TABLE IF EXISTS TaskCard',
                "CREATE TABLE TaskCard (
                    Id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
                    Title VARCHAR(255) NOT NULL,
                    Body TEXT NOT NULL,
                    Status VARCHAR(20) NOT NULL DEFAULT 'todo',
                    AssignedTo VARCHAR(255) NULL,
                    Priority INT NOT NULL DEFAULT 0,
                    DueDate DATE NULL,
                    CompletedAt DATETIME NULL,
                    UpdatedAt DATETIME NOT NULL
                )",
                "INSERT INTO TaskCard (Id, Title, Body, Status, AssignedTo, Priority, DueDate, CompletedAt, UpdatedAt) VALUES
                    (1, 'Draft PostgreSQL card', 'First task body', 'todo', 'alice', 3, '2026-06-22', NULL, '2026-06-20 09:00:00'),
                    (2, 'Review generated names', 'Second task body', 'doing', 'bob', 5, '2026-06-21', NULL, '2026-06-20 10:00:00'),
                    (3, 'Done reference task', 'Closed task body', 'done', 'carol', 1, '2026-06-19', '2026-06-20 11:00:00', '2026-06-20 11:00:00')",
            ],
            'pgsql' => [
                'DROP TABLE IF EXISTS TaskCard',
                "CREATE TABLE TaskCard (
                    Id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    Title VARCHAR(255) NOT NULL,
                    Body TEXT NOT NULL,
                    Status VARCHAR(20) NOT NULL DEFAULT 'todo',
                    AssignedTo VARCHAR(255) NULL,
                    Priority INTEGER NOT NULL DEFAULT 0,
                    DueDate DATE NULL,
                    CompletedAt TIMESTAMP NULL,
                    UpdatedAt TIMESTAMP NOT NULL
                )",
                "INSERT INTO TaskCard (Id, Title, Body, Status, AssignedTo, Priority, DueDate, CompletedAt, UpdatedAt) VALUES
                    (1, 'Draft PostgreSQL card', 'First task body', 'todo', 'alice', 3, '2026-06-22', NULL, '2026-06-20 09:00:00'),
                    (2, 'Review generated names', 'Second task body', 'doing', 'bob', 5, '2026-06-21', NULL, '2026-06-20 10:00:00'),
                    (3, 'Done reference task', 'Closed task body', 'done', 'carol', 1, '2026-06-19', '2026-06-20 11:00:00', '2026-06-20 11:00:00')",
                'ALTER TABLE TaskCard ALTER COLUMN Id RESTART WITH 4',
            ],
            'sqlite' => [
                'DROP TABLE IF EXISTS TaskCard',
                "CREATE TABLE TaskCard (
                    Id INTEGER PRIMARY KEY AUTOINCREMENT,
                    Title TEXT NOT NULL,
                    Body TEXT NOT NULL,
                    Status TEXT NOT NULL DEFAULT 'todo',
                    AssignedTo TEXT NULL,
                    Priority INTEGER NOT NULL DEFAULT 0,
                    DueDate TEXT NULL,
                    CompletedAt TEXT NULL,
                    UpdatedAt TEXT NOT NULL
                )",
                "INSERT INTO TaskCard (Id, Title, Body, Status, AssignedTo, Priority, DueDate, CompletedAt, UpdatedAt) VALUES
                    (1, 'Draft PostgreSQL card', 'First task body', 'todo', 'alice', 3, '2026-06-22', NULL, '2026-06-20 09:00:00'),
                    (2, 'Review generated names', 'Second task body', 'doing', 'bob', 5, '2026-06-21', NULL, '2026-06-20 10:00:00'),
                    (3, 'Done reference task', 'Closed task body', 'done', 'carol', 1, '2026-06-19', '2026-06-20 11:00:00', '2026-06-20 11:00:00')",
            ],
        ],
        'runner' => 'app_user_db_contract_runtime_run_sample18',
    ];
}

/**
 * @return array<string,mixed>
 */
function app_user_db_contract_runtime_sample21_definition(): array
{
    $commonRows = "INSERT INTO EbookCatalogItem
        (BookId, BookTitle, BookSlug, SeriesName, AuthorName, AuthorSlug, GenreName, GenreSlug, SeriesSlug, PublishedAt, Summary, EpubStatus, PrimaryEpubUrl, Status)
        VALUES
        (1, 'First Ebook', 'first-ebook', 'Starter Series', 'Aki Author', 'aki-author', 'Guides', 'guides', 'starter-series', '2026-06-20 09:00:00', 'First summary', 'ready', '/ebooks/first.epub', 'published'),
        (2, 'Second Ebook', 'second-ebook', 'Starter Series', 'Aki Author', 'aki-author', 'Guides', 'guides', 'starter-series', '2026-06-21 09:00:00', 'Second summary', 'ready', '/ebooks/second.epub', 'published'),
        (3, 'Draft Ebook', 'draft-ebook', 'Draft Series', 'Mika Draft', 'mika-draft', 'Drafts', 'drafts', 'draft-series', NULL, 'Draft summary', 'draft', NULL, 'draft')";

    return [
        'sample' => 'sample21-ebook-catalog-api-demo',
        'dataclass_files' => [
            'data-EbookCatalogItem.php',
        ],
        'dbaccess_files' => [
            'dbaccess-EbookCatalogItem.php',
        ],
        'fixture_sql' => [
            'mysql' => [
                'DROP TABLE IF EXISTS EbookCatalogItem',
                "CREATE TABLE EbookCatalogItem (
                    BookId BIGINT NOT NULL PRIMARY KEY,
                    BookTitle VARCHAR(255) NOT NULL,
                    BookSlug VARCHAR(191) NOT NULL,
                    SeriesName VARCHAR(255) NOT NULL,
                    AuthorName VARCHAR(255) NOT NULL,
                    AuthorSlug VARCHAR(191) NOT NULL,
                    GenreName VARCHAR(255) NOT NULL,
                    GenreSlug VARCHAR(191) NOT NULL,
                    SeriesSlug VARCHAR(191) NOT NULL,
                    PublishedAt DATETIME NULL,
                    Summary TEXT NOT NULL,
                    EpubStatus VARCHAR(32) NOT NULL,
                    PrimaryEpubUrl VARCHAR(255) NULL,
                    Status VARCHAR(32) NOT NULL
                )",
                $commonRows,
            ],
            'pgsql' => [
                'DROP TABLE IF EXISTS EbookCatalogItem',
                "CREATE TABLE EbookCatalogItem (
                    BookId BIGINT NOT NULL PRIMARY KEY,
                    BookTitle VARCHAR(255) NOT NULL,
                    BookSlug VARCHAR(191) NOT NULL,
                    SeriesName VARCHAR(255) NOT NULL,
                    AuthorName VARCHAR(255) NOT NULL,
                    AuthorSlug VARCHAR(191) NOT NULL,
                    GenreName VARCHAR(255) NOT NULL,
                    GenreSlug VARCHAR(191) NOT NULL,
                    SeriesSlug VARCHAR(191) NOT NULL,
                    PublishedAt TIMESTAMP NULL,
                    Summary TEXT NOT NULL,
                    EpubStatus VARCHAR(32) NOT NULL,
                    PrimaryEpubUrl VARCHAR(255) NULL,
                    Status VARCHAR(32) NOT NULL
                )",
                $commonRows,
            ],
            'sqlite' => [
                'DROP TABLE IF EXISTS EbookCatalogItem',
                "CREATE TABLE EbookCatalogItem (
                    BookId INTEGER NOT NULL PRIMARY KEY,
                    BookTitle TEXT NOT NULL,
                    BookSlug TEXT NOT NULL,
                    SeriesName TEXT NOT NULL,
                    AuthorName TEXT NOT NULL,
                    AuthorSlug TEXT NOT NULL,
                    GenreName TEXT NOT NULL,
                    GenreSlug TEXT NOT NULL,
                    SeriesSlug TEXT NOT NULL,
                    PublishedAt TEXT NULL,
                    Summary TEXT NOT NULL,
                    EpubStatus TEXT NOT NULL,
                    PrimaryEpubUrl TEXT NULL,
                    Status TEXT NOT NULL
                )",
                $commonRows,
            ],
        ],
        'runner' => 'app_user_db_contract_runtime_run_sample21',
    ];
}

/**
 * @return array<string,mixed>
 */
function app_user_db_contract_runtime_sample22_definition(): array
{
    $publishedRows = "INSERT INTO EbookWorkflowPublishedChapter
        (ChapterId, BookId, BookSlug, ChapterTitle, ChapterSlug, SpineOrder, NavLabel, EpubResourcePath, BodyMarkdown, Status)
        VALUES
        (1, 1, 'workflow-book', 'Opening', 'opening', 1, 'Opening', 'chapters/opening.xhtml', '# Opening', 'published'),
        (2, 1, 'workflow-book', 'Middle', 'middle', 2, 'Middle', 'chapters/middle.xhtml', '# Middle', 'published'),
        (3, 1, 'workflow-book', 'Draft Hidden', 'draft-hidden', 3, 'Draft', 'chapters/draft.xhtml', '# Draft', 'draft')";
    $chapterRows = "INSERT INTO EbookWorkflowChapter
        (Id, EbookWorkflowBookId, ChapterTitle, ChapterSlug, Status, SpineOrder, NavLabel, EpubResourcePath, BodyMarkdown, PublishedAt, UpdatedAt)
        VALUES
        (1, 1, 'Opening', 'opening', 'published', 1, 'Opening', 'chapters/opening.xhtml', '# Opening', '2026-06-20 09:00:00', '2026-06-20 09:00:00'),
        (2, 1, 'Draft Chapter', 'draft-chapter', 'draft', 2, 'Draft', 'chapters/draft.xhtml', '# Draft', NULL, '2026-06-20 10:00:00')";

    return [
        'sample' => 'sample22-ebook-chapter-workflow-demo',
        'dataclass_files' => [
            'data-EbookWorkflowChapter.php',
            'data-EbookWorkflowPublishedChapter.php',
        ],
        'dbaccess_files' => [
            'dbaccess-EbookWorkflowChapter.php',
        ],
        'fixture_sql' => [
            'mysql' => [
                'DROP TABLE IF EXISTS EbookWorkflowPublishedChapter',
                'DROP TABLE IF EXISTS EbookWorkflowChapter',
                "CREATE TABLE EbookWorkflowPublishedChapter (
                    ChapterId BIGINT NOT NULL PRIMARY KEY,
                    BookId BIGINT NOT NULL,
                    BookSlug VARCHAR(191) NOT NULL,
                    ChapterTitle VARCHAR(255) NOT NULL,
                    ChapterSlug VARCHAR(191) NOT NULL,
                    SpineOrder INT NOT NULL,
                    NavLabel VARCHAR(255) NOT NULL,
                    EpubResourcePath VARCHAR(255) NOT NULL,
                    BodyMarkdown TEXT NOT NULL,
                    Status VARCHAR(32) NOT NULL
                )",
                "CREATE TABLE EbookWorkflowChapter (
                    Id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
                    EbookWorkflowBookId BIGINT NOT NULL,
                    ChapterTitle VARCHAR(255) NOT NULL,
                    ChapterSlug VARCHAR(191) NOT NULL,
                    Status VARCHAR(32) NOT NULL,
                    SpineOrder INT NOT NULL,
                    NavLabel VARCHAR(255) NOT NULL,
                    EpubResourcePath VARCHAR(255) NOT NULL,
                    BodyMarkdown TEXT NOT NULL,
                    PublishedAt DATETIME NULL,
                    UpdatedAt DATETIME NOT NULL
                )",
                $publishedRows,
                $chapterRows,
            ],
            'pgsql' => [
                'DROP TABLE IF EXISTS EbookWorkflowPublishedChapter',
                'DROP TABLE IF EXISTS EbookWorkflowChapter',
                "CREATE TABLE EbookWorkflowPublishedChapter (
                    ChapterId BIGINT NOT NULL PRIMARY KEY,
                    BookId BIGINT NOT NULL,
                    BookSlug VARCHAR(191) NOT NULL,
                    ChapterTitle VARCHAR(255) NOT NULL,
                    ChapterSlug VARCHAR(191) NOT NULL,
                    SpineOrder INTEGER NOT NULL,
                    NavLabel VARCHAR(255) NOT NULL,
                    EpubResourcePath VARCHAR(255) NOT NULL,
                    BodyMarkdown TEXT NOT NULL,
                    Status VARCHAR(32) NOT NULL
                )",
                "CREATE TABLE EbookWorkflowChapter (
                    Id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    EbookWorkflowBookId BIGINT NOT NULL,
                    ChapterTitle VARCHAR(255) NOT NULL,
                    ChapterSlug VARCHAR(191) NOT NULL,
                    Status VARCHAR(32) NOT NULL,
                    SpineOrder INTEGER NOT NULL,
                    NavLabel VARCHAR(255) NOT NULL,
                    EpubResourcePath VARCHAR(255) NOT NULL,
                    BodyMarkdown TEXT NOT NULL,
                    PublishedAt TIMESTAMP NULL,
                    UpdatedAt TIMESTAMP NOT NULL
                )",
                $publishedRows,
                $chapterRows,
                'ALTER TABLE EbookWorkflowChapter ALTER COLUMN Id RESTART WITH 3',
            ],
            'sqlite' => [
                'DROP TABLE IF EXISTS EbookWorkflowPublishedChapter',
                'DROP TABLE IF EXISTS EbookWorkflowChapter',
                "CREATE TABLE EbookWorkflowPublishedChapter (
                    ChapterId INTEGER NOT NULL PRIMARY KEY,
                    BookId INTEGER NOT NULL,
                    BookSlug TEXT NOT NULL,
                    ChapterTitle TEXT NOT NULL,
                    ChapterSlug TEXT NOT NULL,
                    SpineOrder INTEGER NOT NULL,
                    NavLabel TEXT NOT NULL,
                    EpubResourcePath TEXT NOT NULL,
                    BodyMarkdown TEXT NOT NULL,
                    Status TEXT NOT NULL
                )",
                "CREATE TABLE EbookWorkflowChapter (
                    Id INTEGER PRIMARY KEY AUTOINCREMENT,
                    EbookWorkflowBookId INTEGER NOT NULL,
                    ChapterTitle TEXT NOT NULL,
                    ChapterSlug TEXT NOT NULL,
                    Status TEXT NOT NULL,
                    SpineOrder INTEGER NOT NULL,
                    NavLabel TEXT NOT NULL,
                    EpubResourcePath TEXT NOT NULL,
                    BodyMarkdown TEXT NOT NULL,
                    PublishedAt TEXT NULL,
                    UpdatedAt TEXT NOT NULL
                )",
                $publishedRows,
                $chapterRows,
            ],
        ],
        'runner' => 'app_user_db_contract_runtime_run_sample22',
    ];
}

/**
 * @return array<string,mixed>
 */
function app_user_db_contract_runtime_sample23_definition(): array
{
    $deliveryRows = "INSERT INTO EbookMediaDelivery
        (DeliveryId, BookId, BookSlug, AssetId, AssetSlug, AssetKind, DisplayRole, DisplayName, PublicUrl, MimeType, FileSizeBytes, Sha256, VersionLabel, SortOrder, IsPrimaryAsset, Status)
        VALUES
        (1, 1, 'media-book', 1, 'cover-image', 'image', 'cover', 'Cover Image', '/media/cover.jpg', 'image/jpeg', 1200, 'sha-cover', 'v1', 1, 1, 'published'),
        (2, 1, 'media-book', 2, 'epub-file', 'epub', 'download', 'EPUB File', '/media/book.epub', 'application/epub+zip', 3400, 'sha-epub', 'v1', 2, 0, 'published')";
    $assetRows = "INSERT INTO EbookMediaAsset
        (Id, AssetSlug, AssetKind, DisplayName, PublicUrl, StoragePath, MimeType, FileSizeBytes, Sha256, VersionLabel, Status, UpdatedAt)
        VALUES
        (1, 'cover-image', 'image', 'Cover Image', '/media/cover.jpg', '/storage/cover.jpg', 'image/jpeg', 1200, 'sha-cover', 'v1', 'published', '2026-06-20 09:00:00')";

    return [
        'sample' => 'sample23-ebook-media-metadata-demo',
        'dataclass_files' => [
            'data-EbookMediaAsset.php',
            'data-EbookMediaDelivery.php',
        ],
        'dbaccess_files' => [
            'dbaccess-EbookMediaAsset.php',
        ],
        'fixture_sql' => [
            'mysql' => [
                'DROP TABLE IF EXISTS EbookMediaDelivery',
                'DROP TABLE IF EXISTS EbookMediaAsset',
                "CREATE TABLE EbookMediaDelivery (
                    DeliveryId BIGINT NOT NULL PRIMARY KEY,
                    BookId BIGINT NOT NULL,
                    BookSlug VARCHAR(191) NOT NULL,
                    AssetId BIGINT NOT NULL,
                    AssetSlug VARCHAR(191) NOT NULL,
                    AssetKind VARCHAR(32) NOT NULL,
                    DisplayRole VARCHAR(64) NOT NULL,
                    DisplayName VARCHAR(255) NOT NULL,
                    PublicUrl VARCHAR(255) NOT NULL,
                    MimeType VARCHAR(128) NOT NULL,
                    FileSizeBytes BIGINT NOT NULL,
                    Sha256 VARCHAR(128) NOT NULL,
                    VersionLabel VARCHAR(64) NOT NULL,
                    SortOrder INT NOT NULL,
                    IsPrimaryAsset INT NOT NULL,
                    Status VARCHAR(32) NOT NULL
                )",
                "CREATE TABLE EbookMediaAsset (
                    Id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
                    AssetSlug VARCHAR(191) NOT NULL,
                    AssetKind VARCHAR(32) NOT NULL,
                    DisplayName VARCHAR(255) NOT NULL,
                    PublicUrl VARCHAR(255) NOT NULL,
                    StoragePath VARCHAR(255) NOT NULL,
                    MimeType VARCHAR(128) NOT NULL,
                    FileSizeBytes BIGINT NOT NULL,
                    Sha256 VARCHAR(128) NOT NULL,
                    VersionLabel VARCHAR(64) NOT NULL,
                    Status VARCHAR(32) NOT NULL,
                    UpdatedAt DATETIME NOT NULL
                )",
                $deliveryRows,
                $assetRows,
            ],
            'pgsql' => [
                'DROP TABLE IF EXISTS EbookMediaDelivery',
                'DROP TABLE IF EXISTS EbookMediaAsset',
                "CREATE TABLE EbookMediaDelivery (
                    DeliveryId BIGINT NOT NULL PRIMARY KEY,
                    BookId BIGINT NOT NULL,
                    BookSlug VARCHAR(191) NOT NULL,
                    AssetId BIGINT NOT NULL,
                    AssetSlug VARCHAR(191) NOT NULL,
                    AssetKind VARCHAR(32) NOT NULL,
                    DisplayRole VARCHAR(64) NOT NULL,
                    DisplayName VARCHAR(255) NOT NULL,
                    PublicUrl VARCHAR(255) NOT NULL,
                    MimeType VARCHAR(128) NOT NULL,
                    FileSizeBytes BIGINT NOT NULL,
                    Sha256 VARCHAR(128) NOT NULL,
                    VersionLabel VARCHAR(64) NOT NULL,
                    SortOrder INTEGER NOT NULL,
                    IsPrimaryAsset INTEGER NOT NULL,
                    Status VARCHAR(32) NOT NULL
                )",
                "CREATE TABLE EbookMediaAsset (
                    Id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    AssetSlug VARCHAR(191) NOT NULL,
                    AssetKind VARCHAR(32) NOT NULL,
                    DisplayName VARCHAR(255) NOT NULL,
                    PublicUrl VARCHAR(255) NOT NULL,
                    StoragePath VARCHAR(255) NOT NULL,
                    MimeType VARCHAR(128) NOT NULL,
                    FileSizeBytes BIGINT NOT NULL,
                    Sha256 VARCHAR(128) NOT NULL,
                    VersionLabel VARCHAR(64) NOT NULL,
                    Status VARCHAR(32) NOT NULL,
                    UpdatedAt TIMESTAMP NOT NULL
                )",
                $deliveryRows,
                $assetRows,
                'ALTER TABLE EbookMediaAsset ALTER COLUMN Id RESTART WITH 2',
            ],
            'sqlite' => [
                'DROP TABLE IF EXISTS EbookMediaDelivery',
                'DROP TABLE IF EXISTS EbookMediaAsset',
                "CREATE TABLE EbookMediaDelivery (
                    DeliveryId INTEGER NOT NULL PRIMARY KEY,
                    BookId INTEGER NOT NULL,
                    BookSlug TEXT NOT NULL,
                    AssetId INTEGER NOT NULL,
                    AssetSlug TEXT NOT NULL,
                    AssetKind TEXT NOT NULL,
                    DisplayRole TEXT NOT NULL,
                    DisplayName TEXT NOT NULL,
                    PublicUrl TEXT NOT NULL,
                    MimeType TEXT NOT NULL,
                    FileSizeBytes INTEGER NOT NULL,
                    Sha256 TEXT NOT NULL,
                    VersionLabel TEXT NOT NULL,
                    SortOrder INTEGER NOT NULL,
                    IsPrimaryAsset INTEGER NOT NULL,
                    Status TEXT NOT NULL
                )",
                "CREATE TABLE EbookMediaAsset (
                    Id INTEGER PRIMARY KEY AUTOINCREMENT,
                    AssetSlug TEXT NOT NULL,
                    AssetKind TEXT NOT NULL,
                    DisplayName TEXT NOT NULL,
                    PublicUrl TEXT NOT NULL,
                    StoragePath TEXT NOT NULL,
                    MimeType TEXT NOT NULL,
                    FileSizeBytes INTEGER NOT NULL,
                    Sha256 TEXT NOT NULL,
                    VersionLabel TEXT NOT NULL,
                    Status TEXT NOT NULL,
                    UpdatedAt TEXT NOT NULL
                )",
                $deliveryRows,
                $assetRows,
            ],
        ],
        'runner' => 'app_user_db_contract_runtime_run_sample23',
    ];
}

/**
 * @return array<string,mixed>
 */
function app_user_db_contract_runtime_sample24_definition(): array
{
    $bookRows = "INSERT INTO EbookReaderBook (Id, Title, Slug, AuthorName, GenreName, Summary, Status, PublishedAt) VALUES
        (1, 'Reader Book', 'reader-book', 'Aki Reader', 'Guides', 'Reader summary', 'published', '2026-06-20 09:00:00'),
        (2, 'Draft Reader Book', 'draft-reader-book', 'Mika Draft', 'Drafts', 'Draft summary', 'draft', NULL)";
    $chapterRows = "INSERT INTO EbookReaderChapter (Id, BookSlug, ChapterTitle, ChapterSlug, SpineOrder, BodyMarkdown, Status) VALUES
        (1, 'reader-book', 'Opening', 'opening', 1, '# Opening', 'published'),
        (2, 'reader-book', 'Second', 'second', 2, '# Second', 'published')";
    $deliveryRows = "INSERT INTO EbookReaderMediaDelivery (Id, BookSlug, AssetSlug, AssetKind, DisplayName, PublicUrl, MimeType, FileSizeBytes, Sha256, VersionLabel, Status) VALUES
        (1, 'reader-book', 'reader-epub', 'epub', 'Reader EPUB', '/reader/book.epub', 'application/epub+zip', 4500, 'sha-reader', 'v1', 'published')";

    return [
        'sample' => 'sample24-ebook-public-reader-site-demo',
        'dataclass_files' => [
            'data-EbookReaderBook.php',
            'data-EbookReaderChapter.php',
            'data-EbookReaderMediaDelivery.php',
        ],
        'dbaccess_files' => [
            'dbaccess-EbookReaderBook.php',
        ],
        'fixture_sql' => [
            'mysql' => [
                'DROP TABLE IF EXISTS EbookReaderMediaDelivery',
                'DROP TABLE IF EXISTS EbookReaderChapter',
                'DROP TABLE IF EXISTS EbookReaderBook',
                "CREATE TABLE EbookReaderBook (
                    Id BIGINT NOT NULL PRIMARY KEY,
                    Title VARCHAR(255) NOT NULL,
                    Slug VARCHAR(191) NOT NULL,
                    AuthorName VARCHAR(255) NOT NULL,
                    GenreName VARCHAR(255) NOT NULL,
                    Summary TEXT NOT NULL,
                    Status VARCHAR(32) NOT NULL,
                    PublishedAt DATETIME NULL
                )",
                "CREATE TABLE EbookReaderChapter (
                    Id BIGINT NOT NULL PRIMARY KEY,
                    BookSlug VARCHAR(191) NOT NULL,
                    ChapterTitle VARCHAR(255) NOT NULL,
                    ChapterSlug VARCHAR(191) NOT NULL,
                    SpineOrder INT NOT NULL,
                    BodyMarkdown TEXT NOT NULL,
                    Status VARCHAR(32) NOT NULL
                )",
                "CREATE TABLE EbookReaderMediaDelivery (
                    Id BIGINT NOT NULL PRIMARY KEY,
                    BookSlug VARCHAR(191) NOT NULL,
                    AssetSlug VARCHAR(191) NOT NULL,
                    AssetKind VARCHAR(32) NOT NULL,
                    DisplayName VARCHAR(255) NOT NULL,
                    PublicUrl VARCHAR(255) NOT NULL,
                    MimeType VARCHAR(128) NOT NULL,
                    FileSizeBytes BIGINT NOT NULL,
                    Sha256 VARCHAR(128) NOT NULL,
                    VersionLabel VARCHAR(64) NOT NULL,
                    Status VARCHAR(32) NOT NULL
                )",
                $bookRows,
                $chapterRows,
                $deliveryRows,
            ],
            'pgsql' => [
                'DROP TABLE IF EXISTS EbookReaderMediaDelivery',
                'DROP TABLE IF EXISTS EbookReaderChapter',
                'DROP TABLE IF EXISTS EbookReaderBook',
                "CREATE TABLE EbookReaderBook (
                    Id BIGINT NOT NULL PRIMARY KEY,
                    Title VARCHAR(255) NOT NULL,
                    Slug VARCHAR(191) NOT NULL,
                    AuthorName VARCHAR(255) NOT NULL,
                    GenreName VARCHAR(255) NOT NULL,
                    Summary TEXT NOT NULL,
                    Status VARCHAR(32) NOT NULL,
                    PublishedAt TIMESTAMP NULL
                )",
                "CREATE TABLE EbookReaderChapter (
                    Id BIGINT NOT NULL PRIMARY KEY,
                    BookSlug VARCHAR(191) NOT NULL,
                    ChapterTitle VARCHAR(255) NOT NULL,
                    ChapterSlug VARCHAR(191) NOT NULL,
                    SpineOrder INTEGER NOT NULL,
                    BodyMarkdown TEXT NOT NULL,
                    Status VARCHAR(32) NOT NULL
                )",
                "CREATE TABLE EbookReaderMediaDelivery (
                    Id BIGINT NOT NULL PRIMARY KEY,
                    BookSlug VARCHAR(191) NOT NULL,
                    AssetSlug VARCHAR(191) NOT NULL,
                    AssetKind VARCHAR(32) NOT NULL,
                    DisplayName VARCHAR(255) NOT NULL,
                    PublicUrl VARCHAR(255) NOT NULL,
                    MimeType VARCHAR(128) NOT NULL,
                    FileSizeBytes BIGINT NOT NULL,
                    Sha256 VARCHAR(128) NOT NULL,
                    VersionLabel VARCHAR(64) NOT NULL,
                    Status VARCHAR(32) NOT NULL
                )",
                $bookRows,
                $chapterRows,
                $deliveryRows,
            ],
            'sqlite' => [
                'DROP TABLE IF EXISTS EbookReaderMediaDelivery',
                'DROP TABLE IF EXISTS EbookReaderChapter',
                'DROP TABLE IF EXISTS EbookReaderBook',
                "CREATE TABLE EbookReaderBook (
                    Id INTEGER NOT NULL PRIMARY KEY,
                    Title TEXT NOT NULL,
                    Slug TEXT NOT NULL,
                    AuthorName TEXT NOT NULL,
                    GenreName TEXT NOT NULL,
                    Summary TEXT NOT NULL,
                    Status TEXT NOT NULL,
                    PublishedAt TEXT NULL
                )",
                "CREATE TABLE EbookReaderChapter (
                    Id INTEGER NOT NULL PRIMARY KEY,
                    BookSlug TEXT NOT NULL,
                    ChapterTitle TEXT NOT NULL,
                    ChapterSlug TEXT NOT NULL,
                    SpineOrder INTEGER NOT NULL,
                    BodyMarkdown TEXT NOT NULL,
                    Status TEXT NOT NULL
                )",
                "CREATE TABLE EbookReaderMediaDelivery (
                    Id INTEGER NOT NULL PRIMARY KEY,
                    BookSlug TEXT NOT NULL,
                    AssetSlug TEXT NOT NULL,
                    AssetKind TEXT NOT NULL,
                    DisplayName TEXT NOT NULL,
                    PublicUrl TEXT NOT NULL,
                    MimeType TEXT NOT NULL,
                    FileSizeBytes INTEGER NOT NULL,
                    Sha256 TEXT NOT NULL,
                    VersionLabel TEXT NOT NULL,
                    Status TEXT NOT NULL
                )",
                $bookRows,
                $chapterRows,
                $deliveryRows,
            ],
        ],
        'runner' => 'app_user_db_contract_runtime_run_sample24',
    ];
}

/**
 * @return array<string,mixed>
 */
function app_user_db_contract_runtime_sample25_definition(): array
{
    $chapterRows = "INSERT INTO EbookEditorChapter
        (Id, EbookEditorBookId, ChapterTitle, ChapterSlug, Status, SpineOrder, BodyMarkdown, PublishedAt, UpdatedAt)
        VALUES
        (1, 1, 'Editor Opening', 'editor-opening', 'draft', 1, '# Draft editor opening', NULL, '2026-06-20 09:00:00'),
        (2, 1, 'Published Editor', 'published-editor', 'published', 2, '# Published editor', '2026-06-20 10:00:00', '2026-06-20 10:00:00')";

    return [
        'sample' => 'sample25-ebook-editor-auth-cms-demo',
        'dataclass_files' => [
            'data-EbookEditorChapter.php',
        ],
        'dbaccess_files' => [
            'dbaccess-EbookEditorChapter.php',
        ],
        'fixture_sql' => [
            'mysql' => [
                'DROP TABLE IF EXISTS EbookEditorChapter',
                "CREATE TABLE EbookEditorChapter (
                    Id BIGINT NOT NULL PRIMARY KEY,
                    EbookEditorBookId BIGINT NOT NULL,
                    ChapterTitle VARCHAR(255) NOT NULL,
                    ChapterSlug VARCHAR(191) NOT NULL,
                    Status VARCHAR(32) NOT NULL,
                    SpineOrder INT NOT NULL,
                    BodyMarkdown TEXT NOT NULL,
                    PublishedAt DATETIME NULL,
                    UpdatedAt DATETIME NOT NULL
                )",
                $chapterRows,
            ],
            'pgsql' => [
                'DROP TABLE IF EXISTS EbookEditorChapter',
                "CREATE TABLE EbookEditorChapter (
                    Id BIGINT NOT NULL PRIMARY KEY,
                    EbookEditorBookId BIGINT NOT NULL,
                    ChapterTitle VARCHAR(255) NOT NULL,
                    ChapterSlug VARCHAR(191) NOT NULL,
                    Status VARCHAR(32) NOT NULL,
                    SpineOrder INTEGER NOT NULL,
                    BodyMarkdown TEXT NOT NULL,
                    PublishedAt TIMESTAMP NULL,
                    UpdatedAt TIMESTAMP NOT NULL
                )",
                $chapterRows,
            ],
            'sqlite' => [
                'DROP TABLE IF EXISTS EbookEditorChapter',
                "CREATE TABLE EbookEditorChapter (
                    Id INTEGER NOT NULL PRIMARY KEY,
                    EbookEditorBookId INTEGER NOT NULL,
                    ChapterTitle TEXT NOT NULL,
                    ChapterSlug TEXT NOT NULL,
                    Status TEXT NOT NULL,
                    SpineOrder INTEGER NOT NULL,
                    BodyMarkdown TEXT NOT NULL,
                    PublishedAt TEXT NULL,
                    UpdatedAt TEXT NOT NULL
                )",
                $chapterRows,
            ],
        ],
        'runner' => 'app_user_db_contract_runtime_run_sample25',
    ];
}

/**
 * @return array<string,mixed>
 */
function app_user_db_contract_runtime_sample26_definition(): array
{
    $bookRows = "INSERT INTO EbookCmsBook
        (Id, Title, Slug, AuthorName, GenreName, CoverImageUrl, Summary, EpubDownloadUrl, EpubMimeType, EpubSha256, Status, PublishedAt)
        VALUES
        (1, 'CMS Book', 'cms-book', 'Aki CMS', 'Guides', '/covers/cms.jpg', 'CMS summary', '/cms/book.epub', 'application/epub+zip', 'sha-cms', 'published', '2026-06-20 09:00:00'),
        (2, 'Draft CMS Book', 'draft-cms-book', 'Mika Draft', 'Drafts', '/covers/draft.jpg', 'Draft summary', NULL, NULL, NULL, 'draft', NULL)";
    $chapterRows = "INSERT INTO EbookCmsChapter
        (Id, EbookCmsBookId, BookSlug, ChapterTitle, ChapterSlug, Status, SpineOrder, BodyMarkdown, PublishedAt, UpdatedAt)
        VALUES
        (1, 1, 'cms-book', 'Opening', 'opening', 'published', 1, '# Opening', '2026-06-20 10:00:00', '2026-06-20 10:00:00'),
        (2, 1, 'cms-book', 'Draft Chapter', 'draft-chapter', 'draft', 2, '# Draft', NULL, '2026-06-20 11:00:00')";

    return [
        'sample' => 'sample26-ebook-headless-cms-capstone',
        'dataclass_files' => [
            'data-EbookCmsBook.php',
            'data-EbookCmsChapter.php',
        ],
        'dbaccess_files' => [
            'dbaccess-EbookCmsBook.php',
        ],
        'fixture_sql' => [
            'mysql' => [
                'DROP TABLE IF EXISTS EbookCmsChapter',
                'DROP TABLE IF EXISTS EbookCmsBook',
                "CREATE TABLE EbookCmsBook (
                    Id BIGINT NOT NULL PRIMARY KEY,
                    Title VARCHAR(255) NOT NULL,
                    Slug VARCHAR(191) NOT NULL,
                    AuthorName VARCHAR(255) NOT NULL,
                    GenreName VARCHAR(255) NOT NULL,
                    CoverImageUrl VARCHAR(255) NOT NULL,
                    Summary TEXT NOT NULL,
                    EpubDownloadUrl VARCHAR(255) NULL,
                    EpubMimeType VARCHAR(128) NULL,
                    EpubSha256 VARCHAR(128) NULL,
                    Status VARCHAR(32) NOT NULL,
                    PublishedAt DATETIME NULL
                )",
                "CREATE TABLE EbookCmsChapter (
                    Id BIGINT NOT NULL PRIMARY KEY,
                    EbookCmsBookId BIGINT NOT NULL,
                    BookSlug VARCHAR(191) NOT NULL,
                    ChapterTitle VARCHAR(255) NOT NULL,
                    ChapterSlug VARCHAR(191) NOT NULL,
                    Status VARCHAR(32) NOT NULL,
                    SpineOrder INT NOT NULL,
                    BodyMarkdown TEXT NOT NULL,
                    PublishedAt DATETIME NULL,
                    UpdatedAt DATETIME NOT NULL
                )",
                $bookRows,
                $chapterRows,
            ],
            'pgsql' => [
                'DROP TABLE IF EXISTS EbookCmsChapter',
                'DROP TABLE IF EXISTS EbookCmsBook',
                "CREATE TABLE EbookCmsBook (
                    Id BIGINT NOT NULL PRIMARY KEY,
                    Title VARCHAR(255) NOT NULL,
                    Slug VARCHAR(191) NOT NULL,
                    AuthorName VARCHAR(255) NOT NULL,
                    GenreName VARCHAR(255) NOT NULL,
                    CoverImageUrl VARCHAR(255) NOT NULL,
                    Summary TEXT NOT NULL,
                    EpubDownloadUrl VARCHAR(255) NULL,
                    EpubMimeType VARCHAR(128) NULL,
                    EpubSha256 VARCHAR(128) NULL,
                    Status VARCHAR(32) NOT NULL,
                    PublishedAt TIMESTAMP NULL
                )",
                "CREATE TABLE EbookCmsChapter (
                    Id BIGINT NOT NULL PRIMARY KEY,
                    EbookCmsBookId BIGINT NOT NULL,
                    BookSlug VARCHAR(191) NOT NULL,
                    ChapterTitle VARCHAR(255) NOT NULL,
                    ChapterSlug VARCHAR(191) NOT NULL,
                    Status VARCHAR(32) NOT NULL,
                    SpineOrder INTEGER NOT NULL,
                    BodyMarkdown TEXT NOT NULL,
                    PublishedAt TIMESTAMP NULL,
                    UpdatedAt TIMESTAMP NOT NULL
                )",
                $bookRows,
                $chapterRows,
            ],
            'sqlite' => [
                'DROP TABLE IF EXISTS EbookCmsChapter',
                'DROP TABLE IF EXISTS EbookCmsBook',
                "CREATE TABLE EbookCmsBook (
                    Id INTEGER NOT NULL PRIMARY KEY,
                    Title TEXT NOT NULL,
                    Slug TEXT NOT NULL,
                    AuthorName TEXT NOT NULL,
                    GenreName TEXT NOT NULL,
                    CoverImageUrl TEXT NOT NULL,
                    Summary TEXT NOT NULL,
                    EpubDownloadUrl TEXT NULL,
                    EpubMimeType TEXT NULL,
                    EpubSha256 TEXT NULL,
                    Status TEXT NOT NULL,
                    PublishedAt TEXT NULL
                )",
                "CREATE TABLE EbookCmsChapter (
                    Id INTEGER NOT NULL PRIMARY KEY,
                    EbookCmsBookId INTEGER NOT NULL,
                    BookSlug TEXT NOT NULL,
                    ChapterTitle TEXT NOT NULL,
                    ChapterSlug TEXT NOT NULL,
                    Status TEXT NOT NULL,
                    SpineOrder INTEGER NOT NULL,
                    BodyMarkdown TEXT NOT NULL,
                    PublishedAt TEXT NULL,
                    UpdatedAt TEXT NOT NULL
                )",
                $bookRows,
                $chapterRows,
            ],
        ],
        'runner' => 'app_user_db_contract_runtime_run_sample26',
    ];
}

/**
 * @return array<string,mixed>
 */
function app_user_db_contract_runtime_sample19_definition(): array
{
    return [
        'sample' => 'sample19-json-first-content-model-demo',
        'dataclass_files' => [
            'data-ArticleJsonModel.php',
            'data-ArticlePublicSummary.php',
            'data-JsonAuthor.php',
            'data-JsonCategory.php',
        ],
        'dbaccess_files' => [
            'dbaccess-ArticleJsonModel.php',
        ],
        'fixture_sql' => [
            'mysql' => [
                'DROP TABLE IF EXISTS ArticleJsonModel',
                'DROP TABLE IF EXISTS JsonAuthor',
                'DROP TABLE IF EXISTS JsonCategory',
                "CREATE TABLE JsonAuthor (
                    Id BIGINT NOT NULL PRIMARY KEY,
                    Name VARCHAR(255) NOT NULL
                )",
                "CREATE TABLE JsonCategory (
                    Id BIGINT NOT NULL PRIMARY KEY,
                    Name VARCHAR(255) NOT NULL
                )",
                "CREATE TABLE ArticleJsonModel (
                    Id BIGINT NOT NULL PRIMARY KEY,
                    JsonAuthorId BIGINT NOT NULL,
                    JsonCategoryId BIGINT NOT NULL,
                    Title VARCHAR(255) NOT NULL,
                    Slug VARCHAR(255) NOT NULL,
                    Status VARCHAR(20) NOT NULL,
                    PublishedAt DATETIME NULL,
                    Body TEXT NOT NULL
                )",
                "INSERT INTO JsonAuthor (Id, Name) VALUES
                    (1, 'Aki JSON'),
                    (2, 'Mika Draft')",
                "INSERT INTO JsonCategory (Id, Name) VALUES
                    (1, 'Guides'),
                    (2, 'Internal')",
                "INSERT INTO ArticleJsonModel (Id, JsonAuthorId, JsonCategoryId, Title, Slug, Status, PublishedAt, Body) VALUES
                    (1, 1, 1, 'JSON-first public article', 'json-first-public', 'published', '2026-06-20 09:00:00', '{\"kind\":\"public\"}'),
                    (2, 2, 2, 'Draft JSON article', 'draft-json', 'draft', NULL, '{\"kind\":\"draft\"}'),
                    (3, 1, 1, 'Second public article', 'second-public', 'published', '2026-06-21 10:00:00', '{\"kind\":\"public\"}')",
            ],
            'pgsql' => [
                'DROP TABLE IF EXISTS ArticleJsonModel',
                'DROP TABLE IF EXISTS JsonAuthor',
                'DROP TABLE IF EXISTS JsonCategory',
                "CREATE TABLE JsonAuthor (
                    Id BIGINT NOT NULL PRIMARY KEY,
                    Name VARCHAR(255) NOT NULL
                )",
                "CREATE TABLE JsonCategory (
                    Id BIGINT NOT NULL PRIMARY KEY,
                    Name VARCHAR(255) NOT NULL
                )",
                "CREATE TABLE ArticleJsonModel (
                    Id BIGINT NOT NULL PRIMARY KEY,
                    JsonAuthorId BIGINT NOT NULL,
                    JsonCategoryId BIGINT NOT NULL,
                    Title VARCHAR(255) NOT NULL,
                    Slug VARCHAR(255) NOT NULL,
                    Status VARCHAR(20) NOT NULL,
                    PublishedAt TIMESTAMP NULL,
                    Body TEXT NOT NULL
                )",
                "INSERT INTO JsonAuthor (Id, Name) VALUES
                    (1, 'Aki JSON'),
                    (2, 'Mika Draft')",
                "INSERT INTO JsonCategory (Id, Name) VALUES
                    (1, 'Guides'),
                    (2, 'Internal')",
                "INSERT INTO ArticleJsonModel (Id, JsonAuthorId, JsonCategoryId, Title, Slug, Status, PublishedAt, Body) VALUES
                    (1, 1, 1, 'JSON-first public article', 'json-first-public', 'published', '2026-06-20 09:00:00', '{\"kind\":\"public\"}'),
                    (2, 2, 2, 'Draft JSON article', 'draft-json', 'draft', NULL, '{\"kind\":\"draft\"}'),
                    (3, 1, 1, 'Second public article', 'second-public', 'published', '2026-06-21 10:00:00', '{\"kind\":\"public\"}')",
            ],
            'sqlite' => [
                'DROP TABLE IF EXISTS ArticleJsonModel',
                'DROP TABLE IF EXISTS JsonAuthor',
                'DROP TABLE IF EXISTS JsonCategory',
                "CREATE TABLE JsonAuthor (
                    Id INTEGER NOT NULL PRIMARY KEY,
                    Name TEXT NOT NULL
                )",
                "CREATE TABLE JsonCategory (
                    Id INTEGER NOT NULL PRIMARY KEY,
                    Name TEXT NOT NULL
                )",
                "CREATE TABLE ArticleJsonModel (
                    Id INTEGER NOT NULL PRIMARY KEY,
                    JsonAuthorId INTEGER NOT NULL,
                    JsonCategoryId INTEGER NOT NULL,
                    Title TEXT NOT NULL,
                    Slug TEXT NOT NULL,
                    Status TEXT NOT NULL,
                    PublishedAt TEXT NULL,
                    Body TEXT NOT NULL
                )",
                "INSERT INTO JsonAuthor (Id, Name) VALUES
                    (1, 'Aki JSON'),
                    (2, 'Mika Draft')",
                "INSERT INTO JsonCategory (Id, Name) VALUES
                    (1, 'Guides'),
                    (2, 'Internal')",
                "INSERT INTO ArticleJsonModel (Id, JsonAuthorId, JsonCategoryId, Title, Slug, Status, PublishedAt, Body) VALUES
                    (1, 1, 1, 'JSON-first public article', 'json-first-public', 'published', '2026-06-20 09:00:00', '{\"kind\":\"public\"}'),
                    (2, 2, 2, 'Draft JSON article', 'draft-json', 'draft', NULL, '{\"kind\":\"draft\"}'),
                    (3, 1, 1, 'Second public article', 'second-public', 'published', '2026-06-21 10:00:00', '{\"kind\":\"public\"}')",
            ],
        ],
        'runner' => 'app_user_db_contract_runtime_run_sample19',
    ];
}

/**
 * @return array<string,mixed>
 */
function app_user_db_contract_runtime_sample06_definition(): array
{
    return [
        'sample' => 'sample06-dbaccess-filter-sort-page',
        'dataclass_files' => [
            'data-Announcement.php',
        ],
        'dbaccess_files' => [
            'dbaccess-Announcement.php',
        ],
        'fixture_sql' => [
            'mysql' => [
                'DROP TABLE IF EXISTS Announcement',
                "CREATE TABLE Announcement (
                    Id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
                    Title VARCHAR(255) NOT NULL,
                    Status VARCHAR(20) NOT NULL DEFAULT 'draft',
                    PublishedAt DATETIME NULL
                )",
                "INSERT INTO Announcement (Id, Title, Status, PublishedAt) VALUES
                    (1, 'Welcome Release', 'published', '2026-05-20 09:00:00'),
                    (2, 'Planned Maintenance', 'draft', NULL),
                    (3, 'May Newsletter', 'published', '2026-05-22 08:30:00'),
                    (4, 'June Newsletter', 'published', '2026-06-01 07:30:00')",
            ],
            'pgsql' => [
                'DROP TABLE IF EXISTS Announcement',
                "CREATE TABLE Announcement (
                    Id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    Title VARCHAR(255) NOT NULL,
                    Status VARCHAR(20) NOT NULL DEFAULT 'draft',
                    PublishedAt TIMESTAMP NULL
                )",
                "INSERT INTO Announcement (Id, Title, Status, PublishedAt) VALUES
                    (1, 'Welcome Release', 'published', '2026-05-20 09:00:00'),
                    (2, 'Planned Maintenance', 'draft', NULL),
                    (3, 'May Newsletter', 'published', '2026-05-22 08:30:00'),
                    (4, 'June Newsletter', 'published', '2026-06-01 07:30:00')",
                'ALTER TABLE Announcement ALTER COLUMN Id RESTART WITH 5',
            ],
            'sqlite' => [
                'DROP TABLE IF EXISTS Announcement',
                "CREATE TABLE Announcement (
                    Id INTEGER PRIMARY KEY AUTOINCREMENT,
                    Title TEXT NOT NULL,
                    Status TEXT NOT NULL DEFAULT 'draft',
                    PublishedAt TEXT NULL
                )",
                "INSERT INTO Announcement (Id, Title, Status, PublishedAt) VALUES
                    (1, 'Welcome Release', 'published', '2026-05-20 09:00:00'),
                    (2, 'Planned Maintenance', 'draft', NULL),
                    (3, 'May Newsletter', 'published', '2026-05-22 08:30:00'),
                    (4, 'June Newsletter', 'published', '2026-06-01 07:30:00')",
            ],
        ],
        'runner' => 'app_user_db_contract_runtime_run_sample06',
    ];
}

/**
 * @return array<string,mixed>
 */
function app_user_db_contract_runtime_sample08_definition(): array
{
    return [
        'sample' => 'sample08-dbaccess-join-read-model',
        'dataclass_files' => [
            'data-BlogAuthor.php',
            'data-BlogPost.php',
            'data-BlogPostAuthorSummary.php',
        ],
        'dbaccess_files' => [
            'dbaccess-BlogPost.php',
        ],
        'fixture_sql' => [
            'mysql' => [
                'DROP TABLE IF EXISTS BlogPostAuthorSummary',
                'DROP TABLE IF EXISTS BlogPost',
                'DROP TABLE IF EXISTS BlogAuthor',
                "CREATE TABLE BlogAuthor (
                    Id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                    Name VARCHAR(255) NOT NULL,
                    IsActive TINYINT(1) NOT NULL DEFAULT 1,
                    PRIMARY KEY (Id)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
                "CREATE TABLE BlogPost (
                    Id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                    BlogAuthorId BIGINT UNSIGNED NOT NULL,
                    Title VARCHAR(255) NOT NULL,
                    Status VARCHAR(20) NOT NULL DEFAULT 'draft',
                    PRIMARY KEY (Id),
                    KEY idx_blog_post_author_id (BlogAuthorId),
                    CONSTRAINT fk_blog_post_author
                        FOREIGN KEY (BlogAuthorId)
                        REFERENCES BlogAuthor (Id)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
                "CREATE TABLE BlogPostAuthorSummary (
                    BlogPostId BIGINT UNSIGNED NOT NULL,
                    BlogPostTitle VARCHAR(255) NOT NULL,
                    BlogAuthorId BIGINT UNSIGNED NOT NULL,
                    BlogAuthorName VARCHAR(255) NOT NULL,
                    PRIMARY KEY (BlogPostId)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
                "INSERT INTO BlogAuthor (Id, Name, IsActive) VALUES
                    (1, 'Alice Editor', 1),
                    (2, 'Bob Archived', 0),
                    (3, 'Carol Writer', 1)",
                "INSERT INTO BlogPost (Id, BlogAuthorId, Title, Status) VALUES
                    (1, 1, 'Canonical Join Tutorial', 'published'),
                    (2, 2, 'Inactive Author Should Not Appear', 'published'),
                    (3, 3, 'Draft Posts Stay Hidden', 'draft'),
                    (4, 3, 'Roadmap Checkpoint', 'published')",
            ],
            'pgsql' => [
                'DROP TABLE IF EXISTS BlogPostAuthorSummary',
                'DROP TABLE IF EXISTS BlogPost',
                'DROP TABLE IF EXISTS BlogAuthor',
                "CREATE TABLE BlogAuthor (
                    Id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    Name VARCHAR(255) NOT NULL,
                    IsActive SMALLINT NOT NULL DEFAULT 1
                )",
                "CREATE TABLE BlogPost (
                    Id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    BlogAuthorId BIGINT NOT NULL REFERENCES BlogAuthor (Id),
                    Title VARCHAR(255) NOT NULL,
                    Status VARCHAR(20) NOT NULL DEFAULT 'draft'
                )",
                "CREATE TABLE BlogPostAuthorSummary (
                    BlogPostId BIGINT NOT NULL PRIMARY KEY,
                    BlogPostTitle VARCHAR(255) NOT NULL,
                    BlogAuthorId BIGINT NOT NULL,
                    BlogAuthorName VARCHAR(255) NOT NULL
                )",
                "INSERT INTO BlogAuthor (Id, Name, IsActive) VALUES
                    (1, 'Alice Editor', 1),
                    (2, 'Bob Archived', 0),
                    (3, 'Carol Writer', 1)",
                "INSERT INTO BlogPost (Id, BlogAuthorId, Title, Status) VALUES
                    (1, 1, 'Canonical Join Tutorial', 'published'),
                    (2, 2, 'Inactive Author Should Not Appear', 'published'),
                    (3, 3, 'Draft Posts Stay Hidden', 'draft'),
                    (4, 3, 'Roadmap Checkpoint', 'published')",
                'ALTER TABLE BlogAuthor ALTER COLUMN Id RESTART WITH 4',
                'ALTER TABLE BlogPost ALTER COLUMN Id RESTART WITH 5',
            ],
            'sqlite' => [
                'DROP TABLE IF EXISTS BlogPostAuthorSummary',
                'DROP TABLE IF EXISTS BlogPost',
                'DROP TABLE IF EXISTS BlogAuthor',
                "CREATE TABLE BlogAuthor (
                    Id INTEGER PRIMARY KEY AUTOINCREMENT,
                    Name TEXT NOT NULL,
                    IsActive INTEGER NOT NULL DEFAULT 1
                )",
                "CREATE TABLE BlogPost (
                    Id INTEGER PRIMARY KEY AUTOINCREMENT,
                    BlogAuthorId INTEGER NOT NULL,
                    Title TEXT NOT NULL,
                    Status TEXT NOT NULL DEFAULT 'draft',
                    FOREIGN KEY (BlogAuthorId) REFERENCES BlogAuthor (Id)
                )",
                "CREATE TABLE BlogPostAuthorSummary (
                    BlogPostId INTEGER NOT NULL PRIMARY KEY,
                    BlogPostTitle TEXT NOT NULL,
                    BlogAuthorId INTEGER NOT NULL,
                    BlogAuthorName TEXT NOT NULL
                )",
                "INSERT INTO BlogAuthor (Id, Name, IsActive) VALUES
                    (1, 'Alice Editor', 1),
                    (2, 'Bob Archived', 0),
                    (3, 'Carol Writer', 1)",
                "INSERT INTO BlogPost (Id, BlogAuthorId, Title, Status) VALUES
                    (1, 1, 'Canonical Join Tutorial', 'published'),
                    (2, 2, 'Inactive Author Should Not Appear', 'published'),
                    (3, 3, 'Draft Posts Stay Hidden', 'draft'),
                    (4, 3, 'Roadmap Checkpoint', 'published')",
            ],
        ],
        'runner' => 'app_user_db_contract_runtime_run_sample08',
    ];
}

/**
 * @return array<string,mixed>
 */
function app_user_db_contract_runtime_sample09_definition(): array
{
    return [
        'sample' => 'sample09-dbaccess-aggregate-report',
        'dataclass_files' => [
            'data-SalesCategory.php',
            'data-SalesRecord.php',
            'data-SalesCategoryReport.php',
        ],
        'dbaccess_files' => [
            'dbaccess-SalesRecord.php',
        ],
        'fixture_sql' => [
            'mysql' => [
                'DROP TABLE IF EXISTS SalesCategoryReport',
                'DROP TABLE IF EXISTS SalesRecord',
                'DROP TABLE IF EXISTS SalesCategory',
                "CREATE TABLE SalesCategory (
                    Id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                    Name VARCHAR(255) NOT NULL,
                    IsActive TINYINT(1) NOT NULL DEFAULT 1,
                    PRIMARY KEY (Id)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
                "CREATE TABLE SalesRecord (
                    Id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                    SalesCategoryId BIGINT UNSIGNED NOT NULL,
                    Title VARCHAR(255) NOT NULL,
                    Status VARCHAR(20) NOT NULL DEFAULT 'open',
                    Amount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
                    PRIMARY KEY (Id),
                    KEY idx_sales_record_category_id (SalesCategoryId),
                    CONSTRAINT fk_sales_record_category
                        FOREIGN KEY (SalesCategoryId)
                        REFERENCES SalesCategory (Id)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
                "CREATE TABLE SalesCategoryReport (
                    SalesCategoryId BIGINT UNSIGNED NOT NULL,
                    SalesCategoryName VARCHAR(255) NOT NULL,
                    ClosedSaleCount INT UNSIGNED NOT NULL,
                    ClosedSaleTotalAmount DECIMAL(10,2) NOT NULL,
                    PRIMARY KEY (SalesCategoryId)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
                "INSERT INTO SalesCategory (Id, Name, IsActive) VALUES
                    (1, 'Hardware', 1),
                    (2, 'Software', 1),
                    (3, 'Legacy', 0)",
                "INSERT INTO SalesRecord (Id, SalesCategoryId, Title, Status, Amount) VALUES
                    (1, 1, 'Keyboard refresh', 'closed', 120.00),
                    (2, 1, 'Mouse replacement', 'closed', 80.00),
                    (3, 2, 'License renewal', 'closed', 40.00),
                    (4, 2, 'Future subscription', 'open', 500.00),
                    (5, 3, 'Unsupported backlog', 'closed', 999.00)",
            ],
            'pgsql' => [
                'DROP TABLE IF EXISTS SalesCategoryReport',
                'DROP TABLE IF EXISTS SalesRecord',
                'DROP TABLE IF EXISTS SalesCategory',
                "CREATE TABLE SalesCategory (
                    Id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    Name VARCHAR(255) NOT NULL,
                    IsActive SMALLINT NOT NULL DEFAULT 1
                )",
                "CREATE TABLE SalesRecord (
                    Id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    SalesCategoryId BIGINT NOT NULL REFERENCES SalesCategory (Id),
                    Title VARCHAR(255) NOT NULL,
                    Status VARCHAR(20) NOT NULL DEFAULT 'open',
                    Amount DECIMAL(10,2) NOT NULL DEFAULT 0.00
                )",
                "CREATE TABLE SalesCategoryReport (
                    SalesCategoryId BIGINT NOT NULL PRIMARY KEY,
                    SalesCategoryName VARCHAR(255) NOT NULL,
                    ClosedSaleCount INTEGER NOT NULL,
                    ClosedSaleTotalAmount DECIMAL(10,2) NOT NULL
                )",
                "INSERT INTO SalesCategory (Id, Name, IsActive) VALUES
                    (1, 'Hardware', 1),
                    (2, 'Software', 1),
                    (3, 'Legacy', 0)",
                "INSERT INTO SalesRecord (Id, SalesCategoryId, Title, Status, Amount) VALUES
                    (1, 1, 'Keyboard refresh', 'closed', 120.00),
                    (2, 1, 'Mouse replacement', 'closed', 80.00),
                    (3, 2, 'License renewal', 'closed', 40.00),
                    (4, 2, 'Future subscription', 'open', 500.00),
                    (5, 3, 'Unsupported backlog', 'closed', 999.00)",
                'ALTER TABLE SalesCategory ALTER COLUMN Id RESTART WITH 4',
                'ALTER TABLE SalesRecord ALTER COLUMN Id RESTART WITH 6',
            ],
            'sqlite' => [
                'DROP TABLE IF EXISTS SalesCategoryReport',
                'DROP TABLE IF EXISTS SalesRecord',
                'DROP TABLE IF EXISTS SalesCategory',
                "CREATE TABLE SalesCategory (
                    Id INTEGER PRIMARY KEY AUTOINCREMENT,
                    Name TEXT NOT NULL,
                    IsActive INTEGER NOT NULL DEFAULT 1
                )",
                "CREATE TABLE SalesRecord (
                    Id INTEGER PRIMARY KEY AUTOINCREMENT,
                    SalesCategoryId INTEGER NOT NULL,
                    Title TEXT NOT NULL,
                    Status TEXT NOT NULL DEFAULT 'open',
                    Amount NUMERIC NOT NULL DEFAULT 0.00,
                    FOREIGN KEY (SalesCategoryId) REFERENCES SalesCategory (Id)
                )",
                "CREATE TABLE SalesCategoryReport (
                    SalesCategoryId INTEGER NOT NULL PRIMARY KEY,
                    SalesCategoryName TEXT NOT NULL,
                    ClosedSaleCount INTEGER NOT NULL,
                    ClosedSaleTotalAmount NUMERIC NOT NULL
                )",
                "INSERT INTO SalesCategory (Id, Name, IsActive) VALUES
                    (1, 'Hardware', 1),
                    (2, 'Software', 1),
                    (3, 'Legacy', 0)",
                "INSERT INTO SalesRecord (Id, SalesCategoryId, Title, Status, Amount) VALUES
                    (1, 1, 'Keyboard refresh', 'closed', 120.00),
                    (2, 1, 'Mouse replacement', 'closed', 80.00),
                    (3, 2, 'License renewal', 'closed', 40.00),
                    (4, 2, 'Future subscription', 'open', 500.00),
                    (5, 3, 'Unsupported backlog', 'closed', 999.00)",
            ],
        ],
        'runner' => 'app_user_db_contract_runtime_run_sample09',
    ];
}

/**
 * @return array<string,mixed>
 */
function app_user_db_contract_runtime_sample10_definition(): array
{
    return [
        'sample' => 'sample10-dbaccess-mini-crud-flow',
        'dataclass_files' => [
            'data-SupportTicket.php',
        ],
        'dbaccess_files' => [
            'dbaccess-SupportTicket.php',
        ],
        'fixture_sql' => [
            'mysql' => [
                'DROP TABLE IF EXISTS SupportTicket',
                "CREATE TABLE SupportTicket (
                    Id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
                    Title VARCHAR(255) NOT NULL,
                    Status VARCHAR(32) NOT NULL,
                    AssignedTo VARCHAR(255) NULL,
                    Body TEXT NULL,
                    UpdatedAt DATETIME NOT NULL
                )",
                "INSERT INTO SupportTicket (Id, Title, Status, AssignedTo, Body, UpdatedAt) VALUES
                    (1, 'First open ticket', 'open', 'alice', 'First body', '2026-06-17 09:00:00'),
                    (2, 'Second open ticket', 'open', 'bob', 'Second body', '2026-06-17 10:00:00'),
                    (3, 'Closed ticket', 'closed', 'carol', 'Closed body', '2026-06-16 09:00:00')",
            ],
            'pgsql' => [
                'DROP TABLE IF EXISTS SupportTicket',
                "CREATE TABLE SupportTicket (
                    Id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    Title VARCHAR(255) NOT NULL,
                    Status VARCHAR(32) NOT NULL,
                    AssignedTo VARCHAR(255) NULL,
                    Body TEXT NULL,
                    UpdatedAt TIMESTAMP NOT NULL
                )",
                "INSERT INTO SupportTicket (Id, Title, Status, AssignedTo, Body, UpdatedAt) VALUES
                    (1, 'First open ticket', 'open', 'alice', 'First body', '2026-06-17 09:00:00'),
                    (2, 'Second open ticket', 'open', 'bob', 'Second body', '2026-06-17 10:00:00'),
                    (3, 'Closed ticket', 'closed', 'carol', 'Closed body', '2026-06-16 09:00:00')",
                'ALTER TABLE SupportTicket ALTER COLUMN Id RESTART WITH 4',
            ],
            'sqlite' => [
                'DROP TABLE IF EXISTS SupportTicket',
                "CREATE TABLE SupportTicket (
                    Id INTEGER PRIMARY KEY AUTOINCREMENT,
                    Title TEXT NOT NULL,
                    Status TEXT NOT NULL,
                    AssignedTo TEXT NULL,
                    Body TEXT NULL,
                    UpdatedAt TEXT NOT NULL
                )",
                "INSERT INTO SupportTicket (Id, Title, Status, AssignedTo, Body, UpdatedAt) VALUES
                    (1, 'First open ticket', 'open', 'alice', 'First body', '2026-06-17 09:00:00'),
                    (2, 'Second open ticket', 'open', 'bob', 'Second body', '2026-06-17 10:00:00'),
                    (3, 'Closed ticket', 'closed', 'carol', 'Closed body', '2026-06-16 09:00:00')",
            ],
        ],
        'runner' => 'app_user_db_contract_runtime_run_sample10',
    ];
}

function app_user_db_contract_runtime_prepare_mysql_fixture(array $definition): void
{
    $host = (string) (getenv('MTOOL_RUNTIME_DB_HOST') ?: 'db-lab');
    $user = (string) (getenv('MTOOL_RUNTIME_DB_USER') ?: 'lab_app');
    $password = (string) getenv('MTOOL_RUNTIME_DB_PASSWORD');
    $database = (string) (getenv('MTOOL_RUNTIME_DB_NAME') ?: 'lab_app');
    $port = (int) (getenv('MTOOL_RUNTIME_DB_PORT') ?: 3306);

    $db = new mysqli($host, $user, $password, $database, $port);
    if ($db->connect_errno !== 0) {
        throw new RuntimeException('mysql fixture connection failed: ' . $db->connect_error);
    }

    foreach (app_user_db_contract_runtime_fixture_sql($definition, 'mysql') as $sql) {
        if (!$db->query($sql)) {
            throw new RuntimeException('mysql fixture SQL failed: ' . $db->error . ' sql=' . $sql);
        }
    }
}

function app_user_db_contract_runtime_prepare_sqlite_fixture(array $definition, string $sqlitePath): void
{
    $parentDir = dirname($sqlitePath);
    if ($parentDir !== '' && $parentDir !== '.' && !is_dir($parentDir)) {
        mkdir($parentDir, 0775, true);
    }

    if (is_file($sqlitePath)) {
        unlink($sqlitePath);
    }

    $db = new PDO('sqlite:' . $sqlitePath, null, null, [
        PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
    ]);

    foreach (app_user_db_contract_runtime_fixture_sql($definition, 'sqlite') as $sql) {
        $db->exec($sql);
    }
}

function app_user_db_contract_runtime_prepare_pgsql_fixture(array $definition): void
{
    $dsn = trim((string) getenv('MTOOL_RUNTIME_PGSQL_DSN'));
    if ($dsn === '') {
        $host = (string) (getenv('MTOOL_RUNTIME_PGSQL_HOST') ?: getenv('MTOOL_RUNTIME_DB_HOST') ?: '127.0.0.1');
        $port = (string) (getenv('MTOOL_RUNTIME_PGSQL_PORT') ?: getenv('MTOOL_RUNTIME_DB_PORT') ?: '5432');
        $database = (string) (getenv('MTOOL_RUNTIME_PGSQL_DB') ?: getenv('MTOOL_RUNTIME_DB_NAME') ?: 'lab_app');
        $dsn = 'pgsql:host=' . $host . ';port=' . $port . ';dbname=' . $database;
    }

    $user = (string) (getenv('MTOOL_RUNTIME_PGSQL_USER') ?: getenv('MTOOL_RUNTIME_DB_USER') ?: 'lab_app');
    $password = (string) (getenv('MTOOL_RUNTIME_PGSQL_PASSWORD') ?: getenv('MTOOL_RUNTIME_DB_PASSWORD'));

    $db = new PDO($dsn, $user, $password, [
        PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
    ]);

    foreach (app_user_db_contract_runtime_fixture_sql($definition, 'pgsql') as $sql) {
        $db->exec($sql);
    }
}

/**
 * @return list<string>
 */
function app_user_db_contract_runtime_fixture_sql(array $definition, string $dialect): array
{
    $sql = $definition['fixture_sql'][$dialect] ?? null;
    if (!is_array($sql)) {
        throw new RuntimeException('fixture SQL not defined for dialect: ' . $dialect);
    }

    return array_values(array_map('strval', $sql));
}

function app_user_db_contract_runtime_require_sample_files(
    array $definition,
    string $dbaccessRoot,
    string $dataclassRoot,
): void {
    foreach (($definition['dataclass_files'] ?? []) as $file) {
        require_once rtrim($dataclassRoot, '/') . '/' . (string) $file;
    }

    foreach (($definition['dbaccess_files'] ?? []) as $file) {
        require_once rtrim($dbaccessRoot, '/') . '/' . (string) $file;
    }
}

/**
 * @return array<string,mixed>
 */
function app_user_db_contract_runtime_run_sample(
    array $definition,
    string $dbaccessRoot,
    string $dataclassRoot,
): array {
    app_user_db_contract_runtime_require_sample_files($definition, $dbaccessRoot, $dataclassRoot);

    $runner = (string) ($definition['runner'] ?? '');
    if ($runner === '' || !function_exists($runner)) {
        throw new RuntimeException('runtime contract runner not found: ' . $runner);
    }

    return $runner();
}

/**
 * @return array<string,mixed>
 */
function app_user_db_contract_runtime_run_sample06(): array
{
    $access = new AnnouncementDBAccess();

    return [
        'operations' => [
            'published_limit_10' => app_user_db_contract_runtime_list_summary(
                $access->GetAnnouncementList('published', 10),
            ),
            'published_limit_1' => app_user_db_contract_runtime_list_summary(
                $access->GetAnnouncementList('published', 1),
            ),
            'draft_limit_10' => app_user_db_contract_runtime_list_summary(
                $access->GetAnnouncementList('draft', 10),
            ),
            'missing_status' => app_user_db_contract_runtime_list_summary(
                $access->GetAnnouncementList('archived', 10),
            ),
        ],
    ];
}

/**
 * @return array<string,mixed>
 */
function app_user_db_contract_runtime_run_sample08(): array
{
    $access = new BlogPostDBAccess();

    return [
        'operations' => [
            'published_active_author_summary' => app_user_db_contract_runtime_list_summary(
                $access->GetPublishedBlogPostAuthorSummaryList(),
            ),
        ],
    ];
}

/**
 * @return array<string,mixed>
 */
function app_user_db_contract_runtime_run_sample09(): array
{
    $access = new SalesRecordDBAccess();

    return [
        'operations' => [
            'closed_sales_category_report' => app_user_db_contract_runtime_list_summary(
                $access->GetClosedSalesCategoryReportList(),
            ),
        ],
    ];
}

/**
 * @return array<string,mixed>
 */
function app_user_db_contract_runtime_run_sample10(): array
{
    $access = new SupportTicketDBAccess();

    $listBefore = $access->GetSupportTicketList('open', 10);
    $detailBefore = $access->GetSupportTicket(1);

    $newTicket = new SupportTicketData();
    $newTicket->Title = 'New runtime ticket';
    $newTicket->Status = 'open';
    $newTicket->AssignedTo = 'dana';
    $newTicket->Body = 'New body';
    $newTicket->UpdatedAt = '2026-06-17 12:00:00';
    $insertResult = $access->InsertSupportTicket($newTicket);

    $updateTicket = new SupportTicketData();
    $updateTicket->Id = 2;
    $updateTicket->Title = 'Second ticket updated';
    $updateTicket->Status = 'closed';
    $updateTicket->AssignedTo = 'erin';
    $updateTicket->Body = 'Updated body';
    $updateTicket->UpdatedAt = '2026-06-17 13:00:00';
    $updateResult = $access->UpdateSupportTicket($updateTicket);
    $detailAfterUpdate = $access->GetSupportTicket(2);

    $deleteTicket = new SupportTicketData();
    $deleteTicket->Id = 3;
    $deleteResult = $access->DeleteSupportTicket($deleteTicket);
    $detailAfterDelete = $access->GetSupportTicket(3);

    $listAfter = $access->GetSupportTicketList('open', 10);

    return [
        'operations' => [
            'list_before' => app_user_db_contract_runtime_list_summary($listBefore),
            'detail_before' => app_user_db_contract_runtime_record_summary($detailBefore),
            'insert' => app_user_db_contract_runtime_write_summary($insertResult),
            'update' => app_user_db_contract_runtime_write_summary($updateResult),
            'detail_after_update' => app_user_db_contract_runtime_record_summary($detailAfterUpdate),
            'delete' => app_user_db_contract_runtime_write_summary($deleteResult),
            'detail_after_delete' => app_user_db_contract_runtime_record_summary($detailAfterDelete),
            'list_after' => app_user_db_contract_runtime_list_summary($listAfter),
        ],
    ];
}

/**
 * @return array<string,mixed>
 */
function app_user_db_contract_runtime_run_sample18(): array
{
    $access = new TaskCardDBAccess();

    $todoBefore = $access->GetTaskCardList('todo', 10);
    $doingBefore = $access->GetTaskCard(2);

    $newCard = new TaskCardData();
    $newCard->Title = 'Inserted PostgreSQL card';
    $newCard->Body = 'Inserted body';
    $newCard->Status = 'todo';
    $newCard->AssignedTo = 'dana';
    $newCard->Priority = 4;
    $newCard->DueDate = '2026-06-23';
    $newCard->UpdatedAt = '2026-06-20 12:00:00';
    $insertResult = $access->InsertTaskCard($newCard);

    $updateCard = new TaskCardData();
    $updateCard->Id = 2;
    $updateCard->Title = 'Review generated names updated';
    $updateCard->Body = 'Updated task body';
    $updateCard->Status = 'doing';
    $updateCard->AssignedTo = 'erin';
    $updateCard->Priority = 6;
    $updateCard->DueDate = '2026-06-24';
    $updateCard->CompletedAt = null;
    $updateCard->UpdatedAt = '2026-06-20 13:00:00';
    $updateResult = $access->UpdateTaskCard($updateCard);
    $detailAfterUpdate = $access->GetTaskCard(2);

    $completeCard = new TaskCardData();
    $completeCard->Id = 1;
    $completeCard->CompletedAt = '2026-06-20 14:00:00';
    $completeCard->UpdatedAt = '2026-06-20 14:00:00';
    $completeResult = $access->CompleteTaskCard($completeCard);
    $detailAfterComplete = $access->GetTaskCard(1);

    return [
        'operations' => [
            'todo_before' => app_user_db_contract_runtime_list_summary($todoBefore),
            'doing_before' => app_user_db_contract_runtime_record_summary($doingBefore),
            'insert' => app_user_db_contract_runtime_write_summary($insertResult),
            'update' => app_user_db_contract_runtime_write_summary($updateResult),
            'detail_after_update' => app_user_db_contract_runtime_record_summary($detailAfterUpdate),
            'complete' => app_user_db_contract_runtime_write_summary($completeResult),
            'detail_after_complete' => app_user_db_contract_runtime_record_summary($detailAfterComplete),
            'todo_after' => app_user_db_contract_runtime_list_summary($access->GetTaskCardList('todo', 10)),
        ],
    ];
}

/**
 * @return array<string,mixed>
 */
function app_user_db_contract_runtime_run_sample19(): array
{
    $access = new ArticleJsonModelDBAccess();

    return [
        'operations' => [
            'published_article_public_summary' => app_user_db_contract_runtime_list_summary(
                $access->GetPublishedArticlePublicSummaryList(),
            ),
        ],
    ];
}

/**
 * @return array<string,mixed>
 */
function app_user_db_contract_runtime_run_sample21(): array
{
    $access = new EbookCatalogItemDBAccess();

    return [
        'operations' => [
            'catalog_filtered' => app_user_db_contract_runtime_list_summary(
                $access->GetPublicEbookCatalogList('aki-author', 'guides', 'starter-series', '%Ebook%', 10),
            ),
            'book_detail' => app_user_db_contract_runtime_record_summary(
                $access->GetPublicEbookBook('first-ebook'),
            ),
            'missing_book' => app_user_db_contract_runtime_record_summary(
                $access->GetPublicEbookBook('missing-ebook'),
            ),
        ],
    ];
}

/**
 * @return array<string,mixed>
 */
function app_user_db_contract_runtime_run_sample22(): array
{
    $access = new EbookWorkflowChapterDBAccess();

    $newChapter = new EbookWorkflowChapterData();
    $newChapter->EbookWorkflowBookId = 1;
    $newChapter->ChapterTitle = 'Inserted Workflow Chapter';
    $newChapter->ChapterSlug = 'inserted-workflow-chapter';
    $newChapter->SpineOrder = 4;
    $newChapter->NavLabel = 'Inserted';
    $newChapter->EpubResourcePath = 'chapters/inserted.xhtml';
    $newChapter->BodyMarkdown = '# Inserted';
    $insertResult = $access->InsertEbookWorkflowChapter($newChapter);

    $updateChapter = new EbookWorkflowChapterData();
    $updateChapter->Id = 2;
    $updateChapter->ChapterTitle = 'Draft Chapter Updated';
    $updateChapter->NavLabel = 'Draft Updated';
    $updateChapter->EpubResourcePath = 'chapters/draft-updated.xhtml';
    $updateChapter->BodyMarkdown = '# Draft Updated';
    $updateResult = $access->UpdateEbookWorkflowChapterDraft($updateChapter);

    $orderChapter = new EbookWorkflowChapterData();
    $orderChapter->Id = 2;
    $orderChapter->SpineOrder = 5;
    $orderChapter->NavLabel = 'Draft Ordered';
    $orderChapter->EpubResourcePath = 'chapters/draft-ordered.xhtml';
    $orderResult = $access->UpdateEbookWorkflowChapterOrder($orderChapter);

    $publishChapter = new EbookWorkflowChapterData();
    $publishChapter->Id = 2;
    $publishResult = $access->PublishEbookWorkflowChapter($publishChapter);

    return [
        'operations' => [
            'published_chapter_list' => app_user_db_contract_runtime_list_summary(
                $access->GetPublishedEbookWorkflowChapterList('workflow-book'),
            ),
            'published_chapter_detail' => app_user_db_contract_runtime_record_summary(
                $access->GetPublishedEbookWorkflowChapter('workflow-book', 'opening'),
            ),
            'insert' => app_user_db_contract_runtime_write_summary($insertResult),
            'update_draft' => app_user_db_contract_runtime_write_summary($updateResult),
            'update_order' => app_user_db_contract_runtime_write_summary($orderResult),
            'publish' => app_user_db_contract_runtime_write_summary($publishResult),
        ],
    ];
}

/**
 * @return array<string,mixed>
 */
function app_user_db_contract_runtime_run_sample23(): array
{
    $access = new EbookMediaAssetDBAccess();

    $newAsset = new EbookMediaAssetData();
    $newAsset->AssetSlug = 'new-asset';
    $newAsset->AssetKind = 'image';
    $newAsset->DisplayName = 'New Asset';
    $newAsset->PublicUrl = '/media/new.jpg';
    $newAsset->StoragePath = '/storage/new.jpg';
    $newAsset->MimeType = 'image/jpeg';
    $newAsset->FileSizeBytes = 2222;
    $newAsset->Sha256 = 'sha-new';
    $newAsset->VersionLabel = 'v1';
    $insertResult = $access->InsertEbookMediaAsset($newAsset);

    $updateAsset = new EbookMediaAssetData();
    $updateAsset->Id = 1;
    $updateAsset->DisplayName = 'Cover Image Updated';
    $updateAsset->PublicUrl = '/media/cover-updated.jpg';
    $updateAsset->StoragePath = '/storage/cover-updated.jpg';
    $updateAsset->MimeType = 'image/jpeg';
    $updateAsset->FileSizeBytes = 1300;
    $updateAsset->Sha256 = 'sha-cover-updated';
    $updateAsset->VersionLabel = 'v2';
    $updateAsset->Status = 'published';
    $updateResult = $access->UpdateEbookMediaAssetMetadata($updateAsset);

    return [
        'operations' => [
            'delivery_list' => app_user_db_contract_runtime_list_summary(
                $access->GetPublicEbookMediaDeliveryList('media-book'),
            ),
            'asset_detail' => app_user_db_contract_runtime_record_summary(
                $access->GetPublicEbookMediaAsset('cover-image'),
            ),
            'insert' => app_user_db_contract_runtime_write_summary($insertResult),
            'update_metadata' => app_user_db_contract_runtime_write_summary($updateResult),
        ],
    ];
}

/**
 * @return array<string,mixed>
 */
function app_user_db_contract_runtime_run_sample24(): array
{
    $access = new EbookReaderBookDBAccess();

    return [
        'operations' => [
            'book_list' => app_user_db_contract_runtime_list_summary(
                $access->GetPublicEbookReaderBookList(10),
            ),
            'book_detail' => app_user_db_contract_runtime_record_summary(
                $access->GetPublicEbookReaderBook('reader-book'),
            ),
            'chapter_list' => app_user_db_contract_runtime_list_summary(
                $access->GetPublicEbookReaderChapterList('reader-book'),
            ),
            'chapter_detail' => app_user_db_contract_runtime_record_summary(
                $access->GetPublicEbookReaderChapter('reader-book', 'opening'),
            ),
            'media_delivery_list' => app_user_db_contract_runtime_list_summary(
                $access->GetPublicEbookReaderMediaDeliveryList('reader-book'),
            ),
        ],
    ];
}

/**
 * @return array<string,mixed>
 */
function app_user_db_contract_runtime_run_sample25(): array
{
    $access = new EbookEditorChapterDBAccess();
    $detailBefore = $access->GetEditorEbookChapter(1);

    $updateChapter = new EbookEditorChapterData();
    $updateChapter->Id = 1;
    $updateChapter->ChapterTitle = 'Editor Opening Updated';
    $updateChapter->ChapterSlug = 'editor-opening-updated';
    $updateChapter->SpineOrder = 3;
    $updateChapter->BodyMarkdown = '# Editor Opening Updated';
    $updateResult = $access->UpdateEditorEbookChapterDraft($updateChapter);

    $publishChapter = new EbookEditorChapterData();
    $publishChapter->Id = 1;
    $publishResult = $access->PublishEditorEbookChapter($publishChapter);

    return [
        'operations' => [
            'detail_before' => app_user_db_contract_runtime_record_summary($detailBefore),
            'update_draft' => app_user_db_contract_runtime_write_summary($updateResult),
            'publish' => app_user_db_contract_runtime_write_summary($publishResult),
            'detail_after_publish' => app_user_db_contract_runtime_record_summary_without_fields(
                $access->GetEditorEbookChapter(1),
                ['PublishedAt', 'UpdatedAt'],
            ),
        ],
    ];
}

/**
 * @return array<string,mixed>
 */
function app_user_db_contract_runtime_run_sample26(): array
{
    $access = new EbookCmsBookDBAccess();
    $editorDetailBefore = $access->GetEditorEbookCmsChapter(2);

    $updateChapter = new EbookCmsChapterData();
    $updateChapter->Id = 2;
    $updateChapter->ChapterTitle = 'Draft Chapter Updated';
    $updateChapter->ChapterSlug = 'draft-chapter-updated';
    $updateChapter->SpineOrder = 4;
    $updateChapter->BodyMarkdown = '# Draft Updated';
    $updateResult = $access->UpdateEditorEbookCmsChapterDraft($updateChapter);

    $publishChapter = new EbookCmsChapterData();
    $publishChapter->Id = 2;
    $publishResult = $access->PublishEditorEbookCmsChapter($publishChapter);

    return [
        'operations' => [
            'book_list' => app_user_db_contract_runtime_list_summary(
                $access->GetPublicEbookCmsBookList(10),
            ),
            'book_detail' => app_user_db_contract_runtime_record_summary(
                $access->GetPublicEbookCmsBook('cms-book'),
            ),
            'chapter_list' => app_user_db_contract_runtime_list_summary(
                $access->GetPublicEbookCmsChapterList('cms-book'),
            ),
            'chapter_detail' => app_user_db_contract_runtime_record_summary(
                $access->GetPublicEbookCmsChapter('cms-book', 'opening'),
            ),
            'epub_delivery_list' => app_user_db_contract_runtime_list_summary(
                $access->GetPublicEbookCmsEpubDeliveryList('cms-book'),
            ),
            'editor_detail_before' => app_user_db_contract_runtime_record_summary($editorDetailBefore),
            'update_draft' => app_user_db_contract_runtime_write_summary($updateResult),
            'publish' => app_user_db_contract_runtime_write_summary($publishResult),
            'editor_detail_after_publish' => app_user_db_contract_runtime_record_summary_without_fields(
                $access->GetEditorEbookCmsChapter(2),
                ['PublishedAt', 'UpdatedAt'],
            ),
        ],
    ];
}

/**
 * @return array<string,mixed>
 */
function app_user_db_contract_runtime_result(
    array $definition,
    string $dbaccessRoot,
    string $dataclassRoot,
    string $dialect,
): array {
    $result = app_user_db_contract_runtime_run_sample($definition, $dbaccessRoot, $dataclassRoot);

    return [
        'schema' => 'user-db-contract-runtime-v1',
        'sample' => (string) ($definition['sample'] ?? ''),
        'dialect' => $dialect,
        'operations' => $result['operations'] ?? [],
    ];
}

/**
 * @return array<string,mixed>
 */
function app_user_db_contract_runtime_list_summary(mixed $list): array
{
    if (!is_array($list)) {
        return [
            'ok' => false,
            'count' => 0,
            'records' => [],
        ];
    }

    return [
        'ok' => true,
        'count' => count($list),
        'records' => array_map('app_user_db_contract_runtime_object_summary', $list),
    ];
}

/**
 * @return array<string,mixed>
 */
function app_user_db_contract_runtime_record_summary(mixed $record): array
{
    if (!is_object($record)) {
        return [
            'found' => false,
        ];
    }

    return [
        'found' => true,
        'record' => app_user_db_contract_runtime_object_summary($record),
    ];
}

/**
 * @param list<string> $fieldNames
 * @return array<string,mixed>
 */
function app_user_db_contract_runtime_record_summary_without_fields(mixed $record, array $fieldNames): array
{
    $summary = app_user_db_contract_runtime_record_summary($record);
    if (!isset($summary['record']) || !is_array($summary['record'])) {
        return $summary;
    }

    foreach ($fieldNames as $fieldName) {
        unset($summary['record'][$fieldName]);
    }

    return $summary;
}

/**
 * @return array<string,mixed>
 */
function app_user_db_contract_runtime_object_summary(mixed $record): array
{
    if (!is_object($record)) {
        return [];
    }

    $values = get_object_vars($record);
    ksort($values, SORT_STRING);

    return array_map('app_user_db_contract_runtime_normalize_value', $values);
}

function app_user_db_contract_runtime_normalize_value(mixed $value): mixed
{
    if (is_string($value) && preg_match('/^-?\d+\.\d+$/', $value) === 1) {
        $normalized = rtrim(rtrim($value, '0'), '.');
        if ($normalized === '-0') {
            $normalized = '0';
        }
        if (preg_match('/^-?\d+$/', $normalized) === 1) {
            return (int) $normalized;
        }

        return (float) $normalized;
    }

    return $value;
}

/**
 * @return array<string,mixed>
 */
function app_user_db_contract_runtime_write_summary(mixed $result): array
{
    return [
        'ok' => $result !== false,
    ];
}
