<?php

declare(strict_types=1);

require_once __DIR__ . '/user_db_contract.php';

function app_user_db_contract_runtime_usage(): string
{
    return <<<'TXT'
usage:
  php mtool/scripts/user_db_contract_runtime_smoke.php --dbaccess-root=PATH --dataclass-root=PATH --dialect=mysql|sqlite|pgsql --output=PATH [--sample=KEY] [--sqlite-path=PATH] [--pretty]

TXT;
}

/**
 * @return array<string,mixed>
 */
function app_user_db_contract_runtime_parse_options(array $argv): array
{
    $options = [
        'pretty' => false,
        'sample' => 'sample10-dbaccess-mini-crud-flow',
    ];
    foreach (array_slice($argv, 1) as $argument) {
        if ($argument === '--pretty') {
            $options['pretty'] = true;
            continue;
        }

        if (str_starts_with($argument, '--') && str_contains($argument, '=')) {
            [$key, $value] = explode('=', substr($argument, 2), 2);
            $options[$key] = $value;
            continue;
        }

        throw new InvalidArgumentException('unsupported argument: ' . $argument);
    }

    return $options;
}

/**
 * @return array<string,mixed>
 */
function app_user_db_contract_runtime_sample_definition(string $sample): array
{
    if ($sample === 'sample10-dbaccess-mini-crud-flow') {
        return app_user_db_contract_runtime_sample10_definition();
    }

    if ($sample === 'sample18-mini-task-board-demo') {
        return app_user_db_contract_runtime_sample18_definition();
    }

    if ($sample === 'sample19-json-first-content-model-demo') {
        return app_user_db_contract_runtime_sample19_definition();
    }

    if ($sample === 'sample21-ebook-catalog-api-demo') {
        return app_user_db_contract_runtime_sample21_definition();
    }

    if ($sample === 'sample22-ebook-chapter-workflow-demo') {
        return app_user_db_contract_runtime_sample22_definition();
    }

    if ($sample === 'sample23-ebook-media-metadata-demo') {
        return app_user_db_contract_runtime_sample23_definition();
    }

    if ($sample === 'sample24-ebook-public-reader-site-demo') {
        return app_user_db_contract_runtime_sample24_definition();
    }

    if ($sample === 'sample25-ebook-editor-auth-cms-demo') {
        return app_user_db_contract_runtime_sample25_definition();
    }

    if ($sample === 'sample26-ebook-headless-cms-capstone') {
        return app_user_db_contract_runtime_sample26_definition();
    }

    if ($sample === 'sample06-dbaccess-filter-sort-page') {
        return app_user_db_contract_runtime_sample06_definition();
    }

    if ($sample === 'sample08-dbaccess-join-read-model') {
        return app_user_db_contract_runtime_sample08_definition();
    }

    if ($sample === 'sample09-dbaccess-aggregate-report') {
        return app_user_db_contract_runtime_sample09_definition();
    }

    throw new InvalidArgumentException('unsupported runtime contract sample: ' . $sample);
}

/**
 * @return array<string,mixed>
 */
function app_user_db_contract_runtime_sample18_definition(): array
{
    return [
        'sample' => 'sample18-mini-task-board-demo',
        'dataclass_files' => [
            'data-TaskCard.php',
        ],
        'dbaccess_files' => [
            'dbaccess-TaskCard.php',
        ],
        'fixture_sql' => [
            'mysql' => [
                'DROP TABLE IF EXISTS TaskCard',
                "CREATE TABLE TaskCard (
                    Id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
                    Title VARCHAR(255) NOT NULL,
                    Body TEXT NOT NULL,
                    Status VARCHAR(20) NOT NULL DEFAULT 'todo',
                    AssignedTo VARCHAR(255) NULL,
                    Priority INT NOT NULL DEFAULT 0,
                    DueDate DATE NULL,
                    CompletedAt DATETIME NULL,
                    UpdatedAt DATETIME NOT NULL
                )",
                "INSERT INTO TaskCard (Id, Title, Body, Status, AssignedTo, Priority, DueDate, CompletedAt, UpdatedAt) VALUES
                    (1, 'Draft PostgreSQL card', 'First task body', 'todo', 'alice', 3, '2026-06-22', NULL, '2026-06-20 09:00:00'),
                    (2, 'Review generated names', 'Second task body', 'doing', 'bob', 5, '2026-06-21', NULL, '2026-06-20 10:00:00'),
                    (3, 'Done reference task', 'Closed task body', 'done', 'carol', 1, '2026-06-19', '2026-06-20 11:00:00', '2026-06-20 11:00:00')",
            ],
            'pgsql' => [
                'DROP TABLE IF EXISTS TaskCard',
                "CREATE TABLE TaskCard (
                    Id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    Title VARCHAR(255) NOT NULL,
                    Body TEXT NOT NULL,
                    Status VARCHAR(20) NOT NULL DEFAULT 'todo',
                    AssignedTo VARCHAR(255) NULL,
                    Priority INTEGER NOT NULL DEFAULT 0,
                    DueDate DATE NULL,
                    CompletedAt TIMESTAMP NULL,
                    UpdatedAt TIMESTAMP NOT NULL
                )",
                "INSERT INTO TaskCard (Id, Title, Body, Status, AssignedTo, Priority, DueDate, CompletedAt, UpdatedAt) VALUES
                    (1, 'Draft PostgreSQL card', 'First task body', 'todo', 'alice', 3, '2026-06-22', NULL, '2026-06-20 09:00:00'),
                    (2, 'Review generated names', 'Second task body', 'doing', 'bob', 5, '2026-06-21', NULL, '2026-06-20 10:00:00'),
                    (3, 'Done reference task', 'Closed task body', 'done', 'carol', 1, '2026-06-19', '2026-06-20 11:00:00', '2026-06-20 11:00:00')",
                'ALTER TABLE TaskCard ALTER COLUMN Id RESTART WITH 4',
            ],
            'sqlite' => [
                'DROP TABLE IF EXISTS TaskCard',
                "CREATE TABLE TaskCard (
                    Id INTEGER PRIMARY KEY AUTOINCREMENT,
                    Title TEXT NOT NULL,
                    Body TEXT NOT NULL,
                    Status TEXT NOT NULL DEFAULT 'todo',
                    AssignedTo TEXT NULL,
                    Priority INTEGER NOT NULL DEFAULT 0,
                    DueDate TEXT NULL,
                    CompletedAt TEXT NULL,
                    UpdatedAt TEXT NOT NULL
                )",
                "INSERT INTO TaskCard (Id, Title, Body, Status, AssignedTo, Priority, DueDate, CompletedAt, UpdatedAt) VALUES
                    (1, 'Draft PostgreSQL card', 'First task body', 'todo', 'alice', 3, '2026-06-22', NULL, '2026-06-20 09:00:00'),
                    (2, 'Review generated names', 'Second task body', 'doing', 'bob', 5, '2026-06-21', NULL, '2026-06-20 10:00:00'),
                    (3, 'Done reference task', 'Closed task body', 'done', 'carol', 1, '2026-06-19', '2026-06-20 11:00:00', '2026-06-20 11:00:00')",
            ],
        ],
        'runner' => 'app_user_db_contract_runtime_run_sample18',
    ];
}

/**
 * @return array<string,mixed>
 */
function app_user_db_contract_runtime_sample21_definition(): array
{
    $commonRows = "INSERT INTO ebook_catalog_item
        (book_id, book_title, book_slug, series_name, author_name, author_slug, genre_name, genre_slug, series_slug, published_at, summary, epub_status, primary_epub_url, status)
        VALUES
        (1, 'First Ebook', 'first-ebook', 'Starter Series', 'Aki Author', 'aki-author', 'Guides', 'guides', 'starter-series', '2026-06-20 09:00:00', 'First summary', 'ready', '/ebooks/first.epub', 'published'),
        (2, 'Second Ebook', 'second-ebook', 'Starter Series', 'Aki Author', 'aki-author', 'Guides', 'guides', 'starter-series', '2026-06-21 09:00:00', 'Second summary', 'ready', '/ebooks/second.epub', 'published'),
        (3, 'Draft Ebook', 'draft-ebook', 'Draft Series', 'Mika Draft', 'mika-draft', 'Drafts', 'drafts', 'draft-series', NULL, 'Draft summary', 'draft', NULL, 'draft')";

    return [
        'sample' => 'sample21-ebook-catalog-api-demo',
        'dataclass_files' => [
            'data-EbookCatalogItem.php',
        ],
        'dbaccess_files' => [
            'dbaccess-EbookCatalogItem.php',
        ],
        'fixture_sql' => [
            'mysql' => [
                'DROP TABLE IF EXISTS ebook_catalog_item',
                "CREATE TABLE ebook_catalog_item (
                    book_id BIGINT NOT NULL PRIMARY KEY,
                    book_title VARCHAR(255) NOT NULL,
                    book_slug VARCHAR(191) NOT NULL,
                    series_name VARCHAR(255) NOT NULL,
                    author_name VARCHAR(255) NOT NULL,
                    author_slug VARCHAR(191) NOT NULL,
                    genre_name VARCHAR(255) NOT NULL,
                    genre_slug VARCHAR(191) NOT NULL,
                    series_slug VARCHAR(191) NOT NULL,
                    published_at DATETIME NULL,
                    summary TEXT NOT NULL,
                    epub_status VARCHAR(32) NOT NULL,
                    primary_epub_url VARCHAR(255) NULL,
                    status VARCHAR(32) NOT NULL
                )",
                $commonRows,
            ],
            'pgsql' => [
                'DROP TABLE IF EXISTS ebook_catalog_item',
                "CREATE TABLE ebook_catalog_item (
                    book_id BIGINT NOT NULL PRIMARY KEY,
                    book_title VARCHAR(255) NOT NULL,
                    book_slug VARCHAR(191) NOT NULL,
                    series_name VARCHAR(255) NOT NULL,
                    author_name VARCHAR(255) NOT NULL,
                    author_slug VARCHAR(191) NOT NULL,
                    genre_name VARCHAR(255) NOT NULL,
                    genre_slug VARCHAR(191) NOT NULL,
                    series_slug VARCHAR(191) NOT NULL,
                    published_at TIMESTAMP NULL,
                    summary TEXT NOT NULL,
                    epub_status VARCHAR(32) NOT NULL,
                    primary_epub_url VARCHAR(255) NULL,
                    status VARCHAR(32) NOT NULL
                )",
                $commonRows,
            ],
            'sqlite' => [
                'DROP TABLE IF EXISTS ebook_catalog_item',
                "CREATE TABLE ebook_catalog_item (
                    book_id INTEGER NOT NULL PRIMARY KEY,
                    book_title TEXT NOT NULL,
                    book_slug TEXT NOT NULL,
                    series_name TEXT NOT NULL,
                    author_name TEXT NOT NULL,
                    author_slug TEXT NOT NULL,
                    genre_name TEXT NOT NULL,
                    genre_slug TEXT NOT NULL,
                    series_slug TEXT NOT NULL,
                    published_at TEXT NULL,
                    summary TEXT NOT NULL,
                    epub_status TEXT NOT NULL,
                    primary_epub_url TEXT NULL,
                    status TEXT NOT NULL
                )",
                $commonRows,
            ],
        ],
        'runner' => 'app_user_db_contract_runtime_run_sample21',
    ];
}

/**
 * @return array<string,mixed>
 */
function app_user_db_contract_runtime_sample22_definition(): array
{
    $publishedRows = "INSERT INTO ebook_workflow_published_chapter
        (chapter_id, book_id, book_slug, chapter_title, chapter_slug, spine_order, nav_label, epub_resource_path, body_markdown, status)
        VALUES
        (1, 1, 'workflow-book', 'Opening', 'opening', 1, 'Opening', 'chapters/opening.xhtml', '# Opening', 'published'),
        (2, 1, 'workflow-book', 'Middle', 'middle', 2, 'Middle', 'chapters/middle.xhtml', '# Middle', 'published'),
        (3, 1, 'workflow-book', 'Draft Hidden', 'draft-hidden', 3, 'Draft', 'chapters/draft.xhtml', '# Draft', 'draft')";
    $chapterRows = "INSERT INTO ebook_workflow_chapter
        (id, ebook_workflow_book_id, chapter_title, chapter_slug, status, spine_order, nav_label, epub_resource_path, body_markdown, published_at, updated_at)
        VALUES
        (1, 1, 'Opening', 'opening', 'published', 1, 'Opening', 'chapters/opening.xhtml', '# Opening', '2026-06-20 09:00:00', '2026-06-20 09:00:00'),
        (2, 1, 'Draft Chapter', 'draft-chapter', 'draft', 2, 'Draft', 'chapters/draft.xhtml', '# Draft', NULL, '2026-06-20 10:00:00')";

    return [
        'sample' => 'sample22-ebook-chapter-workflow-demo',
        'dataclass_files' => [
            'data-EbookWorkflowChapter.php',
            'data-EbookWorkflowPublishedChapter.php',
        ],
        'dbaccess_files' => [
            'dbaccess-EbookWorkflowChapter.php',
        ],
        'fixture_sql' => [
            'mysql' => [
                'DROP TABLE IF EXISTS ebook_workflow_published_chapter',
                'DROP TABLE IF EXISTS ebook_workflow_chapter',
                "CREATE TABLE ebook_workflow_published_chapter (
                    chapter_id BIGINT NOT NULL PRIMARY KEY,
                    book_id BIGINT NOT NULL,
                    book_slug VARCHAR(191) NOT NULL,
                    chapter_title VARCHAR(255) NOT NULL,
                    chapter_slug VARCHAR(191) NOT NULL,
                    spine_order INT NOT NULL,
                    nav_label VARCHAR(255) NOT NULL,
                    epub_resource_path VARCHAR(255) NOT NULL,
                    body_markdown TEXT NOT NULL,
                    status VARCHAR(32) NOT NULL
                )",
                "CREATE TABLE ebook_workflow_chapter (
                    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
                    ebook_workflow_book_id BIGINT NOT NULL,
                    chapter_title VARCHAR(255) NOT NULL,
                    chapter_slug VARCHAR(191) NOT NULL,
                    status VARCHAR(32) NOT NULL,
                    spine_order INT NOT NULL,
                    nav_label VARCHAR(255) NOT NULL,
                    epub_resource_path VARCHAR(255) NOT NULL,
                    body_markdown TEXT NOT NULL,
                    published_at DATETIME NULL,
                    updated_at DATETIME NOT NULL
                )",
                $publishedRows,
                $chapterRows,
            ],
            'pgsql' => [
                'DROP TABLE IF EXISTS ebook_workflow_published_chapter',
                'DROP TABLE IF EXISTS ebook_workflow_chapter',
                "CREATE TABLE ebook_workflow_published_chapter (
                    chapter_id BIGINT NOT NULL PRIMARY KEY,
                    book_id BIGINT NOT NULL,
                    book_slug VARCHAR(191) NOT NULL,
                    chapter_title VARCHAR(255) NOT NULL,
                    chapter_slug VARCHAR(191) NOT NULL,
                    spine_order INTEGER NOT NULL,
                    nav_label VARCHAR(255) NOT NULL,
                    epub_resource_path VARCHAR(255) NOT NULL,
                    body_markdown TEXT NOT NULL,
                    status VARCHAR(32) NOT NULL
                )",
                "CREATE TABLE ebook_workflow_chapter (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ebook_workflow_book_id BIGINT NOT NULL,
                    chapter_title VARCHAR(255) NOT NULL,
                    chapter_slug VARCHAR(191) NOT NULL,
                    status VARCHAR(32) NOT NULL,
                    spine_order INTEGER NOT NULL,
                    nav_label VARCHAR(255) NOT NULL,
                    epub_resource_path VARCHAR(255) NOT NULL,
                    body_markdown TEXT NOT NULL,
                    published_at TIMESTAMP NULL,
                    updated_at TIMESTAMP NOT NULL
                )",
                $publishedRows,
                $chapterRows,
                'ALTER TABLE ebook_workflow_chapter ALTER COLUMN id RESTART WITH 3',
            ],
            'sqlite' => [
                'DROP TABLE IF EXISTS ebook_workflow_published_chapter',
                'DROP TABLE IF EXISTS ebook_workflow_chapter',
                "CREATE TABLE ebook_workflow_published_chapter (
                    chapter_id INTEGER NOT NULL PRIMARY KEY,
                    book_id INTEGER NOT NULL,
                    book_slug TEXT NOT NULL,
                    chapter_title TEXT NOT NULL,
                    chapter_slug TEXT NOT NULL,
                    spine_order INTEGER NOT NULL,
                    nav_label TEXT NOT NULL,
                    epub_resource_path TEXT NOT NULL,
                    body_markdown TEXT NOT NULL,
                    status TEXT NOT NULL
                )",
                "CREATE TABLE ebook_workflow_chapter (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    ebook_workflow_book_id INTEGER NOT NULL,
                    chapter_title TEXT NOT NULL,
                    chapter_slug TEXT NOT NULL,
                    status TEXT NOT NULL,
                    spine_order INTEGER NOT NULL,
                    nav_label TEXT NOT NULL,
                    epub_resource_path TEXT NOT NULL,
                    body_markdown TEXT NOT NULL,
                    published_at TEXT NULL,
                    updated_at TEXT NOT NULL
                )",
                $publishedRows,
                $chapterRows,
            ],
        ],
        'runner' => 'app_user_db_contract_runtime_run_sample22',
    ];
}

/**
 * @return array<string,mixed>
 */
function app_user_db_contract_runtime_sample23_definition(): array
{
    $deliveryRows = "INSERT INTO ebook_media_delivery
        (delivery_id, book_id, book_slug, asset_id, asset_slug, asset_kind, display_role, display_name, public_url, mime_type, file_size_bytes, sha256, version_label, sort_order, is_primary_asset, status)
        VALUES
        (1, 1, 'media-book', 1, 'cover-image', 'image', 'cover', 'Cover Image', '/media/cover.jpg', 'image/jpeg', 1200, 'sha-cover', 'v1', 1, 1, 'published'),
        (2, 1, 'media-book', 2, 'epub-file', 'epub', 'download', 'EPUB File', '/media/book.epub', 'application/epub+zip', 3400, 'sha-epub', 'v1', 2, 0, 'published')";
    $assetRows = "INSERT INTO ebook_media_asset
        (id, asset_slug, asset_kind, display_name, public_url, storage_path, mime_type, file_size_bytes, sha256, version_label, status, updated_at)
        VALUES
        (1, 'cover-image', 'image', 'Cover Image', '/media/cover.jpg', '/storage/cover.jpg', 'image/jpeg', 1200, 'sha-cover', 'v1', 'published', '2026-06-20 09:00:00')";

    return [
        'sample' => 'sample23-ebook-media-metadata-demo',
        'dataclass_files' => [
            'data-EbookMediaAsset.php',
            'data-EbookMediaDelivery.php',
        ],
        'dbaccess_files' => [
            'dbaccess-EbookMediaAsset.php',
        ],
        'fixture_sql' => [
            'mysql' => [
                'DROP TABLE IF EXISTS ebook_media_delivery',
                'DROP TABLE IF EXISTS ebook_media_asset',
                "CREATE TABLE ebook_media_delivery (
                    delivery_id BIGINT NOT NULL PRIMARY KEY,
                    book_id BIGINT NOT NULL,
                    book_slug VARCHAR(191) NOT NULL,
                    asset_id BIGINT NOT NULL,
                    asset_slug VARCHAR(191) NOT NULL,
                    asset_kind VARCHAR(32) NOT NULL,
                    display_role VARCHAR(64) NOT NULL,
                    display_name VARCHAR(255) NOT NULL,
                    public_url VARCHAR(255) NOT NULL,
                    mime_type VARCHAR(128) NOT NULL,
                    file_size_bytes BIGINT NOT NULL,
                    sha256 VARCHAR(128) NOT NULL,
                    version_label VARCHAR(64) NOT NULL,
                    sort_order INT NOT NULL,
                    is_primary_asset INT NOT NULL,
                    status VARCHAR(32) NOT NULL
                )",
                "CREATE TABLE ebook_media_asset (
                    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
                    asset_slug VARCHAR(191) NOT NULL,
                    asset_kind VARCHAR(32) NOT NULL,
                    display_name VARCHAR(255) NOT NULL,
                    public_url VARCHAR(255) NOT NULL,
                    storage_path VARCHAR(255) NOT NULL,
                    mime_type VARCHAR(128) NOT NULL,
                    file_size_bytes BIGINT NOT NULL,
                    sha256 VARCHAR(128) NOT NULL,
                    version_label VARCHAR(64) NOT NULL,
                    status VARCHAR(32) NOT NULL,
                    updated_at DATETIME NOT NULL
                )",
                $deliveryRows,
                $assetRows,
            ],
            'pgsql' => [
                'DROP TABLE IF EXISTS ebook_media_delivery',
                'DROP TABLE IF EXISTS ebook_media_asset',
                "CREATE TABLE ebook_media_delivery (
                    delivery_id BIGINT NOT NULL PRIMARY KEY,
                    book_id BIGINT NOT NULL,
                    book_slug VARCHAR(191) NOT NULL,
                    asset_id BIGINT NOT NULL,
                    asset_slug VARCHAR(191) NOT NULL,
                    asset_kind VARCHAR(32) NOT NULL,
                    display_role VARCHAR(64) NOT NULL,
                    display_name VARCHAR(255) NOT NULL,
                    public_url VARCHAR(255) NOT NULL,
                    mime_type VARCHAR(128) NOT NULL,
                    file_size_bytes BIGINT NOT NULL,
                    sha256 VARCHAR(128) NOT NULL,
                    version_label VARCHAR(64) NOT NULL,
                    sort_order INTEGER NOT NULL,
                    is_primary_asset INTEGER NOT NULL,
                    status VARCHAR(32) NOT NULL
                )",
                "CREATE TABLE ebook_media_asset (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    asset_slug VARCHAR(191) NOT NULL,
                    asset_kind VARCHAR(32) NOT NULL,
                    display_name VARCHAR(255) NOT NULL,
                    public_url VARCHAR(255) NOT NULL,
                    storage_path VARCHAR(255) NOT NULL,
                    mime_type VARCHAR(128) NOT NULL,
                    file_size_bytes BIGINT NOT NULL,
                    sha256 VARCHAR(128) NOT NULL,
                    version_label VARCHAR(64) NOT NULL,
                    status VARCHAR(32) NOT NULL,
                    updated_at TIMESTAMP NOT NULL
                )",
                $deliveryRows,
                $assetRows,
                'ALTER TABLE ebook_media_asset ALTER COLUMN id RESTART WITH 2',
            ],
            'sqlite' => [
                'DROP TABLE IF EXISTS ebook_media_delivery',
                'DROP TABLE IF EXISTS ebook_media_asset',
                "CREATE TABLE ebook_media_delivery (
                    delivery_id INTEGER NOT NULL PRIMARY KEY,
                    book_id INTEGER NOT NULL,
                    book_slug TEXT NOT NULL,
                    asset_id INTEGER NOT NULL,
                    asset_slug TEXT NOT NULL,
                    asset_kind TEXT NOT NULL,
                    display_role TEXT NOT NULL,
                    display_name TEXT NOT NULL,
                    public_url TEXT NOT NULL,
                    mime_type TEXT NOT NULL,
                    file_size_bytes INTEGER NOT NULL,
                    sha256 TEXT NOT NULL,
                    version_label TEXT NOT NULL,
                    sort_order INTEGER NOT NULL,
                    is_primary_asset INTEGER NOT NULL,
                    status TEXT NOT NULL
                )",
                "CREATE TABLE ebook_media_asset (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    asset_slug TEXT NOT NULL,
                    asset_kind TEXT NOT NULL,
                    display_name TEXT NOT NULL,
                    public_url TEXT NOT NULL,
                    storage_path TEXT NOT NULL,
                    mime_type TEXT NOT NULL,
                    file_size_bytes INTEGER NOT NULL,
                    sha256 TEXT NOT NULL,
                    version_label TEXT NOT NULL,
                    status TEXT NOT NULL,
                    updated_at TEXT NOT NULL
                )",
                $deliveryRows,
                $assetRows,
            ],
        ],
        'runner' => 'app_user_db_contract_runtime_run_sample23',
    ];
}

/**
 * @return array<string,mixed>
 */
function app_user_db_contract_runtime_sample24_definition(): array
{
    $bookRows = "INSERT INTO ebook_reader_book (id, title, slug, author_name, genre_name, summary, status, published_at) VALUES
        (1, 'Reader Book', 'reader-book', 'Aki Reader', 'Guides', 'Reader summary', 'published', '2026-06-20 09:00:00'),
        (2, 'Draft Reader Book', 'draft-reader-book', 'Mika Draft', 'Drafts', 'Draft summary', 'draft', NULL)";
    $chapterRows = "INSERT INTO ebook_reader_chapter (id, book_slug, chapter_title, chapter_slug, spine_order, body_markdown, status) VALUES
        (1, 'reader-book', 'Opening', 'opening', 1, '# Opening', 'published'),
        (2, 'reader-book', 'Second', 'second', 2, '# Second', 'published')";
    $deliveryRows = "INSERT INTO ebook_reader_media_delivery (id, book_slug, asset_slug, asset_kind, display_name, public_url, mime_type, file_size_bytes, sha256, version_label, status) VALUES
        (1, 'reader-book', 'reader-epub', 'epub', 'Reader EPUB', '/reader/book.epub', 'application/epub+zip', 4500, 'sha-reader', 'v1', 'published')";

    return [
        'sample' => 'sample24-ebook-public-reader-site-demo',
        'dataclass_files' => [
            'data-EbookReaderBook.php',
            'data-EbookReaderChapter.php',
            'data-EbookReaderMediaDelivery.php',
        ],
        'dbaccess_files' => [
            'dbaccess-EbookReaderBook.php',
        ],
        'fixture_sql' => [
            'mysql' => [
                'DROP TABLE IF EXISTS ebook_reader_media_delivery',
                'DROP TABLE IF EXISTS ebook_reader_chapter',
                'DROP TABLE IF EXISTS ebook_reader_book',
                "CREATE TABLE ebook_reader_book (
                    id BIGINT NOT NULL PRIMARY KEY,
                    title VARCHAR(255) NOT NULL,
                    slug VARCHAR(191) NOT NULL,
                    author_name VARCHAR(255) NOT NULL,
                    genre_name VARCHAR(255) NOT NULL,
                    summary TEXT NOT NULL,
                    status VARCHAR(32) NOT NULL,
                    published_at DATETIME NULL
                )",
                "CREATE TABLE ebook_reader_chapter (
                    id BIGINT NOT NULL PRIMARY KEY,
                    book_slug VARCHAR(191) NOT NULL,
                    chapter_title VARCHAR(255) NOT NULL,
                    chapter_slug VARCHAR(191) NOT NULL,
                    spine_order INT NOT NULL,
                    body_markdown TEXT NOT NULL,
                    status VARCHAR(32) NOT NULL
                )",
                "CREATE TABLE ebook_reader_media_delivery (
                    id BIGINT NOT NULL PRIMARY KEY,
                    book_slug VARCHAR(191) NOT NULL,
                    asset_slug VARCHAR(191) NOT NULL,
                    asset_kind VARCHAR(32) NOT NULL,
                    display_name VARCHAR(255) NOT NULL,
                    public_url VARCHAR(255) NOT NULL,
                    mime_type VARCHAR(128) NOT NULL,
                    file_size_bytes BIGINT NOT NULL,
                    sha256 VARCHAR(128) NOT NULL,
                    version_label VARCHAR(64) NOT NULL,
                    status VARCHAR(32) NOT NULL
                )",
                $bookRows,
                $chapterRows,
                $deliveryRows,
            ],
            'pgsql' => [
                'DROP TABLE IF EXISTS ebook_reader_media_delivery',
                'DROP TABLE IF EXISTS ebook_reader_chapter',
                'DROP TABLE IF EXISTS ebook_reader_book',
                "CREATE TABLE ebook_reader_book (
                    id BIGINT NOT NULL PRIMARY KEY,
                    title VARCHAR(255) NOT NULL,
                    slug VARCHAR(191) NOT NULL,
                    author_name VARCHAR(255) NOT NULL,
                    genre_name VARCHAR(255) NOT NULL,
                    summary TEXT NOT NULL,
                    status VARCHAR(32) NOT NULL,
                    published_at TIMESTAMP NULL
                )",
                "CREATE TABLE ebook_reader_chapter (
                    id BIGINT NOT NULL PRIMARY KEY,
                    book_slug VARCHAR(191) NOT NULL,
                    chapter_title VARCHAR(255) NOT NULL,
                    chapter_slug VARCHAR(191) NOT NULL,
                    spine_order INTEGER NOT NULL,
                    body_markdown TEXT NOT NULL,
                    status VARCHAR(32) NOT NULL
                )",
                "CREATE TABLE ebook_reader_media_delivery (
                    id BIGINT NOT NULL PRIMARY KEY,
                    book_slug VARCHAR(191) NOT NULL,
                    asset_slug VARCHAR(191) NOT NULL,
                    asset_kind VARCHAR(32) NOT NULL,
                    display_name VARCHAR(255) NOT NULL,
                    public_url VARCHAR(255) NOT NULL,
                    mime_type VARCHAR(128) NOT NULL,
                    file_size_bytes BIGINT NOT NULL,
                    sha256 VARCHAR(128) NOT NULL,
                    version_label VARCHAR(64) NOT NULL,
                    status VARCHAR(32) NOT NULL
                )",
                $bookRows,
                $chapterRows,
                $deliveryRows,
            ],
            'sqlite' => [
                'DROP TABLE IF EXISTS ebook_reader_media_delivery',
                'DROP TABLE IF EXISTS ebook_reader_chapter',
                'DROP TABLE IF EXISTS ebook_reader_book',
                "CREATE TABLE ebook_reader_book (
                    id INTEGER NOT NULL PRIMARY KEY,
                    title TEXT NOT NULL,
                    slug TEXT NOT NULL,
                    author_name TEXT NOT NULL,
                    genre_name TEXT NOT NULL,
                    summary TEXT NOT NULL,
                    status TEXT NOT NULL,
                    published_at TEXT NULL
                )",
                "CREATE TABLE ebook_reader_chapter (
                    id INTEGER NOT NULL PRIMARY KEY,
                    book_slug TEXT NOT NULL,
                    chapter_title TEXT NOT NULL,
                    chapter_slug TEXT NOT NULL,
                    spine_order INTEGER NOT NULL,
                    body_markdown TEXT NOT NULL,
                    status TEXT NOT NULL
                )",
                "CREATE TABLE ebook_reader_media_delivery (
                    id INTEGER NOT NULL PRIMARY KEY,
                    book_slug TEXT NOT NULL,
                    asset_slug TEXT NOT NULL,
                    asset_kind TEXT NOT NULL,
                    display_name TEXT NOT NULL,
                    public_url TEXT NOT NULL,
                    mime_type TEXT NOT NULL,
                    file_size_bytes INTEGER NOT NULL,
                    sha256 TEXT NOT NULL,
                    version_label TEXT NOT NULL,
                    status TEXT NOT NULL
                )",
                $bookRows,
                $chapterRows,
                $deliveryRows,
            ],
        ],
        'runner' => 'app_user_db_contract_runtime_run_sample24',
    ];
}

/**
 * @return array<string,mixed>
 */
function app_user_db_contract_runtime_sample25_definition(): array
{
    $chapterRows = "INSERT INTO ebook_editor_chapter
        (id, ebook_editor_book_id, chapter_title, chapter_slug, status, spine_order, body_markdown, published_at, updated_at)
        VALUES
        (1, 1, 'Editor Opening', 'editor-opening', 'draft', 1, '# Draft editor opening', NULL, '2026-06-20 09:00:00'),
        (2, 1, 'Published Editor', 'published-editor', 'published', 2, '# Published editor', '2026-06-20 10:00:00', '2026-06-20 10:00:00')";

    return [
        'sample' => 'sample25-ebook-editor-auth-cms-demo',
        'dataclass_files' => [
            'data-EbookEditorChapter.php',
        ],
        'dbaccess_files' => [
            'dbaccess-EbookEditorChapter.php',
        ],
        'fixture_sql' => [
            'mysql' => [
                'DROP TABLE IF EXISTS ebook_editor_chapter',
                "CREATE TABLE ebook_editor_chapter (
                    id BIGINT NOT NULL PRIMARY KEY,
                    ebook_editor_book_id BIGINT NOT NULL,
                    chapter_title VARCHAR(255) NOT NULL,
                    chapter_slug VARCHAR(191) NOT NULL,
                    status VARCHAR(32) NOT NULL,
                    spine_order INT NOT NULL,
                    body_markdown TEXT NOT NULL,
                    published_at DATETIME NULL,
                    updated_at DATETIME NOT NULL
                )",
                $chapterRows,
            ],
            'pgsql' => [
                'DROP TABLE IF EXISTS ebook_editor_chapter',
                "CREATE TABLE ebook_editor_chapter (
                    id BIGINT NOT NULL PRIMARY KEY,
                    ebook_editor_book_id BIGINT NOT NULL,
                    chapter_title VARCHAR(255) NOT NULL,
                    chapter_slug VARCHAR(191) NOT NULL,
                    status VARCHAR(32) NOT NULL,
                    spine_order INTEGER NOT NULL,
                    body_markdown TEXT NOT NULL,
                    published_at TIMESTAMP NULL,
                    updated_at TIMESTAMP NOT NULL
                )",
                $chapterRows,
            ],
            'sqlite' => [
                'DROP TABLE IF EXISTS ebook_editor_chapter',
                "CREATE TABLE ebook_editor_chapter (
                    id INTEGER NOT NULL PRIMARY KEY,
                    ebook_editor_book_id INTEGER NOT NULL,
                    chapter_title TEXT NOT NULL,
                    chapter_slug TEXT NOT NULL,
                    status TEXT NOT NULL,
                    spine_order INTEGER NOT NULL,
                    body_markdown TEXT NOT NULL,
                    published_at TEXT NULL,
                    updated_at TEXT NOT NULL
                )",
                $chapterRows,
            ],
        ],
        'runner' => 'app_user_db_contract_runtime_run_sample25',
    ];
}

/**
 * @return array<string,mixed>
 */
function app_user_db_contract_runtime_sample26_definition(): array
{
    $bookRows = "INSERT INTO ebook_cms_book
        (id, title, slug, author_name, genre_name, cover_image_url, summary, epub_download_url, epub_mime_type, epub_sha256, status, published_at)
        VALUES
        (1, 'CMS Book', 'cms-book', 'Aki CMS', 'Guides', '/covers/cms.jpg', 'CMS summary', '/cms/book.epub', 'application/epub+zip', 'sha-cms', 'published', '2026-06-20 09:00:00'),
        (2, 'Draft CMS Book', 'draft-cms-book', 'Mika Draft', 'Drafts', '/covers/draft.jpg', 'Draft summary', NULL, NULL, NULL, 'draft', NULL)";
    $chapterRows = "INSERT INTO ebook_cms_chapter
        (id, ebook_cms_book_id, book_slug, chapter_title, chapter_slug, status, spine_order, body_markdown, published_at, updated_at)
        VALUES
        (1, 1, 'cms-book', 'Opening', 'opening', 'published', 1, '# Opening', '2026-06-20 10:00:00', '2026-06-20 10:00:00'),
        (2, 1, 'cms-book', 'Draft Chapter', 'draft-chapter', 'draft', 2, '# Draft', NULL, '2026-06-20 11:00:00')";

    return [
        'sample' => 'sample26-ebook-headless-cms-capstone',
        'dataclass_files' => [
            'data-EbookCmsBook.php',
            'data-EbookCmsChapter.php',
        ],
        'dbaccess_files' => [
            'dbaccess-EbookCmsBook.php',
        ],
        'fixture_sql' => [
            'mysql' => [
                'DROP TABLE IF EXISTS ebook_cms_chapter',
                'DROP TABLE IF EXISTS ebook_cms_book',
                "CREATE TABLE ebook_cms_book (
                    id BIGINT NOT NULL PRIMARY KEY,
                    title VARCHAR(255) NOT NULL,
                    slug VARCHAR(191) NOT NULL,
                    author_name VARCHAR(255) NOT NULL,
                    genre_name VARCHAR(255) NOT NULL,
                    cover_image_url VARCHAR(255) NOT NULL,
                    summary TEXT NOT NULL,
                    epub_download_url VARCHAR(255) NULL,
                    epub_mime_type VARCHAR(128) NULL,
                    epub_sha256 VARCHAR(128) NULL,
                    status VARCHAR(32) NOT NULL,
                    published_at DATETIME NULL
                )",
                "CREATE TABLE ebook_cms_chapter (
                    id BIGINT NOT NULL PRIMARY KEY,
                    ebook_cms_book_id BIGINT NOT NULL,
                    book_slug VARCHAR(191) NOT NULL,
                    chapter_title VARCHAR(255) NOT NULL,
                    chapter_slug VARCHAR(191) NOT NULL,
                    status VARCHAR(32) NOT NULL,
                    spine_order INT NOT NULL,
                    body_markdown TEXT NOT NULL,
                    published_at DATETIME NULL,
                    updated_at DATETIME NOT NULL
                )",
                $bookRows,
                $chapterRows,
            ],
            'pgsql' => [
                'DROP TABLE IF EXISTS ebook_cms_chapter',
                'DROP TABLE IF EXISTS ebook_cms_book',
                "CREATE TABLE ebook_cms_book (
                    id BIGINT NOT NULL PRIMARY KEY,
                    title VARCHAR(255) NOT NULL,
                    slug VARCHAR(191) NOT NULL,
                    author_name VARCHAR(255) NOT NULL,
                    genre_name VARCHAR(255) NOT NULL,
                    cover_image_url VARCHAR(255) NOT NULL,
                    summary TEXT NOT NULL,
                    epub_download_url VARCHAR(255) NULL,
                    epub_mime_type VARCHAR(128) NULL,
                    epub_sha256 VARCHAR(128) NULL,
                    status VARCHAR(32) NOT NULL,
                    published_at TIMESTAMP NULL
                )",
                "CREATE TABLE ebook_cms_chapter (
                    id BIGINT NOT NULL PRIMARY KEY,
                    ebook_cms_book_id BIGINT NOT NULL,
                    book_slug VARCHAR(191) NOT NULL,
                    chapter_title VARCHAR(255) NOT NULL,
                    chapter_slug VARCHAR(191) NOT NULL,
                    status VARCHAR(32) NOT NULL,
                    spine_order INTEGER NOT NULL,
                    body_markdown TEXT NOT NULL,
                    published_at TIMESTAMP NULL,
                    updated_at TIMESTAMP NOT NULL
                )",
                $bookRows,
                $chapterRows,
            ],
            'sqlite' => [
                'DROP TABLE IF EXISTS ebook_cms_chapter',
                'DROP TABLE IF EXISTS ebook_cms_book',
                "CREATE TABLE ebook_cms_book (
                    id INTEGER NOT NULL PRIMARY KEY,
                    title TEXT NOT NULL,
                    slug TEXT NOT NULL,
                    author_name TEXT NOT NULL,
                    genre_name TEXT NOT NULL,
                    cover_image_url TEXT NOT NULL,
                    summary TEXT NOT NULL,
                    epub_download_url TEXT NULL,
                    epub_mime_type TEXT NULL,
                    epub_sha256 TEXT NULL,
                    status TEXT NOT NULL,
                    published_at TEXT NULL
                )",
                "CREATE TABLE ebook_cms_chapter (
                    id INTEGER NOT NULL PRIMARY KEY,
                    ebook_cms_book_id INTEGER NOT NULL,
                    book_slug TEXT NOT NULL,
                    chapter_title TEXT NOT NULL,
                    chapter_slug TEXT NOT NULL,
                    status TEXT NOT NULL,
                    spine_order INTEGER NOT NULL,
                    body_markdown TEXT NOT NULL,
                    published_at TEXT NULL,
                    updated_at TEXT NOT NULL
                )",
                $bookRows,
                $chapterRows,
            ],
        ],
        'runner' => 'app_user_db_contract_runtime_run_sample26',
    ];
}

/**
 * @return array<string,mixed>
 */
function app_user_db_contract_runtime_sample19_definition(): array
{
    return [
        'sample' => 'sample19-json-first-content-model-demo',
        'dataclass_files' => [
            'data-ArticleJsonModel.php',
            'data-ArticlePublicSummary.php',
            'data-JsonAuthor.php',
            'data-JsonCategory.php',
        ],
        'dbaccess_files' => [
            'dbaccess-ArticleJsonModel.php',
        ],
        'fixture_sql' => [
            'mysql' => [
                'DROP TABLE IF EXISTS ArticleJsonModel',
                'DROP TABLE IF EXISTS JsonAuthor',
                'DROP TABLE IF EXISTS JsonCategory',
                "CREATE TABLE JsonAuthor (
                    Id BIGINT NOT NULL PRIMARY KEY,
                    Name VARCHAR(255) NOT NULL
                )",
                "CREATE TABLE JsonCategory (
                    Id BIGINT NOT NULL PRIMARY KEY,
                    Name VARCHAR(255) NOT NULL
                )",
                "CREATE TABLE ArticleJsonModel (
                    Id BIGINT NOT NULL PRIMARY KEY,
                    JsonAuthorId BIGINT NOT NULL,
                    JsonCategoryId BIGINT NOT NULL,
                    Title VARCHAR(255) NOT NULL,
                    Slug VARCHAR(255) NOT NULL,
                    Status VARCHAR(20) NOT NULL,
                    PublishedAt DATETIME NULL,
                    Body TEXT NOT NULL
                )",
                "INSERT INTO JsonAuthor (Id, Name) VALUES
                    (1, 'Aki JSON'),
                    (2, 'Mika Draft')",
                "INSERT INTO JsonCategory (Id, Name) VALUES
                    (1, 'Guides'),
                    (2, 'Internal')",
                "INSERT INTO ArticleJsonModel (Id, JsonAuthorId, JsonCategoryId, Title, Slug, Status, PublishedAt, Body) VALUES
                    (1, 1, 1, 'JSON-first public article', 'json-first-public', 'published', '2026-06-20 09:00:00', '{\"kind\":\"public\"}'),
                    (2, 2, 2, 'Draft JSON article', 'draft-json', 'draft', NULL, '{\"kind\":\"draft\"}'),
                    (3, 1, 1, 'Second public article', 'second-public', 'published', '2026-06-21 10:00:00', '{\"kind\":\"public\"}')",
            ],
            'pgsql' => [
                'DROP TABLE IF EXISTS ArticleJsonModel',
                'DROP TABLE IF EXISTS JsonAuthor',
                'DROP TABLE IF EXISTS JsonCategory',
                "CREATE TABLE JsonAuthor (
                    Id BIGINT NOT NULL PRIMARY KEY,
                    Name VARCHAR(255) NOT NULL
                )",
                "CREATE TABLE JsonCategory (
                    Id BIGINT NOT NULL PRIMARY KEY,
                    Name VARCHAR(255) NOT NULL
                )",
                "CREATE TABLE ArticleJsonModel (
                    Id BIGINT NOT NULL PRIMARY KEY,
                    JsonAuthorId BIGINT NOT NULL,
                    JsonCategoryId BIGINT NOT NULL,
                    Title VARCHAR(255) NOT NULL,
                    Slug VARCHAR(255) NOT NULL,
                    Status VARCHAR(20) NOT NULL,
                    PublishedAt TIMESTAMP NULL,
                    Body TEXT NOT NULL
                )",
                "INSERT INTO JsonAuthor (Id, Name) VALUES
                    (1, 'Aki JSON'),
                    (2, 'Mika Draft')",
                "INSERT INTO JsonCategory (Id, Name) VALUES
                    (1, 'Guides'),
                    (2, 'Internal')",
                "INSERT INTO ArticleJsonModel (Id, JsonAuthorId, JsonCategoryId, Title, Slug, Status, PublishedAt, Body) VALUES
                    (1, 1, 1, 'JSON-first public article', 'json-first-public', 'published', '2026-06-20 09:00:00', '{\"kind\":\"public\"}'),
                    (2, 2, 2, 'Draft JSON article', 'draft-json', 'draft', NULL, '{\"kind\":\"draft\"}'),
                    (3, 1, 1, 'Second public article', 'second-public', 'published', '2026-06-21 10:00:00', '{\"kind\":\"public\"}')",
            ],
            'sqlite' => [
                'DROP TABLE IF EXISTS ArticleJsonModel',
                'DROP TABLE IF EXISTS JsonAuthor',
                'DROP TABLE IF EXISTS JsonCategory',
                "CREATE TABLE JsonAuthor (
                    Id INTEGER NOT NULL PRIMARY KEY,
                    Name TEXT NOT NULL
                )",
                "CREATE TABLE JsonCategory (
                    Id INTEGER NOT NULL PRIMARY KEY,
                    Name TEXT NOT NULL
                )",
                "CREATE TABLE ArticleJsonModel (
                    Id INTEGER NOT NULL PRIMARY KEY,
                    JsonAuthorId INTEGER NOT NULL,
                    JsonCategoryId INTEGER NOT NULL,
                    Title TEXT NOT NULL,
                    Slug TEXT NOT NULL,
                    Status TEXT NOT NULL,
                    PublishedAt TEXT NULL,
                    Body TEXT NOT NULL
                )",
                "INSERT INTO JsonAuthor (Id, Name) VALUES
                    (1, 'Aki JSON'),
                    (2, 'Mika Draft')",
                "INSERT INTO JsonCategory (Id, Name) VALUES
                    (1, 'Guides'),
                    (2, 'Internal')",
                "INSERT INTO ArticleJsonModel (Id, JsonAuthorId, JsonCategoryId, Title, Slug, Status, PublishedAt, Body) VALUES
                    (1, 1, 1, 'JSON-first public article', 'json-first-public', 'published', '2026-06-20 09:00:00', '{\"kind\":\"public\"}'),
                    (2, 2, 2, 'Draft JSON article', 'draft-json', 'draft', NULL, '{\"kind\":\"draft\"}'),
                    (3, 1, 1, 'Second public article', 'second-public', 'published', '2026-06-21 10:00:00', '{\"kind\":\"public\"}')",
            ],
        ],
        'runner' => 'app_user_db_contract_runtime_run_sample19',
    ];
}

/**
 * @return array<string,mixed>
 */
function app_user_db_contract_runtime_sample06_definition(): array
{
    return [
        'sample' => 'sample06-dbaccess-filter-sort-page',
        'dataclass_files' => [
            'data-Announcement.php',
        ],
        'dbaccess_files' => [
            'dbaccess-Announcement.php',
        ],
        'fixture_sql' => [
            'mysql' => [
                'DROP TABLE IF EXISTS Announcement',
                "CREATE TABLE Announcement (
                    Id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
                    Title VARCHAR(255) NOT NULL,
                    Status VARCHAR(20) NOT NULL DEFAULT 'draft',
                    PublishedAt DATETIME NULL
                )",
                "INSERT INTO Announcement (Id, Title, Status, PublishedAt) VALUES
                    (1, 'Welcome Release', 'published', '2026-05-20 09:00:00'),
                    (2, 'Planned Maintenance', 'draft', NULL),
                    (3, 'May Newsletter', 'published', '2026-05-22 08:30:00'),
                    (4, 'June Newsletter', 'published', '2026-06-01 07:30:00')",
            ],
            'pgsql' => [
                'DROP TABLE IF EXISTS Announcement',
                "CREATE TABLE Announcement (
                    Id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    Title VARCHAR(255) NOT NULL,
                    Status VARCHAR(20) NOT NULL DEFAULT 'draft',
                    PublishedAt TIMESTAMP NULL
                )",
                "INSERT INTO Announcement (Id, Title, Status, PublishedAt) VALUES
                    (1, 'Welcome Release', 'published', '2026-05-20 09:00:00'),
                    (2, 'Planned Maintenance', 'draft', NULL),
                    (3, 'May Newsletter', 'published', '2026-05-22 08:30:00'),
                    (4, 'June Newsletter', 'published', '2026-06-01 07:30:00')",
                'ALTER TABLE Announcement ALTER COLUMN Id RESTART WITH 5',
            ],
            'sqlite' => [
                'DROP TABLE IF EXISTS Announcement',
                "CREATE TABLE Announcement (
                    Id INTEGER PRIMARY KEY AUTOINCREMENT,
                    Title TEXT NOT NULL,
                    Status TEXT NOT NULL DEFAULT 'draft',
                    PublishedAt TEXT NULL
                )",
                "INSERT INTO Announcement (Id, Title, Status, PublishedAt) VALUES
                    (1, 'Welcome Release', 'published', '2026-05-20 09:00:00'),
                    (2, 'Planned Maintenance', 'draft', NULL),
                    (3, 'May Newsletter', 'published', '2026-05-22 08:30:00'),
                    (4, 'June Newsletter', 'published', '2026-06-01 07:30:00')",
            ],
        ],
        'runner' => 'app_user_db_contract_runtime_run_sample06',
    ];
}

/**
 * @return array<string,mixed>
 */
function app_user_db_contract_runtime_sample08_definition(): array
{
    return [
        'sample' => 'sample08-dbaccess-join-read-model',
        'dataclass_files' => [
            'data-BlogAuthor.php',
            'data-BlogPost.php',
            'data-BlogPostAuthorSummary.php',
        ],
        'dbaccess_files' => [
            'dbaccess-BlogPost.php',
        ],
        'fixture_sql' => [
            'mysql' => [
                'DROP TABLE IF EXISTS blog_post_author_summary',
                'DROP TABLE IF EXISTS blog_post',
                'DROP TABLE IF EXISTS blog_author',
                "CREATE TABLE blog_author (
                    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                    name VARCHAR(255) NOT NULL,
                    is_active TINYINT(1) NOT NULL DEFAULT 1,
                    PRIMARY KEY (id)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
                "CREATE TABLE blog_post (
                    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                    blog_author_id BIGINT UNSIGNED NOT NULL,
                    title VARCHAR(255) NOT NULL,
                    status VARCHAR(20) NOT NULL DEFAULT 'draft',
                    PRIMARY KEY (id),
                    KEY idx_blog_post_author_id (blog_author_id),
                    CONSTRAINT fk_blog_post_author
                        FOREIGN KEY (blog_author_id)
                        REFERENCES blog_author (id)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
                "CREATE TABLE blog_post_author_summary (
                    blog_post_id BIGINT UNSIGNED NOT NULL,
                    blog_post_title VARCHAR(255) NOT NULL,
                    blog_author_id BIGINT UNSIGNED NOT NULL,
                    blog_author_name VARCHAR(255) NOT NULL,
                    PRIMARY KEY (blog_post_id)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
                "INSERT INTO blog_author (id, name, is_active) VALUES
                    (1, 'Alice Editor', 1),
                    (2, 'Bob Archived', 0),
                    (3, 'Carol Writer', 1)",
                "INSERT INTO blog_post (id, blog_author_id, title, status) VALUES
                    (1, 1, 'Canonical Join Tutorial', 'published'),
                    (2, 2, 'Inactive Author Should Not Appear', 'published'),
                    (3, 3, 'Draft Posts Stay Hidden', 'draft'),
                    (4, 3, 'Roadmap Checkpoint', 'published')",
            ],
            'pgsql' => [
                'DROP TABLE IF EXISTS blog_post_author_summary',
                'DROP TABLE IF EXISTS blog_post',
                'DROP TABLE IF EXISTS blog_author',
                "CREATE TABLE blog_author (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name VARCHAR(255) NOT NULL,
                    is_active SMALLINT NOT NULL DEFAULT 1
                )",
                "CREATE TABLE blog_post (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    blog_author_id BIGINT NOT NULL REFERENCES blog_author (id),
                    title VARCHAR(255) NOT NULL,
                    status VARCHAR(20) NOT NULL DEFAULT 'draft'
                )",
                "CREATE TABLE blog_post_author_summary (
                    blog_post_id BIGINT NOT NULL PRIMARY KEY,
                    blog_post_title VARCHAR(255) NOT NULL,
                    blog_author_id BIGINT NOT NULL,
                    blog_author_name VARCHAR(255) NOT NULL
                )",
                "INSERT INTO blog_author (id, name, is_active) VALUES
                    (1, 'Alice Editor', 1),
                    (2, 'Bob Archived', 0),
                    (3, 'Carol Writer', 1)",
                "INSERT INTO blog_post (id, blog_author_id, title, status) VALUES
                    (1, 1, 'Canonical Join Tutorial', 'published'),
                    (2, 2, 'Inactive Author Should Not Appear', 'published'),
                    (3, 3, 'Draft Posts Stay Hidden', 'draft'),
                    (4, 3, 'Roadmap Checkpoint', 'published')",
                'ALTER TABLE blog_author ALTER COLUMN id RESTART WITH 4',
                'ALTER TABLE blog_post ALTER COLUMN id RESTART WITH 5',
            ],
            'sqlite' => [
                'DROP TABLE IF EXISTS blog_post_author_summary',
                'DROP TABLE IF EXISTS blog_post',
                'DROP TABLE IF EXISTS blog_author',
                "CREATE TABLE blog_author (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    name TEXT NOT NULL,
                    is_active INTEGER NOT NULL DEFAULT 1
                )",
                "CREATE TABLE blog_post (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    blog_author_id INTEGER NOT NULL,
                    title TEXT NOT NULL,
                    status TEXT NOT NULL DEFAULT 'draft',
                    FOREIGN KEY (blog_author_id) REFERENCES blog_author (id)
                )",
                "CREATE TABLE blog_post_author_summary (
                    blog_post_id INTEGER NOT NULL PRIMARY KEY,
                    blog_post_title TEXT NOT NULL,
                    blog_author_id INTEGER NOT NULL,
                    blog_author_name TEXT NOT NULL
                )",
                "INSERT INTO blog_author (id, name, is_active) VALUES
                    (1, 'Alice Editor', 1),
                    (2, 'Bob Archived', 0),
                    (3, 'Carol Writer', 1)",
                "INSERT INTO blog_post (id, blog_author_id, title, status) VALUES
                    (1, 1, 'Canonical Join Tutorial', 'published'),
                    (2, 2, 'Inactive Author Should Not Appear', 'published'),
                    (3, 3, 'Draft Posts Stay Hidden', 'draft'),
                    (4, 3, 'Roadmap Checkpoint', 'published')",
            ],
        ],
        'runner' => 'app_user_db_contract_runtime_run_sample08',
    ];
}

/**
 * @return array<string,mixed>
 */
function app_user_db_contract_runtime_sample09_definition(): array
{
    return [
        'sample' => 'sample09-dbaccess-aggregate-report',
        'dataclass_files' => [
            'data-SalesCategory.php',
            'data-SalesRecord.php',
            'data-SalesCategoryReport.php',
        ],
        'dbaccess_files' => [
            'dbaccess-SalesRecord.php',
        ],
        'fixture_sql' => [
            'mysql' => [
                'DROP TABLE IF EXISTS sales_category_report',
                'DROP TABLE IF EXISTS sales_record',
                'DROP TABLE IF EXISTS sales_category',
                "CREATE TABLE sales_category (
                    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                    name VARCHAR(255) NOT NULL,
                    is_active TINYINT(1) NOT NULL DEFAULT 1,
                    PRIMARY KEY (id)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
                "CREATE TABLE sales_record (
                    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                    sales_category_id BIGINT UNSIGNED NOT NULL,
                    title VARCHAR(255) NOT NULL,
                    status VARCHAR(20) NOT NULL DEFAULT 'open',
                    amount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
                    PRIMARY KEY (id),
                    KEY idx_sales_record_category_id (sales_category_id),
                    CONSTRAINT fk_sales_record_category
                        FOREIGN KEY (sales_category_id)
                        REFERENCES sales_category (id)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
                "CREATE TABLE sales_category_report (
                    sales_category_id BIGINT UNSIGNED NOT NULL,
                    sales_category_name VARCHAR(255) NOT NULL,
                    closed_sale_count INT UNSIGNED NOT NULL,
                    closed_sale_total_amount DECIMAL(10,2) NOT NULL,
                    PRIMARY KEY (sales_category_id)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
                "INSERT INTO sales_category (id, name, is_active) VALUES
                    (1, 'Hardware', 1),
                    (2, 'Software', 1),
                    (3, 'Legacy', 0)",
                "INSERT INTO sales_record (id, sales_category_id, title, status, amount) VALUES
                    (1, 1, 'Keyboard refresh', 'closed', 120.00),
                    (2, 1, 'Mouse replacement', 'closed', 80.00),
                    (3, 2, 'License renewal', 'closed', 40.00),
                    (4, 2, 'Future subscription', 'open', 500.00),
                    (5, 3, 'Unsupported backlog', 'closed', 999.00)",
            ],
            'pgsql' => [
                'DROP TABLE IF EXISTS sales_category_report',
                'DROP TABLE IF EXISTS sales_record',
                'DROP TABLE IF EXISTS sales_category',
                "CREATE TABLE sales_category (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name VARCHAR(255) NOT NULL,
                    is_active SMALLINT NOT NULL DEFAULT 1
                )",
                "CREATE TABLE sales_record (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    sales_category_id BIGINT NOT NULL REFERENCES sales_category (id),
                    title VARCHAR(255) NOT NULL,
                    status VARCHAR(20) NOT NULL DEFAULT 'open',
                    amount DECIMAL(10,2) NOT NULL DEFAULT 0.00
                )",
                "CREATE TABLE sales_category_report (
                    sales_category_id BIGINT NOT NULL PRIMARY KEY,
                    sales_category_name VARCHAR(255) NOT NULL,
                    closed_sale_count INTEGER NOT NULL,
                    closed_sale_total_amount DECIMAL(10,2) NOT NULL
                )",
                "INSERT INTO sales_category (id, name, is_active) VALUES
                    (1, 'Hardware', 1),
                    (2, 'Software', 1),
                    (3, 'Legacy', 0)",
                "INSERT INTO sales_record (id, sales_category_id, title, status, amount) VALUES
                    (1, 1, 'Keyboard refresh', 'closed', 120.00),
                    (2, 1, 'Mouse replacement', 'closed', 80.00),
                    (3, 2, 'License renewal', 'closed', 40.00),
                    (4, 2, 'Future subscription', 'open', 500.00),
                    (5, 3, 'Unsupported backlog', 'closed', 999.00)",
                'ALTER TABLE sales_category ALTER COLUMN id RESTART WITH 4',
                'ALTER TABLE sales_record ALTER COLUMN id RESTART WITH 6',
            ],
            'sqlite' => [
                'DROP TABLE IF EXISTS sales_category_report',
                'DROP TABLE IF EXISTS sales_record',
                'DROP TABLE IF EXISTS sales_category',
                "CREATE TABLE sales_category (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    name TEXT NOT NULL,
                    is_active INTEGER NOT NULL DEFAULT 1
                )",
                "CREATE TABLE sales_record (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    sales_category_id INTEGER NOT NULL,
                    title TEXT NOT NULL,
                    status TEXT NOT NULL DEFAULT 'open',
                    amount NUMERIC NOT NULL DEFAULT 0.00,
                    FOREIGN KEY (sales_category_id) REFERENCES sales_category (id)
                )",
                "CREATE TABLE sales_category_report (
                    sales_category_id INTEGER NOT NULL PRIMARY KEY,
                    sales_category_name TEXT NOT NULL,
                    closed_sale_count INTEGER NOT NULL,
                    closed_sale_total_amount NUMERIC NOT NULL
                )",
                "INSERT INTO sales_category (id, name, is_active) VALUES
                    (1, 'Hardware', 1),
                    (2, 'Software', 1),
                    (3, 'Legacy', 0)",
                "INSERT INTO sales_record (id, sales_category_id, title, status, amount) VALUES
                    (1, 1, 'Keyboard refresh', 'closed', 120.00),
                    (2, 1, 'Mouse replacement', 'closed', 80.00),
                    (3, 2, 'License renewal', 'closed', 40.00),
                    (4, 2, 'Future subscription', 'open', 500.00),
                    (5, 3, 'Unsupported backlog', 'closed', 999.00)",
            ],
        ],
        'runner' => 'app_user_db_contract_runtime_run_sample09',
    ];
}

/**
 * @return array<string,mixed>
 */
function app_user_db_contract_runtime_sample10_definition(): array
{
    return [
        'sample' => 'sample10-dbaccess-mini-crud-flow',
        'dataclass_files' => [
            'data-SupportTicket.php',
        ],
        'dbaccess_files' => [
            'dbaccess-SupportTicket.php',
        ],
        'fixture_sql' => [
            'mysql' => [
                'DROP TABLE IF EXISTS support_ticket',
                "CREATE TABLE support_ticket (
                    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
                    title VARCHAR(255) NOT NULL,
                    status VARCHAR(32) NOT NULL,
                    assigned_to VARCHAR(255) NULL,
                    body TEXT NULL,
                    updated_at DATETIME NOT NULL
                )",
                "INSERT INTO support_ticket (id, title, status, assigned_to, body, updated_at) VALUES
                    (1, 'First open ticket', 'open', 'alice', 'First body', '2026-06-17 09:00:00'),
                    (2, 'Second open ticket', 'open', 'bob', 'Second body', '2026-06-17 10:00:00'),
                    (3, 'Closed ticket', 'closed', 'carol', 'Closed body', '2026-06-16 09:00:00')",
            ],
            'pgsql' => [
                'DROP TABLE IF EXISTS support_ticket',
                "CREATE TABLE support_ticket (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    title VARCHAR(255) NOT NULL,
                    status VARCHAR(32) NOT NULL,
                    assigned_to VARCHAR(255) NULL,
                    body TEXT NULL,
                    updated_at TIMESTAMP NOT NULL
                )",
                "INSERT INTO support_ticket (id, title, status, assigned_to, body, updated_at) VALUES
                    (1, 'First open ticket', 'open', 'alice', 'First body', '2026-06-17 09:00:00'),
                    (2, 'Second open ticket', 'open', 'bob', 'Second body', '2026-06-17 10:00:00'),
                    (3, 'Closed ticket', 'closed', 'carol', 'Closed body', '2026-06-16 09:00:00')",
                'ALTER TABLE support_ticket ALTER COLUMN id RESTART WITH 4',
            ],
            'sqlite' => [
                'DROP TABLE IF EXISTS support_ticket',
                "CREATE TABLE support_ticket (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    title TEXT NOT NULL,
                    status TEXT NOT NULL,
                    assigned_to TEXT NULL,
                    body TEXT NULL,
                    updated_at TEXT NOT NULL
                )",
                "INSERT INTO support_ticket (id, title, status, assigned_to, body, updated_at) VALUES
                    (1, 'First open ticket', 'open', 'alice', 'First body', '2026-06-17 09:00:00'),
                    (2, 'Second open ticket', 'open', 'bob', 'Second body', '2026-06-17 10:00:00'),
                    (3, 'Closed ticket', 'closed', 'carol', 'Closed body', '2026-06-16 09:00:00')",
            ],
        ],
        'runner' => 'app_user_db_contract_runtime_run_sample10',
    ];
}

function app_user_db_contract_runtime_prepare_mysql_fixture(array $definition): void
{
    $host = (string) (getenv('MTOOL_RUNTIME_DB_HOST') ?: 'db-lab');
    $user = (string) (getenv('MTOOL_RUNTIME_DB_USER') ?: 'lab_app');
    $password = (string) getenv('MTOOL_RUNTIME_DB_PASSWORD');
    $database = (string) (getenv('MTOOL_RUNTIME_DB_NAME') ?: 'lab_app');
    $port = (int) (getenv('MTOOL_RUNTIME_DB_PORT') ?: 3306);

    $db = new mysqli($host, $user, $password, $database, $port);
    if ($db->connect_errno !== 0) {
        throw new RuntimeException('mysql fixture connection failed: ' . $db->connect_error);
    }

    foreach (app_user_db_contract_runtime_fixture_sql($definition, 'mysql') as $sql) {
        if (!$db->query($sql)) {
            throw new RuntimeException('mysql fixture SQL failed: ' . $db->error . ' sql=' . $sql);
        }
    }
}

function app_user_db_contract_runtime_prepare_sqlite_fixture(array $definition, string $sqlitePath): void
{
    $parentDir = dirname($sqlitePath);
    if ($parentDir !== '' && $parentDir !== '.' && !is_dir($parentDir)) {
        mkdir($parentDir, 0775, true);
    }

    if (is_file($sqlitePath)) {
        unlink($sqlitePath);
    }

    $db = new PDO('sqlite:' . $sqlitePath, null, null, [
        PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
    ]);

    foreach (app_user_db_contract_runtime_fixture_sql($definition, 'sqlite') as $sql) {
        $db->exec($sql);
    }
}

function app_user_db_contract_runtime_prepare_pgsql_fixture(array $definition): void
{
    $dsn = trim((string) getenv('MTOOL_RUNTIME_PGSQL_DSN'));
    if ($dsn === '') {
        $host = (string) (getenv('MTOOL_RUNTIME_PGSQL_HOST') ?: getenv('MTOOL_RUNTIME_DB_HOST') ?: '127.0.0.1');
        $port = (string) (getenv('MTOOL_RUNTIME_PGSQL_PORT') ?: getenv('MTOOL_RUNTIME_DB_PORT') ?: '5432');
        $database = (string) (getenv('MTOOL_RUNTIME_PGSQL_DB') ?: getenv('MTOOL_RUNTIME_DB_NAME') ?: 'lab_app');
        $dsn = 'pgsql:host=' . $host . ';port=' . $port . ';dbname=' . $database;
    }

    $user = (string) (getenv('MTOOL_RUNTIME_PGSQL_USER') ?: getenv('MTOOL_RUNTIME_DB_USER') ?: 'lab_app');
    $password = (string) (getenv('MTOOL_RUNTIME_PGSQL_PASSWORD') ?: getenv('MTOOL_RUNTIME_DB_PASSWORD'));

    $db = new PDO($dsn, $user, $password, [
        PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
    ]);

    foreach (app_user_db_contract_runtime_fixture_sql($definition, 'pgsql') as $sql) {
        $db->exec($sql);
    }
}

/**
 * @return list<string>
 */
function app_user_db_contract_runtime_fixture_sql(array $definition, string $dialect): array
{
    $sql = $definition['fixture_sql'][$dialect] ?? null;
    if (!is_array($sql)) {
        throw new RuntimeException('fixture SQL not defined for dialect: ' . $dialect);
    }

    return array_values(array_map('strval', $sql));
}

function app_user_db_contract_runtime_require_sample_files(
    array $definition,
    string $dbaccessRoot,
    string $dataclassRoot,
): void {
    foreach (($definition['dataclass_files'] ?? []) as $file) {
        require_once rtrim($dataclassRoot, '/') . '/' . (string) $file;
    }

    foreach (($definition['dbaccess_files'] ?? []) as $file) {
        require_once rtrim($dbaccessRoot, '/') . '/' . (string) $file;
    }
}

/**
 * @return array<string,mixed>
 */
function app_user_db_contract_runtime_run_sample(
    array $definition,
    string $dbaccessRoot,
    string $dataclassRoot,
): array {
    app_user_db_contract_runtime_require_sample_files($definition, $dbaccessRoot, $dataclassRoot);

    $runner = (string) ($definition['runner'] ?? '');
    if ($runner === '' || !function_exists($runner)) {
        throw new RuntimeException('runtime contract runner not found: ' . $runner);
    }

    return $runner();
}

/**
 * @return array<string,mixed>
 */
function app_user_db_contract_runtime_run_sample06(): array
{
    $access = new AnnouncementDBAccess();

    return [
        'operations' => [
            'published_limit_10' => app_user_db_contract_runtime_list_summary(
                $access->GetAnnouncementList('published', 10),
            ),
            'published_limit_1' => app_user_db_contract_runtime_list_summary(
                $access->GetAnnouncementList('published', 1),
            ),
            'draft_limit_10' => app_user_db_contract_runtime_list_summary(
                $access->GetAnnouncementList('draft', 10),
            ),
            'missing_status' => app_user_db_contract_runtime_list_summary(
                $access->GetAnnouncementList('archived', 10),
            ),
        ],
    ];
}

/**
 * @return array<string,mixed>
 */
function app_user_db_contract_runtime_run_sample08(): array
{
    $access = new BlogPostDBAccess();

    return [
        'operations' => [
            'published_active_author_summary' => app_user_db_contract_runtime_list_summary(
                $access->GetPublishedBlogPostAuthorSummaryList(),
            ),
        ],
    ];
}

/**
 * @return array<string,mixed>
 */
function app_user_db_contract_runtime_run_sample09(): array
{
    $access = new SalesRecordDBAccess();

    return [
        'operations' => [
            'closed_sales_category_report' => app_user_db_contract_runtime_list_summary(
                $access->GetClosedSalesCategoryReportList(),
            ),
        ],
    ];
}

/**
 * @return array<string,mixed>
 */
function app_user_db_contract_runtime_run_sample10(): array
{
    $access = new SupportTicketDBAccess();

    $listBefore = $access->GetSupportTicketList('open', 10);
    $detailBefore = $access->GetSupportTicket(1);

    $newTicket = new SupportTicketData();
    $newTicket->title = 'New runtime ticket';
    $newTicket->status = 'open';
    $newTicket->assignedTo = 'dana';
    $newTicket->body = 'New body';
    $newTicket->updatedAt = '2026-06-17 12:00:00';
    $insertResult = $access->InsertSupportTicket($newTicket);

    $updateTicket = new SupportTicketData();
    $updateTicket->id = 2;
    $updateTicket->title = 'Second ticket updated';
    $updateTicket->status = 'closed';
    $updateTicket->assignedTo = 'erin';
    $updateTicket->body = 'Updated body';
    $updateTicket->updatedAt = '2026-06-17 13:00:00';
    $updateResult = $access->UpdateSupportTicket($updateTicket);
    $detailAfterUpdate = $access->GetSupportTicket(2);

    $deleteTicket = new SupportTicketData();
    $deleteTicket->id = 3;
    $deleteResult = $access->DeleteSupportTicket($deleteTicket);
    $detailAfterDelete = $access->GetSupportTicket(3);

    $listAfter = $access->GetSupportTicketList('open', 10);

    return [
        'operations' => [
            'list_before' => app_user_db_contract_runtime_list_summary($listBefore),
            'detail_before' => app_user_db_contract_runtime_record_summary($detailBefore),
            'insert' => app_user_db_contract_runtime_write_summary($insertResult),
            'update' => app_user_db_contract_runtime_write_summary($updateResult),
            'detail_after_update' => app_user_db_contract_runtime_record_summary($detailAfterUpdate),
            'delete' => app_user_db_contract_runtime_write_summary($deleteResult),
            'detail_after_delete' => app_user_db_contract_runtime_record_summary($detailAfterDelete),
            'list_after' => app_user_db_contract_runtime_list_summary($listAfter),
        ],
    ];
}

/**
 * @return array<string,mixed>
 */
function app_user_db_contract_runtime_run_sample18(): array
{
    $access = new TaskCardDBAccess();

    $todoBefore = $access->GetTaskCardList('todo', 10);
    $doingBefore = $access->GetTaskCard(2);

    $newCard = new TaskCardData();
    $newCard->Title = 'Inserted PostgreSQL card';
    $newCard->Body = 'Inserted body';
    $newCard->Status = 'todo';
    $newCard->AssignedTo = 'dana';
    $newCard->Priority = 4;
    $newCard->DueDate = '2026-06-23';
    $newCard->UpdatedAt = '2026-06-20 12:00:00';
    $insertResult = $access->InsertTaskCard($newCard);

    $updateCard = new TaskCardData();
    $updateCard->Id = 2;
    $updateCard->Title = 'Review generated names updated';
    $updateCard->Body = 'Updated task body';
    $updateCard->Status = 'doing';
    $updateCard->AssignedTo = 'erin';
    $updateCard->Priority = 6;
    $updateCard->DueDate = '2026-06-24';
    $updateCard->CompletedAt = null;
    $updateCard->UpdatedAt = '2026-06-20 13:00:00';
    $updateResult = $access->UpdateTaskCard($updateCard);
    $detailAfterUpdate = $access->GetTaskCard(2);

    $completeCard = new TaskCardData();
    $completeCard->Id = 1;
    $completeCard->CompletedAt = '2026-06-20 14:00:00';
    $completeCard->UpdatedAt = '2026-06-20 14:00:00';
    $completeResult = $access->CompleteTaskCard($completeCard);
    $detailAfterComplete = $access->GetTaskCard(1);

    return [
        'operations' => [
            'todo_before' => app_user_db_contract_runtime_list_summary($todoBefore),
            'doing_before' => app_user_db_contract_runtime_record_summary($doingBefore),
            'insert' => app_user_db_contract_runtime_write_summary($insertResult),
            'update' => app_user_db_contract_runtime_write_summary($updateResult),
            'detail_after_update' => app_user_db_contract_runtime_record_summary($detailAfterUpdate),
            'complete' => app_user_db_contract_runtime_write_summary($completeResult),
            'detail_after_complete' => app_user_db_contract_runtime_record_summary($detailAfterComplete),
            'todo_after' => app_user_db_contract_runtime_list_summary($access->GetTaskCardList('todo', 10)),
        ],
    ];
}

/**
 * @return array<string,mixed>
 */
function app_user_db_contract_runtime_run_sample19(): array
{
    $access = new ArticleJsonModelDBAccess();

    return [
        'operations' => [
            'published_article_public_summary' => app_user_db_contract_runtime_list_summary(
                $access->GetPublishedArticlePublicSummaryList(),
            ),
        ],
    ];
}

/**
 * @return array<string,mixed>
 */
function app_user_db_contract_runtime_run_sample21(): array
{
    $access = new EbookCatalogItemDBAccess();

    return [
        'operations' => [
            'catalog_filtered' => app_user_db_contract_runtime_list_summary(
                $access->GetPublicEbookCatalogList('aki-author', 'guides', 'starter-series', '%Ebook%', 10),
            ),
            'book_detail' => app_user_db_contract_runtime_record_summary(
                $access->GetPublicEbookBook('first-ebook'),
            ),
            'missing_book' => app_user_db_contract_runtime_record_summary(
                $access->GetPublicEbookBook('missing-ebook'),
            ),
        ],
    ];
}

/**
 * @return array<string,mixed>
 */
function app_user_db_contract_runtime_run_sample22(): array
{
    $access = new EbookWorkflowChapterDBAccess();

    $newChapter = new EbookWorkflowChapterData();
    $newChapter->ebookWorkflowBookId = 1;
    $newChapter->chapterTitle = 'Inserted Workflow Chapter';
    $newChapter->chapterSlug = 'inserted-workflow-chapter';
    $newChapter->spineOrder = 4;
    $newChapter->navLabel = 'Inserted';
    $newChapter->epubResourcePath = 'chapters/inserted.xhtml';
    $newChapter->bodyMarkdown = '# Inserted';
    $insertResult = $access->InsertEbookWorkflowChapter($newChapter);

    $updateChapter = new EbookWorkflowChapterData();
    $updateChapter->id = 2;
    $updateChapter->chapterTitle = 'Draft Chapter Updated';
    $updateChapter->navLabel = 'Draft Updated';
    $updateChapter->epubResourcePath = 'chapters/draft-updated.xhtml';
    $updateChapter->bodyMarkdown = '# Draft Updated';
    $updateResult = $access->UpdateEbookWorkflowChapterDraft($updateChapter);

    $orderChapter = new EbookWorkflowChapterData();
    $orderChapter->id = 2;
    $orderChapter->spineOrder = 5;
    $orderChapter->navLabel = 'Draft Ordered';
    $orderChapter->epubResourcePath = 'chapters/draft-ordered.xhtml';
    $orderResult = $access->UpdateEbookWorkflowChapterOrder($orderChapter);

    $publishChapter = new EbookWorkflowChapterData();
    $publishChapter->id = 2;
    $publishResult = $access->PublishEbookWorkflowChapter($publishChapter);

    return [
        'operations' => [
            'published_chapter_list' => app_user_db_contract_runtime_list_summary(
                $access->GetPublishedEbookWorkflowChapterList('workflow-book'),
            ),
            'published_chapter_detail' => app_user_db_contract_runtime_record_summary(
                $access->GetPublishedEbookWorkflowChapter('workflow-book', 'opening'),
            ),
            'insert' => app_user_db_contract_runtime_write_summary($insertResult),
            'update_draft' => app_user_db_contract_runtime_write_summary($updateResult),
            'update_order' => app_user_db_contract_runtime_write_summary($orderResult),
            'publish' => app_user_db_contract_runtime_write_summary($publishResult),
        ],
    ];
}

/**
 * @return array<string,mixed>
 */
function app_user_db_contract_runtime_run_sample23(): array
{
    $access = new EbookMediaAssetDBAccess();

    $newAsset = new EbookMediaAssetData();
    $newAsset->assetSlug = 'new-asset';
    $newAsset->assetKind = 'image';
    $newAsset->displayName = 'New Asset';
    $newAsset->publicUrl = '/media/new.jpg';
    $newAsset->storagePath = '/storage/new.jpg';
    $newAsset->mimeType = 'image/jpeg';
    $newAsset->fileSizeBytes = 2222;
    $newAsset->sha256 = 'sha-new';
    $newAsset->versionLabel = 'v1';
    $insertResult = $access->InsertEbookMediaAsset($newAsset);

    $updateAsset = new EbookMediaAssetData();
    $updateAsset->id = 1;
    $updateAsset->displayName = 'Cover Image Updated';
    $updateAsset->publicUrl = '/media/cover-updated.jpg';
    $updateAsset->storagePath = '/storage/cover-updated.jpg';
    $updateAsset->mimeType = 'image/jpeg';
    $updateAsset->fileSizeBytes = 1300;
    $updateAsset->sha256 = 'sha-cover-updated';
    $updateAsset->versionLabel = 'v2';
    $updateAsset->status = 'published';
    $updateResult = $access->UpdateEbookMediaAssetMetadata($updateAsset);

    return [
        'operations' => [
            'delivery_list' => app_user_db_contract_runtime_list_summary(
                $access->GetPublicEbookMediaDeliveryList('media-book'),
            ),
            'asset_detail' => app_user_db_contract_runtime_record_summary(
                $access->GetPublicEbookMediaAsset('cover-image'),
            ),
            'insert' => app_user_db_contract_runtime_write_summary($insertResult),
            'update_metadata' => app_user_db_contract_runtime_write_summary($updateResult),
        ],
    ];
}

/**
 * @return array<string,mixed>
 */
function app_user_db_contract_runtime_run_sample24(): array
{
    $access = new EbookReaderBookDBAccess();

    return [
        'operations' => [
            'book_list' => app_user_db_contract_runtime_list_summary(
                $access->GetPublicEbookReaderBookList(10),
            ),
            'book_detail' => app_user_db_contract_runtime_record_summary(
                $access->GetPublicEbookReaderBook('reader-book'),
            ),
            'chapter_list' => app_user_db_contract_runtime_list_summary(
                $access->GetPublicEbookReaderChapterList('reader-book'),
            ),
            'chapter_detail' => app_user_db_contract_runtime_record_summary(
                $access->GetPublicEbookReaderChapter('reader-book', 'opening'),
            ),
            'media_delivery_list' => app_user_db_contract_runtime_list_summary(
                $access->GetPublicEbookReaderMediaDeliveryList('reader-book'),
            ),
        ],
    ];
}

/**
 * @return array<string,mixed>
 */
function app_user_db_contract_runtime_run_sample25(): array
{
    $access = new EbookEditorChapterDBAccess();
    $detailBefore = $access->GetEditorEbookChapter(1);

    $updateChapter = new EbookEditorChapterData();
    $updateChapter->id = 1;
    $updateChapter->chapterTitle = 'Editor Opening Updated';
    $updateChapter->chapterSlug = 'editor-opening-updated';
    $updateChapter->spineOrder = 3;
    $updateChapter->bodyMarkdown = '# Editor Opening Updated';
    $updateResult = $access->UpdateEditorEbookChapterDraft($updateChapter);

    $publishChapter = new EbookEditorChapterData();
    $publishChapter->id = 1;
    $publishResult = $access->PublishEditorEbookChapter($publishChapter);

    return [
        'operations' => [
            'detail_before' => app_user_db_contract_runtime_record_summary($detailBefore),
            'update_draft' => app_user_db_contract_runtime_write_summary($updateResult),
            'publish' => app_user_db_contract_runtime_write_summary($publishResult),
            'detail_after_publish' => app_user_db_contract_runtime_record_summary_without_fields(
                $access->GetEditorEbookChapter(1),
                ['publishedAt', 'updatedAt'],
            ),
        ],
    ];
}

/**
 * @return array<string,mixed>
 */
function app_user_db_contract_runtime_run_sample26(): array
{
    $access = new EbookCmsBookDBAccess();
    $editorDetailBefore = $access->GetEditorEbookCmsChapter(2);

    $updateChapter = new EbookCmsChapterData();
    $updateChapter->id = 2;
    $updateChapter->chapterTitle = 'Draft Chapter Updated';
    $updateChapter->chapterSlug = 'draft-chapter-updated';
    $updateChapter->spineOrder = 4;
    $updateChapter->bodyMarkdown = '# Draft Updated';
    $updateResult = $access->UpdateEditorEbookCmsChapterDraft($updateChapter);

    $publishChapter = new EbookCmsChapterData();
    $publishChapter->id = 2;
    $publishResult = $access->PublishEditorEbookCmsChapter($publishChapter);

    return [
        'operations' => [
            'book_list' => app_user_db_contract_runtime_list_summary(
                $access->GetPublicEbookCmsBookList(10),
            ),
            'book_detail' => app_user_db_contract_runtime_record_summary(
                $access->GetPublicEbookCmsBook('cms-book'),
            ),
            'chapter_list' => app_user_db_contract_runtime_list_summary(
                $access->GetPublicEbookCmsChapterList('cms-book'),
            ),
            'chapter_detail' => app_user_db_contract_runtime_record_summary(
                $access->GetPublicEbookCmsChapter('cms-book', 'opening'),
            ),
            'epub_delivery_list' => app_user_db_contract_runtime_list_summary(
                $access->GetPublicEbookCmsEpubDeliveryList('cms-book'),
            ),
            'editor_detail_before' => app_user_db_contract_runtime_record_summary($editorDetailBefore),
            'update_draft' => app_user_db_contract_runtime_write_summary($updateResult),
            'publish' => app_user_db_contract_runtime_write_summary($publishResult),
            'editor_detail_after_publish' => app_user_db_contract_runtime_record_summary_without_fields(
                $access->GetEditorEbookCmsChapter(2),
                ['publishedAt', 'updatedAt'],
            ),
        ],
    ];
}

/**
 * @return array<string,mixed>
 */
function app_user_db_contract_runtime_result(
    array $definition,
    string $dbaccessRoot,
    string $dataclassRoot,
    string $dialect,
): array {
    $result = app_user_db_contract_runtime_run_sample($definition, $dbaccessRoot, $dataclassRoot);

    return [
        'schema' => 'user-db-contract-runtime-v1',
        'sample' => (string) ($definition['sample'] ?? ''),
        'dialect' => $dialect,
        'operations' => $result['operations'] ?? [],
    ];
}

/**
 * @return array<string,mixed>
 */
function app_user_db_contract_runtime_list_summary(mixed $list): array
{
    if (!is_array($list)) {
        return [
            'ok' => false,
            'count' => 0,
            'records' => [],
        ];
    }

    return [
        'ok' => true,
        'count' => count($list),
        'records' => array_map('app_user_db_contract_runtime_object_summary', $list),
    ];
}

/**
 * @return array<string,mixed>
 */
function app_user_db_contract_runtime_record_summary(mixed $record): array
{
    if (!is_object($record)) {
        return [
            'found' => false,
        ];
    }

    return [
        'found' => true,
        'record' => app_user_db_contract_runtime_object_summary($record),
    ];
}

/**
 * @param list<string> $fieldNames
 * @return array<string,mixed>
 */
function app_user_db_contract_runtime_record_summary_without_fields(mixed $record, array $fieldNames): array
{
    $summary = app_user_db_contract_runtime_record_summary($record);
    if (!isset($summary['record']) || !is_array($summary['record'])) {
        return $summary;
    }

    foreach ($fieldNames as $fieldName) {
        unset($summary['record'][$fieldName]);
    }

    return $summary;
}

/**
 * @return array<string,mixed>
 */
function app_user_db_contract_runtime_object_summary(mixed $record): array
{
    if (!is_object($record)) {
        return [];
    }

    $values = get_object_vars($record);
    ksort($values, SORT_STRING);

    return array_map('app_user_db_contract_runtime_normalize_value', $values);
}

function app_user_db_contract_runtime_normalize_value(mixed $value): mixed
{
    if (is_string($value) && preg_match('/^-?\d+\.\d+$/', $value) === 1) {
        $normalized = rtrim(rtrim($value, '0'), '.');
        if ($normalized === '-0') {
            $normalized = '0';
        }
        if (preg_match('/^-?\d+$/', $normalized) === 1) {
            return (int) $normalized;
        }

        return (float) $normalized;
    }

    return $value;
}

/**
 * @return array<string,mixed>
 */
function app_user_db_contract_runtime_write_summary(mixed $result): array
{
    return [
        'ok' => $result !== false,
    ];
}
