<?php

// AUTO-GENERATED BASE FILE.
// Do not edit this file manually or with AI/Codex.
// Keep customizations in the wrapper class and use this base file exactly as regenerated by the tool.

// Generated from canonical DataClass metadata.
// Base DTO generated from DataClass / DataClass fields.

class ContentArticleDataBase
{
    public $id;
    public $title;
    public $slug;
    public $categoryName;
    public $authorName;
    public $status;
    public $publishedAt;
    public $summary;
    public $body;
    public $updatedAt;

    public function __construct()
    {
    }
}

?>