<?php

// AUTO-GENERATED BASE FILE.
// Do not edit this file manually or with AI/Codex.
// Keep customizations in the wrapper class and use this base file exactly as regenerated by the tool.

// Generated by migrating a legacy data class.
// Generated members are kept in this base file. Former editable areas move to the wrapper file.
// Generated trailing enum-type classes also stay in this base file when present.

class dafuncselectwhereDataBase
{
    public $ProjectPID;
    public $daPID;
    public $dafuncPID;
    public $PID;
    public $targetTableName;
    public $targetTableAliasName;
    public $targetTableColumnName;
    public $ParameterType;
    public $ParameterDataType;
    public $FixedParameter;
    public $AnotherTableName;
    public $AnotherTableAliasName;
    public $AnotherFieldName;
    public $JoinType;
    public $ORGroup;
    public $RelationalOperator;
    public $WhereOrder;

    public function __construct()
    {
    }
}

?>
