<?php

// AUTO-GENERATED BASE FILE.
// Do not edit this file manually or with AI/Codex.
// Keep customizations in the wrapper class and use this base file exactly as regenerated by the tool.

// Generated by migrating a legacy data class.
// Generated members are kept in this base file. Former editable areas move to the wrapper file.
// Generated trailing enum-type classes also stay in this base file when present.

class LastBuildDataBase
{
    public $PID;
    public $ProjectPID;
    public $ProjectSourceOutputPID;
    public $BuildClassType;
    public $EachTargetPID;
    public $ToTempFolder;
    public $OutputAfterCopyToTempFolder;
    public $LastBuildDT;

    public function __construct()
    {
    }
}

class LastBuildBuildClassTypeEnum
{
	static $UNKNOWN = "Unknown";
	static $DATACLASS = "dataclass";
	static $DA = "da";
	static $PROXYSERVER = "proxyserver";
	static $PROXYCLIENT = "proxyclient";
	static $CUSTOMPROXYSERVER = "customproxyserver";
	static $CUSTOMPROXYCLIENT = "customproxyclient";
	static $HTML = "html";
	static $LANGUAGERESOURCE = "LanguageResource";
}


?>
