__INSERT_ID_INITIALIZE__
	$DA__CLASS_BASE_NAME__ = new __CLASS_BASE_NAME__DBAccess();
	for($index = 0 ; $index < count($data->__LIST_OBJECT_NAME__); $index++) {
__CHECK_IF_ALREADY_INSERTED__
		$__SINGLE_RESULT_FOR_LIST__ = $DA__CLASS_BASE_NAME__->__FUNCTION_NAME__(
__REQUEST_PARAMS__
		);
__ADD_RESULT__
__CHECK_ERROR__
__INSERT_ID_SET__
__SET_INSERTED_ID_BY_INSERT_TOKEN__
__EDITABLE_AREA_IN_THE_END_OF_LOOP__
	}
