	$DA__CLASS_BASE_NAME__ = new __CLASS_BASE_NAME__DBAccess();
__CHECK_IF_ALREADY_INSERTED_BEGIN__
__INDENT_FOR_CHECK_IF_ALREADY_INSERTED__	$__RESULT____RESULT_NO__ = $DA__CLASS_BASE_NAME__->__FUNCTION_NAME__(
__REQUEST_PARAMS__
__INDENT_FOR_CHECK_IF_ALREADY_INSERTED__		);
__CHECK_ERROR__
__INSERT_ID_SET__
__SET_INSERTED_ID_BY_INSERT_TOKEN__
__CHECK_IF_ALREADY_INSERTED_END__
