
#ifndef __CLASS_NAME___h
#define __CLASS_NAME___h

#import <UIKit/UIKit.h>
#import "DegoDBCommonLib.h"
__INCLUDE_CLASS_OR_ENUM_HEADER__

// == START OF EDITABLE AREA FOR ABOVE ==
// == END OF EDITABLE AREA FOR ABOVE ==

// THIS CLASS WAS AUTOMATICALLY CREATED BY MTOOL. DON'T EDIT EXCEPT THE EDITABLE AREA.
// [JP] このクラスは自動生成されています。編集可能領域以外は変更しないで下さい。

@interface __CLASS_NAME____INHERIT_CLASS__
{
	// == START OF EDITABLE AREA FOR ADDITIONAL VARIABLE DEFINITION ==
	// == END OF EDITABLE AREA FOR ADDITIONAL VARIABLE DEFINITION ==
}

__AUTOMATED_CODE_COMES_HERE__

- (id) init;
- (id) initWithDic:(NSDictionary*)dic;
- (NSDictionary*)Serialize;

// == START OF EDITABLE AREA FOR ADDITIONAL CLASS INTERFACE DEFINITION ==
// == END OF EDITABLE AREA FOR ADDITIONAL CLASS INTERFACE DEFINITION ==

@end

__CONST_DEFINITION__

// == START OF EDITABLE AREA FOR BOTTOM ==
// == END OF EDITABLE AREA FOR BOTTOM ==

#endif /* __CLASS_NAME___h */
