<?php

// AUTO-GENERATED BASE FILE.
// Do not edit this file manually or with AI/Codex.
// Keep customizations in the wrapper class and use this base file exactly as regenerated by the tool.

// Generated from canonical data class metadata.
// Base DTO generated from dataclass / dataclassfields.

class EbookEditorChapterDataBase
{
    public $Id;
    public $EbookEditorBookId;
    public $ChapterTitle;
    public $ChapterSlug;
    public $Status;
    public $SpineOrder;
    public $BodyMarkdown;
    public $PublishedAt;
    public $UpdatedAt;

    public function __construct()
    {
    }
}

?>