<?php

// AUTO-GENERATED BASE FILE.
// Do not edit this file manually or with AI/Codex.
// Keep customizations in the wrapper class and use this base file exactly as regenerated by the tool.

// Generated from canonical DataClass metadata.
// Base DTO generated from DataClass / DataClass fields.

class EbookMediaAssetDataBase
{
    public $id;
    public $assetSlug;
    public $assetKind;
    public $displayName;
    public $publicUrl;
    public $storagePath;
    public $mimeType;
    public $fileSizeBytes;
    public $sha256;
    public $versionLabel;
    public $status;
    public $updatedAt;

    public function __construct()
    {
    }
}

?>