<?php

// AUTO-GENERATED BASE FILE.
// Do not edit this file manually or with AI/Codex.
// Keep customizations in the wrapper class and use this base file exactly as regenerated by the tool.

// Generated from canonical DB Access metadata.
// Base class generated from project_db_access_* metadata.

require_once __DIR__ . '/../_support/mtool_runtime_db.php';


class EbookEditorChapterDBAccessBase
{
    public function __construct()
    {
    }

    // source_of_truth=manual class_source=manual action_type=SELECTSINGLE order=10 generation=canonical-sql
    public function GetEditorEbookChapter($param_EbookEditorChapter_Id_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'select ebook_editor_chapter.id, ebook_editor_chapter.ebook_editor_book_id, ebook_editor_chapter.chapter_title, ebook_editor_chapter.chapter_slug, ebook_editor_chapter.status, ebook_editor_chapter.spine_order, ebook_editor_chapter.body_markdown, ebook_editor_chapter.published_at, ebook_editor_chapter.updated_at from ebook_editor_chapter where ebook_editor_chapter.id = ?';
        $ret = $mtooldb->execute($last_sql_command_for_mtooldb, [
            $param_EbookEditorChapter_Id_where,
        ]);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new EbookEditorChapterData();
            $thisresult->id = $thisline[0];
            $thisresult->ebookEditorBookId = $thisline[1];
            $thisresult->chapterTitle = $thisline[2];
            $thisresult->chapterSlug = $thisline[3];
            $thisresult->status = $thisline[4];
            $thisresult->spineOrder = $thisline[5];
            $thisresult->bodyMarkdown = $thisline[6];
            $thisresult->publishedAt = $thisline[7];
            $thisresult->updatedAt = $thisline[8];
            return $thisresult;
        }
        return NULL;
    }

    // source_of_truth=manual class_source=manual action_type=UPDATE order=20 generation=canonical-sql
    public function UpdateEditorEbookChapterDraft($EbookEditorChapterObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'update ebook_editor_chapter SET chapter_title = ?, chapter_slug = ?, spine_order = ?, body_markdown = ?, updated_at = NOW() where ebook_editor_chapter.id = ?';
        $result = $mtooldb->execute($last_sql_command_for_mtooldb, [
            $EbookEditorChapterObj->chapterTitle,
            $EbookEditorChapterObj->chapterSlug,
            $EbookEditorChapterObj->spineOrder,
            $EbookEditorChapterObj->bodyMarkdown,
            $EbookEditorChapterObj->id,
        ]);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }

    // source_of_truth=manual class_source=manual action_type=UPDATE order=30 generation=canonical-sql
    public function PublishEditorEbookChapter($EbookEditorChapterObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'update ebook_editor_chapter SET status = ?, published_at = NOW(), updated_at = NOW() where ebook_editor_chapter.id = ?';
        $result = $mtooldb->execute($last_sql_command_for_mtooldb, [
            'published',
            $EbookEditorChapterObj->id,
        ]);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }
}

?>