<?php

// AUTO-GENERATED BASE FILE.
// Do not edit this file manually or with AI/Codex.
// Keep customizations in the wrapper class and use this base file exactly as regenerated by the tool.

// Generated from canonical DB Access metadata.
// Base class generated from project_db_access_* metadata.

require_once __DIR__ . '/../_support/mtool_runtime_db.php';


class EbookEditorChapterDBAccessBase
{
    public function __construct()
    {
    }

    // source_of_truth=manual class_source=manual action_type=SELECTSINGLE order=10 generation=canonical-sql
    public function GetEditorEbookChapter($param_EbookEditorChapter_Id_where)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'select EbookEditorChapter.Id, EbookEditorChapter.EbookEditorBookId, EbookEditorChapter.ChapterTitle, EbookEditorChapter.ChapterSlug, EbookEditorChapter.Status, EbookEditorChapter.SpineOrder, EbookEditorChapter.BodyMarkdown, EbookEditorChapter.PublishedAt, EbookEditorChapter.UpdatedAt from EbookEditorChapter where EbookEditorChapter.Id = ?';
        $ret = $mtooldb->execute($last_sql_command_for_mtooldb, [
            $param_EbookEditorChapter_Id_where,
        ]);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
            return $ret;
        }
        while($thisline=$ret->fetch_row()) {
            $thisresult = new EbookEditorChapterData();
            $thisresult->Id = $thisline[0];
            $thisresult->EbookEditorBookId = $thisline[1];
            $thisresult->ChapterTitle = $thisline[2];
            $thisresult->ChapterSlug = $thisline[3];
            $thisresult->Status = $thisline[4];
            $thisresult->SpineOrder = $thisline[5];
            $thisresult->BodyMarkdown = $thisline[6];
            $thisresult->PublishedAt = $thisline[7];
            $thisresult->UpdatedAt = $thisline[8];
            return $thisresult;
        }
        return NULL;
    }

    // source_of_truth=manual class_source=manual action_type=UPDATE order=20 generation=canonical-sql
    public function UpdateEditorEbookChapterDraft($EbookEditorChapterObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'update EbookEditorChapter SET ChapterTitle = ?, ChapterSlug = ?, SpineOrder = ?, BodyMarkdown = ?, UpdatedAt = NOW() where EbookEditorChapter.Id = ?';
        $result = $mtooldb->execute($last_sql_command_for_mtooldb, [
            $EbookEditorChapterObj->ChapterTitle,
            $EbookEditorChapterObj->ChapterSlug,
            $EbookEditorChapterObj->SpineOrder,
            $EbookEditorChapterObj->BodyMarkdown,
            $EbookEditorChapterObj->Id,
        ]);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }

    // source_of_truth=manual class_source=manual action_type=UPDATE order=30 generation=canonical-sql
    public function PublishEditorEbookChapter($EbookEditorChapterObj)
    {
        global $mtooldb, $last_sql_command_for_mtooldb;
        connect_mtooldb_if_not_yet();
        reconnect_mtooldb_if_necessary();

        $last_sql_command_for_mtooldb = 'update EbookEditorChapter SET Status = ?, PublishedAt = NOW(), UpdatedAt = NOW() where EbookEditorChapter.Id = ?';
        $result = $mtooldb->execute($last_sql_command_for_mtooldb, [
            'published',
            $EbookEditorChapterObj->Id,
        ]);
        if ($mtooldb->errno != 0) {
            error_log("Error occured while executing SQL: " . $mtooldb->error . " in " . __FILE__ . " on line " . __LINE__);
        }
        return $result;
    }
}

?>