<?php

// AUTO-GENERATED BASE FILE.
// Do not edit this file manually or with AI/Codex.
// Keep customizations in the wrapper class and use this base file exactly as regenerated by the tool.

// Generated from canonical data class metadata.
// Base DTO generated from dataclass / dataclassfields.

class TaskPriorityDataBase
{
    public $Id;
    public $PriorityKey;
    public $Name;
    public $Caption;
    public $SortOrder;
    public $Weight;

    public function __construct()
    {
    }
}

?>