name: mtool-sample-sample06-dbaccess-filter-sort-page-sqlite

services:
  web-admin:
    environment:
      APP_WORK_ROOT: /var/www/work/sample-packs/sample06-dbaccess-filter-sort-page-sqlite

  web-lab:
    environment:
      APP_WORK_ROOT: /var/www/work/sample-packs/sample06-dbaccess-filter-sort-page-sqlite
