<?php

// AUTO-GENERATED BASE FILE.
// Do not edit this file manually or with AI/Codex.
// Keep customizations in the wrapper class and use this base file exactly as regenerated by the tool.

// Generated by migrating a legacy data class.
// Generated members are kept in this base file. Former editable areas move to the wrapper file.
// Generated trailing enum-type classes also stay in this base file when present.

class CompareOutputDataBase
{
    public $PID;
    public $ProjectPID;
    public $DropboxBaseFolderPID;
    public $OutputFilePath;
    public $OutputFileType;
    public $ComparePath;
    public $CompareToolFilePath;

    public function __construct()
    {
    }
}

class CompareOutputOutputFileTypeEnum
{
	static $UNKNOWN = "Unknown";
	static $TEXT = "Text";
	static $WINDOWSBATCH = "WindowsBatch";
	static $MACCOMMAND = "MacCommand";
}


?>